### ISSUE TITLE
Error "Unable to load extension 'dev-spaces-preview'" with version 2.0.81

### ISSUE THREAD

**Issue by terry-citrix** [Azure/azure-cli-extensions#1249]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
dev-spaces-preview

### Description of issue (in as much detail as possible)

When I run just about any command other than "--version" I get the following error message:

`Unable to load extension 'dev-spaces-preview'. Use --debug for more information.`

**Repro**
1. On a Win10 64-bit machine install an older version of the "az cli". (Unfortunately I don't recall the version that I had)
2. Download the latest version, which is currently "azure-cli-2.0.81.msi", and install it.
3. Confirm you have a version above 2.0.32 by typing "az --version".
4. Type a command such as "az keyvault --help --debug".

**Expected**
That I do _not_ get a message that it's unable to load an extension.

I also expect that if I uninstall everything, reboot my machine (hey why not), and then install the 'az cli' as a fresh install that it should work (it doesn't -- it still gives me the error).

**Actual**
I get the following message:

```
Loaded all modules in 0.563 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\terrydu\.azure\cliextensions'
Found 1 extensions: ['dev-spaces-preview']
Extensions directory: 'C:\Users\terrydu\.azure\cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.81 min_required=2.0.32 max_required=None
Event: MainLoader.OnFailedExtensionLoad []
Unable to load extension 'dev-spaces-preview'. Use --debug for more information.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\__init__.py", line 210,
in _update_command_table_from_extensions
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 969, in _load_extension_command_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 955, in _load_command_loader
  File "C:\Users\terrydu\.azure\cliextensions\dev-spaces-preview\azext_dev_spaces_preview\__init__.py", line 23, in load
_command_table
    with self.command_group('ads') as g:
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\__init__.py", line 454,
in command_group
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 1069, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 1093, in _merge_kwargs
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 1044, in _merge_kwargs
TypeError: unrecognized kwargs: ['min_profile']

Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04035A08>]
az_command_data_logger : command args: keyvault --help --debug
metadata file logging enabled - writing logs to 'C:\Users\terrydu\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_param
eter at 0x041AC660>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x041AC150
>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x041AC780>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04D44E40>]
```
----

Note that `is_compatible` is `True`.  For whatever reason the issue seems to be that it can't read `min_profile`.

**Comment by arrownj** [comment]
Hi @fengzhou-msft , could you please help with this ?

**Comment by fengzhou-msft** [comment]
@terry-citrix `dev-spaces-preview` is deprecated and replaced by `dev-spaces`. You can manually delete the `dev-spaces-preview` extension under C:\Users\terrydu\.azure\cliextensions

**Comment by terry-citrix** [comment]
Thanks, that fixed it!
