### ISSUE TITLE
Error on update azurefunction subscription on eventgrid

### ISSUE THREAD

**Issue by phmzum** [Azure/azure-cli-extensions#1268]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
eventgrid

### Description of issue (in as much detail as possible)

when executed the command bellow to update an azurefunction subscription 

`az eventgrid event-subscription update --name $name --source-resource-id $topic --endpoint-type azurefunction --endpoint $endPoint --included-event-types $events`

i received the following error

```
2020-02-12T12:44:54.6327192Z ERROR: 'AzureFunctionEventSubscriptionDestination' object has no attribute 'azure_active_directory_tenant_id'
2020-02-12T12:44:54.6327868Z Traceback (most recent call last):
2020-02-12T12:44:54.6328798Z   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
2020-02-12T12:44:54.6329172Z     cmd_result = self.invocation.execute(args)
2020-02-12T12:44:54.6330049Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
2020-02-12T12:44:54.6330371Z     raise ex
2020-02-12T12:44:54.6331245Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
2020-02-12T12:44:54.6332351Z     results.append(self._run_job(expanded_arg, cmd_copy))
2020-02-12T12:44:54.6333741Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
2020-02-12T12:44:54.6334123Z     six.reraise(*sys.exc_info())
2020-02-12T12:44:54.6334928Z   File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
2020-02-12T12:44:54.6335275Z     raise value
2020-02-12T12:44:54.6336123Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
2020-02-12T12:44:54.6336441Z     result = cmd_copy(params)
2020-02-12T12:44:54.6337925Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line ***7***, in __call__
2020-02-12T12:44:54.6338381Z     return self.handler(*args, **kwargs)
2020-02-12T12:44:54.6339295Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 477, in handler
2020-02-12T12:44:54.6339732Z     instance = custom_function(instance=instance, **custom_func_args)
2020-02-12T12:44:54.6340290Z   File "/vsts/agent/_work/_temp/.azclitask/cliextensions/eventgrid/azext_eventgrid/custom.py", line 6***3, in update_event_subscription
2020-02-12T12:44:54.6340700Z     event_subscription_destination.azure_active_directory_tenant_id,
2020-02-12T12:44:54.6342127Z AttributeError: 'AzureFunctionEventSubscriptionDestination' object has no attribute 'azure_active_directory_tenant_id'
-----
```

**Comment by arrownj** [comment]
@phmzum , thanks for reporting, we are looking at it.

**Comment by ahamad-MS** [comment]
Thanks @phmzum for reporting this issue. We would need additional information to understand this issue:

1. What is the extension version you are using?

Please provide the output of this command:
Azure:~$ az extension list

If version is not 0.4.4, please make sure to delete any installed extension and install new one.

The output should look like this.
[
  {
    "extensionType": "whl",
    "name": "eventgrid",
    "version": "0.4.4"
  }
]

2. What is the exact repro steps here?
Was the original event subscription of azure function type? if not, what was the previous type? if yes, what were you trying to change. 

complete list of commands will be helpful

3. Is this 100% repo?

thanks

**Comment by phmzum** [comment]
1. the output was exatly this look. (version 0.4.4)

2. the previous type is azure function (when the original event subscription is webhook works ok)
i trying change the param --included-event-types

this is the only command that i'm running, previous code is only to set variables values.
bellow sample of the variables contents (subscriptions guid replaced by empty guid and specific names replaced by ***) 

$name => Proposta-Cidade
$topic => /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/***/providers/Microsoft.EventGrid/domains/***/topics/***
$endPoint => /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/***/providers/Microsoft.Web/sites/***/functions/***
$events => cidade-insert cidade-update

3. not sure the meanigs of this question but i think yes, the same result when changing the variables values

**Comment by ahamad-MS** [comment]
Thanks @phmzum for the additional info. I am able to repro the issue and identify the root cause. We will working on a fix now and will be available soon.

If you are blocked, you can either delete the event subscription and re-create it again or try to call create again with same values..

please let me know if you have any other issues.

**Comment by phmzum** [comment]
thanks @ahamad-MS, i'm already using this workaround for now, but please let me know when the fix is published.

no other issues detected!

**Comment by ahamad-MS** [comment]
This issue is resolved now with latest event grid extension. Please uninstall any existing extension and install latest one (Version: version 0.4.6).
