### ISSUE TITLE
az blueprint assignment create - fails

### ISSUE THREAD

**Issue by robfrut135** [Azure/azure-cli-extensions#1541]
## Describe the bug

**Command Name**
`az blueprint assignment create
Extension Name: blueprint. Version: 0.1.0.`

**Errors:**
```
'artifact_name'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 625, in execute
    raise ex
cli/core/commands/__init__.py, ln 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cliextensions/blueprint/azext_blueprint/custom.py, ln 526, in <dictcomp>
    body['resource_groups'] = {rg['artifact_name']: _del_artifact_name(rg) for rg in resource_groups} if resource_groups is not None else {}
KeyError: 'artifact_name'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az blueprint assignment create --subscription {} --name {} --location {} --identity-type {} --description {} --blueprint-version {} --locks-mode {} --resource-group-value {} {} {} --parameters {}`

## Environment Summary
```
Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1

Extensions:
blueprint 0.1.0

```

**Comment by yonzhan** [comment]
blueprint

**Comment by yonzhan** [comment]
@fengzhou-msft  please take a look

**Comment by fengzhou-msft** [comment]
@robfrut135 did you specify the `artifact_name` value in `--resource-group-value`? It is the key of your resource group under `resourceGroups` of your blueprint definition. An example is [here](https://github.com/Azure/azure-cli-extensions/blame/master/src/blueprint/README.md#L133).

**Comment by brennaman** [comment]
@fengzhou-msft i get the same key error and I am specifying the `artifact_name` value in `--resource-group-value`. The command I run looks something like this:

```
az blueprint assignment update --subscription XXXX --name MyAssignment \
--location eastus --identity-type SystemAssigned \
--blueprint-version "/providers/Microsoft.Management/managementGroups/mymg/providers/Microsoft.Blueprint/blueprints/myblueprint/versions/v5" \
--resource-group-value artifact_name=SingleRG name=my-new-rg location=eastus
``` 
Error:
```
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : 'artifact_name'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 665, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 574, in default_command_handler
    return op(**command_args)
  File "/home/paulb1/.azure/cliextensions/blueprint/azext_blueprint/custom.py", line 594, in update_blueprint_assignment
    body['resource_groups'] = {rg['artifact_name']: _del_artifact_name(rg) for rg in resource_groups}  # dictionary
  File "/home/paulb1/.azure/cliextensions/blueprint/azext_blueprint/custom.py", line 594, in <dictcomp>
    body['resource_groups'] = {rg['artifact_name']: _del_artifact_name(rg) for rg in resource_groups}  # dictionary
KeyError: 'artifact_name'
'artifact_name'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 665, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 574, in default_command_handler
    return op(**command_args)
  File "/home/paulb1/.azure/cliextensions/blueprint/azext_blueprint/custom.py", line 594, in update_blueprint_assignment
    body['resource_groups'] = {rg['artifact_name']: _del_artifact_name(rg) for rg in resource_groups}  # dictionary
  File "/home/paulb1/.azure/cliextensions/blueprint/azext_blueprint/custom.py", line 594, in <dictcomp>
    body['resource_groups'] = {rg['artifact_name']: _del_artifact_name(rg) for rg in resource_groups}  # dictionary
KeyError: 'artifact_name'
```

**Comment by fengzhou-msft** [comment]
Reproduced this issue with Python 3.6 and 3.7, but not with Python 3.8.

In Python 3.6 and 3.7, `_del_artifact_name(rg)` happens before `rg['artifact_name']` in:
`body['resource_groups'] = {rg['artifact_name']: _del_artifact_name(rg) for rg in resource_groups}`

I will submit a fix to process a copy of `rg` in `_del_artifact_name`.
