### ISSUE TITLE
Cannot set SQL Server AD Admin

### ISSUE THREAD

**Issue by JayReally** [Azure/azure-cli-extensions#1554]
**Command Name**
`az sql server ad-admin create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


create_or_update() missing 1 required positional argument: 'parameters'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/sql/custom.py", line 2074, in server_ad_admin_set
    properties=kwargs)
TypeError: create_or_update() missing 1 required positional argument: 'parameters'
```

## To Reproduce:

I was able to set the ad admin using the portal using the same information, and double checked the display name and object-id values using "export template" funcationality.

Command executed from azure cloud shell (bash)

Command issued:
- `az sql server ad-admin create --display-name {"my.name@company.com"} --object-id {"00000000-0000-0000-0000-000000000000"} --resource-group {"my-rg"} --server {"my-sql-server"}`

## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
sql

**Comment by RakeshMohanMSFT** [comment]
This is working now. Please upgrade to latest version of azure cli
![image](https://user-images.githubusercontent.com/49954584/201276410-5d986824-df60-4dcc-b934-d268bf7d29e9.png)
