### ISSUE TITLE
image copy throws No module named 'azure.mgmt.compute.v2019_07_01'

### ISSUE THREAD

**Issue by lunarfs** [Azure/azure-cli-extensions#1557]
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.3.`

**Errors:**
```
Command '['/usr/bin/python3', '-m', 'azure.cli', 'image', 'show', '--name', 'managedImage-xxxxxx-xxxxxx', '--resource-group', 'packerbuild', '--output', 'json']' returned non-zero exit status 1.
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
...
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'azure.cli', 'image', 'show', '--name', 'managedImage-xxxxxx-xxxxxx', '--resource-group', 'xxxxx', '--output', 'json']' returned non-zero exit status 1.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {} --cleanup --subscription {} --target-subscription {}`

## Environment Summary
```
Linux-4.19.76-linuxkit-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Installer: RPM

azure-cli 2.3.1

Extensions:
image-copy-extension 0.2.3

```
## Additional Context
So we are running this in a docker container centos7 based 
```
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo
RUN yum install -y python3 azure-cli
```
and then before actually doing the copying we do 
```
az extension add --name image-copy-extension
```
so previousley we successfully used 
```
azure-cli                         2.0.81 *
command-modules-nspkg              2.0.3
core                              2.0.81 *
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
image-copy-extension               0.2.3
```
But copying to multiple regions stopped working, the command simply returned sucessfully after a few seconds.. but no content was actually copied .. so we descided to upgrade to latest and greatest. but are now facing this exception
```
command failed: ['/usr/bin/python3', '-m', 'azure.cli', 'image', 'show', '--name', 'xxxxxx-jenkinsSlave-xxxxxx', '--resource-group', 'xxxxxx', '--output', 'json']
output: The command failed with an unexpected error. Here is the traceback:

No module named 'azure.mgmt.compute.v2019_07_01'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 546, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 330, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 309, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/commands.py", line 105, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 723, in generic_show_arguments_loader
    cmd_args = get_arguments_loader(context, getter_op, operation_group=kwargs.get('operation_group'))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 402, in get_arguments_loader
    getter_args = dict(extract_args_from_signature(context.get_op_handler(getter_op, operation_group=operation_group),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 574, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.compute.v2019_07_01'

To open an issue, please run: 'az feedback'

The command failed with an unexpected error. Here is the traceback:

Command '['/usr/bin/python3', '-m', 'azure.cli', 'image', 'show', '--name', 'managedImage-xxxxxx-xxxxxx', '--resource-group', 'xxxxxx', '--output', 'json']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 682, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
    return op(**command_args)
  File "/home/ansibleme/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 31, in imagecopy
    json_cmd_output = run_cli_command(cli_cmd, return_as_json=True)
  File "/home/ansibleme/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 46, in run_cli_command
    raise ex
  File "/home/ansibleme/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'azure.cli', 'image', 'show', '--name', 'managedImage-xxxxxx-xxxxxx', '--resource-group', 'xxxxxx', '--output', 'json']' returned non-zero exit status 1.
```

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
It's a rare problem. I try it in a CentOS VM and don't reproduce the error.

**Comment by qwordy** [comment]
Could you install the latest Azure CLI and image copy extension and try again?

**Comment by lunarfs** [comment]
Thanks for your support, I think this boils down to an old installation. We have now upgraded to the latest and greatest. and the issue is gone. It for sure looks like azure develop on the API and that getting to fare behind is a bad idea.

**Comment by qwordy** [comment]
Glad to see your problem is solved.
