### ISSUE TITLE
App Insights - Error listing components

### ISSUE THREAD

**Issue by dlopes7** [Azure/azure-cli-extensions#1642]
Cannot list app insight components with python 3.8.2

**Command Name**
`az monitor app-insights component show
Extension Name: application-insights. Version: 0.1.7.`

**Errors:**
```
Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
python3.8/site-packages/msrest/serialization.py, ln 1355, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
python3.8/site-packages/msrest/serialization.py, ln 1119, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'

...

python3.8/site-packages/msrest/serialization.py, ln 1119, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az monitor app-insights component show`

## Environment Summary
```
Linux-5.6.8-arch1-1-x86_64-with-glibc2.2.5
Python 3.8.2
Installer: 

azure-cli 2.5.1

Extensions:
interactive 0.4.4
application-insights 0.1.7

```

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@dlopes7 Hello. Are you showing the components in your sub? How many components in your sub?

**Comment by MyronFanQiu** [comment]
I just tried this command locally and it works well. Based on your error message, it should be related with `paged` and `nextlink`.

**Comment by MyronFanQiu** [comment]
@dlopes7 Do you still encounter such issue?

**Comment by dlopes7** [comment]
Yes, I believe the account did not have application insights after all. But I expected an empty response instead of an exception

**Comment by MyronFanQiu** [comment]
> Yes, I believe the account did not have application insights after all. But I expected an empty response instead of an exception

I see. Empty scenario is also an edge case. Let me check it. Thanks.

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
@dlopes7 Hi. I cannot reproduce this issue. Usually the root cause should be service issue and I think they have fixed them. Could you install the latest extension and try again?

**Comment by dlopes7** [comment]
Latest version 0.1.8 still presents the same issue, but since the account did not have app insights I am ok with it

```
azure-cli 2.8.0

Extensions:
interactive 0.4.4
application-insights 0.1.8
```

**Comment by MyronFanQiu** [comment]
@dlopes7  Hi. Can you run the command with --debug and paste the part of https response? I think this issue should be a service issue? We can help you route this issue to service team with your help.

**Comment by dlopes7** [comment]
I can't seem to be able to run with `--debug`

```
❯ az --debug monitor app-insights component show
Command arguments: ['--debug', 'monitor', 'app-insights', 'component', 'show']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f6cc5f40f70>, <function OutputProducer.on_global_arguments at 0x7f6cc5f295e0>, <function CLIQuery.on_global_arguments at 0x7f6cc5ec5c10>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'util', 'vm']
Loaded module 'acr' in 0.003 seconds.
Loaded module 'acs' in 0.004 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.003 seconds.
Loaded module 'apim' in 0.001 seconds.
Loaded module 'appconfig' in 0.001 seconds.
Loaded module 'appservice' in 0.064 seconds.
Loaded module 'aro' in 0.004 seconds.
Loaded module 'backup' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.014 seconds.
Loaded module 'batchai' in 0.002 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.003 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.018 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'deploymentmanager' in 0.001 seconds.
Loaded module 'dla' in 0.002 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.001 seconds.
Loaded module 'eventgrid' in 0.001 seconds.
Loaded module 'eventhubs' in 0.002 seconds.
Loaded module 'extension' in 0.005 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.002 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.003 seconds.
Loaded module 'kusto' in 0.001 seconds.
Loaded module 'lab' in 0.002 seconds.
Loaded module 'managedservices' in 0.003 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.005 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.001 seconds.
Loaded module 'network' in 0.028 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.008 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.004 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'relay' in 0.001 seconds.
Loaded module 'reservations' in 0.001 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.003 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.001 seconds.
Loaded module 'servicebus' in 0.003 seconds.
Loaded module 'servicefabric' in 0.001 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.009 seconds.
Loaded module 'sqlvm' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.029 seconds.
Loaded module 'util' in 0.001 seconds.
Loaded module 'vm' in 0.010 seconds.
Loaded all modules in 0.287 seconds. (note: there's always an overhead with the first module loaded)
Found 2 extensions: ['interactive', 'application-insights']
Extension compatibility result: is_compatible=True cli_core_version=2.8.0 min_required=2.0.62 max_required=None
Extensions directory: '/home/david/.azure/cliextensions/interactive'
Loaded extension 'interactive' in 0.000 seconds.
Extension compatibility result: is_compatible=True cli_core_version=2.8.0 min_required=2.0.79 max_required=None
Extensions directory: '/home/david/.azure/cliextensions/application-insights'
Loaded extension 'application-insights' in 0.004 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f6cc58e3430>]
az_command_data_logger : command args: --debug {} {} {} {}
metadata file logging enabled - writing logs to '/home/david/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f6cc5901940>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f6cc58b9160>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f6cc58b9280>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f6cc4cccdc0>]
cli.azure.cli.core.parser : az monitor: 'app-insights' is not in the 'az monitor' command group. See 'az monitor --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
az monitor: 'app-insights' is not in the 'az monitor' command group. See 'az monitor --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
recommendation_provider: version: 2.8.0, command: monitor app-insights, parameters: [], extension: None
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f6cc58e3670>]
az_command_data_logger : exit code: 2
telemetry.save : Save telemetry record of length 2818 in cache
telemetry.check : Negative: The /home/david/.azure/telemetry.txt was modified at 2020-06-23 21:45:09.660147, which in less than 600.000000 s
Command ran in 0.404 seconds (init: 0.022, invoke: 0.382)
```

**Comment by MyronFanQiu** [comment]
Hi @dlopes7  Could you run `az monitor app-insights component show --debug`?

**Comment by dlopes7** [comment]
My bad, it looks like the response is an empty array `[]`

```
❯ az monitor app-insights component show --debug
Command arguments: ['monitor', 'app-insights', 'component', 'show', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fef6c334040>, <function OutputProducer.on_global_arguments at 0x7fef6c319670>, <function CLIQuery.on_global_arguments at 0x7fef6c3b5ca0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'util', 'vm']
Loaded module 'acr' in 0.003 seconds.
Loaded module 'acs' in 0.005 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.003 seconds.
Loaded module 'apim' in 0.001 seconds.
Loaded module 'appconfig' in 0.002 seconds.
Loaded module 'appservice' in 0.062 seconds.
Loaded module 'aro' in 0.003 seconds.
Loaded module 'backup' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.014 seconds.
Loaded module 'batchai' in 0.002 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.003 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.010 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.001 seconds.
Loaded module 'container' in 0.001 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'deploymentmanager' in 0.001 seconds.
Loaded module 'dla' in 0.002 seconds.
Loaded module 'dls' in 0.001 seconds.
Loaded module 'dms' in 0.001 seconds.
Loaded module 'eventgrid' in 0.001 seconds.
Loaded module 'eventhubs' in 0.002 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.000 seconds.
Loaded module 'find' in 0.000 seconds.
Loaded module 'hdinsight' in 0.001 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.002 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.003 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.002 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.004 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.001 seconds.
Loaded module 'network' in 0.017 seconds.
Loaded module 'policyinsights' in 0.001 seconds.
Loaded module 'privatedns' in 0.003 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.004 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'relay' in 0.001 seconds.
Loaded module 'reservations' in 0.001 seconds.
Loaded module 'resource' in 0.005 seconds.
Loaded module 'role' in 0.002 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.001 seconds.
Loaded module 'servicebus' in 0.003 seconds.
Loaded module 'servicefabric' in 0.001 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.005 seconds.
Loaded module 'sqlvm' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.020 seconds.
Loaded module 'util' in 0.001 seconds.
Loaded module 'vm' in 0.008 seconds.
Loaded all modules in 0.224 seconds. (note: there's always an overhead with the first module loaded)
Found 2 extensions: ['interactive', 'application-insights']
Extension compatibility result: is_compatible=True cli_core_version=2.8.0 min_required=2.0.62 max_required=None
Extensions directory: '/home/david/.azure/cliextensions/interactive'
Loaded extension 'interactive' in 0.000 seconds.
Extension compatibility result: is_compatible=True cli_core_version=2.8.0 min_required=2.0.79 max_required=None
Extensions directory: '/home/david/.azure/cliextensions/application-insights'
Loaded extension 'application-insights' in 0.002 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fef6bd1f430>]
az_command_data_logger : command args: monitor app-insights component show --debug
metadata file logging enabled - writing logs to '/home/david/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fef6bd3f940>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fef6bca9160>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fef6bca9280>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fef6b0c6dc0>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fef6c319700>, <function CLIQuery.handle_query_parameter at 0x7fef6c3b5d30>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fef6bca91f0>, <function handler at 0x7fef6af25700>]
az_command_data_logger : extension name: application-insights
az_command_data_logger : extension version: 0.1.8
Getting management service client client_type=ApplicationInsightsManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.async_paging : Paging async iterator protocol is not available for ApplicationInsightsComponentPaged
attempting to read file /home/david/.azure/accessTokens.json as utf-8-sig
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - Authority:Performing instance discovery: ...
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - Authority:Performing static instance discovery
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - Authority:Authority validated via static instance discovery
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - TokenRequest:Getting token with client credentials.
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - TokenRequest:No user_id passed for cache query
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - CacheDriver:finding with query keys: {'_clientId': '...'}
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - CacheDriver:Looking for potential cache entries: {'_clientId': '...'}
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - CacheDriver:Found 0 potential entries.
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /513294a0-3e20-41b2-a970-6d30bf1546fa/oauth2/token HTTP/1.1" 200 1354
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - OAuth2Client:Get Token Server returned this correlation_id: ca339d31-2592-4f02-8492-aff3d916dc4c
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - CacheDriver:Adding entry AccessTokenId: b'8mIuM6HbijME2p2ELJrGilK/tRorCVihnXZ2yEyMbwI='
adal-python : ca339d31-2592-4f02-8492-aff3d916dc4c - CacheDriver:Added entry is MRRT
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/b5fda631-44bf-4470-bf2c-259d09649075/providers/Microsoft.Insights/components?api-version=2018-05-01-preview'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'User-Agent': 'python/3.8.3 (Linux-5.7.4-arch1-1-x86_64-with-glibc2.2.5) msrest/0.6.16 msrest_azure/0.6.3 azure-mgmt-applicationinsights/0.2.0 Azure-SDK-For-Python AZURECLI/2.8.0'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/b5fda631-44bf-4470-bf2c-259d09649075/providers/Microsoft.Insights/components?api-version=2018-05-01-preview HTTP/1.1" 200 122
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-request-id': 'eccadcc0-b78d-485f-b185-26c79da025e7'
msrest.http_logger :     'x-ms-correlation-request-id': 'eccadcc0-b78d-485f-b185-26c79da025e7'
msrest.http_logger :     'x-ms-routing-request-id': 'BRAZILSOUTH:20200624T011526Z:eccadcc0-b78d-485f-b185-26c79da025e7'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Wed, 24 Jun 2020 01:15:26 GMT'
msrest.http_logger :     'Content-Length': '122'
msrest.http_logger : Response content:
msrest.http_logger : []
msrest.exceptions : Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1403, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1151, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.8/site-packages/knack/cli.py", line 217, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 655, in execute
    raise ex
  File "/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/azure-cli/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 704, in _run_job
    result = list(result)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/paging.py", line 130, in advance_page
    self._derserializer(self, self._response)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1343, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1421, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1403, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1151, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1403, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1151, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.8/site-packages/knack/cli.py", line 217, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 655, in execute
    raise ex
  File "/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/azure-cli/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 704, in _run_job
    result = list(result)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/paging.py", line 130, in advance_page
    self._derserializer(self, self._response)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1343, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1421, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1403, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/azure-cli/lib/python3.8/site-packages/msrest/serialization.py", line 1151, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
cli.azure.cli.core.util : 
To open an issue, please run: 'az feedback'

To open an issue, please run: 'az feedback'
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fef6bd1f670>]
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 5492 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/opt/azure-cli/bin/python /opt/azure-cli/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py /home/david/.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
Command ran in 1.211 seconds (init: 0.028, invoke: 1.183)

```

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/847317c96b37d744f4b837fe1a66ece98a2828cb/specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01-preview/components_API.json#L574-L578

@sameergMS Hi. Service's response is not consistent with swagger spec. Please fix the server's issue.

**Comment by navba-MSFT** [comment]
@dlopes7 Apologies for the late reply. This issue is open for quite sometime. Could you please let us know if you are still facing this issue ? Awaiting your reply.
