### ISSUE TITLE
"az storage blob directory access show" throws error for missing permissions

### ISSUE THREAD

**Issue by TobiTh** [Azure/azure-cli-extensions#1655]
## "az storage blob directory access show" throws error for missing permissions even though they are set on the SP that executes this command. Test for real user results in same error message

**Command Name**
`az storage blob directory access show
Extension Name: storage-preview. Version: 0.2.10.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login --service-principal (redacted)`
- `az storage blob directory access show -d {} -c {} --account-name {}`

## Expected Behavior
The permissions of the directory are printed because the permissions are set on the storage account and the container too. With an user, the same error gets printed

## Environment Summary
```
Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81 *

Extensions:
storage-preview 0.2.10

```

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @TobiTh, `az storage blob directory access show` is for ADLS Gen2 command. Currently we already support it in azure-cli not extension. You can use `az storage fs access` to set/show permissions  of files/directories in your ADLS Gen2 account.

By the way, for the issue you reported, can you share more information with `--debug` in your command?

**Comment by TobiTh** [comment]
Hi @Juliehzl the `az storage fs access show` does work, but only when I add the account-key param.

```
$ az storage fs access show --account-name _redacted_ -f container -p path
Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
ErrorCode:AuthenticationFailed
```
```
$ az storage fs access show --account-name _redacted_ -f container -p path --account-key _redacted_
{
  "acl": "user::rwx,user:_redacted_:rwx,group::r-x,mask::rwx,other::---,default:user::rwx,default:user:_redacted_:rwx,default:group::r-x,default:mask::rwx,default:other::---",
  "group": "_redacted_",
  "owner": "$superuser",
  "permissions": "rwxrwx---+"
}
```

**Comment by TobiTh** [comment]
@Juliehzl Here is the output of the storage extension command with --debug:
```
$ az storage blob directory access show --account-name redacted --container-name container --directory-path path --debug
Command arguments: ['storage', 'blob', 'directory', 'access', 'show', '--account-name', 'redacted', '--container-name', 'container', '--directory-path', 'path', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f2cfcd94378>, <function OutputProducer.on_global_arguments at 0x7f2cfcaf3378>, <function CLIQuery.on_global_arguments at 0x7f2cfcb1c598>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.008 seconds.
Loaded module 'acs' in 0.004 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.004 seconds.
Loaded module 'apim' in 0.001 seconds.
Loaded module 'appconfig' in 0.002 seconds.
Loaded module 'appservice' in 0.008 seconds.
Loaded module 'aro' in 0.003 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.023 seconds.
Loaded module 'batchai' in 0.002 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.004 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.001 seconds.
Loaded module 'cosmosdb' in 0.005 seconds.
Loaded module 'deploymentmanager' in 0.002 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.003 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.002 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.000 seconds.
Loaded module 'find' in 0.000 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.004 seconds.
Loaded module 'kusto' in 0.001 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.002 seconds.
Loaded module 'network' in 0.028 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.003 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.006 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.002 seconds.
Loaded module 'reservations' in 0.001 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.004 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.002 seconds.
Loaded module 'servicebus' in 0.003 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.007 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.054 seconds.
Loaded module 'vm' in 0.013 seconds.
Loaded all modules in 0.267 seconds. (note: there's always an overhead with the first module loaded)
Found 1 extensions: ['storage-preview']
Extension compatibility result: is_compatible=True cli_core_version=2.6.0 min_required=2.0.67 max_required=None
Extensions directory: '/home/redacted/.azure/cliextensions/storage-preview'
Event: CommandLoader.OnLoadCommandTable []
Loaded extension 'storage-preview' in 0.012 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f2cfa1406a8>]
az_command_data_logger : command args: storage blob directory access show --account-name {} --container-name {} --directory-path {} --debug
metadata file logging enabled - writing logs to '/home/redacted/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f2cfa1167b8>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f2cfa116bf8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f2cfa116d90>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f2cf97af620>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f2cfcaf3400>, <function CLIQuery.handle_query_parameter at 0x7f2cfcb1c620>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f2cfa116c80>, <function handler at 0x7f2cf96110d0>]
az_command_data_logger : extension name: storage-preview
az_command_data_logger : extension version: 0.2.10
Command group 'storage blob directory access' is in preview. It may be changed/removed in a future release.
Getting data service client service_type=BlockBlobService
azext_storage_preview.vendored_sdks.azure_adls_storage_preview.v2019_02_02_preview.common._auth : String_to_sign=HEAD











x-ms-client-request-id:ac1217ac-b202-11ea-a99b-00155d00c375
x-ms-date:Fri, 19 Jun 2020 07:58:33 GMT
x-ms-version:2019-02-02
/redacted/container/path
action:getAccessControl
upn:False
azext_storage_preview.vendored_sdks.azure_adls_storage_preview.v2019_02_02_preview.common.storageclient : Client-Request-ID=ac4bbea8-b202-11ea-a99b-00155d00c375 Outgoing request: Method=HEAD, Path=/temporary/gkk, Query={'action': 'getAccessControl', 'upn': 'False', 'timeout': None}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.6.5; Linux 4.19.104-microsoft-standard) AZURECLI/2.6.0 (DEB)', 'x-ms-client-request-id': 'ac1217ac-b202-11ea-a99b-00155d00c375', 'x-ms-date': 'Fri, 19 Jun 2020 07:58:33 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (1): redacted.dfs.core.windows.net:443
urllib3.connectionpool : https://redacted.dfs.core.windows.net:443 "HEAD /container/path?action=getAccessControl&upn=False HTTP/1.1" 403 0
azext_storage_preview.vendored_sdks.azure_adls_storage_preview.v2019_02_02_preview.common.storageclient : Client-Request-ID=ac4bbea8-b202-11ea-a99b-00155d00c375 Receiving Response: Server-Timestamp=Fri, 19 Jun 2020 07:58:32 GMT, Server-Request-ID=dd1769ad-601f-0070-4a0f-4624c1000000, HTTP Status Code=403, Message=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Headers={'server': 'Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-error-code': 'AuthenticationFailed', 'x-ms-request-id': 'dd1769ad-601f-0070-4a0f-4624c1000000', 'x-ms-version': '2019-02-02', 'x-ms-client-request-id': 'ac1217ac-b202-11ea-a99b-00155d00c375', 'date': 'Fri, 19 Jun 2020 07:58:32 GMT'}.
azext_storage_preview.vendored_sdks.azure_adls_storage_preview.v2019_02_02_preview.common.storageclient : Client-Request-ID=ac4bbea8-b202-11ea-a99b-00155d00c375 Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Fri, 19 Jun 2020 07:58:32 GMT, Server-Request-ID=dd1769ad-601f-0070-4a0f-4624c1000000, HTTP status code=403, Exception=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: AuthenticationFailed.
azext_storage_preview.vendored_sdks.azure_adls_storage_preview.v2019_02_02_preview.common.storageclient : Client-Request-ID=ac4bbea8-b202-11ea-a99b-00155d00c375 Retry policy did not allow for a retry: Server-Timestamp=Fri, 19 Jun 2020 07:58:32 GMT, Server-Request-ID=dd1769ad-601f-0070-4a0f-4624c1000000, HTTP status code=403, Exception=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: AuthenticationFailed.

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor (Preview)"
    "Storage Blob Data Reader (Preview)"
    "Storage Queue Data Contributor (Preview)"
    "Storage Queue Data Reader (Preview)"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

Event: CommandInvoker.OnFilterResult []
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : 'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 221, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 149, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 39, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 221, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 149, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 39, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
cli.azure.cli.core.util :
To open an issue, please run: 'az feedback'

To open an issue, please run: 'az feedback'
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f2cfa1408c8>]
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2662 in cache
telemetry.check : Negative: The /home/redacted/.azure/telemetry.txt was modified at 2020-06-19 09:54:49.340491, which in less than 600.000000 s
command ran in 0.515 seconds.

**Comment by Juliehzl** [comment]
Hi @TobiTh, to use `--auth-mode login`, you will need to grant RBAC role according to https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal?toc=/azure/storage/blobs/toc.json#rbac-roles-for-blobs-and-queues.

For more information about ACLs, you can refer to https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-access-control#role-based-access-control.

**Comment by Juliehzl** [comment]
I just added such support in `az storage fs access`  in next release with PR https://github.com/Azure/azure-cli/pull/14506. you could try to use with edge build now or stable version after 08/04/2020.

So I will close the issue now and if you still have problem, feel free to create a new one or reopen it.
