### ISSUE TITLE
AZ CLI THROWING AN EXCEPTION WHILE TRYING TO ACCESS THE AKS

### ISSUE THREAD

**Issue by Sam123ben** [Azure/azure-cli-extensions#1787]
## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.4.35.`

**Errors:**
```
'name'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 2483, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 2427, in _handle_merge
    if i['name'] == j['name']:
KeyError: 'name'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --overwrite-existing`

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.6.0

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"09c357ed5fb70a194790ad4ff9dc3b2cd6336445", GitTreeState:"clean", BuildDate:"2020-04-08T23:39:48Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Extensions:
dev-spaces 1.0.5
aks-preview 0.4.35
azure-devops 0.12.0

```

**Comment by yonzhan** [comment]
aks

**Comment by Sam123ben** [comment]
Not sure i tried by reinstalling the python3, pip3 and then az cli still getting the issue with the az aks command.

Please do help us to resolve this as we are blocked to proceed with our automation further.

`az aks get-credentials --resource-group civ-authority-cloud-rg-v1 --name civ-cloud-nonprod-v1 --overwrite-existing
The behavior of this command has been altered by the following extension: aks-preview
The command failed with an unexpected error. Here is the traceback:

'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/Users/samyakrout/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1266, in aks_get_credentials
    _print_or_merge_credentials(path, kubeconfig, overwrite_existing, context_name)
  File "/Users/samyakrout/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2410, in _print_or_merge_credentials
    merge_kubernetes_configurations(path, temp_path, overwrite_existing, context_name)
  File "/Users/samyakrout/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2483, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
  File "/Users/samyakrout/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2427, in _handle_merge
    if i['name'] == j['name']:
KeyError: 'name'`


az --version
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
dev-spaces                         1.0.5
aks-preview                       0.4.35
azure-devops                      0.12.0

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/samyakrout/.azure/cliextensions'

Python (Darwin) 3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Comment by bpdohall** [comment]
@Sam123ben - You should remove the extension `aks-preview` if you are blocked as the command has different logic in the GA version. `az extension remove --name aks-preview`

@yonzhan - There is a missing test for dictionary key presence in the [aks-preview _handle_merge()](https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/azext_aks_preview/custom.py#L2514). In the [acs module in azure-cli](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/custom.py#L1126) the missing key condition will be skipped.

**Comment by Sam123ben** [comment]
@bpdohall Thanks for that, I have removed the aks-preview as suggested but now I am getting the below error exception:

The command failed with an unexpected error. Here is the traceback:

'users'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 2027, in aks_get_credentials
    _print_or_merge_credentials(path, kubeconfig, overwrite_existing, context_name)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 3198, in _print_or_merge_credentials
    merge_kubernetes_configurations(path, temp_path, overwrite_existing, context_name)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1185, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'users', replace)
  File "/usr/local/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1120, in _handle_merge
    if existing[key] is None:
KeyError: 'users'

**Comment by bpdohall** [comment]
@Sam123ben - seems like your kubeconfig is not playing along nicely at all with the `get-credentials` command.

There are 3 top level keys that should appear in your file `clusters`, `contexts` and `users`. The latest error can likely be resolved by adding a line that contains `users: []` to the end of the file `~/.kube/config`.

I would be tempted to rename the local file `~/.kube/config` and get a fresh start. If there's something in there that you need to recover, you will can always dig in and get it.

@yonzhan - Neither implementation of `_handle_merge` (in `[azure-cli](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/custom.py#L1120)` and `[aks-preview](https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/azext_aks_preview/custom.py#L2508)`) guards against a missing list in the kubeconfig file. I'm not sure whether there's a schema for kubeconfig files that says the key of an empty list must be present.

**Comment by Sam123ben** [comment]
@bpdohall yeah you are rte, i removed it and then it worked but still confused why its like that.

**Comment by navba-MSFT** [comment]
@Sam123ben Apologies for the late reply. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Comment by navba-MSFT** [comment]
@Sam123ben I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by Sam123ben** [comment]
> @Sam123ben I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

Hi, all good i have managed to work on it and fix it.

Thanks

**Comment by navba-MSFT** [comment]
@Sam123ben Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
