### ISSUE TITLE
Error log-analytics query....

### ISSUE THREAD

**Issue by cladic** [Azure/azure-cli-extensions#1799]
## Describe the bug

**Command Name**
`az monitor log-analytics query
Extension Name: log-analytics. Version: 0.1.4.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:



Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\cli.py", line 221, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\output.py", line 149, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\output.py", line 42, in format_json
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\encoder.py", line 202, in encode
    return ''.join(chunks)
MemoryError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor log-analytics query -w {} --analytics-query {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1 *

Extensions:
log-analytics 0.1.4

```

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
@jiasli Please take a look. It's a known issue for Knack/Azure CLI Core.

**Comment by phenggeler** [comment]
I also encountered this issue:

`The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.util : 
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\knack\knack\cli.py", line 221, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\knack\knack\output.py", line 151, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\colorama\colorama\ansitowin32.py", line 41, in write
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\colorama\colorama\ansitowin32.py", line 162, in write
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\colorama\colorama\ansitowin32.py", line 190, in write_and_convert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\colorama\colorama\ansitowin32.py", line 195, in write_plain_text
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
MemoryError`

**Comment by jiasli** [comment]
[`MemoryError`](https://stackoverflow.com/questions/40399933/memoryerror-when-loading-a-json-file) indicates the operating system is running out of memory. 

https://github.com/microsoft/knack/blob/4cb4c2e0516f760b08defa8b9afacc004f7e4fac/knack/output.py#L36-L41
Azure CLI uses the built-in [`json` module](https://docs.python.org/3/library/json.html) to parse the result of `az monitor log-analytics query`. As stated in this [stackoverflow post](https://stackoverflow.com/a/40400130/2199657), the memory usage of JSON data is much higher than that of the original JSON string. 

To temporarily solve this, you may limit the size of returned data with `--timespan` (See `az monitor log-analytics query --help` for more details).

We will evaluate using `json.dump` or `isort` to solve it permanently.

**Comment by jiasli** [comment]
[`MemoryError`](https://stackoverflow.com/questions/40399933/memoryerror-when-loading-a-json-file) indicates the operating system is running out of memory. 

https://github.com/microsoft/knack/blob/4cb4c2e0516f760b08defa8b9afacc004f7e4fac/knack/output.py#L36-L41

```py
def format_json(obj):
    result = obj.result
    # OrderedDict.__dict__ is always '{}', to persist the data, convert to dict first.
    input_dict = dict(result) if hasattr(result, '__dict__') else result
    return json.dumps(input_dict, ensure_ascii=False, indent=2, sort_keys=True, cls=_ComplexEncoder,
                      separators=(',', ': ')) + '\n'
```

Knack uses the built-in [`json` module](https://docs.python.org/3/library/json.html) to dump the result of `az monitor log-analytics query`.

To temporarily solve this, you may limit the size of returned data with `--timespan` (See `az monitor log-analytics query --help` for more details).

We will evaluate possible solutions to avoid saving the result to a variable (memory).
