### ISSUE TITLE
Issue while creating az fusion azure-zone create

### ISSUE THREAD

**Issue by vbalaut** [Azure/azure-cli-extensions#1970]
## Describe the bug

**Command Name**
`az fusion azure-zone create
Extension Name: fusion. Version: 0.4.2.`

**Errors:**
```
JSON is invalid: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
site-packages/msrest/pipeline/universal.py, ln 170, in deserialize_from_text
    return json.loads(data_as_str)
lib/python3.8/json/__init__.py, ln 357, in loads
    return _default_decoder.decode(s)
lib/python3.8/json/decoder.py, ln 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
...

site-packages/msrest/pipeline/universal.py, ln 172, in deserialize_from_text
    raise DeserializationError("JSON is invalid: {}".format(err), err)
msrest.exceptions.DeserializationError: JSON is invalid: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az fusion azure-zone create -g {} -n {} --azure-zone-name {} --storage-account-id {} --storage-container {} --virtual-network-id {} --subnet {} --storage-managed-identity {} --location {} --node-count {} --vm-size {}`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.8.0

Extensions:
fusion 0.4.2

```

**Comment by yonzhan** [comment]
az fusion

**Comment by vbalaut** [comment]
I checked in and found when my role is a contributor and I am using  storage-managed-identity value in command, it's giving me this issue

  return op(**command_args)
  File "/Users/vbalaut/.azure/cliextensions/fusion/azext_fusion/custom.py", line 57, in create_azure_zone
    storage_managed_identity_object = VirtualMachineIdentity.deserialize(**storage_managed_identity,**
  File "/usr/local/Cellar/azure-cli/2.8.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 328, in deserialize

**Comment by yungezz** [comment]
hi @vbalaut which extension you're using ? cannot find `azext_fusion` in our released extensions.
