### ISSUE TITLE
az image copy fails with `No module named azure.cli.__main__

### ISSUE THREAD

**Issue by henti** [Azure/azure-cli-extensions#2079]
## Extension name (the extension in question)
image-copy-extension (version 0.2.6)

### Description of issue (in as much detail as possible)
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"
--
azure-cli:
  Installed: 2.9.1-1~bionic
  Candidate: 2.9.1-1~bionic
  Version table:
 *** 2.9.1-1~bionic 500
        500 https://packages.microsoft.com/repos/azure-cli bionic/main amd64 Packages
        100 /var/lib/dpkg/status

--
azure-cli                          2.9.1

command-modules-nspkg              2.0.3
core                               2.9.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
image-copy-extension               0.2.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/henti/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jul 16 2020, 08:13:20) 
[GCC 7.5.0]
--
henti@henti:~$ az image copy --source-resource-group $old_grp --source-object-name $img --target-location $new_loc --target-resource-group new_grp --target-subscription $new_sub --cleanup
command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'group', 'exists', '-n', 'image-copy-rg', '--output', 'tsv']
output: /opt/az/bin/python3: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed

The command failed with an unexpected error. Here is the traceback:

Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'group', 'exists', '-n', 'image-copy-rg', '--output', 'tsv']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 776, in default_command_handler
    return op(**command_args)
  File "/home/henti/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 29, in imagecopy
    cmd_output = run_cli_command(cli_cmd)
  File "/home/henti/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/henti/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/az/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'group', 'exists', '-n', 'image-copy-rg', '--output', 'tsv']' returned non-zero exit status 1.

To open an issue, please run: 'az feedback'
```
-----

**Comment by yonzhan** [comment]
image copy

**Comment by qwordy** [comment]
How do you install Azure CLI?
Can you try reinstall Azure CLI and extensions?
What's the result of `python3 -m azure.cli group exists -n image-copy-rg --output tsv`

**Comment by henti** [comment]
> How do you install Azure CLI?

apt-get install azure-cli

```
root@henti:~# apt-cache policy azure-cli
azure-cli:
  Installed: 2.11.1-1~bionic
  Candidate: 2.11.1-1~bionic
  Version table:
 *** 2.11.1-1~bionic 100
        100 /var/lib/dpkg/status
```

> Can you try reinstall Azure CLI and extensions?

I've added https://packages.microsoft.com/repos/azure-cli/ repo and updated to latest

```
root@henti:~# apt-cache policy azure-cli
azure-cli:
  Installed: 2.12.1-1~bionic
  Candidate: 2.12.1-1~bionic
  Version table:
 *** 2.12.1-1~bionic 500
        500 https://packages.microsoft.com/repos/azure-cli bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

and updated the `image-copy-extension` extension

> What's the result of `python3 -m azure.cli group exists -n image-copy-rg --output tsv`

```
henti@henti:~$ az group exists -n image-copy-rg --output tsv
false
```

I've since worked around this so not really needed anymore. Close if required.
