### ISSUE TITLE
TypeError: login() got an unexpected keyword argument 'msi'

### ISSUE THREAD

**Issue by eshxd41** [Azure/azure-cli-extensions#2194]
## Describe the bug

**Command Name**
`az login
Extension Name: azure-ml-admin-cli. Version: 0.0.1.`

**Errors:**
```
login() got an unexpected keyword argument 'msi'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-kl_cpqvn\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 711, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-imoq0319\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-d55550gx\azure\cli\core\__init__.py, ln 779, in default_command_handler
.azure\cliextensions\azure-ml-admin-cli\azext_admin\custom.py, ln 88, in mls_login
    msi_port=msi_port)
TypeError: login() got an unexpected keyword argument 'msi'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1

Extensions:
azure-ml-admin-cli 0.0.1

```

**Comment by yonzhan** [comment]
add to S175

**Comment by jiasli** [comment]
Could you share the full command for us to diagnose the issue?

**Comment by amariann** [comment]
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9>az login
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
login() got an unexpected keyword argument 'msi'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 654, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 717, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 710, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-in8b2jw5\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\annm\.azure\cliextensions\azure-ml-admin-cli\azext_admin\custom.py", line 88, in mls_login
    msi_port=msi_port)
TypeError: login() got an unexpected keyword argument 'msi'
To open an issue, please run: 'az feedback'

**Comment by amariann** [comment]
Windows 10

C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9>az version
{
  "azure-cli": "2.16.0",
  "azure-cli-core": "2.16.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-ml-admin-cli": "0.0.1"
  }
}
