### ISSUE TITLE
az aks get-credentials fails if ~/.kube/config exists but is empty

### ISSUE THREAD

**Issue by wtkwsk** [Azure/azure-cli-extensions#2522]
### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
az aks get-credentials [...] fails if the file ~/.kube/config exists but is empty. If the file doesn't exist, or isn't empty it's fine.

Error Message:
```python
The command failed with an unexpected error. Here is the traceback:
string indices must be integers
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/home/wmk6fe/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1433, in aks_get_credentials
    _print_or_merge_credentials(path, kubeconfig, overwrite_existing, context_name)
  File "/home/wmk6fe/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2669, in _print_or_merge_credentials
    merge_kubernetes_configurations(path, temp_path, overwrite_existing, context_name)
  File "/home/wmk6fe/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2742, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
  File "/home/wmk6fe/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2680, in _handle_merge
    if existing[key] is None:
TypeError: string indices must be integers```
-----

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by RakeshMohanMSFT** [comment]
Please uninstall and reinstall aks-preview and retry the operation. Reopen if you still face the issue.
