### ISSUE TITLE
subprocess.CalledProcessError returned non-zero exit status 3.

### ISSUE THREAD

**Issue by dadams0641** [Azure/azure-cli-extensions#2529]
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.7.`

**Errors:**
```
Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Windows-2019-Crowe-Template-NCUS-PRD1_os_disk_snapshot', '--location', 'northcentralus', '--resource-group', 'IS-CoreSystem-PRD1', '--source', '/subscriptions/945ba228-5e34-4294-9834-12b2fd7feca9/resourceGroups/TEMP-image-transfer/providers/Microsoft.Compute/snapshots/Windows-2019-Crowe-Template_os_disk_snapshot-northcentralus', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-object-name {} --source-resource-group {} --target-location {} --target-resource-group {} --target-subscription {} --target-name {}`

## Environment Summary
```
Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Python 3.6.8
Installer: RPM

azure-cli 2.13.0

Extensions:
log-analytics 0.2.1
image-copy-extension 0.2.7

```

**Comment by yungezz** [comment]
hi @qwordy could you pls help to have a look? thanks

**Comment by qwordy** [comment]
@dadams0641 Can you show the traceback? Thanks.

**Comment by dadams0641** [comment]
Sure!

`Getting OS disk ID of the source VM/image
Creating source snapshot
command failed: ['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Windows-2019-Crowe-Template-NCUS-PRD1_os_disk_snapshot', '--location', 'northcentralus', '--resource-group', 'IS-CoreSystem-PRD1', '--source', '/subscriptions/<<removed>>/resourceGroups/TEMP-image-transfer/providers/Microsoft.Compute/snapshots/Windows-2019-Crowe-Template_os_disk_snapshot-northcentralus', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ResourceNotFoundError: Resource Windows-2019-Crowe-Template_os_disk_snapshot-northcentralus is not found.

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Windows-2019-Crowe-Template-NCUS-PRD1_os_disk_snapshot', '--location', 'northcentralus', '--resource-group', 'IS-CoreSystem-PRD1', '--source', '/subscriptions/<<removed>>/resourceGroups/TEMP-image-transfer/providers/Microsoft.Compute/snapshots/Windows-2019-Crowe-Template_os_disk_snapshot-northcentralus', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/home/resadmin/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 105, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/resadmin/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/resadmin/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Windows-2019-Crowe-Template-NCUS-PRD1_os_disk_snapshot', '--location', 'northcentralus', '--resource-group', 'IS-CoreSystem-PRD1', '--source', '/subscriptions/<<removed>>/resourceGroups/TEMP-image-transfer/providers/Microsoft.Compute/snapshots/Windows-2019-Crowe-Template_os_disk_snapshot-northcentralus', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.`

**Comment by qwordy** [comment]
It says "Resource Windows-2019-Crowe-Template_os_disk_snapshot-northcentralus is not found". Can you check if it exists?

**Comment by dadams0641** [comment]
So, that's what I was thinking at first, maybe I got the name, subscription, or RG incorrect, but so far as I can tell, I got them right. 

Here's the command I ran: 

`az image copy --source-object-name "Windows-2019-Crowe-Template-NCUS-PRD1" --source-resource-group "IS-CoreSystem-PRD1" --target-location "North Central US" --target-resource-group "IS-CoreSystem-QA1" --target-subscription "Crowe QA 1" --target-name "Windows-2019-Crowe-Template-NCUS-QA1" --verbose`

![image](https://user-images.githubusercontent.com/8340360/96585294-60f14980-12ad-11eb-8954-15d717563fae.png)

With ResourceID:

`/subscriptions/<<removed>>/resourceGroups/IS-CoreSystem-PRD1/providers/Microsoft.Compute/images/Windows-2019-Crowe-Template-NCUS-PRD1`

**Comment by michaelschmit** [comment]
I am running into this same issue.  What is likely happening is that the original OS disk that was used to create the image no longer exists.  This error is occurring for me as well because I am using packer to generate the image.  Packer creates a temporary resource group, creates a VM, takes an image, then puts the image in the specified resource group.  Finally, Packer cleans up the temporary VM and resource group.  When the copy image command runs it tries to locate the original OS disk that no longer exists and fails.  Perhaps there would be a way to output a better error message to help people who run into this issue as a short term fix.  For a long term fix it would be nice to not have to require the original OS image, but I realize there are likely some azure constraints to work around.  It would be create if azure had the ability to just clone an image rather than these other games that are being played.

**Comment by qwordy** [comment]
A similar issue https://github.com/Azure/azure-cli-extensions/issues/1756. I am still trying to find the cause.

**Comment by qwordy** [comment]
> 
> 
> I am running into this same issue. What is likely happening is that the original OS disk that was used to create the image no longer exists. This error is occurring for me as well because I am using packer to generate the image. Packer creates a temporary resource group, creates a VM, takes an image, then puts the image in the specified resource group. Finally, Packer cleans up the temporary VM and resource group. When the copy image command runs it tries to locate the original OS disk that no longer exists and fails. Perhaps there would be a way to output a better error message to help people who run into this issue as a short term fix. For a long term fix it would be nice to not have to require the original OS disk, but I realize there are likely some azure constraints to work around. It would be great if azure had the ability to just clone an image rather than these other games that are being played.

Totally agree. This extension is full of magic. It is a very long path to copy a image. I suggest Azure service support image copy operation. But unfortunately, they are all devoted to shared image gallery. It is an advanced version of image management. You can have a try. Need some learning time.

**Comment by qwordy** [comment]
I can't reproduce it and find cause so far.

**Comment by yungezz** [comment]
image-copy extension need to be improved systematically, add feature-request to this one.

**Comment by ttt-dlloyd** [comment]
This bug was never fixed and it appears that the az image copy command isn't able to function at all - over a year later from these comments. It isn't a feature request - I don't think that is in dispute. It is a feature that exists but doesn't work. az image copy has been broken for years now without being fixed.

PS /home/csp> az image copy --source-resource-group CustomImagesRG `
>>               --source-object-name Win10MultiV9.5-20220107 `
>>               --target-resource-group CustomImagesRG `
>>               --target-location eastus `
>>               --target-subscription 12345678-1234-1234-1234-605185bb3005 `
>> 
Getting OS disk ID of the source VM/image
Creating source snapshot
command failed: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Win10MultiV9.5-20220107_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'CustomImagesRG', '--source', '/subscriptions/12345678-1234-1234-1234-605185bb3005/resourceGroups/AVDImageBuildRG/providers/Microsoft.Compute/disks/AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: (NotFound) Resource AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88 is not found.
Code: NotFound
Message: Resource AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88 is not found.

The command failed with an unexpected error. Here is the traceback:
Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Win10MultiV9.5-20220107_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'CustomImagesRG', '--source', '/subscriptions/12345678-1234-1234-1234-605185bb3005/resourceGroups/AVDImageBuildRG/providers/Microsoft.Compute/disks/AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/csp/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/csp/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/csp/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/az/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Win10MultiV9.5-20220107_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'CustomImagesRG', '--source', '/subscriptions/12345678-1234-1234-1234-605185bb3005/resourceGroups/AVDImageBuildRG/providers/Microsoft.Compute/disks/AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
