### ISSUE TITLE
webapp remote-connection create fails if specifying --port on version 0.2.7

### ISSUE THREAD

**Issue by hplatou** [Azure/azure-cli-extensions#268]
### Extension name (the extension in question)
webapp

### Description of issue (in as much detail as possible)
The following command will fail when specifying --port after updating to version 0.2.7. Works fine in 0.2.6.
```
webapp remote-connection create --resource-group rg --name name --port xxx 
```
with the following message:
```
connect_ex() takes exactly one argument (2 given)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\xxx\.azure\cliextensions\webapp\azext_webapp\custom.py", line 254, in create_tunnel
    tunnel_server = TunnelServer('', port, host_name, user_name, user_password)
  File "C:\Users\xxx\.azure\cliextensions\webapp\azext_webapp\tunnel.py", line 42, in __init__
    if self.local_port != 0 and not self.is_port_open():
  File "C:\Users\xxx\.azure\cliextensions\webapp\azext_webapp\tunnel.py", line 69, in is_port_open
    if sock.connect_ex('', self.local_port) == 0:
TypeError: connect_ex() takes exactly one argument (2 given)
```
-----

**Comment by patricklee2** [comment]
I suspect this change broke it, I'll test it out
https://github.com/Azure/azure-cli-extensions/commit/8241b5dc24efb4243a1a470e4d504310445463e3#diff-88168b5d56c3f34bf694d46475a1a0b2L68

**Comment by CameronVetter** [comment]
Confirmed this is currently broken, had to revert to 0.2.6 to fix
