### ISSUE TITLE
image-copy-extension - ERROR: Resource <temp-resource-group> is not found

### ISSUE THREAD

**Issue by raghav8888** [Azure/azure-cli-extensions#270]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
[
  {
    "extensionType": "whl",
    "name": "image-copy-extension",
    "version": "0.0.8"
  }
]

### Description of issue (in as much detail as possible)

I'm trying to copy image from one subscription to another under the same tenant, where the location of source and target image is different.

Triggered the below command:

```
az image copy --source-resource-group Images --source-object-name SourceImage --target-name TargetImage --target-location eastus --target-resource-group Images --target-subscription <target-subscription-id>
```

Output:
```
Getting os disk id of the source vm/image
Creating source snapshot
command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'SourceImage_os_disk_snapshot', '--resource-group', 'Images', '--source', '/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: Resource pkros2f7zlqhv52 is not found.

Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'SourceImage_os_disk_snapshot', '--resource-group', 'Images', '--source', '/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/packer/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 78, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/packer/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 35, in run_cli_command
    raise ex
  File "/home/packer/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/az/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'SourceImage_os_disk_snapshot', '--resource-group', 'Images', '--source', '/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
```

**Comment by tamirkamara** [comment]
Hi,

Looks like it doesn't find the source disk resource:
/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52

If I remember currently packer creates the image and then removes the resources used to get there. If that's right it means that the disk (of the vm) is no longer present and that is required for this extension to work...

**Comment by raghav8888** [comment]
I only have the image in my source subscription as the temp resources created while creating the image via packer were cleared up. Now that I'm trying to use the extension to copy it over, it is spitting the above error.

1. I dont see the resource group mentioned packer-Resource-Group-2f7zlqhv52 in the subscription. It fails so fast that I dont believe it ever created that resource group. Please correct me if this might be possible.
2. The ID associated (2f7zlqhv52) is common everytime I tried this. As per my knowledge, this should get changed. Is it possible that some value from testing remained over in the code which it is trying to fetch?

**Comment by raghav8888** [comment]
Below is the debug output

```
Command arguments: ['image', 'copy', '--source-resource-group', 'Images', '--source-object-name', 'SourceImage', '--target-name', 'TargetImage', '--target-location', 'eastus', '--target-resource-group', 'Images', '--target-subscription', '<target-subscription-id>', '--cleanup', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f6376bffbf8>, <function OutputProducer.on_global_arguments at 0x7f6376999b70>, <function CLIQuery.on_global_arguments at 0x7f63767366a8>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x7f6376bffc80>]
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'reservations', 'resource', 'role', 'servicebus', 'servicefabric', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.003 seconds.
Loaded module 'acs' in 0.003 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.003 seconds.
Loaded module 'appservice' in 0.006 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.011 seconds.
Loaded module 'batchai' in 0.002 seconds.
Loaded module 'billing' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'configure' in 0.000 seconds.
Loaded module 'consumption' in 0.005 seconds.
Loaded module 'container' in 0.001 seconds.
Loaded module 'cosmosdb' in 0.003 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.002 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'keyvault' in 0.004 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.004 seconds.
Loaded module 'network' in 0.021 seconds.
Loaded module 'policyinsights' in 0.001 seconds.
Loaded module 'profile' in 0.009 seconds.
Loaded module 'rdbms' in 0.004 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'reservations' in 0.001 seconds.
Loaded module 'resource' in 0.006 seconds.
Loaded module 'role' in 0.002 seconds.
Loaded module 'servicebus' in 0.004 seconds.
Loaded module 'servicefabric' in 0.001 seconds.
Loaded module 'sql' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.021 seconds.
Loaded module 'vm' in 0.019 seconds.
Loaded all modules in 0.178 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/packer/.azure/cliextensions'
Found 1 extensions: ['image-copy-extension']
Extensions directory: '/home/packer/.azure/cliextensions'
Loaded extension 'image-copy-extension' in 0.014 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x7f6375de2730>, <function register_global_subscription_parameter.<locals>.add_subscription_parameter at 0x7f6375e41488>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f6375956158>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f6376999bf8>, <function CLIQuery.handle_query_parameter at 0x7f6376736730>, <function register_global_subscription_parameter.<locals>.parse_subscription_parameter at 0x7f6375e04620>, <function handler at 0x7f637589af28>]
Extensions directory: '/home/packer/.azure/cliextensions'
Extensions directory: '/home/packer/.azure/cliextensions'
Getting os disk id of the source vm/image
command: ['/opt/az/bin/python3', '-m', 'azure.cli', 'image', 'show', '--name', 'SourceImage', '--resource-group', 'Images', '--output', 'json'] ended with output: {
  "id": "/subscriptions/<source-subscription-id>/resourceGroups/Images/providers/Microsoft.Compute/images/SourceImage",
  "location": "westeurope",
  "name": "SourceImage",
  "provisioningState": "Succeeded",
  "resourceGroup": "Images",
  "sourceVirtualMachine": {
    "id": "/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/virtualMachines/pkrvm2f7zlqhv52",
    "resourceGroup": "packer-Resource-Group-2f7zlqhv52"
  },
  "storageProfile": {
    "dataDisks": [],
    "osDisk": {
      "blobUri": null,
      "caching": "ReadWrite",
      "diskSizeGb": 127,
      "managedDisk": {
        "id": "/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52",
        "resourceGroup": "packer-Resource-Group-2f7zlqhv52"
      },
      "osState": "Generalized",
      "osType": "Windows",
      "snapshot": null,
      "storageAccountType": "Standard_LRS"
    },
    "zoneResilient": null
  },
  "tags": null,
  "type": "Microsoft.Compute/images"
}

found DISK: /subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52
source_os_disk_type: DISK. source_os_disk_id: /subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52. source_os_type: Windows
Creating source snapshot
command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'SourceImage_os_disk_snapshot', '--resource-group', 'Images', '--source', '/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: Resource pkros2f7zlqhv52 is not found.

Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'SourceImage_os_disk_snapshot', '--resource-group', 'Images', '--source', '/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/packer/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 78, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/packer/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 35, in run_cli_command
    raise ex
  File "/home/packer/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/az/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'SourceImage_os_disk_snapshot', '--resource-group', 'Images', '--source', '/subscriptions/<source-subscription-id>/resourceGroups/packer-Resource-Group-2f7zlqhv52/providers/Microsoft.Compute/disks/pkros2f7zlqhv52', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
```

**Comment by tamirkamara** [comment]
1 - no, it doesn't spin up a VM from the image.
More details on your questions:

When I say a VM I mean the sources used to create the original image. This can be the original VM used to prepare the source image, a source vhd file in blob or a snapshot for a disk.

packer-Resource-Group-2f7zlqhv52 is coming from the process that created the original image. Packer probably created the group, provisioned a VM, run a bunch of stuff in it and then captured it to an image saved in another group. That image still retains the references to the sources resources (the OS disk here), despite them not existing anymore. 
Since there's no way to access the actual data embedded in the image, we're forced to use the sources used to create it.

**Comment by tamirkamara** [comment]
BTW, if this is something routine you need to do, I'd also look here:
https://azure.microsoft.com/en-us/blog/shared-image-gallery-now-in-limited-public-preview/

This should be the native way to distribute images on Azure

**Comment by tamirkamara** [comment]
@raghav8888 
Can you please close this issue since I don't think there's something wrong here?

**Comment by raghav8888** [comment]
I'm closing this @tamirkamara . I don't think you can help here since this is something Azure sucks at. They should reaaaallly think about use cases when providing features like Images, rather than having people go for workarounds for something as basic of a use case as this. Thank you for your help. I think you have developed something very nice here. Just doesn't fit in my use-case :)

**Comment by riezebosch** [comment]
@tamirkamara I'm currently facing the same issue and understand that a `shared image gallery` is the way forward but it is still preview and not enabled/installed by default.

Why don't you think there's something wrong? From my user perspective, I just can't copy a `managed image` and as far as I can see there's nothing wrong with the image because it is possible to create VM's from it.

**Comment by tamirkamara** [comment]
@riezebosch Are you also using packer?
If no, please post an output of your cli command (add the --debug flag).

**Comment by riezebosch** [comment]
Yes, using packer. At the same time I'm working on a PR to enable zone resiliency on managed image so I probably don't need to copy it to a different region anymore.

**Comment by tamirkamara** [comment]
so @riezebosch as I explained above - packer deletes the VM disk after it creates an Image from it, and since this extension needs that underlining resource it would fail in this case.
(the actual stored image isn't accessible by normal means)
For these cases _Shared Image Galley_ is probably the best option.
