### ISSUE TITLE
Latest webapp up doesn't run on Windows

### ISSUE THREAD

**Issue by fiveisprime** [Azure/azure-cli-extensions#272]
I'm using the latest version of `webapp` and I'm unable to deploy, I get the following error. It seems related to checking the local node version, which I have v8.11.4 installed via the typical node installer (no nvm or anything like that).

When running command `$ az webapp up -n mahernatest123`

```sh
could not convert string to float: '.'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\fivei\.azure\cliextensions\webapp\azext_webapp\custom.py", line 66, in create_deploy_webapp
    data = get_runtime_version_details(lang_details.get('file_loc'), language)
  File "C:\Users\fivei\.azure\cliextensions\webapp\azext_webapp\create_util.py", line 70, in get_runtime_version_details
    version_detected = parse_node_version(file_path)[0]
  File "C:\Users\fivei\.azure\cliextensions\webapp\azext_webapp\create_util.py", line 205, in parse_node_version
    version_detected = sorted(data, key=float, reverse=True)
ValueError: could not convert string to float: '.'
```

**Comment by ahmedelnably** [comment]
@fiveisprime does you package.json contain 8.11.4? if yes can you please change it to 8.11
The command does not check your local node version.

**Comment by fiveisprime** [comment]
No engines field in this project, though I can confirm it's something related to the package.json. Here's the app that's failing to deploy: https://github.com/fiveisprime/TypeScript-Node-Starter/blob/master/package.json

I created a new app with the express generator as a test and it deployed just fine.

**Comment by ahmedelnably** [comment]
You are right, the code is having hard time parsing your package.json
@panchagnula Can you please take a look.
