### ISSUE TITLE
KeyError: 'IngressApplicationGateway' - when installing AGIC add-on with a Service Principal AKS cluster

### ISSUE THREAD

**Issue by axelgMS** [Azure/azure-cli-extensions#2788]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

aks-preview

### Description of issue (in as much detail as possible)

Issue:
Getting error while creating AKS Cluster with AGIC enabled, when Service Principal is used.
Following https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new

From the tests,
it seems that the AZ CLI is having issues when enabling AGIC Add-on with AKS Cluster (either new or existing) with a **Service Principal (either new or existing).**
AGIC Add-on has no issues with MSI AKS Cluster.
 

Error:
'IngressApplicationGateway'

Traceback (most recent call last):
  File "…\cli.py", line 215, in invoke
  File "…\__init__.py", line 654, in execute
  File "…\__init__.py", line 717, in _run_jobs_serially
  File "…\__init__.py", line 710, in _run_job
  File "…\six.py", line 703, in reraise
  File "…\__init__.py", line 688, in _run_job
  File "…\__init__.py", line 325, in __call__
  File "…\__init__.py", line 784, in default_command_handler
  File "…\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 1134, in aks_create
    _add_ingress_appgw_addon_role_assignment(created_cluster, cmd)
  File "…\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 741, in _add_ingress_appgw_addon_role_assignment
    config = result.addon_profiles[CONST_INGRESS_APPGW_ADDON_NAME].config
KeyError: 'IngressApplicationGateway'

CLI Version:
{
  "azure-cli": "2.16.0",
  "azure-cli-core": "2.16.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.60"
  }
}

Also happens with CloudShell

-----

**Comment by yonzhan** [comment]
aks-preview

**Comment by miwithro** [comment]
@akshaysngupta

**Comment by akshaysngupta** [comment]
@axelgMS can you please update the aks-preview extension using `az extension update -n aks-preview` and see if you still see the error ?

**Comment by mbifeld** [comment]
Closing as the above message indicates this is resolved. Please tag me / reopen if this is still an active issue. Thank you!
