### ISSUE TITLE
Error Info from HTTPOperator not returning without --debug flag

### ISSUE THREAD

**Issue by jonathan-innis** [Azure/azure-cli-extensions#2793]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

k8sconfiguration

### Description of issue (in as much detail as possible)

- Error messages that are returned from our RP endpoint are not being propagated back to the user without using the --debug flag. Error that's returned is:
```
UnknownError: Operator returned an invalid status code 'Bad Request'
```

If you have access to the subscription, you can reproduce this error by performing the following commands
```
az account set --subscription 37524548-5887-4df0-a359-38a687fdb3bc
az k8sconfiguration create -n https-auth-config -g joinnis-test --cluster-name joinnis-arc-eus --cluster-type connectedClusters --scope cluster --operator-namespace config5 --operator-instance-name config5
```
-----

**Comment by jonathan-innis** [comment]
Error Info:
```
Command arguments: ['k8sconfiguration', 'create', '-n', 'https-auth-config', '-g', 'joinnis-test', '--cluster-name', 'joinnis-arc-eus', '--cluster-type', 'connectedClusters', '--scope', 'cluster', '--operator-namespace', 'config5', '--operator-instance-name', 'config5', '-u', 'https://github.com/Azure/arc-k8s-demo', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7ff9a6128950>, <function OutputProducer.on_global_arguments at 0x7ff9a607b6a8>, <function CLIQuery.on_global_arguments at 0x7ff9a600f950>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'k8sconfiguration': ['azext_k8sconfiguration']
Loading command modules:
Name                  Load Time    Groups  Commands
Total (0)                 0.000         0         0
These extensions are not installed and will be skipped: ['azext_ai_examples']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
k8sconfiguration          0.279         1         5  /home/joinnis/.azure/cliextensions/k8sconfiguration
Total (1)                 0.279         1         5
Loaded 1 groups, 5 commands.
Found a match in the command table.
Raw command  : k8sconfiguration create
Command table: k8sconfiguration create
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7ff9a5c8a9d8>]
az_command_data_logger : command args: k8sconfiguration create -n {} -g {} --cluster-name {} --cluster-type {} --scope {} --operator-namespace {} --operator-instance-name {} -u {} --debug
metadata file logging enabled - writing logs to '/home/joinnis/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7ff9a5c386a8>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7ff9a5ba4d90>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7ff9a5ba4e18>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7ff9a5ba4f28>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7ff9a607b730>, <function CLIQuery.handle_query_parameter at 0x7ff9a600f9d8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7ff9a5ba4d08>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7ff9a5ba4ea0>]
az_command_data_logger : extension name: k8sconfiguration
az_command_data_logger : extension version: 0.2.2
Command group 'k8sconfiguration' is in preview. It may be changed/removed in a future release.
Getting management service client client_type=SourceControlConfigurationClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Warning! https url is being used without https auth params, ensure the repository url provided is not a private repo
AdalAuthentication.signed_session invoked by Track 1 SDK
Retrieving token from ADAL for resource 'https://management.core.windows.net/'
attempting to read file /home/joinnis/.azure/accessTokens.json as utf-8-sig
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - Authority:Performing instance discovery: ...
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - Authority:Performing static instance discovery
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - Authority:Authority validated via static instance discovery
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - CacheDriver:Found 3 potential entries.
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - CacheDriver:Resource specific token found.
adal-python : 369a26f6-e584-4ef7-9b25-080c431df794 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'fNOlrHNTC9xxrTcXgtDy022psxt48z6480EHyYcSVJI=', RefreshTokenId: b'rNm1UkPdCh9hSxrqg7iT0A34DUSomWTPHW0mISHSXUY='
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/37524548-5887-4df0-a359-38a687fdb3bc/resourceGroups/joinnis-test/providers/Microsoft.Kubernetes/connectedClusters/joinnis-arc-eus/providers/Microsoft.KubernetesConfiguration/sourceControlConfigurations/https-auth-config?api-version=2020-10-01-preview'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '282'
msrest.http_logger :     'User-Agent': 'python/3.6.10 (Linux-4.19.128-microsoft-standard-x86_64-with-debian-bullseye-sid) msrest/0.6.18 msrest_azure/0.6.3 azure-mgmt-kubernetesconfiguration/0.2.0 Azure-SDK-For-Python AZURECLI/2.15.1 (DEB)'
msrest.http_logger : Request body:
msrest.http_logger : {"properties": {"repositoryUrl": "https://github.com/Azure/arc-k8s-demo", "operatorNamespace": "config5", "operatorInstanceName": "config5", "operatorType": "flux", "operatorParams": "", "configurationProtectedSettings": {}, "operatorScope": "cluster", "sshKnownHostsContents": ""}}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/37524548-5887-4df0-a359-38a687fdb3bc/resourceGroups/joinnis-test/providers/Microsoft.Kubernetes/connectedClusters/joinnis-arc-eus/providers/Microsoft.KubernetesConfiguration/sourceControlConfigurations/https-auth-config?api-version=2020-10-01-preview HTTP/1.1" 400 95
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Length': '95'
msrest.http_logger :     'Content-Type': 'application/json'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-request-id': 'f4aceca9-01a7-48e2-861c-e9f3895b143b'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'api-supported-versions': '2019-11-01-Preview, 2020-07-01-Preview, 2020-10-01-Preview'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Server': 'openresty/1.15.8.2'
msrest.http_logger :     'x-ms-correlation-request-id': 'f4aceca9-01a7-48e2-861c-e9f3895b143b'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS2:20201215T024408Z:f4aceca9-01a7-48e2-861c-e9f3895b143b'
msrest.http_logger :     'Date': 'Tue, 15 Dec 2020 02:44:07 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {"Error":{"Code":"ValidationFailed","Message":"Updating immutable properties is not allowed."}}
msrest.exceptions : Operation returned an invalid status code 'Bad Request'
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/home/joinnis/.azure/cliextensions/k8sconfiguration/azext_k8sconfiguration/custom.py", line 105, in create_k8sconfiguration
    name, source_control_configuration)
  File "/home/joinnis/.azure/cliextensions/k8sconfiguration/azext_k8sconfiguration/vendored_sdks/operations/_source_control_configurations_operations.py", line 192, in create_or_update
    raise models.ErrorResponseException(self._deserialize, response)
azext_k8sconfiguration.vendored_sdks.models._models_py3.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

cli.azure.cli.core.azclierror : UnknownError: Operation returned an invalid status code 'Bad Request'
UnknownError: Operation returned an invalid status code 'Bad Request'
```

**Comment by yonzhan** [comment]
k8sconfiguration
