### ISSUE TITLE
azure mesh deployment demo failed 

### ISSUE THREAD

**Issue by jerry2102** [Azure/azure-cli-extensions#2894]
## Describe the bug

**Command Name**
`az mesh deployment create
Extension Name: mesh. Version: 0.10.6.`

**Errors:**
```
BadRequestError: The request content was invalid and could not be deserialized: 'Could not find member 'templateLink' on object of type 'DeploymentDefinition'. Path 'templateLink', line 1, position 16.'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az mesh deployment create --resource-group {} --template-uri {} --parameters {}`

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1
azure-cli-ml 1.19.0

Extensions:
mesh 0.10.6
ai-examples 0.2.5
azure-cli-ml 1.19.0

```

**Comment by yonzhan** [comment]
mesh

**Comment by zhoxing-ms** [comment]
Hi @jerry2102 This is an ARM template related issue, which needs to be investigated by the ARM service team
Could you please help to provide the correlation id? (you can add `--debug` to the original command and find `x-ms-correlation-request-id` in the response headers from the printed information)

**Comment by zhoxing-ms** [comment]
This is an ARM template related issue, which needs to be investigated by the ARM service team

**Comment by jerry2102** [comment]
> Hi @jerry2102 Could you please help to provide the correlation id? (you can add `--debug` to the original command and find `x-ms-correlation-request-id` in the response headers from the printed information)

I re-executed the command and got the detailed error message:

**Comment by jerry2102** [comment]
> Hi @jerry2102 Could you please help to provide the correlation id? (you can add `--debug` to the original command and find `x-ms-correlation-request-id` in the response headers from the printed information)

jiang@Azure:~$ az mesh deployment create --resource-group myResourceGroup --template-uri https://raw.githubusercontent.com/Azure-Samples/service-fabric-mesh/master/templates/helloworld/helloworld.linux.json --parameters "{'location': {'value': 'eastus'}}" --debug
Command arguments: ['mesh', 'deployment', 'create', '--resource-group', 'myResourceGroup', '--template-uri', 'https://raw.githubusercontent.com/Azure-Samples/service-fabric-mesh/master/templates/helloworld/helloworld.linux.json', '--parameters', "{'location': {'value': 'eastus'}}", '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f783cead950>, <function OutputProducer.on_global_arguments at 0x7f783cdff6a8>, <function CLIQuery.on_global_arguments at 0x7f783cd92950>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'mesh': ['azext_mesh']
Loading command modules:
Name                  Load Time    Groups  Commands
Total (0)                 0.000         0         0
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
mesh                      0.053        12        26  /home/jiang/.azure/cliextensions/mesh
ai-examples               0.142         1         1  /opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples
Total (2)                 0.195        13        27
Loaded 13 groups, 27 commands.
Found a match in the command table.
Raw command  : mesh deployment create
Command table: mesh deployment create
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f783caaca60>]
az_command_data_logger : command args: mesh deployment create --resource-group {} --template-uri {} --parameters {} --debug
metadata file logging enabled - writing logs to '/home/jiang/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f783ca5abf8>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f783c9bb378>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f783c9bb400>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f783c9bb510>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f783cdff730>, <function CLIQuery.handle_query_parameter at 0x7f783cd929d8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f783c9bb2f0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f783c9bb488>]
az_command_data_logger : extension name: mesh
az_command_data_logger : extension version: 0.10.6
Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Adding custom headers to the client:
    'x-ms-client-request-id': '268cca42-560c-11eb-96ad-0a580af497ab'
    'CommandName': 'mesh deployment create'
    'ParameterSetName': '--resource-group --template-uri --parameters --debug'
Deploying . . .
You can get the state of the deployment with the cmd
az group deployment show --name helloworld.linux --resource-group myResourceGroup
AdalAuthentication.signed_session invoked by Track 1 SDK
Retrieving token from ADAL for resource 'https://management.core.windows.net/'
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2014
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2014
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/5a4ccd73-a172-4591-a8f2-9c77a32f9f61/resourcegroups/myResourceGroup/providers/Microsoft.Resources/deployments/helloworld.linux?api-version=2020-06-01'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '218'
msrest.http_logger :     'User-Agent': 'python/3.6.10 (Linux-4.15.0-1103-azure-x86_64-with-debian-10.2) msrest/0.6.18 cloud-shell/1.0 msrest_azure/0.6.3 azure-mgmt-resource/10.3.0 Azure-SDK-For-Python AZURECLI/2.17.1 (DEB)'
msrest.http_logger : Request body:
msrest.http_logger : {"templateLink": {"uri": "https://raw.githubusercontent.com/Azure-Samples/service-fabric-mesh/master/templates/helloworld/helloworld.linux.json"}, "parameters": {"location": {"value": "eastus"}}, "mode": "Incremental"}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/5a4ccd73-a172-4591-a8f2-9c77a32f9f61/resourcegroups/myResourceGroup/providers/Microsoft.Resources/deployments/helloworld.linux?api-version=2020-06-01 HTTP/1.1" 400 241
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-request-id': '78fd0538-0399-4bcc-b5c2-88d77e999bde'
msrest.http_logger :     'x-ms-correlation-request-id': '78fd0538-0399-4bcc-b5c2-88d77e999bde'
msrest.http_logger :     'x-ms-routing-request-id': 'SOUTHEASTASIA:20210114T015937Z:78fd0538-0399-4bcc-b5c2-88d77e999bde'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Thu, 14 Jan 2021 01:59:36 GMT'
msrest.http_logger :     'Content-Length': '241'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Could not find member 'templateLink' on object of type 'DeploymentDefinition'. Path 'templateLink', line 1, position 16.'."}}
msrest.exceptions : The request content was invalid and could not be deserialized: 'Could not find member 'templateLink' on object of type 'DeploymentDefinition'. Path 'templateLink', line 1, position 16.'.
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/home/jiang/.azure/cliextensions/mesh/azext_mesh/custom.py", line 293, in deploy_arm_template
    input_yaml_files, deployment_name, parameters, mode, no_wait=no_wait)
  File "/home/jiang/.azure/cliextensions/mesh/azext_mesh/custom.py", line 286, in _deploy_arm_template_core
    return sdk_no_wait(no_wait, smc.deployments.create_or_update, resource_group_name, deployment_name, properties)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 638, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2020_06_01/operations/_deployments_operations.py", line 3014, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2020_06_01/operations/_deployments_operations.py", line 2964, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'templateLink' on object of type 'DeploymentDefinition'. Path 'templateLink', line 1, position 16.'.

cli.azure.cli.core.azclierror : BadRequestError: The request content was invalid and could not be deserialized: 'Could not find member 'templateLink' on object of type 'DeploymentDefinition'. Path 'templateLink', line 1, position 16.'.
BadRequestError: The request content was invalid and could not be deserialized: 'Could not find member 'templateLink' on object of type 'DeploymentDefinition'. Path 'templateLink', line 1, position 16.'.
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f783caacc80>]
az_command_data_logger : exit code: 1
Command ran in 2.178 seconds (init: 0.135, invoke: 2.042)
telemetry.save : Save telemetry record of length 3251 in cache
telemetry.check : Negative: The /home/jiang/.azure/telemetry.txt was modified at 2021-01-14 01:58:11.139202, which in less than 600.000000 s
