### ISSUE TITLE
az network vpn-gateway connection ipsec-policy add not working

### ISSUE THREAD

**Issue by ktleach** [Azure/azure-cli-extensions#2982]
### Extension name (the extension in question)
 az network vpn-gateway connection ipsec-policy add

### Description of issue (in as much detail as possible)
Cannot add an ipsec policy to a connection.  get error. Here is the output

```
az network vpn-gateway connection ipsec-policy add --connection-name Connection-vsite-core-hub-eus --dh-group ECP384 --gateway-name ff65e17342c64f01890f6f5f8d033d1e-eastus-gw --ike-encryption AES256 --ike-integrity SHA384 --ipsec-encryption AES256 --ipsec-integrity SHA256 --pfs-group ECP384 --resource-group rg-core-ntwk-hub-infra000 --sa-data-size 102400000 --sa-lifetime 27000 --no-wait
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/home/ken/.azure/cliextensions/virtual-wan/azext_vwan/custom.py", line 567, in add_vpn_gateway_connection_ipsec_policy
    conn.ipsec_policies.append(
AttributeError: 'NoneType' object has no attribute 'append'
To open an issue, please run: 'az feedback'



PS C:\WINDOWS\system32> az extension list
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "resource-graph",
    "path": "C:\\Users\\Ken Leach\\.azure\\cliextensions\\resource-graph",
    "preview": false,
    "version": "1.0.0"
  },
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "virtual-wan",
    "path": "C:\\Users\\Ken Leach\\.azure\\cliextensions\\virtual-wan",
    "preview": true,
    **"version": "0.2.4"**
  }
]
```
-----

**Comment by yonzhan** [comment]
network

**Comment by 00Kai0** [comment]
Has been fixed: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/custom.py#L6898.
Can you try again? @ktleach
