### ISSUE TITLE
az webapp up crashes instantly: cannot import name 'SnapshotRecoveryRequest'

### ISSUE THREAD

**Issue by timothyparez** [Azure/azure-cli-extensions#317]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### webapp
webapp on the web based CLI at portal.azure.com

### Description of issue (in as much detail as possible)
Until recently I was using `az webapp  up -n somename` and it worked fine.
However since a few days ago, this command simply results in the following error:

```
cannot import name 'SnapshotRecoveryRequest'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 262, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 253, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 141, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 440, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/timothy/.azure/cliextensions/webapp/azext_webapp/custom.py", line 10, in <module>
    from azure.mgmt.web.models import (AppServicePlan, SkuDescription, SnapshotRecoveryRequest, SnapshotRecoveryTarget)
ImportError: cannot import name 'SnapshotRecoveryRequest'
```
-----

**Comment by adewaleo** [comment]
Hello @timothyparez @ahmedelnably, what version of the _webapp_ extension and the _CLI_ are you using?  
Try: `az extension show -n webapp --query version` to get the version of your webapp extension.

There was a breaking change in the SDK / CLI that necessitated [this](https://github.com/Azure/azure-cli-extensions/pull/312/files) pull request and newer version of webapp (0.2.9). 

Updating your extension with `az extension update -n webapp` should fix your issue.

Please let me know if this helps.

cc/ @panchagnula

**Comment by timothyparez** [comment]
That seems to do the trick, thank you very much.
