### ISSUE TITLE
az webapp up failing to create an App Service Plan

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli-extensions#325]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
webapp v 0.2.10

### Description of issue (in as much detail as possible)
trying the following command on a Mac machine gives the following error, also it is defaulting to the wrong location (should default to Central US), this was originally reported by @chrisdias 

~/src/myExpressApp$ az webapp up -n <app name>
Resource group 'appsvc_rg_Linux_westus' already exists.
Creating App service plan 'appsvc_asp_Linux_westus' ...
__init__() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 366, in execute
    cmd.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/commands.py", line 54, in _polish_bad_errors
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/Users/chris/.azure/cliextensions/webapp/azext_webapp/custom.py", line 131, in create_deploy_webapp
    sku=sku_def, reserved=(is_linux or None))
TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given

-----

**Comment by ahmedelnably** [comment]
This is related to moving the webapp extension to the new sdk. @Nking92 is working on a fix right now.

**Comment by ahmedelnably** [comment]
Fix is now available in the latest version
