### ISSUE TITLE
az postgres up fails unpleasantly when database name contains dash

### ISSUE THREAD

**Issue by kw217** [Azure/azure-cli-extensions#3301]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

db-up

### Description of issue (in as much detail as possible)

Based on https://docs.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=bash%2Cclone I tried
```
az postgres up --resource-group s2h-webapp-rg --location uksouth --sku-name B_Gen5_1 --server-name metaswitch-stepstohope-web --database-name s2h-webapp --admin-user s2hadmin --admin-password $ADMIN_PASS --ssl-enforcement enabled
```
and got a failure originating from the database blaming the database name symbol `-`. It looks like the database is created OK, but then when it tried to set up the access controls it fails.

It would be nice if `az postgres up` used a parameter for this (or quoted it), or forbade database names which need escaping.

```
(s2h) ksw@waiheke:~/s2h-webapp$ az postgres up --resource-group s2h-webapp-rg --location uksouth --sku-name B_Gen5_1 --server-name metaswitch-stepstohope-web --database-name s2h-webapp --admin-user s2hadmin --admin-password $ADMIN_PASS --ssl-enforcement enabled
Found existing PostgreSQL Server 'metaswitch-stepstohope-web' in group 's2h-webapp-rg'
Updating existing PostgreSQL Server 'metaswitch-stepstohope-web' with given arguments
Creating PostgreSQL database 's2h-webapp'...
Checking your ip address...
If PostgreSQL server declines your IP address, please create a new firewall rule using:
    `az postgres server firewall-rule create -g s2h-webapp-rg -s metaswitch-stepstohope-web -n {rule_name} --start-ip-address {ip_address} --end-ip-address {ip_address}`
Configuring server firewall rule, 'azure-access', to accept connections from all Azure resources...
Successfully Connected to PostgreSQL.
The command failed with an unexpected error. Here is the traceback:
syntax error at or near "-"
LINE 1: GRANT ALL PRIVILEGES ON DATABASE s2h-webapp TO root
                                            ^
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 807, in default_command_handler
    return op(**command_args)
  File "/home/ksw/.azure/cliextensions/db-up/azext_db_up/custom.py", line 134, in postgres_up
    _run_postgresql_commands(host, user, administrator_login_password, database_name)
  File "/home/ksw/.azure/cliextensions/db-up/azext_db_up/custom.py", line 390, in _run_postgresql_commands
    cursor.execute("GRANT ALL PRIVILEGES ON DATABASE {} TO root".format(database))
psycopg2.errors.SyntaxError: syntax error at or near "-"
LINE 1: GRANT ALL PRIVILEGES ON DATABASE s2h-webapp TO root
                                            ^

To open an issue, please run: 'az feedback'
(s2h) ksw@waiheke:~/s2h-webapp$ 
```

-----

**Comment by yonzhan** [comment]
postgres up

**Comment by kw217** [comment]
Thanks!
