### ISSUE TITLE
az ssh

### ISSUE THREAD

**Issue by timoharecvx** [Azure/azure-cli-extensions#3379]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 0.1.5.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\nnti\.azure\cliextensions\ssh\azext_ssh\custom.py", line 21, in ssh_vm
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip,
  File "C:\Users\nnti\.azure\cliextensions\ssh\azext_ssh\custom.py", line 40, in _do_ssh_op
    ssh_ip = ssh_ip or ip_utils.get_ssh_ip(cmd, resource_group, vm_name, use_private_ip)
  File "C:\Users\nnti\.azure\cliextensions\ssh\azext_ssh\ip_utils.py", line 27, in get_ssh_ip
    parsed_ip_id = tools.parse_resource_id(public_ip_ref.id)
AttributeError: 'NoneType' object has no attribute 'id'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm -n {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.23.0

Extensions:
ssh 0.1.5

```

**Comment by yungezz** [comment]
@N6UDP could you have a look?

**Comment by mbendana** [comment]
The error happens when the target VM doesn't have a public IP address assigned.

parsed_ip_id = tools.parse_resource_id(public_ip_ref.id)

**Comment by N6UDP** [comment]
#3501 dupe as well.
