### ISSUE TITLE
Issue with specific step in CLI Tutorial

### ISSUE THREAD

**Issue by zzfinancing** [Azure/azure-cli-extensions#3383]
## Describe the bug

**Command Name**
`az postgres up
Extension Name: db-up. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host "zzstockloans-postgres-dbserver-cli.postgres.database.azure.com" (40.71.8.203) and accepting
	TCP/IP connections on port 5432?
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\eli\.azure\cliextensions\db-up\azext_db_up\custom.py", line 134, in postgres_up
    _run_postgresql_commands(host, user, administrator_login_password, database_name)
  File "C:\Users\eli\.azure\cliextensions\db-up\azext_db_up\custom.py", line 380, in _run_postgresql_commands
    connection = psycopg2.connect(user=user, host=host, password=password, database=database)
  File "C:\Users\eli\.azure\cliextensions\db-up\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host "zzstockloans-postgres-dbserver-cli.postgres.database.azure.com" (40.71.8.203) and accepting
	TCP/IP connections on port 5432?


```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres up --resource-group {} --location {} --sku-name {} --server-name {} --database-name {} --admin-user {} --admin-password {} --ssl-enforcement {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.23.0

Extensions:
connection 0.1.0
db-up 0.2.2

```

**Comment by yonzhan** [comment]
db up

**Comment by RakeshMohanMSFT** [comment]
This is working now.
