### ISSUE TITLE
Permission denied error when deploying nodejs app using cloud shell

### ISSUE THREAD

**Issue by harshavarma** [Azure/azure-cli-extensions#339]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
`webapp`

### Description of issue (in as much detail as possible)

Followed this guide(https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-nodejs) to deploy a Nodejs based webapp. Instead of using the example repository, I used my own and every time I tried to use the `az webapp up -n` command, I received the below error.

```javascript
Creating Resource group 'appsvc_rg_Linux_australiasoutheast' ...
Resource group creation complete
Creating App service plan 'appsvc_asp_Linux_australiasoutheast' ...
App service plan creation complete
Creating app 'otolith-analysis-client' ....
Webapp creation complete
Updating app settings to enable build after deployment
Creating zip with contents of dir /home/c875e269-d9bb-46c6-865d-1edb1a2a/otolith-analysis-client ...
[Errno 13] Permission denied: '/home/c875e269-d9bb-46c6-865d-1edb1a2a\\otolith-analysis-client.zip'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 366, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 54, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/c875e269-d9bb-46c6-865d-1edb1a2a/.azure/cliextensions/webapp/azext_webapp/custom.py", line 159, in create_deploy_webapp
    zip_file_path = zip_contents_from_dir(src_dir, language)
  File "/home/c875e269-d9bb-46c6-865d-1edb1a2a/.azure/cliextensions/webapp/azext_webapp/create_util.py", line 39, in zip_contents_from_dir
    with zipfile.ZipFile("{}".format(zip_file_path), "w", zipfile.ZIP_DEFLATED) as zf:
  File "/opt/az/lib/python3.6/zipfile.py", line 1090, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/home/c875e269-d9bb-46c6-865d-1edb1a2a\\otolith-analysis-client.zip'
```

**Comment by harshavarma** [comment]
Issue was resolved after I created a `server.js` file.  Previously, the boot settings are in `./bin/www` as I used ExpressJS 4.0 but the `package.json` did have the start script in it pointing to `./bin/www`. So not sure why that didn't work. Closing this now.
