### ISSUE TITLE
`az postgres up` command crashes with an SSL error

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [Azure/azure-cli-extensions#3390]
## Describe the bug

I was working through Azure's [Ruby Postgres Tutorial](https://docs.microsoft.com/en-us/azure/app-service/tutorial-ruby-postgres-app) and was on the [Create Postgres database in Azure](https://docs.microsoft.com/en-us/azure/app-service/tutorial-ruby-postgres-app#create-postgres-database-in-azure) step.

**Command Name**
`az postgres up
Extension Name: db-up. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
FATAL:  SSL connection is required. Please specify SSL options and retry.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/muel42/.azure/cliextensions/db-up/azext_db_up/custom.py", line 134, in postgres_up
    _run_postgresql_commands(host, user, administrator_login_password, database_name)
  File "/Users/muel42/.azure/cliextensions/db-up/azext_db_up/custom.py", line 380, in _run_postgresql_commands
    connection = psycopg2.connect(user=user, host=host, password=password, database=database)
  File "/Users/muel42/.azure/cliextensions/db-up/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
FATAL:  SSL connection is required. Please specify SSL options and retry.


```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az postgres up --resource-group my-resource-group --server-name postgres-server --database-name database_name --admin-user admin --admin-password password --ssl-enforcement Enabled`

## Expected Behavior

A postgres database to be created in the Azure cloud.

## Environment Summary
```
macOS-11.3.1-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0

Extensions:
db-up 0.2.2

```

**Comment by yonzhan** [comment]
db up

**Comment by RakeshMohanMSFT** [comment]
This is working now.
