### ISSUE TITLE
Create of ExpressRoutePort fails with a serialization exception

### ISSUE THREAD

**Issue by jaredr80** [Azure/azure-cli-extensions#340]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
express-route

### Description of issue (in as much detail as possible)

Using: `az network express-route port create -n ERDirect-01 -g "ERDirect-Customer" --bandwidth "10.0 Gbps" --encapsulation Dot1Q --peering-location "Equinix-Ashburn-DC2"`, the command throws a serialization exception for the --bandwidth value. Have tried using:

`--bandwidth "10.0"`
`--bandwidth "10.0 Gbps"`
`--bandwidth "10.0Gbps"`
`--bandwidth "10 Gbps"`
`--bandwidth "10Gbps"`
-----
Exception: 

Unable to serialize value: ['10.0 Gbps'] as type: 'int'., TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 688, in serialize_data
    return self.serialize_basic(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 734, in serialize_basic
    return eval(data_type)(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/jaredro/.azure/cliextensions/express-route/azext_express_route/custom.py", line 112, in create_express_route_port
    return client.create_or_update(resource_group_name, express_route_port_name, port)
  File "/home/jaredro/.azure/cliextensions/express-route/azext_express_route/vendored_sdks/v2018_08_01/operations/express_route_ports_operations.py", line 268, in create_or_update
    **operation_config
  File "/home/jaredro/.azure/cliextensions/express-route/azext_express_route/vendored_sdks/v2018_08_01/operations/express_route_ports_operations.py", line 212, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'ExpressRoutePort')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 574, in body
    return self._serialize(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 446, in _serialize
    target_obj, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 709, in serialize_data
    return self._serialize(data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 483, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 707, in serialize_data
    SerializationError, msg.format(data, data_type), err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 54, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 688, in serialize_data
    return self.serialize_basic(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 734, in serialize_basic
    return eval(data_type)(data)
msrest.exceptions.SerializationError: Unable to serialize value: ['10.0 Gbps'] as type: 'int'., TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

**Comment by tjprescott** [comment]
It is expecting:
`--bandwidth 10 gbps` with no double quotes. But we can definitely make it more resilient.

**Comment by jaredr80** [comment]
Will try and reply back.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jaredr80** [comment]
No luck still: 

`jaredro@JROSS-X1:~$ az network express-route port create -n ERDirect-01 -g ERDirect-Customer--bandwidth 10 gbps  --encapsulation Dot1Q --peering-location "Equinix-Ashburn-DC2"`
Unable to serialize value: ['10', 'gbps'] as type: 'int'., TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 688, in serialize_data
    return self.serialize_basic(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 734, in serialize_basic
    return eval(data_type)(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/jaredro/.azure/cliextensions/express-route/azext_express_route/custom.py", line 112, in create_express_route_port
    return client.create_or_update(resource_group_name, express_route_port_name, port)
  File "/home/jaredro/.azure/cliextensions/express-route/azext_express_route/vendored_sdks/v2018_08_01/operations/express_route_ports_operations.py", line 268, in create_or_update
    **operation_config
  File "/home/jaredro/.azure/cliextensions/express-route/azext_express_route/vendored_sdks/v2018_08_01/operations/express_route_ports_operations.py", line 212, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'ExpressRoutePort')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 574, in body
    return self._serialize(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 446, in _serialize
    target_obj, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 709, in serialize_data
    return self._serialize(data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 483, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 707, in serialize_data
    SerializationError, msg.format(data, data_type), err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 54, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 688, in serialize_data
    return self.serialize_basic(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 734, in serialize_basic
    return eval(data_type)(data)
msrest.exceptions.SerializationError: Unable to serialize value: ['10', 'gbps'] as type: 'int'., TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

**Comment by tjprescott** [comment]
@williexu the issue is the registration of `--bandwidth` in the `express-route port create/update` commands.

You can use the validator for bandwidth from express-route create as an example.

The desired behavior for this command would be slightly different:
`--bandwidth X`  Assume Gbps
`--bandwidth X {Gbps/Mbps}` convert to Gbps
