### ISSUE TITLE
While creating AKS

### ISSUE THREAD

**Issue by Na-Sathish** [Azure/azure-cli-extensions#3424]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.13.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'DeploymentsOperations' object has no attribute 'begin_create_or_update'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/sathish/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1268, in aks_create
    _ensure_container_insights_for_monitoring(
  File "/Users/sathish/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2756, in _ensure_container_insights_for_monitoring
    return _invoke_deployment(cmd, resource_group, deployment_name, template, params,
  File "/Users/sathish/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 329, in _invoke_deployment
    return sdk_no_wait(no_wait, smc.begin_create_or_update, resource_group_name, deployment_name, deployment)
AttributeError: 'DeploymentsOperations' object has no attribute 'begin_create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -n {} -g {} --load-balancer-sku {} --enable-managed-identity --enable-private-cluster --enable-addons {} --generate-ssh-keys --location {} --zones {} {} {} --network-plugin {} --service-cidr {} --dns-service-ip {} --pod-cidr {} --docker-bridge-address {} --vnet-subnet-id {} --node-count {} --vm-set-type {} --enable-cluster-autoscaler --min-count {} --max-count {} --cluster-autoscaler-profile {} --attach-acr {}`

## Environment Summary
```
macOS-11.3.1-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0

Extensions:
aks-preview 0.5.13

```

**Comment by yonzhan** [comment]
route to service team

**Comment by zhoxing-ms** [comment]
@Na-Sathish Hi, this issue should be due to the migration of Track 2 in CLI, and the compatibility code has been added in the latest version of extension. However, you haven't upgraded the CLI to the latest version. So please use `az upgrade --yes` to upgrade your CLI version.
