### ISSUE TITLE
az dms project task create - MongoDB DMS Migration (dms-preview)

### ISSUE THREAD

**Issue by josevan18** [Azure/azure-cli-extensions#3437]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
dms-preview

### Description of issue (in as much detail as possible)
When running the az dms project task create for dms-preview on a MongoDB Migration Project I'm getting the following error

dms project task create --database-options-json .\databaseOptions.json --project-name uws-nt-dmspr1-ldm-e9 -g uws-nt-rg-cdb-ldm --service-name uws-nt-dms1-ldm-e9 --source-connection-json .\sourceConnection.json --target-connection-json .\targetConnection.json --task-type offlinemigration --n Migration-Task-e8a225e0-519c-4233-888a-37f350af13d8 --validate-only

   The behavior of this command has been altered by the following extension: dms-preview
   UnexpectedError: The command failed with an unexpected error. Here is the traceback:
   Unable to deserialize to object: type, KeyError: 'ValidateOracleAzureDbForPostgreSqlSyncTaskProperties'
   Traceback (most recent call last):
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1430, in _deserialize
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1599, in deserialize_data
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1392, in _deserialize
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1472, in _classify_target
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 383, in _classify
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 357, in _flatten_subtype
   KeyError: 'ValidateOracleAzureDbForPostgreSqlSyncTaskProperties'

   During handling of the above exception, another exception occurred:

   Traceback (most recent call last):
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tuw8_17y\knack\cli.py", line 215, in invoke
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 654, in execute
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 709, in _run_job
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-s56abhv8\azure\cli\command_modules\dms\commands.py", line 22, in dms_api_exception_handler
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 688, in _run_job
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 325, in __call__
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\__init__.py", line 784, in default_command_handler
     File "C:\a\_temp\.azclitask\cliextensions\dms-preview\azext_dms\custom.py", line 193, in create_task
       properties=task_properties)
     File "C:\a\_temp\.azclitask\cliextensions\dms-preview\azext_dms\vendored_sdks\datamigration\operations\_tasks_operations.py", line 201, in create_or_update
       deserialized = self._deserialize('ProjectTask', response)
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1356, in __call__
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1434, in _deserialize
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\exceptions.py", line 51, in raise_with_traceback
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1430, in _deserialize
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1599, in deserialize_data
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1392, in _deserialize
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 1472, in _classify_target
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 383, in _classify
     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-482xwhov\msrest\serialization.py", line 357, in _flatten_subtype
   msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: 'ValidateOracleAzureDbForPostgreSqlSyncTaskProperties'
   To open an issue, please run: 'az feedback'
-----

**Comment by yonzhan** [comment]
route to service team
