### ISSUE TITLE
Fail to create AKS cluster 

### ISSUE THREAD

**Issue by ami857** [Azure/azure-cli-extensions#3445]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.7.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'DeploymentsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/ioan-mircea/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1262, in aks_create
    cmd, addon_profiles[CONST_MONITORING_ADDON_NAME])
  File "/home/ioan-mircea/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2667, in _ensure_container_insights_for_monitoring
    validate=False, no_wait=False, subscription_id=subscription_id)
  File "/home/ioan-mircea/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 326, in _invoke_deployment
    return sdk_no_wait(no_wait, smc.create_or_update, resource_group_name, deployment_name, deployment)
AttributeError: 'DeploymentsOperations' object has no attribute 'create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --kubernetes-version {} --generate-ssh-keys --windows-admin-password {} --windows-admin-username {} --vm-set-type {} --network-plugin {} --enable-managed-identity`

## Environment Summary
```
Linux-5.4.0-1047-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.24.0

Extensions:
aks-preview 0.5.7
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jsturtevant** [comment]
running `az extension update --name aks-preview` fix it for me
