### ISSUE TITLE
az ssh vm with service principal not working?

### ISSUE THREAD

**Issue by johnpetersjr** [Azure/azure-cli-extensions#3462]
## Describe the bug
Tried to assume a service principal identity using the "az login --service-principal" command.

Our service principals have access to multiple subscriptions.

I then ran this command to try and login to a VM that the SP has owner access to:

**Command Name**
`az ssh vm -n vmnamegoeshere -g rg-name-goes-here --subscription idgoes-here-you-know-the-drill 
Extension Name: ssh. Version: 0.1.5.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/u217218/.azure/cliextensions/ssh/azext_ssh/custom.py", line 22, in ssh_vm
    public_key_file, private_key_file, use_private_ip, ssh_utils.start_ssh_connection)
  File "/home/u217218/.azure/cliextensions/ssh/azext_ssh/custom.py", line 40, in _do_ssh_op
    ssh_ip = ssh_ip or ip_utils.get_ssh_ip(cmd, resource_group, vm_name, use_private_ip)
  File "/home/u217218/.azure/cliextensions/ssh/azext_ssh/ip_utils.py", line 27, in get_ssh_ip
    parsed_ip_id = tools.parse_resource_id(public_ip_ref.id)
AttributeError: 'NoneType' object has no attribute 'id'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm -n {} -g {} --subscription {}`

## Expected Behavior
I expected to be signed into the remote VM.

## Environment Summary
```
Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Python 3.6.8
Installer: RPM

azure-cli 2.24.2

Extensions:
ssh 0.1.5

```

**Comment by yonzhan** [comment]
ssh vm

**Comment by Juliehzl** [comment]
dupe with #3501
