### ISSUE TITLE
Cli command runs well on terminal but not on gitlab-ci.yml

### ISSUE THREAD

**Issue by kelvinduan2020** [Azure/azure-cli-extensions#3468]
**Gitlab-ci.yml pipeline output**
$ az webapp deployment source sync --name "$AZURE_APP_SERVICE_NAME" --resource-group "$AZURE_RESOURCE_GROUP_NAME"
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Cannot deserialize content-type: text/html
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 1664, in sync_site_repo
    return _generic_site_operation(cmd.cli_ctx, resource_group_name, name, 'sync_repository', slot)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/appservice/_appservice_utils.py", line 20, in _generic_site_operation
    return (operation(resource_group_name, name)
  File "/usr/local/lib/python3.8/site-packages/azure/mgmt/web/v2020_09_01/operations/_web_apps_operations.py", line 27666, in sync_repository
    error = self._deserialize(_models.DefaultErrorResponse, response)
  File "/usr/local/lib/python3.8/site-packages/msrest/serialization.py", line 1367, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/usr/local/lib/python3.8/site-packages/msrest/serialization.py", line 1539, in _unpack_content
    return RawDeserializer.deserialize_from_http_generics(
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html
To open an issue, please run: 'az feedback'
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1

**Comment by yonzhan** [comment]
route to service team

**Comment by kelvinduan2020** [comment]
> route to service team

hi, is there any update for this issue?

**Comment by yonzhan** [comment]
webapp service team should look into this.

**Comment by panchagnula** [comment]
@kelvinduan2020 is the issue specific to this command or CLI commands have the problem with running on gitLab

**Comment by calvinsID** [comment]
Please remove the webapp azure-cli-extensions, as that is deprecated, in favor of core CLI
