### ISSUE TITLE
AZ CLI k8s-extension No such file or directory: 'settings-extension.json'

### ISSUE THREAD

**Issue by maikvandergaag** [Azure/azure-cli-extensions#3475]
Problem while setting up the instance for event grid and following the documentation outline:

https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/custom-locations

**Command Name**
`az k8s-extension create
Extension Name: k8s-extension. Version: 0.4.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: 'settings-extension.json'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\MaikvanderGaag\.azure\cliextensions\k8s-extension\azext_k8s_extension\custom.py", line 102, in create_k8s_extension
    config_settings = __get_config_settings_from_file(configuration_settings_file)
  File "C:\Users\MaikvanderGaag\.azure\cliextensions\k8s-extension\azext_k8s_extension\custom.py", line 276, in __get_config_settings_from_file
    config_file = open(file_path,)
FileNotFoundError: [Errno 2] No such file or directory: 'settings-extension.json'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az k8s-extension create --name {} --extension-type {} --cluster-type {} -c {} -g {} --scope {} --release-namespace {} --configuration-protected-settings-file {} --configuration-settings-file {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: 

azure-cli 2.24.2

Extensions:
connectedk8s 1.1.5
customlocation 0.1.2
k8s-extension 0.4.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by mbifeld** [comment]
Hi @maikvandergaag, checking in on this older issue. Sorry it never got a meaningful reply. Is this still an active issue for you?

**Comment by mbifeld** [comment]
Closing as no response from original author. Please reopen / tag me if this is still an active issue.
