### ISSUE TITLE
Getting errors when trying to run az hcs get-config

### ISSUE THREAD

**Issue by ChipV223** [Azure/azure-cli-extensions#3477]
## Describe the bug

**Command Name**
`az hcs get-config
Extension Name: hcs. Version: 0.4.4.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ARMPipelineClient' object has no attribute 'send'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/cvaughn/.azure/cliextensions/hcs/azext_hcs/custom.py", line 404, in get_config
    cmd, resource_group_name, name, "config")
  File "/home/cvaughn/.azure/cliextensions/hcs/azext_hcs/custom.py", line 305, in custom_provider_request
    response = client.send(request)
AttributeError: 'ARMPipelineClient' object has no attribute 'send'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az hcs get-config --name {} --resource-group {} --subscription {}`

## Environment Summary
```
Linux-5.4.0-1048-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.24.2

Extensions:
hcs 0.4.4
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jsntcy** [comment]
@ChipV223, could you tell us where you installed this extension from as this extension is not hosted in our public extension repo https://github.com/Azure/azure-cli-extensions? If you installed from other places, please contact proper service team as actually we don't which team owns this extension.

**Comment by jsntcy** [comment]
Close this one as there is a duplicated issue #3539
