### ISSUE TITLE
AttributeError: 'ARMPipelineClient' object has no attribute 'send'

### ISSUE THREAD

**Issue by pereirawill** [Azure/azure-cli-extensions#3539]
## Describe the bug

**Command Name**
`az hcs get-config
Extension Name: hcs. Version: 0.4.4.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ARMPipelineClient' object has no attribute 'send'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/will/.azure/cliextensions/hcs/azext_hcs/custom.py", line 404, in get_config
    cmd, resource_group_name, name, "config")
  File "/home/will/.azure/cliextensions/hcs/azext_hcs/custom.py", line 305, in custom_provider_request
    response = client.send(request)
AttributeError: 'ARMPipelineClient' object has no attribute 'send'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az hcs get-config --resource-group {} --name {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.25.0

Extensions:
hcs 0.4.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jsntcy** [comment]
@pereirawill, could you tell us where you installed this extension from as this extension is not hosted in our public extension repo https://github.com/Azure/azure-cli-extensions? If you installed from other places, please contact proper service team as actually we don't know which team owns this extension.

**Comment by pereirawill** [comment]
It's a hashicorp extension for consul managed service.

I've tried to use the following extensions:
az extension add \
  --source https://releases.hashicorp.com/hcs/0.4.4/hcs-0.4.4-py2.py3-none-any.whl
az extension add \
  --source https://releases.hashicorp.com/hcs/0.4.9/hcs-0.4.9-py2.py3-none-any.whl

**Comment by jsntcy** [comment]
@pereirawill, could you please contact hashicorp for help using the email below as they own the extension?

Summary: Microsoft Azure Command-Line Tools HCS Extension
Home-page: https://github.com/hashicorp/cloud-hcs-cli
Author: HashiCorp Cloud
Author-email: team-cloud@hashicorp.com

**Comment by WilliansPereira-CAL** [comment]
thanks @jsntcy

**Comment by pereirawill** [comment]
thanks @jsntcy
