### ISSUE TITLE
az login fails on Linux DSVM

### ISSUE THREAD

**Issue by skurscheid** [Azure/azure-cli-extensions#355]
I am referencing issue #125. This same error seems to still persist on the latest Linux DSVM.

### Extension name (the extension in question)
azure-ml-admin-cli

### Description of issue (in as much detail as possible)
```
$ az login
The behavior of this command has been altered by the following extension: azure-ml-admin-cli
login() got an unexpected keyword argument 'msi'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/extensions/azure-ml-admin-cli/azext_admin/custom.py", line 88, in mls_login
    msi_port=msi_port)
TypeError: login() got an unexpected keyword argument 'msi'
$ az extension remove --name azure-ml-admin-cli
$ az login
The behavior of this command has been altered by the following extension: azure-ml-admin-cli
login() got an unexpected keyword argument 'msi'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/extensions/azure-ml-admin-cli/azext_admin/custom.py", line 88, in mls_login
    msi_port=msi_port)
TypeError: login() got an unexpected keyword argument 'msi'

```
Reboot after removal does not seem to make a difference, as the same error is caused.

Are there any suggestions how to deal with this issue on the Linux DSVM?

-----

**Comment by skurscheid** [comment]
Curiously, the az remove command does not seem to be able to actually remove the extension:

```
$ az extension remove --name azure-ml-admin-cli
$ az extension list
[
  {
    "extensionType": "whl",
    "name": "azure-cli-ml",
    "version": "0.1.50"
  },
  {
    "extensionType": "whl",
    "name": "azure-ml-admin-cli",
    "version": "0.0.1"
  }
]

```

**Comment by marabout2015** [comment]
@skurscheid Here's how @gopitk recommended to remove the extension:
```
sudo -i az extension remove --name azure-ml-admin-cli
```

**Comment by skurscheid** [comment]
@marabout2015 thank you for the suggestion! I just **unsuccessfully** tried to replicate the error on a DSVM which is very strange as I haven't made any changes and the azure-ml-admin-cli extension is in fact still installed.

I will close the issue for now and report back if it re-occurs.
