### ISSUE TITLE
Azure CLI event Hub Error

### ISSUE THREAD

**Issue by markdopag** [Azure/azure-cli-extensions#3564]
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-cli-iot-ext. Version: 0.8.9.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/home/prabakar/.local/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/prabakar/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/prabakar/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/prabakar/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/prabakar/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/prabakar/.local/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/prabakar/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 1325, in iot_hub_monitor_events
    repair=repair, login=login, content_type=content_type, device_query=device_query)
  File "/home/prabakar/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 1369, in _iot_hub_monitor_events
    target = get_iot_hub_connection_string(cmd, hub_name, resource_group_name, include_events=True, login=login)
  File "/home/prabakar/.azure/cliextensions/azure-cli-iot-ext/azext_iot/common/_azure.py", line 158, in get_iot_hub_connection_string
    result['subscription'] = client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events -n {} -d {} --cg {}`

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.7.3
Installer: PIP

azure-cli 2.25.0
azure-cli-iot-ext 0.8.9

Extensions:
azure-cli-iot-ext 0.8.9
azure-iot 0.10.13

```

**Comment by markdopag** [comment]
I am getting error while running IoT hub monitor events
![2021-06-28 11_50_27-Window](https://user-images.githubusercontent.com/86641992/123738506-89acf280-d8c2-11eb-95db-24e87fe97492.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by markdopag** [comment]
I have rectified the issue
