### ISSUE TITLE
az aks update attach acr fails because of monitoring addon issues

### ISSUE THREAD

**Issue by edoboker** [Azure/azure-cli-extensions#3592]
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\edobo\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 1554, in aks_update
    monitoring_addon_enabled = CONST_MONITORING_ADDON_NAME in instance.addon_profiles and \
TypeError: argument of type 'NoneType' is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --name {} --resource-group {} --attach-acr {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.25.0

Extensions:
aks-preview 0.5.0
aro 1.0.0
azure-devops 0.18.0

```
## Additional Context
AKS runs in a private cluster with egress traffic being limited, so it can't create any external connectivity and obviously, my desktop can't reach the cluster (the AKS is private, inside a VNet)

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
This issue is Fixed. Please upgrade to latest version of az cli [2.36.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
