### ISSUE TITLE
ModuleNotFoundError: No module named 'vsts_cd_manager', when running "az appservice kube --help"

### ISSUE THREAD

**Issue by chunliu** [Azure/azure-cli-extensions#3620]
### Extension name (the extension in question)
"appservice-kube": "0.1.20"

### Description of issue (in as much detail as possible)

**Command Name**
`az appservice kube --help`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'vsts_cd_manager'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 582, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 260, in parse_args
    return super().parse_args(args)
  File "/opt/az/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1024, in __call__
    parser.print_help()
  File "/opt/az/lib/python3.6/argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 195, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 250, in format_help
    is_group)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 168, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 306, in load
    loader.versioned_load(self, options)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 241, in __getattribute__
    if callable(self._description) else self._description
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/<HOME>/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 90, in <module>
    from .vsts_cd_provider import VstsContinuousDeliveryProvider
  File "/<HOME>/.azure/cliextensions/appservice-kube/azext_appservice_kube/vsts_cd_provider.py", line 8, in <module>
    from vsts_cd_manager.continuous_delivery_manager import ContinuousDeliveryManager
ModuleNotFoundError: No module named 'vsts_cd_manager'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Remove the old version if there is any: `az extension remove --name appservice-kube`
- Add the latest version: `az extension add --yes --source "https://aka.ms/appsvc/appservice_kube-latest-py2.py3-none-any.whl"`
- Run command: `az appservice kube --help`

## Expected Behavior
There should be no error.

## Environment Summary
```
Linux-5.8.0-1036-azure-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.26.0

Extensions:
k8s-extension 0.5.1
connectedk8s 1.1.5
k8s-configuration 1.0.0
appservice-kube 0.1.20
logicapp 0.1.0
customlocation 0.1.2

```
## Additional Context

A workaround is to comment out Line 90 in `~/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py`

-----

**Comment by yonzhan** [comment]
route to service team

**Comment by peter-jvt** [comment]
Same problem with **az logicapp deployment** when using this extension:
az extension add --yes --source "https://aka.ms/logicapp-latest-py2.py3-none-any.whl"

**Comment by StrawnSC** [comment]
Hi, it looks like you're using the private preview version of the `appservice-kube` extension, which is no longer supported. Could you switch to the new public extension by running the following commands: 
```bash
az extension remove -n "appservice-kube"
az extension add -n "appservice-kube"
```

**Comment by StrawnSC** [comment]
Please reopen this issue if removing then reinstalling the extension doesn't fix the bug
