### ISSUE TITLE
webapp remote-connection error

### ISSUE THREAD

**Issue by cloudsoh** [Azure/azure-cli-extensions#365]
### Extension name
webapp

### Description of issue
My PC OS: Ubuntu 16.04
NET Framework version v4.7
PHP version 7.2
Python version Off
Java version: Off

I wanted to access into the console/terminal of the webapp in my local terminal.

I ran `webapp remote-connection create --resource-group group --name app-name --subscription 123123 --slot dev` then resulted in
```
Exception in thread Thread-125:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.azure/cliextensions/webapp/azext_webapp/custom.py", line 229, in _start_tunnel
    if not _check_for_ready_tunnel(remote_debugging_enabled, tunnel_server):
  File "/home/user/.azure/cliextensions/webapp/azext_webapp/custom.py", line 194, in _check_for_ready_tunnel
    default_port = tunnel_server.is_port_set_to_default()
  File "/home/user/.azure/cliextensions/webapp/azext_webapp/tunnel.py", line 96, in is_port_set_to_default
    url, r.status, r.reason))
knack.util.CLIError: Failed to connect to 'https://app-name-dev.scm.azurewebsites.net/AppServiceTunnel/Tunnel.ashx?GetStatus' with status code '404' and reason 'Not Found'
```
-----

**Comment by cloudsoh** [comment]
> any feedback?

I wonder if it has something to do with my webapp being Windows instead of Linux.

**Comment by ahmedelnably** [comment]
@ranjitnmsft Can you please comment on this.
@cloudsoh I think that could be the cause, I think this command is only supported for Linux App Service Apps

**Comment by panchagnula** [comment]
@patricklee2 - can you look at the reported issue?

**Comment by patricklee2** [comment]
ill take a look

**Comment by patricklee2** [comment]
@cloudsoh  The feature is only supported in Linux ASPs
we are working on windows support, but its not ready yet.
