### ISSUE TITLE
Enable addon error for "azure-keyvault-secrets-provider"

### ISSUE THREAD

**Issue by niklev** [Azure/azure-cli-extensions#3666]
## Describe the bug
CLI error when trying to enable "azure-keyvault-secrets-provider" addon for AKS

**Command Name**
`az aks enable-addons
Extension Name: aks-preview. Version: 0.5.23.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'DeploymentsOperations' object has no attribute 'begin_create_or_update'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\nl\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 3500, in aks_enable_addons
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles[CONST_MONITORING_ADDON_NAME], subscription_id, resource_group_name, name, instance.location, aad_route=False)
  File "C:\Users\nl\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 2967, in _ensure_container_insights_for_monitoring
    return _invoke_deployment(cmd, resource_group, deployment_name, template, params,
  File "C:\Users\nl\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 330, in _invoke_deployment
    return sdk_no_wait(no_wait, smc.begin_create_or_update, resource_group_name, deployment_name, deployment)
AttributeError: 'DeploymentsOperations' object has no attribute 'begin_create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Existing AKS Cluster running AKS 1.20.7
- `az aks enable-addons --addons addons azure-keyvault-secrets-provider --name MY_CLUSTER --resource-group MY_RG --debug`

## Expected Behavior
Addon installed successfully as per documentation 
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

## Environment Summary
```
Windows-10
Python 3.8.9
Installer: MSI

azure-cli 2.23.0 *

Extensions:
aks-preview 0.5.23
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team
