### ISSUE TITLE
[logicApp] Get error when run `az logic workflow list`

### ISSUE THREAD

**Issue by ozbillwang** [Azure/azure-cli-extensions#3702]
## Describe the bug

**Command Name**
`Unknown
Extension Name: logic. Version: 0.1.4.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1620, in deserialize_data
    obj_type = self.dependencies[data_type]
KeyError: 'FlowAccessControlConfiguration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bill/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 663, in cli_execute
    result = invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 704, in _run_job
    result = list(result)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/Users/bill/.azure/cliextensions/logic/azext_logic/vendored_sdks/logic/operations/_workflow_operations.py", line 96, in extract_data
    deserialized = self._deserialize('WorkflowListResult', pipeline_response)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1368, in __call__
    return self._deserialize(target_obj, data)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1649, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1649, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1631, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1620, in deserialize_data
    obj_type = self.dependencies[data_type]
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az logic workflow list`

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.25.0 *

Extensions:
logic 0.1.4
azure-devops 0.18.0
interactive 0.4.5
blueprint 0.3.0

```
## Additional Context

I am the owner of that subscription. Should be not permission issue.

**Comment by yonzhan** [comment]
route to service team

**Comment by ozbillwang** [comment]
thanks @yonzhan 

I also run a test with same command on a virtualbox Ubuntu 20.04, got same error.

**Comment by ozbillwang** [comment]
looks fine to me now. thanks
