### ISSUE TITLE
az aks use-dev-spaces NOT WORKING

### ISSUE THREAD

**Issue by PradeeDevananth** [Azure/azure-cli-extensions#3714]
## Describe the bug

**Command Name**
`az aks use-dev-spaces
Extension Name: dev-spaces. Version: 1.0.6.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
<urlopen error [Errno 11001] getaddrinfo failed>
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1414, in connect
  File "http\client.py", line 918, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Pradeep\.azure\cliextensions\dev-spaces\azext_dev_spaces\custom.py", line 42, in ads_use_dev_spaces
    azds_cli = _install_dev_spaces_cli(update, do_not_prompt)
  File "C:\Users\Pradeep\.azure\cliextensions\dev-spaces\azext_dev_spaces\custom.py", line 136, in _install_dev_spaces_cli
    urlretrieve(setup_url, setup_file)
  File "urllib\request.py", line 247, in urlretrieve
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1397, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks use-dev-spaces -g {} -n {} --space {} --yes`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
dev-spaces 1.0.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by PradeeDevananth** [comment]
Please kindly guide me at least temporary fixes.

**Comment by phealy** [comment]
[Azure Dev Spaces has been retired since May 15th, 2021](https://docs.microsoft.com/en-us/previous-versions/azure/dev-spaces/). The extension cannot function without the backend support for it.

The replacement functionality is [Bridge to Kubernetes](https://docs.microsoft.com/en-us/visualstudio/containers/bridge-to-kubernetes?view=vs-2019) - please check that out and see if it will meet your needs!

**Comment by phealy** [comment]
@yonzhan I don't have access to close this out - can you please do so?
