### ISSUE TITLE
az aks enable-addons failing on windows

### ISSUE THREAD

**Issue by srini247** [Azure/azure-cli-extensions#3760]
## Describe the bug

**Command Name**
`az aks enable-addons
Extension Name: aks-preview. Version: 0.5.25.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'DeploymentsOperations' object has no attribute 'begin_create_or_update'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\savani225\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 3508, in aks_enable_addons
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles[CONST_MONITORING_ADDON_NAME], subscription_id, resource_group_name, name, instance.location, aad_route=False)
  File "C:\Users\savani225\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 2972, in _ensure_container_insights_for_monitoring
    return _invoke_deployment(cmd, resource_group, deployment_name, template, params,
  File "C:\Users\savani225\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 331, in _invoke_deployment
    return sdk_no_wait(no_wait, smc.begin_create_or_update, resource_group_name, deployment_name, deployment)
AttributeError: 'DeploymentsOperations' object has no attribute 'begin_create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons {} --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.23.0 *

Extensions:
account 0.2.1
aks-preview 0.5.25
subscription 0.1.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by nerddtvg** [comment]
It seems that the addons try to update the configuration for `omsagent` even if no changes are required.

**Comment by nerddtvg** [comment]
I found a downgrade to 0.5.12 works. Anything above that fails.

**Comment by navba-MSFT** [comment]
@srini247 Apologies for the late reply. Could you please try to upgrade your [akspreview](https://github.com/Azure/azure-cli-extensions/tree/main/src/aks-preview) extension and [AzCLI version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) and let us know if you are still facing this issue? Also this issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.
