### ISSUE TITLE
az connectedk8s proxy fails with KeyError: 'refreshToken'

### ISSUE THREAD

**Issue by mormond** [Azure/azure-cli-extensions#3762]
## Describe the bug

**Command Name**
`az connectedk8s proxy
Extension Name: connectedk8s. Version: 1.1.3.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'refreshToken'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/mike/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 1712, in client_side_proxy_wrapper
    creds = creds_obj[key2]
KeyError: 'refreshToken'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s proxy --name {} --resource-group {}`

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0

Extensions:
connectedk8s 1.1.3
virtual-wan 0.2.5
azure-firewall 0.9.0
k8s-configuration 1.1.0
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@mormond Apologies for the late reply. Could you please try the below steps and let us know if you still face the issue ?

>az upgrade # Update the Azure CLI version
az extension update --name connectedk8s # This will update the existing connectedk8s extension

az login # Login using you Azure account

Then you can try to run the [az connectedk8s proxy](https://docs.microsoft.com/en-us/cli/azure/connectedk8s?view=azure-cli-latest#az-connectedk8s-proxy) command and let us know if you run into any issues.

Also this issue is open for quite sometime. Please let us know if you still need any assistance on this. Awaiting your reply.
