### ISSUE TITLE
az aks create failed unexpectedly

### ISSUE THREAD

**Issue by agrajm** [Azure/azure-cli-extensions#3763]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.9.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ResourcesOperations' object has no attribute 'create_or_update_by_id'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/agrajm/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1256, in aks_create
    enable_secret_rotation
  File "/home/agrajm/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2318, in _handle_addons_args
    cmd, subscription_id, resource_group_name)
  File "/home/agrajm/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2555, in _ensure_default_log_analytics_workspace_for_monitoring
    async_poller = resources.create_or_update_by_id(default_workspace_resource_id, '2015-11-01-preview',
AttributeError: 'ResourcesOperations' object has no attribute 'create_or_update_by_id'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys --network-plugin {} --vnet-subnet-id {} --docker-bridge-address {} --dns-service-ip {} --service-cidr {} --enable-managed-identity`

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.25.0 *

Extensions:
connectedk8s 1.1.5
aks-preview 0.5.9
spring-cloud 2.3.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by agrajm** [comment]
So the error was because my WSL clock was messed up and when I reset the clock this works. Although the error message could have been improved but closing as its working now.
