### ISSUE TITLE
az network vpn-gateway connection ipsec-policy add issue

### ISSUE THREAD

**Issue by jonathan-jehanno-orange** [Azure/azure-cli-extensions#3775]
## Describe the bug

**Command Name**
`az network vpn-gateway connection ipsec-policy add
Extension Name: virtual-wan. Version: 0.2.7.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\jonat\.azure\cliextensions\virtual-wan\azext_vwan\custom.py", line 591, in add_vpn_gateway_connection_ipsec_policy
    conn.ipsec_policies.append(
AttributeError: 'NoneType' object has no attribute 'append'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vpn-gateway connection ipsec-policy add --resource-group {} --connection-name {} --sa-lifetime {} --sa-data-size {} --gateway-name {} --ike-encryption {} --ike-integrity {} --ipsec-encryption {} --ipsec-integrity {} --dh-group {} --pfs-group {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.1

Extensions:
virtual-wan 0.2.7

```

**Comment by yonzhan** [comment]
network
