### ISSUE TITLE
'IotHubResourceOperations' object has no attribute 'config' - cannot use iot commands via AZ CLI

### ISSUE THREAD

**Issue by esttenorio** [Azure/azure-cli-extensions#3816]
## Describe the bug

After updating AZ cli, command throws error

**Command Name**
`az iot hub invoke-module-method
Extension Name: azure-cli-iot-ext. Version: 0.8.9.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "C:\Users\esttenorio\source\repos\k\.venv\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\esttenorio\source\repos\k\.venv\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "C:\Users\esttenorio\source\repos\k\.venv\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\Users\esttenorio\source\repos\k\.venv\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "C:\Users\esttenorio\source\repos\k\.venv\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\esttenorio\source\repos\k\.venv\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "C:\Users\esttenorio\.azure\cliextensions\azure-cli-iot-ext\azext_iot\operations\hub.py", line 879, in iot_device_module_method
    target = get_iot_hub_connection_string(cmd, hub_name, resource_group_name, login=login)
  File "C:\Users\esttenorio\.azure\cliextensions\azure-cli-iot-ext\azext_iot\common\_azure.py", line 158, in get_iot_hub_connection_string
    result['subscription'] = client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub invoke-module-method --hub-name {} --device-id {} --module-id {} --method-name {} --method-payload {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.3rc1
Installer: PIP

azure-cli 2.27.2
azure-cli-iot-ext 0.8.9

Extensions:
acrtransfer 1.0.0
azure-cli-iot-ext 0.8.9
azure-iot 0.10.15
connectedk8s 1.1.7
k8s-extension 0.6.1
storage-preview 0.7.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by PascalBod** [comment]
I get this error for the following command: `az iot hub device-identity create ...`.

Environment:
* Linux Mint 20.1
* Azure CLI 2.72.2
* azure-iot 0.10.10

**Comment by micdudk** [comment]
I have exactly the same issue trying to run `az iot hub connection-string show` on Azure DevOps hosted agent.

**Comment by digimaun** [comment]
@esttenorio , the legacy IoT extension `azure-cli-iot-ext` has been deprecated for almost 2 years now (in favor of `azure-iot`). Please remove it from your environment. It **will** conflict with `azure-iot`. The only Azure IoT extension you should have installed is `azure-iot`.

@PascalBod Unfortunately updating `azure-cli` will not update your extensions, and in some cases (like the one you are running into) you could update to an `azure cli` version which is not compatible with the specific version of `azure-iot` extension you have installed. You can update the IoT extension with `az extension update --name azure-iot`. You need a more recent version of `azure-iot` to be compatible with `azure-cli 2.72.2`.

If issues are still being run into, I would recommend submitting your issues to the [IoT extension repository](https://github.com/Azure/azure-iot-cli-extension) for dedicated support for `azure-iot`.  The news section on the readme has some data points about compatibility.

@Azure/azure-iot-cli-triage

**Comment by digimaun** [comment]
> I have exactly the same issue trying to run `az iot hub connection-string show` on windows Azure DevOps hosted agent. No issue on ubuntu-latest agents.

@micdudk  Does this issue still persist using the current latest `azure-iot 0.10.17`?

**Comment by micdudk** [comment]
> @micdudk Does this issue still persist on the windows devops hosted agent using the current latest `azure-iot 0.10.17`?
@digimaun I don't know, I switched pipeline to ubuntu and haven't tried windows ones.

**Comment by christian-vorhemus** [comment]
Have you updated the azure-iot extension to the latest version (`az extension update --name azure-iot`)?

**Comment by PascalBod** [comment]
@digimaun I updated the IoT extension, and things are OK now. Thanks!
