### ISSUE TITLE
Unable to Enable OSM on AKS with Kubenet

### ISSUE THREAD

**Issue by vr185123** [Azure/azure-cli-extensions#3820]
## Describe the bug

**Command Name**
`az aks enable-addons
Extension Name: aks-preview. Version: 0.5.28.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rpartition'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/raveendran/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3430, in aks_enable_addons
    cmd, result, random_agent_pool.vnet_subnet_id)
  File "/home/raveendran/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3007, in _add_virtual_node_role_assignment
    vnet_id = vnet_subnet_id.rpartition('/')[0]
AttributeError: 'NoneType' object has no attribute 'rpartition'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons {} --resource-group {} --name {}`

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0 *

Extensions:
aks-preview 0.5.28
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by phealy** [comment]
Please provide additional details around your bug report, like what the cluster networking configuration was and exactly what command failed. The example in the report has redacted arguments.
