### ISSUE TITLE
az network vpn-gateway connection ipsec-policy add python issue

### ISSUE THREAD

**Issue by jonathan-jehanno-orange** [Azure/azure-cli-extensions#3837]
## Describe the bug

**Command Name**
`az network vpn-gateway connection ipsec-policy add
Extension Name: virtual-wan. Version: 0.2.8.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'VpnGatewaysOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/jonathan/.azure/cliextensions/virtual-wan/azext_vwan/custom.py", line 608, in add_vpn_gateway_connection_ipsec_policy
    poller = sdk_no_wait(no_wait, client.create_or_update,
AttributeError: 'VpnGatewaysOperations' object has no attribute 'create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vpn-gateway connection ipsec-policy add -g {} --connection-name {} --dh-group {} --gateway-name {} --ike-encryption {} --ike-integrity {} --ipsec-encryption {} --ipsec-integrity {} --pfs-group {} --sa-data-size {} --sa-lifetime {}`

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0 *

Extensions:
virtual-wan 0.2.8
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
network
