### ISSUE TITLE
az iot hub monitor-events fails

### ISSUE THREAD

**Issue by espenairmine** [Azure/azure-cli-extensions#3856]
## Describe the bug

az iot hub monitor-events fails

**Command Name**
`az iot hub monitor-events
Extension Name: azure-cli-iot-ext. Version: 0.8.9.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\espen\.azure\cliextensions\azure-cli-iot-ext\azext_iot\operations\hub.py", line 1322, in iot_hub_monitor_events
    _iot_hub_monitor_events(cmd, hub_name=hub_name, device_id=device_id,
  File "C:\Users\espen\.azure\cliextensions\azure-cli-iot-ext\azext_iot\operations\hub.py", line 1369, in _iot_hub_monitor_events
    target = get_iot_hub_connection_string(cmd, hub_name, resource_group_name, include_events=True, login=login)
  File "C:\Users\espen\.azure\cliextensions\azure-cli-iot-ext\azext_iot\common\_azure.py", line 158, in get_iot_hub_connection_string
    result['subscription'] = client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

install az, 
add iot hub extension
create hub
monitor events with:

- `az iot hub monitor-events -n {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2
azure-cli-iot-ext 0.8.9
azure-cli-ml 1.5.0

Extensions:
azure-cli-iot-ext 0.8.9
azure-cli-ml 1.5.0
azure-iot 0.10.11

```

**Comment by yonzhan** [comment]
route to service team

**Comment by digimaun** [comment]
@espenairmine , please see this comment for how to resolve this issue  https://github.com/Azure/azure-cli-extensions/issues/3816#issuecomment-928192968.
