### ISSUE TITLE
Deserialization error in `az databricks workspace list`

### ISSUE THREAD

**Issue by coryandrewtaylor** [Azure/azure-cli-extensions#3884]
## Describe the bug

**Command Name**
`az databricks workspace list
Extension Name: databricks. Version: 0.7.3.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1172, in rest_key_extractor
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 704, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "C:\Users\zct3045\.azure\cliextensions\databricks\azext_databricks\vendored_sdks\databricks\operations\_workspaces_operations.py", line 542, in get_next
    error = self._deserialize(_models.ErrorResponse, response)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1368, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1172, in rest_key_extractor
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az upgrade`
- `az extension update -n databricks`
- `az databricks workspace list --resource-group {MyResourceGroup}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

Extensions:
aks-preview 0.4.62
azure-devops 0.18.0
databricks 0.7.3
datafactory 0.5.0
storage-preview 0.2.12

```

**Comment by coryandrewtaylor** [comment]
This error occurred after I logged into Azure via `az login` but did not have an active subscription. I was able to list workspaces successfully by following these steps:

- `az login`
- `az account set --subscription {MySubscription}`
- `az databricks workspace list --resource-group {MyResourceGroup`

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
`az login` will always choose a subscription after successful execution. 

- Could you share the result of `az login` before `az account set`?
- Could you share the `--debug` log with the HTTP trace?
