### ISSUE TITLE
The command failed with an unexpected error.

### ISSUE THREAD

**Issue by ollywenn** [Azure/azure-cli-extensions#3935]
## Describe the bug

**Command Name**
`az account subscription list
Extension Name: account. Version: 0.2.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
''
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 236, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 166, in get_formatter
KeyError: ''

```

## To Reproduce: 

just installed azure cli from msi
first time run.
logged in

- `az account subscription list`

## Expected Behavior
A listing of subscriptions

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

Extensions:
account 0.2.1

```

**Comment by ollywenn** [comment]
noticed that I had previously set 
`az config set core.output=`

After setting
`az config set core.output=jsonc`

'az account subscription list' ran as expected.

WIll leave open as the error message was unexpected error, and could be more specific.

**Comment by yonzhan** [comment]
@jiasli for awareness
