### ISSUE TITLE
Error when querying for current attestation policy

### ISSUE THREAD

**Issue by csegarragonz** [Azure/azure-cli-extensions#3937]
## Describe the bug

**Command Name**
`az attestation policy show
Extension Name: attestation. Version: 0.2.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
It is required that you pass in a value for the "algorithms" argument when calling decode().
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/home/csegarra/.azure/cliextensions/attestation/azext_attestation/manual/custom.py", line 191, in get_policy
    policy = jwt.decode(token, verify=False).get('x-ms-policy', '')
  File "/opt/az/lib/python3.6/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/jwt/api_jwt.py", line 87, in decode_complete
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az attestation policy show --resource-group {} --name {} --attestation-type {}`

## Environment Summary
```
Linux-4.15.0-96-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.27.2

Extensions:
attestation 0.2.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jsntcy** [comment]
@csegarragonz, could you please check the version of pyjwt on your machine? There are some [breaking changes](https://pyjwt.readthedocs.io/en/stable/changelog.html#require-explicit-algorithms-in-jwt-decode-by-default) since pyjwt 2.0.0.
