### ISSUE TITLE
az eventgrid event-subscription list / update commands error

### ISSUE THREAD

**Issue by rkotagiri** [Azure/azure-cli-extensions#3938]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

az eventgrid event-subscription
### Description of issue (in as much detail as possible)
az cli unexpected error
-----
$ az eventgrid event-subscription list --source-resource-id /subscriptions/93a32d2e-e079-4cce-95e6-4ab531782090←[91mThe command failed with an unexpected error. Here is the traceback:←[0m
←[91m'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\rp5662\.azure\cliextensions\eventgrid\azext_eventgrid\custom.py", line 863, in cli_event_subscription_list
    return _list_event_subscriptions_by_resource_id(client, source_resource_id, odata_query, DEFAULT_TOP)
  File "C:\Users\rp5662\.azure\cliextensions\eventgrid\azext_eventgrid\custom.py", line 1758, in _list_event_subscriptions_by_resource_id
    _validate_subscription_id_matches_default_subscription_id(
  File "C:\Users\rp5662\.azure\cliextensions\eventgrid\azext_eventgrid\custom.py", line 1811, in _validate_subscription_id_matches_default_subscription_id
    if provided_subscription_id.lower() != default_subscription_id.lower():
AttributeError: 'NoneType' object has no attribute 'lower'←[0m
To open an issue, please run: 'az feedback'

----------
$ az eventgrid event-subscription list --source-resource-id /subscriptions/93A32D2E-E079-4CCE-95E6-4AB531782090/resourceGroups/MCOM-EASTUS2-DEV-N-GEN-RG/providers/MICROSOFT.STORAGE/STORAGEACCOUNTS/HWAPPDEVNSTEASTUS2001
←[91mThe command failed with an unexpected error. Here is the traceback:←[0m
←[91m'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\rp5662\.azure\cliextensions\eventgrid\azext_eventgrid\custom.py", line 863, in cli_event_subscription_list
    return _list_event_subscriptions_by_resource_id(client, source_resource_id, odata_query, DEFAULT_TOP)
  File "C:\Users\rp5662\.azure\cliextensions\eventgrid\azext_eventgrid\custom.py", line 1758, in _list_event_subscriptions_by_resource_id
    _validate_subscription_id_matches_default_subscription_id(
  File "C:\Users\rp5662\.azure\cliextensions\eventgrid\azext_eventgrid\custom.py", line 1811, in _validate_subscription_id_matches_default_subscription_id
    if provided_subscription_id.lower() != default_subscription_id.lower():
AttributeError: 'NoneType' object has no attribute 'lower'←[0m
To open an issue, please run: 'az feedback'

**Comment by yonzhan** [comment]
route to service team
