### ISSUE TITLE
Can't run list-deleted-path command

### ISSUE THREAD

**Issue by huyu** [Azure/azure-cli-extensions#3949]
When I tried to run this command 
```
az storage fs list-deleted-path -f myfilesystem --auth-mode login --account-name myadlsaccount
```
I got error as below:

## Describe the bug

**Command Name**
`az storage fs list-deleted-path
Extension Name: storage-preview. Version: 0.7.4.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
element indices must be integers
Traceback (most recent call last):
  File "/Users/yuhu/.azure/cliextensions/storage-preview/azext_storage_preview/vendored_sdks/azure_storage_filedatalake/v2020_06_12/_list_paths_helper.py", line 57, in _get_next_cb
    return self._command(
  File "/Users/yuhu/.azure/cliextensions/storage-preview/azext_storage_preview/vendored_sdks/azure_storage_filedatalake/v2020_06_12/_generated/operations/_file_system_operations.py", line 629, in list_blob_hierarchy_segment
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'This request is not authorized to perform this operation using this permission.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.28.0_1/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.28.0_1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.28.0_1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.28.0_1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/Users/yuhu/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 252, in new_handler
    handler(ex)
  File "/Users/yuhu/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 194, in handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.28.0_1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.28.0_1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.28.0_1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/yuhu/.azure/cliextensions/storage-preview/azext_storage_preview/operations/filesystem.py", line 16, in list_deleted_path
    result = list_generator(pages=pages, num_results=num_results)
  File "/Users/yuhu/.azure/cliextensions/storage-preview/azext_storage_preview/track2_util.py", line 30, in list_generator
    page = list(next(pages))
  File "/usr/local/Cellar/azure-cli/2.28.0_1/libexec/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/Users/yuhu/.azure/cliextensions/storage-preview/azext_storage_preview/vendored_sdks/azure_storage_filedatalake/v2020_06_12/_list_paths_helper.py", line 64, in _get_next_cb
    process_storage_error(error)
  File "/Users/yuhu/.azure/cliextensions/storage-preview/azext_storage_preview/vendored_sdks/azure_storage_filedatalake/v2020_06_12/_deserialize.py", line 128, in process_storage_error
    additional_data[info] = error_body[info]
TypeError: element indices must be integers

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage fs list-deleted-path -f {} --auth-mode {} --account-name {}`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.28.0 *

Extensions:
storage-preview 0.7.4
account 0.2.1

```

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
