### ISSUE TITLE
'az webpubsub client start' generated an error

### ISSUE THREAD

**Issue by mithunshanbhag** [Azure/azure-cli-extensions#3966]
## Describe the bug

**Command Name**
`az webpubsub client start --hub-name MYHUBNAME --user-id MYUSERNAME -n MYRESOURCENAME -g MYRESOURCEGROUPNAME

Extension Name: webpubsub. Version: 0.2.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
server rejected WebSocket connection: HTTP 500
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\localadmin\.azure\cliextensions\webpubsub\azext_webpubsub\client.py", line 58, in start_client
    asyncio.get_event_loop().run_until_complete(connect(token['url']))
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "C:\Users\localadmin\.azure\cliextensions\webpubsub\azext_webpubsub\client.py", line 43, in connect
    async with websockets.connect(url, subprotocols=['json.webpubsub.azure.v1']) as ws:
  File "C:\Users\localadmin\.azure\cliextensions\webpubsub\websockets\client.py", line 517, in __aenter__
    return await self
  File "C:\Users\localadmin\.azure\cliextensions\webpubsub\websockets\client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "C:\Users\localadmin\.azure\cliextensions\webpubsub\websockets\client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 500
```

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.0

Extensions:
azure-devops 0.18.0
webpubsub 0.2.1

```
## Additional Context

This issue occurs only for some hub names. For other hub names, it generates above error.

**Comment by yonzhan** [comment]
route to service team

**Comment by mithunshanbhag** [comment]
We can close this issue as it's no longer occuring in the latest version of AZ CLI.
