### ISSUE TITLE
Error on adding NAT collection to the existing firewall policy 

### ISSUE THREAD

**Issue by konbec** [Azure/azure-cli-extensions#3986]
## Describe the bug

**Command Name**
`az network firewall policy rule-collection-group collection add-nat-collection
Extension Name: azure-firewall. Version: 0.12.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/beckerk/homebrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/beckerk/homebrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/Users/beckerk/homebrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/beckerk/homebrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/Users/beckerk/.azure/cliextensions/azure-firewall/azext_firewall/_exception_handler.py", line 13, in exception_handler
    raise ex
  File "/Users/beckerk/homebrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/Users/beckerk/homebrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/beckerk/homebrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/beckerk/.azure/cliextensions/azure-firewall/azext_firewall/custom.py", line 780, in add_azure_firewall_policy_nat_rule_collection
    ip_protocols = list(map(FirewallPolicyRuleNetworkProtocol, ip_protocols))
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network firewall policy rule-collection-group collection add-nat-collection --collection-priority {} --name {} --policy-name {} --rcg-name {} --resource-group {}`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.0

Extensions:
azure-firewall 0.12.0

```

**Comment by YuanyuanNi** [comment]
Hi, 
    @konbec  this command works well in the below format, maybe you can update your CLI version and  try again:
az network firewall policy rule-collection-group collection add-nat-collection -n mynatc --policy-name mypolicy01 --rule-collection-group-name myrcg -g nyy02 --collection-priority 10005 --action DNAT --rule-name network-rule --description "test" --destination-addresses "202.120.36.15" --source-addresses "202.120.36.13" "202.120.36.14" --translated-address 128.1.1.1 --translated-port 1234 --destination-ports 12000 --ip-protocols TCP UDP
![image](https://user-images.githubusercontent.com/95396631/174989205-b2733e9c-8c1b-46e2-9e7e-64b3a52353d1.png)
Best wishes.
