### ISSUE TITLE
az ssh vm - 'Profile' object has no attribute 'get_msal_token' - az version 2.30.0

### ISSUE THREAD

**Issue by wase90168** [Azure/azure-cli-extensions#4056]
## Describe the bug

Since latest update `az ssh vm --ip {}` is not working anymore with AzureAD users.

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 0.1.5.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'Profile' object has no attribute 'get_msal_token'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/***/.azure/cliextensions/ssh/azext_ssh/custom.py", line 22, in ssh_vm
    public_key_file, private_key_file, use_private_ip, ssh_utils.start_ssh_connection)
  File "/home/***/.azure/cliextensions/ssh/azext_ssh/custom.py", line 48, in _do_ssh_op
    cert_file, username = _get_and_write_certificate(cmd, public_key_file, None)
  File "/home/***/.azure/cliextensions/ssh/azext_ssh/custom.py", line 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
AttributeError: 'Profile' object has no attribute 'get_msal_token'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --ip {}`

## Expected Behavior

The command should open a ssh connection to the VM/Server/...

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by AndrewFromMelbourne** [comment]
I have had the same issue. I am running az on a Mac installed using Brew. I found a workaround. The issue appears to be with the ssh extension that is downloaded and installed in ~/.azure/cliextensions/ssh
I removed the contents of the directory and next time I ran "az ssh vm --ip {}" I was asked to install the ssh extension. Everything worked after that. Your milage may vary.

**Comment by 9numbernine9** [comment]
@AndrewFromMelbourne 's solution worked for me as well. If an update to the extension is required, it would be nice to find out _before_ the stacktrace appears on my terminal. 😃

**Comment by wase90168** [comment]
@AndrewFromMelbourne
Thanks, your solution worked for me.
For the records: I am using Ubuntu20.04 on Windows Subsystem for Linux (Win11).

As mentioned previously it would be realy nice to get that info before the stacktrace...
