### ISSUE TITLE
Kusto Extension error when creating kusto cluster by "az kusto cluster create"

### ISSUE THREAD

**Issue by lsl-msft** [Azure/azure-cli-extensions#4086]
## Describe the bug

**Command Name**
`az kusto cluster create
Extension Name: kusto. Version: 0.4.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
local variable 'deserialized' referenced before assignment
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/shilei/.azure/cliextensions/kusto/azext_kusto/generated/custom.py", line 122, in kusto_cluster_create
    parameters=parameters)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 646, in sdk_no_wait
    return func(*args, **kwargs)
  File "/home/shilei/.azure/cliextensions/kusto/azext_kusto/vendored_sdks/kusto/operations/_clusters_operations.py", line 226, in begin_create_or_update
    **kwargs
  File "/home/shilei/.azure/cliextensions/kusto/azext_kusto/vendored_sdks/kusto/operations/_clusters_operations.py", line 171, in _create_or_update_initial
    return cls(pipeline_response, deserialized, {})
UnboundLocalError: local variable 'deserialized' referenced before assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az kusto cluster create --cluster-name {} --sku {} {} --resource-group {} --location {}`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
aks-preview 0.5.34
kusto 0.4.0
ai-examples 0.2.5
ssh 0.1.8

```

**Comment by yonzhan** [comment]
route to service team

**Comment by cchildress** [comment]
I can also reproduce this in an automated release tool we use. Is anyone assigned to triage this?
```
Linux-5.4.0-1067-azure-x86_64-with-debian-buster-sid, Ubuntu 18.04.6 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
resource-graph 1.1.0
kusto 0.4.0
```

**Comment by jsntcy** [comment]
@zoharHenMicrosoft, could you please take a look at this issue?

**Comment by zoharHenMicrosoft** [comment]
> @zoharHenMicrosoft, could you please take a look at this issue?

yes, will take a look now, sorry for the delay

**Comment by zoharHenMicrosoft** [comment]
https://github.com/Azure/azure-cli-extensions/pull/4360

**Comment by RakeshMohanMSFT** [comment]
This is fixed. Reopen if you are still facing this issue.
![image](https://user-images.githubusercontent.com/49954584/210966173-3e877bf6-dda0-4df9-8b73-04e319dd143f.png)
