### ISSUE TITLE
can't create cluster

### ISSUE THREAD

**Issue by lexx42** [Azure/azure-cli-extensions#4116]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.42.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'DecoratorEarlyExitException' from 'azure.cli.command_modules.acs._consts' (/opt/homebrew/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/command_modules/acs/_consts.py)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/lars.theiss/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 969, in aks_create
    from azext_aks_preview.decorator import AKSPreviewModels
  File "/Users/lars.theiss/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 10, in <module>
    from azure.cli.command_modules.acs._consts import (
ImportError: cannot import name 'DecoratorEarlyExitException' from 'azure.cli.command_modules.acs._consts' (/opt/homebrew/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/command_modules/acs/_consts.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --enable-addons {} --generate-ssh-keys --vnet-subnet-id {} --node-vm-size {} --dns-name-prefix {} --enable-aad --aad-admin-group-object-ids {} --disable-local-accounts --enable-managed-identity --assign-identity {} --kubernetes-version {}`

## Environment Summary
```
macOS-12.0.1-arm64-arm-64bit, Darwin 21.1.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.2 *

Extensions:
aks-preview 0.5.42
azure-devops 0.20.0
account 0.2.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by mario-galindo** [comment]
I had the same issue please let me know what is wrong, it's happen only when installed the az extension aks-preview

**Comment by sonjubei** [comment]
Spent a while in VS Code trying to get it to work; attempting to use preview functionality of overriding node rg name and separating nodes and pods into different subnets.
Ended up working fine in Cloud Shell:
az aks create -n $clusterName -g $resourceGroup --node-resource-group $nodeResourceGroup vnet-subnet-id  $mcNodeSubscription --pod-subnet-id $podSubscription etc etc

**Comment by mario-galindo** [comment]
Thanks @sonjubei  I tried to do that on azure cloud shell and it goes well for me.

**Comment by AlekseyBlokhin** [comment]
Works for me after `az upgrade`

**Comment by FumingZhang** [comment]
Hi @lexx42, @mario-galindo @sonjubei and @AlekseyBlokhin, sorry for the inconvenience, please update both azure-cli (2.31.0, via `az upgrade`) and aks-preview (0.5.48, via `az extension update -n aks-preview`) to the latest version.

**Comment by lexx42** [comment]
Thanks @FumingZhang!  Works now as expected.
