### ISSUE TITLE
ssh generic config fails

### ISSUE THREAD

**Issue by llegouez** [Azure/azure-cli-extensions#4119]
## Describe the bug
ssh generic config fails. It creates a new folder az_ssh_config instead of the expected output file set in parameter and exit on error the filename is incorrect az_ssh_config\*

**Command Name**
`az ssh config
Extension Name: ssh. Version: 1.0.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\az_ssh_config\\*'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\laurenle\.azure\cliextensions\ssh\azext_ssh\custom.py", line 53, in ssh_config
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip, public_key_file, private_key_file, use_private_ip,
  File "C:\Users\laurenle\.azure\cliextensions\ssh\azext_ssh\custom.py", line 90, in _do_ssh_op
    public_key_file, private_key_file, delete_keys = _check_or_create_public_private_files(public_key_file,
  File "C:\Users\laurenle\.azure\cliextensions\ssh\azext_ssh\custom.py", line 189, in _check_or_create_public_private_files
    os.makedirs(credentials_folder)
  File "os.py", line 223, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\az_ssh_config\\*'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
az login
- `az ssh config --ip {} --file {} --overwrite`
az ssh config --ip * --file c:\mysshconfig.txt

## Expected Behavior
should create c:\mysshconfig.txt with generic config but creates empty folder C:\az_ssh_config and exit on error

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

Extensions:
portal 0.1.2
ssh 1.0.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@llegouez Apologies for the late reply. Could you please follow the below action plan in the order and let me know if that works ?

>az ssh config --ip 23.XXX.XX.86 --file ./sshconfig  # Add the right public IP address of the VM and relative path for --file
ssh -F ./sshconfig 23.XXX.XX.86

You can give the relative path for the --file parameter instead of the absolute path. Please let me know if you face any issues. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@llegouez This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Comment by llegouez** [comment]
Hi @navba-MSFT I got a new laptop and do not have this issue anymore with it
Thanks for your support
