### ISSUE TITLE
Interactive mode 'progress' causes visual corruption when output errors

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli-extensions#413]
### Description
When errors happen with `--progress` set, errors cause the output to become corrupted.

---

```
az>> az vm create -g MyRG -n MyVM --image UbuntuLTS --progress
az>> Exception in thread Thread-120:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inn
    self.run()
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azclishell/app.py", line 736, in run
    self.func(self.args)
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 346, in __cal
    return self.handler(*args, **kwargs)                     *--image:
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 542, in _exec
    exception_handler(ex)                                    *URN, Custom Image name or ID, or VHD Blob URI). 
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 66, in handle_long
    raise cli_error                                          *be replaced by others (for example, `--attach-os-disk`).
CLIError: Deployment failed. {                               *
  "error": {--------------------------------------------------------------------------------------------------------------
    "code": "Conflict",ntu VM with automatic SSH authentication.
    "message": "The request failed due to conflict with a concurrent request. "
  }
}2] Create a simple Windows Server VM with a private IP address.
az vm create -n MyVm -g MyResourceGroup
az>> 
```

**Comment by yonzhan** [comment]
add feature request.
