### ISSUE TITLE
az aks create with '--enable-addons monitoring' options fails with 'DeploymentsOperations' object has no attribute 'create_or_update'

### ISSUE THREAD

**Issue by spockmonster** [Azure/azure-cli-extensions#4130]
## Describe the bug

I'm following the quickstart https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough

these 2 providers are installed:
az provider show -n Microsoft.OperationsManagement -o table
az provider show -n Microsoft.OperationalInsights -o table

this cmd fails: 
    az aks create --resource-group MyGroup --name MyAks --node-count 1 --enable-addons monitoring --generate-ssh-keys

if the command includes --enable-addons monitoring then this fails.  It worked in the office on my Windows 10 Pro machine.  It fails on both my Windows 11 Intel i7 8th Gen , latest az cli, and the Azure Portal Bash shell

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.4.70.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'DeploymentsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/michael/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1085, in aks_create
    _ensure_container_insights_for_monitoring(cmd, addon_profiles[CONST_MONITORING_ADDON_NAME])
  File "/home/michael/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2223, in _ensure_container_insights_for_monitoring
    validate=False, no_wait=False, subscription_id=subscription_id)
  File "/home/michael/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 304, in _invoke_deployment
    return sdk_no_wait(no_wait, smc.create_or_update, resource_group_name, deployment_name, deployment)
AttributeError: 'DeploymentsOperations' object has no attribute 'create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- running on Windows 11, az cli 2.30.0 or in Azure Portal Bash shell
az aks create --resource-group MyGroup --name MyAks --node-count 1 --enable-addons monitoring --generate-ssh-keys

## Expected Behavior
AKS cluster is created, cli reports no error

## Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
aks-preview 0.4.70
azure-iot 0.10.11
ai-examples 0.2.5
ssh 0.1.8

```

**Comment by yonzhan** [comment]
route to service team

**Comment by spockmonster** [comment]
It is noted that the command output states "The behavior of this command has been altered by the following extension: aks-preview"

The Windows machine had previous installed the aks-preview extension for azure cli.  Removing this extension corrected the malbehavior.

Removed the extension with the following az cli command;
az extension remove -n aks-preview
