### ISSUE TITLE
az containerapp create: mapping values are not allowed here in components dapr file

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-cli-extensions#4145]
### Extension name
containerapp-0.2.0-py2.py3-none-any.whl

### Description of issue
I am trying to run the following command,
```
# variables are defined

az containerapp create `
  --name capp-web-blazor-demo `
  --resource-group $RESOURCE_GROUP `
  --environment $CONTAINERAPPS_ENVIRONMENT `
  --image $IMAGE `
  --registry-login-server $REGISTRY `
  --registry-username $REGISTRY_USERNAME `
  --registry-password $REGISTRY_PASSWORD `
  --target-port 3000 `
  --ingress 'external' `
  --min-replicas 1 `
  --max-replicas 1 `
  --enable-dapr `
  --dapr-app-port 3000 `
  --dapr-app-id web-blazor `
  --dapr-components ./components.yaml
```

And my components.yaml looks like this,
```
- name: statestore
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: stcontainerappsdemo
  - name: accountKey
    value: <accountKey>
  - name: containerName
    value: <containerName>
```
And I am getting this error.
```
Command group 'containerapp' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
mapping values are not allowed here
  in "./components.yaml", line 2, column 7
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 719, in _run_job
  File "C:\Users\Jaliya\.azure\cliextensions\containerapp\azext_workerapp\_client_factory.py", line 38, in _polish_bad_errors
    raise ex
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
  File "C:\Users\Jaliya\.azure\cliextensions\containerapp\azext_workerapp\custom.py", line 370, in create_containerapp
    containerapp_dapr_def.components = dapr_components_from_file(cmd, dapr_components)
  File "C:\Users\Jaliya\.azure\cliextensions\containerapp\azext_workerapp\_utils.py", line 11, in dapr_components_from_file
    data = yaml.safe_load(stream)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\__init__.py", line 162, in safe_load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\__init__.py", line 114, in load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\constructor.py", line 49, in get_single_data
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\composer.py", line 36, in get_single_node
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\composer.py", line 55, in compose_document
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\composer.py", line 84, in compose_node
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\composer.py", line 127, in compose_mapping_node
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\parser.py", line 98, in check_event
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\parser.py", line 428, in parse_block_mapping_key
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\scanner.py", line 116, in check_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\scanner.py", line 223, in fetch_more_tokens
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-waxf8o25\yaml\scanner.py", line 579, in fetch_value
yaml.scanner.ScannerError: mapping values are not allowed here
  in "./components.yaml", line 2, column 7
```
And I can do `rapr run` locally without any issues.
![image](https://user-images.githubusercontent.com/5653381/143191641-ddd44d7b-05be-4eb2-9861-3d62975136a9.png)

 I am not seeing anything wrong with the `./components.yaml` file. It's following the same pattern as in here: [https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash#set-up-a-state-store](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash#set-up-a-state-store)

**Comment by yonzhan** [comment]
route to service team

**Comment by calvinsID** [comment]
hi @jaliyaudagedara, this error is to do with the yaml parsing. Can you please double check your yaml file contents, specifically in "./components.yaml", line 2, column 7? (spacing, etc)

**Comment by jaliyaudagedara** [comment]
@calvinsID, I have like triple-checked, it's exactly the same as what I posted above with values replaced.

**Comment by jaliyaudagedara** [comment]
Managed to get it to work, It turned out it's the stupid encoding.

![image](https://user-images.githubusercontent.com/5653381/143193597-96ad6aaf-86f2-4d66-8ac9-35645d773196.png)

**Comment by navba-MSFT** [comment]
@jaliyaudagedara Apologies for the late reply. Thanks for your update. I am glad that the issue is resolved. We will now proceed with the closure of this thread. If you need any further assistance on this, please feel free to reopen this thread. We would be happy to assist you.
