### ISSUE TITLE
Az ssh fails after update az cli

### ISSUE THREAD

**Issue by JukkaUusisalo** [Azure/azure-cli-extensions#4150]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 0.1.5.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'Profile' object has no attribute 'get_msal_token'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/jukka/.azure/cliextensions/ssh/azext_ssh/custom.py", line 22, in ssh_vm
    public_key_file, private_key_file, use_private_ip, ssh_utils.start_ssh_connection)
  File "/home/jukka/.azure/cliextensions/ssh/azext_ssh/custom.py", line 48, in _do_ssh_op
    cert_file, username = _get_and_write_certificate(cmd, public_key_file, None)
  File "/home/jukka/.azure/cliextensions/ssh/azext_ssh/custom.py", line 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
AttributeError: 'Profile' object has no attribute 'get_msal_token'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --ip {}`

## Expected Behavior
Should logged in via az ssh
## Environment Summary
```
Linux-4.15.0-162-generic-x86_64-with-debian-buster-sid, Ubuntu 18.04.6 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jsntcy** [comment]
@vthiebaut10, please help take a look.

**Comment by vthiebaut10** [comment]
@JukkaUusisalo could you update the ssh extension to the most recent version 1.0.0?

**Comment by navba-MSFT** [comment]
@JukkaUusisalo Could you please update your ssh extension using the command `az extension update --name ssh` and run the  command again? Please let me know if you have any further questions on this. Awaiting your reply.
