### ISSUE TITLE
Error when creating new aks cluster using aks-preview

### ISSUE THREAD

**Issue by dmeytin** [Azure/azure-cli-extensions#4151]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.42.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'DecoratorEarlyExitException'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 969, in aks_create
    from azext_aks_preview.decorator import AKSPreviewModels
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 10, in <module>
    from azure.cli.command_modules.acs._consts import (
ImportError: cannot import name 'DecoratorEarlyExitException'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --name {} --resource-group {} --subscription {} --aad-admin-group-object-ids {} --aad-tenant-id {} --admin-username {} --assign-identity {} --assign-kubelet-identity {} --attach-acr {} --auto-upgrade-channel {} --service-principal {} --client-secret {} --dns-name-prefix {} --enable-aad --enable-rbac --enable-azure-rbac --enable-cluster-autoscaler --enable-managed-identity --enable-secret-rotation --kubernetes-version {} --load-balancer-idle-timeout {} --load-balancer-outbound-ips {} --load-balancer-sku {} --location {} --max-count {} --min-count {} --network-plugin {} --node-count {} --node-osdisk-size {} --node-osdisk-type {} --node-vm-size {} --nodepool-name {} --nodepool-labels {} --os-sku {} --outbound-type {} --ssh-key-value {} --vm-set-type {} --vnet-subnet-id {} --zones {} {} {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.27.2 *

Extensions:
azure-devops 0.20.0
aks-preview 0.5.42

```

**Comment by yonzhan** [comment]
route to service team

**Comment by FumingZhang** [comment]
Hi @dmeytin, sorry for the inconvenience, please update both azure-cli (2.31.0, via `az upgrade`) and aks-preview (0.5.48, via `az extension update -n aks-preview`) to the latest version.
