### ISSUE TITLE
az ml online-deployment create fails while trying to upload files to workspace storage account

### ISSUE THREAD

**Issue by asalvo** [Azure/azure-cli-extensions#4157]
## Describe the bug

**Command Name**
`az ml online-deployment create
Extension Name: ml. Version: 2.0.3.`

**Errors:**
```
Error with code: 'NoneCredentials' object has no attribute 'sas_token'

```

**Stack Trace**
```
Traceback (most recent call last):
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_operations\operation_orchestrator.py", line 125, in _get_code_asset_arm_id
    uploaded_code_asset, _ = _check_and_upload_path(artifact=code_asset, asset_operations=self._code_assets)
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_artifacts\_artifact_utilities.py", line 242, in _check_and_upload_path
    uploaded_artifact = _upload_to_datastore(
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_artifacts\_artifact_utilities.py", line 209, in _upload_to_datastore
    artifact = upload_artifact(
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_artifacts\_artifact_utilities.py", line 131, in upload_artifact
    datastore_info = get_datastore_info(datastore_operation, datastore_name)
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_artifacts\_artifact_utilities.py", line 71, in get_datastore_info
    datastore_info["credential"] = credentials.sas_token
AttributeError: 'NoneCredentials' object has no attribute 'sas_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\custom\online_deployment.py", line 42, in ml_online_deployment_create
    ml_client.begin_create_or_update(deployment, local=local, vscode_debug=vscode_debug, no_wait=no_wait)
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_ml_client.py", line 491, in begin_create_or_update
    return _begin_create_or_update(entity, self._operation_container.all_operations, **kwargs)
  File "functools.py", line 875, in wrapper
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_ml_client.py", line 579, in _
    return operations[AzureMLResourceType.ONLINE_DEPLOYMENT].begin_create_or_update(entity, **kwargs)
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_operations\online_deployment_operations.py", line 78, in begin_create_or_update
    self._upload_dependencies(deployment)
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_operations\online_deployment_operations.py", line 235, in _upload_dependencies
    code=orchestrators.get_asset_arm_id(
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_operations\operation_orchestrator.py", line 103, in get_asset_arm_id
    return self._get_code_asset_arm_id(asset, register_asset=register_asset)
  File "C:\Users\asalvo\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ml\_operations\operation_orchestrator.py", line 131, in _get_code_asset_arm_id
    raise Exception(f"Error with code: {e}")
```
**Response Summary**
```
 "id": "/subscriptions/SUBSCRIPTION_ID/resourceGroups/RESOURCE_GROUP/providers/Microsoft.MachineLearningServices/workspaces/WORKSPACE_NAME/datastores/workspaceblobstore",
  "name": "workspaceblobstore",
  "type": "Microsoft.MachineLearningServices/workspaces/datastores",
  "properties": {
    "description": null,
    "tags": null,
    "properties": null,
    "isDefault": true,
    "credentials": {
      "credentialsType": "None"
    },
    "datastoreType": "AzureBlob",
    "accountName": "STORAGE_ACCOUNT_NAME",
    "containerName": "azureml-blobstore-8ebd398d-bacb-40fc-a25a-4885e861bf71",
    "endpoint": "core.windows.net",
    "protocol": "https",
    "serviceDataAccessAuthIdentity": "WorkspaceSystemAssignedIdentity"
  },
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
  - Setup your workspace default storage such that it uses a Managed Identity for authentication. 
- `az ml online-deployment create --endpoint-name {} --debug --all-traffic --name {} --file {} --set {} {} {} {}`

## Expected Behavior
- Command completes without error. 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

Extensions:
ml 2.0.3

```
## Additional Context
- I tried running the CLI command from 2 different users. 1 is a subscription admin, the other has fewer permissions, but still has `Contributor` and `Storage Blob Data Contributor` access at the resource group level.

**Comment by yonzhan** [comment]
route to service team

**Comment by diondrapeck** [comment]
ack'd. I was unable to reproduce this. @asalvo - how are you handling your authentication? Are you configuring Managed Identity via this page? 
![image](https://user-images.githubusercontent.com/16376603/144138360-e8924146-6387-45fd-8e29-87e3cd008ed1.png)

**Comment by asalvo** [comment]
Here is what I have for that page for the default/workspace data store. The intent is to use Managed Identities for everything. 

<img width="435" alt="image" src="https://user-images.githubusercontent.com/164835/144356577-52a38667-7209-455d-bf50-61c6b86b8c92.png">

**Comment by luigiw** [comment]
Hello @asalvo, I'll file a feature request to support credential-less datastore access for the CLI v2. In the meantime, can you enable "Save credentials with the datastore for data access" and try again?

**Comment by rndazurescript** [comment]
Environment creation also fails with the same error if you have not saved the credentials. Folks, during the deployment of the AzureML we allow users to not save credentails. CLI V2 should support default store without saved credentials...

**Comment by diondrapeck** [comment]
This feature has been implemented and will be available in the next release.
