### ISSUE TITLE
Fail executting command: az kusto cluster create 

### ISSUE THREAD

**Issue by imihalcea** [Azure/azure-cli-extensions#4218]
## Describe the bug

**Command Name**
`az kusto cluster create
Extension Name: kusto. Version: 0.4.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
local variable 'deserialized' referenced before assignment
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/ionut/.azure/cliextensions/kusto/azext_kusto/generated/custom.py", line 122, in kusto_cluster_create
    parameters=parameters)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 646, in sdk_no_wait
    return func(*args, **kwargs)
  File "/home/ionut/.azure/cliextensions/kusto/azext_kusto/vendored_sdks/kusto/operations/_clusters_operations.py", line 226, in begin_create_or_update
    **kwargs
  File "/home/ionut/.azure/cliextensions/kusto/azext_kusto/vendored_sdks/kusto/operations/_clusters_operations.py", line 171, in _create_or_update_initial
    return cls(pipeline_response, deserialized, {})
UnboundLocalError: local variable 'deserialized' referenced before assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
Execute this command:

az kusto cluster create --name TotoExplorer --resource-group bh2-cloud-monitoring-dev --sku name="Dev(No SLA)_Standard_E2a_v4" capacity=1 tier="Standard" --location westeurope

- _Put any pre-requisite steps here..._
- `az kusto cluster create --name {} --resource-group {} --sku {} {} {} --location {}`

## Environment Summary
```
Linux-5.13.0-22-generic-x86_64-with-debian-11.0, Ubuntu 21.10
Python 3.6.10
Installer: DEB

azure-cli 2.31.0

Extensions:
kusto 0.4.0
azure-iot 0.11.0

```

**Comment by jsntcy** [comment]
Route to service team.

**Comment by orhasban** [comment]
Thanks for the feedback. We will work to fix that broken experience.
The issue is that you provided dev SKU with Standard sku tier. Dev sku has Basic tier.

The following should work:
az kusto cluster create --name TotoExplorer --resource-group bh2-cloud-monitoring-dev --sku name="**Dev(No SLA)_Standard_E2a_v4**" capacity=1 tier="**Basic**" --location westeurope

**Comment by zoharHenMicrosoft** [comment]
https://github.com/Azure/azure-cli-extensions/pull/4360

**Comment by navba-MSFT** [comment]
@imihalcea Apologies for the late reply. Please let us know if you had a chance to follow the plan suggested by @orhasban . Do let us know if you are still facing this issue. Awaiting your reply.
