### ISSUE TITLE
Azure ML R Managed Endpoint Deployment fails: Deployment template language expression evaluation failed: 'Unable to evaluate language function 'concat'

### ISSUE THREAD

**Issue by lehmus** [Azure/azure-cli-extensions#4225]
## Describe the bug

**Command Name**
`az ml online-deployment create`

Extension Name: ml. Version: 2.0.3.

**Errors:**
```
Code: InvalidTemplate
Message: Deployment template language expression evaluation failed: 'Unable to evaluate language function 'concat': all function arguments must be string literals, integer values, boolean values or arrays. Please see https://aka.ms/arm-template-expressions/#concat for usage details.'. Please see https://aka.ms/arm-template-expressions for usage details.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Build custom Dockerfile and push it to the Workspace Container Registry
- Prepare R inference script, endpoint.yml and deployment.yml
- Deploy Managed Online Endpoint using `az ml online-endpoint create`
- `az ml online-deployment create -n {} --endpoint {} -f {} -w {} -g {}`

## Expected Behavior

The deployment should succeed and the endpoint should be reachable

## Environment Summary
```
Linux-5.11.0-41-generic-x86_64-with-debian-bullseye-sid, Ubuntu 21.04
Python 3.6.13
Installer: PIP

azure-cli 2.30.0 *

Extensions:
azure-devops 0.22.0
application-insights 0.1.14
account 0.2.1
ml 2.0.3

```
## Additional Context

`Dockerfile`:

```
FROM rocker/tidyverse:3.6.3-ubuntu18.04

ENV R_LIBS_USER=/home/dockeruser/lib/r
 
# Install python (this is still required by AzureML, but this requirement will soon be removed )
RUN apt-get update -qq && \
    apt-get install -y python3-pip
RUN ln -f /usr/bin/python3 /usr/bin/python
RUN ln -f /usr/bin/pip3 /usr/bin/pip
RUN pip install -U pip

# Install azureml-base and libfuse (this is required for data access in local execution -- this requirement will also be removed soon)
RUN sudo apt-get install -y libfuse-dev
RUN pip install azureml-dataprep azureml-core

# User account
RUN useradd --create-home dockeruser
WORKDIR /home/dockeruser
USER dockeruser:dockeruser

# Install Miniconda
ENV CONDA_PATH=/home/dockeruser/miniconda
ENV PATH="${PATH}:${CONDA_PATH}/bin/"
RUN wget -qO /home/dockeruser/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-4.7.12-Linux-x86_64.sh && \
    bash /home/dockeruser/miniconda.sh -b -p $CONDA_PATH && \
    rm /home/dockeruser/miniconda.sh
RUN conda init bash

# Install additional R packages
RUN mkdir --parents $R_LIBS_USER
RUN R -e "install.packages('xtable', lib = '$R_LIBS_USER' )"
```

`inference.R`:
```
#* Liveness check
#* @get /live
function() {
  "alive"
}

#* Readiness check
#* @get /ready
function() {
  "ready"
}

#* Test function
#* @param data_folder, Data folder
#* @post /score
function(data_folder) {
    print("Data folder parameter is set to:\n")
    print(data_folder)
    return(data_folder)
}
```

`endpoint.yml`:

```
$schema: https://azuremlsdk2.blob.core.windows.net/latest/managedOnlineEndpoint.schema.json
name: my-test-ep01
description: Test endpoint.
auth_mode: key
```

`deployment.yml`:

```
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: my-test-dpl01
endpoint_name: my-test-01
model:
  local_path: inference.R
code_configuration:
  code: 
    local_path: .
  scoring_script: inference.R
environment: 
  name: my-test-01
  image: mycontainerreg.azurecr.io/testing/my-test-01
instance_type: Standard_DS2_v2
instance_count: 1
```

**Comment by lehmus** [comment]
I got more information about the error by deploying the endpoint locally. The deployment seems to fail because the dockeruser is not an elevated account, thus is missing write permission to the /var/app directory.

If changed the Dockerfile so that all operations are executed as root. This fixed the previous problem, but now it ran into a new error: `AttributeError: 'NoneType' object has no attribute 'keys'`. Probably the deployment.yml file is missing the keys property, but which property is that?

Error report:

```
Step 6/7 : RUN conda env create -n inf-conda-env --file conda.yml
 ---> Running in 9192442d7bc8

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "/root/miniconda/lib/python3.7/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/root/miniconda/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 77, in execute
        directory=os.getcwd())
      File "/root/miniconda/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/root/miniconda/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/root/miniconda/lib/python3.7/site-packages/conda_env/env.py", line 151, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/root/miniconda/lib/python3.7/site-packages/conda_env/env.py", line 137, in from_yaml
        data = validate_keys(data, kwargs)
      File "/root/miniconda/lib/python3.7/site-packages/conda_env/env.py", line 36, in validate_keys
        for key in data.keys():
    AttributeError: 'NoneType' object has no attribute 'keys'

`$ /root/miniconda/bin/conda-env create -n inf-conda-env --file conda.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_PATH=/root/miniconda
               CONDA_ROOT=/root/miniconda
                     PATH=/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/
                          usr/bin:/sbin:/bin:/root/miniconda/bin/
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /root/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/miniconda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/5.11.0-41-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by lehmus** [comment]
It seems that the error message in the title of this issue is given whenever the deployment YAML file contains errors. I was able to fix the previous error by adding a conda environment file (which doesn't make any sense, since I'm using a custom image...)

Now I got the same error about 'concat' again. Deploying locally with the --debug flag, the following error is revealed:

```
Updating local deployment (my-test-ep01 / my-test-dpl01) .docker.api.build: Looking for auth config
docker.api.build: Sending auth config ('myco.azurecr.io', 'https://index.docker.io/v1/', 'mltemp01cr.azurecr.io')
urllib3.connectionpool: http://localhost:None "POST /v1.41/build?t=my-test-ep01%3Amy-test-dpl01&q=False&nocache=False&rm=False&forcerm=False&pull=False&dockerfile=Dockerfile HTTP/1.1" 200 None
urllib3.connectionpool: http://localhost:None "GET /v1.41/images/e6cf7d30c1c2/json HTTP/1.1" 200 None
urllib3.connectionpool: http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22azureml-local-endpoint%22%2C+%22endpoint%3Dmy-test-ep01%22%5D%7D HTTP/1.1" 200 None
urllib3.connectionpool: http://localhost:None "GET /v1.41/containers/88f5dd76ac00d6d364894c32965acf0a46a7246d8d589cfb7e9ee1688b4da468/json HTTP/1.1" 200 None
urllib3.connectionpool: http://localhost:None "POST /v1.41/containers/88f5dd76ac00d6d364894c32965acf0a46a7246d8d589cfb7e9ee1688b4da468/stop HTTP/1.1" 304 0
urllib3.connectionpool: http://localhost:None "DELETE /v1.41/containers/88f5dd76ac00d6d364894c32965acf0a46a7246d8d589cfb7e9ee1688b4da468?v=False&link=False&force=False HTTP/1.1" 204 0
urllib3.connectionpool: http://localhost:None "POST /v1.41/containers/create?name=my-test-ep01.my-test-dpl01 HTTP/1.1" 201 88
urllib3.connectionpool: http://localhost:None "GET /v1.41/containers/8af509f017f9f2be39a31e67f2eb2defe149deb2f043a490ec32ec2b6687a018/json HTTP/1.1" 200 None
urllib3.connectionpool: http://localhost:None "POST /v1.41/containers/8af509f017f9f2be39a31e67f2eb2defe149deb2f043a490ec32ec2b6687a018/start HTTP/1.1" 204 0
...urllib3.connectionpool: http://localhost:None "GET /v1.41/containers/8af509f017f9f2be39a31e67f2eb2defe149deb2f043a490ec32ec2b6687a018/json HTTP/1.1" 200 None
Done (0m 20s)
Traceback (most recent call last):
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 42, in ml_online_deployment_create
    ml_client.begin_create_or_update(deployment, local=local, vscode_debug=vscode_debug, no_wait=no_wait)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_ml_client.py", line 491, in begin_create_or_update
    return _begin_create_or_update(entity, self._operation_container.all_operations, **kwargs)
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_ml_client.py", line 579, in _
    return operations[AzureMLResourceType.ONLINE_DEPLOYMENT].begin_create_or_update(entity, **kwargs)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/online_deployment_operations.py", line 71, in begin_create_or_update
    deployment=deployment, local_endpoint_mode=self._get_local_endpoint_mode(vscode_debug)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/_local_deployment_helper.py", line 92, in create_or_update
    deployment_metadata=deployment_metadata,
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_utils/_endpoint_utils.py", line 70, in local_endpoint_polling_wrapper
    return event.result()
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/_local_deployment_helper.py", line 248, in _create_deployment
    local_endpoint_mode=local_endpoint_mode,
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_local_endpoints/docker_client.py", line 182, in create_deployment
    endpoint_name=endpoint_name, deployment_name=deployment_name, container=container
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_local_endpoints/docker_client.py", line 425, in _validate_container_state
    raise LocalEndpointInFailedStateError(endpoint_name=endpoint_name, deployment_name=deployment_name)
azext_mlv2.manual.vendored_curated_sdk.azure.ml._local_endpoints.errors.LocalEndpointInFailedStateError: Local deployment (my-test-ep01 / my-test-dpl01) is in failed state. Try getting logs to debug scoring script.
cli: None
cli: Traceback (most recent call last):
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 42, in ml_online_deployment_create
    ml_client.begin_create_or_update(deployment, local=local, vscode_debug=vscode_debug, no_wait=no_wait)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_ml_client.py", line 491, in begin_create_or_update
    return _begin_create_or_update(entity, self._operation_container.all_operations, **kwargs)
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_ml_client.py", line 579, in _
    return operations[AzureMLResourceType.ONLINE_DEPLOYMENT].begin_create_or_update(entity, **kwargs)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/online_deployment_operations.py", line 71, in begin_create_or_update
    deployment=deployment, local_endpoint_mode=self._get_local_endpoint_mode(vscode_debug)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/_local_deployment_helper.py", line 92, in create_or_update
    deployment_metadata=deployment_metadata,
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_utils/_endpoint_utils.py", line 70, in local_endpoint_polling_wrapper
    return event.result()
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/_local_deployment_helper.py", line 248, in _create_deployment
    local_endpoint_mode=local_endpoint_mode,
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_local_endpoints/docker_client.py", line 182, in create_deployment
    endpoint_name=endpoint_name, deployment_name=deployment_name, container=container
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_local_endpoints/docker_client.py", line 425, in _validate_container_state
    raise LocalEndpointInFailedStateError(endpoint_name=endpoint_name, deployment_name=deployment_name)
azext_mlv2.manual.vendored_curated_sdk.azure.ml._local_endpoints.errors.LocalEndpointInFailedStateError: Local deployment (my-test-ep01 / my-test-dpl01) is in failed state. Try getting logs to debug scoring script.

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 42, in ml_online_deployment_create
    ml_client.begin_create_or_update(deployment, local=local, vscode_debug=vscode_debug, no_wait=no_wait)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_ml_client.py", line 491, in begin_create_or_update
    return _begin_create_or_update(entity, self._operation_container.all_operations, **kwargs)
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_ml_client.py", line 579, in _
    return operations[AzureMLResourceType.ONLINE_DEPLOYMENT].begin_create_or_update(entity, **kwargs)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/online_deployment_operations.py", line 71, in begin_create_or_update
    deployment=deployment, local_endpoint_mode=self._get_local_endpoint_mode(vscode_debug)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/_local_deployment_helper.py", line 92, in create_or_update
    deployment_metadata=deployment_metadata,
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_utils/_endpoint_utils.py", line 70, in local_endpoint_polling_wrapper
    return event.result()
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_operations/_local_deployment_helper.py", line 248, in _create_deployment
    local_endpoint_mode=local_endpoint_mode,
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_local_endpoints/docker_client.py", line 182, in create_deployment
    endpoint_name=endpoint_name, deployment_name=deployment_name, container=container
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ml/_local_endpoints/docker_client.py", line 425, in _validate_container_state
    raise LocalEndpointInFailedStateError(endpoint_name=endpoint_name, deployment_name=deployment_name)
azext_mlv2.manual.vendored_curated_sdk.azure.ml._local_endpoints.errors.LocalEndpointInFailedStateError: Local deployment (my-test-ep01 / my-test-dpl01) is in failed state. Try getting logs to debug scoring script.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/myusername/anaconda3/envs/azurecli/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 50, in ml_online_deployment_create
    log_and_raise_error(err, debug)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/custom/raise_error.py", line 89, in log_and_raise_error
    _raise_cli_error(error)
  File "/home/myusername/.azure/cliextensions/ml/azext_mlv2/manual/custom/raise_error.py", line 68, in _raise_cli_error
    raise CLIError(message)
knack.util.CLIError: Local deployment (my-test-ep01 / my-test-dpl01) is in failed state. Try getting logs to debug scoring script.

cli.azure.cli.core.azclierror: Local deployment (my-test-ep01 / my-test-dpl01) is in failed state. Try getting logs to debug scoring script.
az_command_data_logger: Local deployment (my-test-ep01 / my-test-dpl01) is in failed state. Try getting logs to debug scoring script.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fe85951af28>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 21.206 seconds (init: 0.106, invoke: 21.100)
telemetry.save: Save telemetry record of length 3269 in cache
telemetry.check: Negative: The /home/myusername/.azure/telemetry.txt was modified at 2021-12-17 18:41:18.218818, which in less than 600.000000 s
```

**Comment by jsntcy** [comment]
Route to service team.

**Comment by Mossaka** [comment]
Hey @lehmus , thanks for reporting this issue. The engineering team will help to investigate this issue. In the meantime, you can use `az ml online-deployment get-logs --name my-deployment --endpoint-name my-endpoint --lines 100 --resource-group my-resource-group --workspace-name my-workspace` to get the logs for your online deployment to help diagnose the current issues. 

If you had a hard time finding the online deployment schema, you can find it [here](https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-deployment-managed-online)

**Comment by lehmus** [comment]
I made a few changes to the deployment definition (model & environment). Again, deploying locally reveals the actual error message:

```
Creating or updating online_deployments
Creating local deployment (my-test-ep01 / my-test-dpl01) .Done (0m 5s)
400 Client Error for http+docker://localhost/v1.41/containers/e6a7f3af39092c518eaebb41ef7c9fceed72e5bc1a2edbe065b15b6f32044694/start: Bad Request ("failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "runsvdir": executable file not found in $PATH: unknown")
```

I also tried to deploy to Azure and fetch the logs as @Mossaka commented. But this command also runs into an error:

```
Code: BadRequest
Message: The request is invalid.
Exception Details:      (DeploymentLogsUnavailable) Logs for deployment are not available because it failed in provisioning. This may be caused by the environment failing to build. Following error was found on the deployment: {"code":"InferencingClientCallFailed","statusCode":404,"message":"{{\"title\":\"Not Found\"}}"}
        Code: DeploymentLogsUnavailable
        Message: Logs for deployment are not available because it failed in provisioning. This may be caused by the environment failing to build. Following error was found on the deployment: {"code":"InferencingClientCallFailed","statusCode":404,"message":"{{\"title\":\"Not Found\"}}"}
```

This is the refined `deployment.yml`:

```
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: my-test-dpl01
endpoint_name: my-test-01
model:
  name: my-test-01
  local_path: inference.R
code_configuration:
  code: 
    local_path: .
  scoring_script: inference.R
environment: azureml:my-test-01:1 # custom environment exists in AML Workspace
instance_type: Standard_DS2_v2
instance_count: 1
```

As a side note, deployment seems to require the `model` schema, although it should be optional when deploying a custom image.

**Comment by lehmus** [comment]
I have managed to deploy the endpoint now. The error messages and the documentation have improved recently, so it is easier to debug issues.
