### ISSUE TITLE
Help-carl817

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli-extensions#4238]
## Describe the bug

**Command Name**
`az kusto cluster create
Extension Name: kusto. Version: 0.4.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
local variable 'deserialized' referenced before assignment
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Carl8\.azure\cliextensions\kusto\azext_kusto\generated\custom.py", line 116, in kusto_cluster_create
    return sdk_no_wait(no_wait,
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 646, in sdk_no_wait
  File "C:\Users\Carl8\.azure\cliextensions\kusto\azext_kusto\vendored_sdks\kusto\operations\_clusters_operations.py", line 219, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "C:\Users\Carl8\.azure\cliextensions\kusto\azext_kusto\vendored_sdks\kusto\operations\_clusters_operations.py", line 171, in _create_or_update_initial
    return cls(pipeline_response, deserialized, {})
UnboundLocalError: local variable 'deserialized' referenced before assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az kusto cluster create --location {} --cluster-name {} --resource-group {} --sku {} {} {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
kusto 0.4.0

```

**Comment by jsntcy** [comment]
Route to service team.

**Comment by zoharHenMicrosoft** [comment]
https://github.com/Azure/azure-cli-extensions/pull/4360

**Comment by navba-MSFT** [comment]
@ghost Apologies for the late reply. Could you please update to the most recent version of the kusto CLI extension (0.5.0) and then run the command again ?

>az extension update --name kusto

Please let us know if you still face the same issue. Awaiting your reply.
