### ISSUE TITLE
az crashed while creating a kusto cluster

### ISSUE THREAD

**Issue by mingqxu** [Azure/azure-cli-extensions#4256]
## Describe the bug

**Command Name**
`az kusto cluster create
Extension Name: kusto. Version: 0.4.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
local variable 'deserialized' referenced before assignment
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/mingqxu/.azure/cliextensions/kusto/azext_kusto/generated/custom.py", line 116, in kusto_cluster_create
    return sdk_no_wait(no_wait,
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 646, in sdk_no_wait
    return func(*args, **kwargs)
  File "/Users/mingqxu/.azure/cliextensions/kusto/azext_kusto/vendored_sdks/kusto/operations/_clusters_operations.py", line 219, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/Users/mingqxu/.azure/cliextensions/kusto/azext_kusto/vendored_sdks/kusto/operations/_clusters_operations.py", line 171, in _create_or_update_initial
    return cls(pipeline_response, deserialized, {})
UnboundLocalError: local variable 'deserialized' referenced before assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az kusto cluster create --location {} --cluster-name {} --resource-group {} --sku {} {} {}`

## Environment Summary
```
macOS-12.1-arm64-arm-64bit, Darwin 21.2.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.31.0

Extensions:
kusto 0.4.0
datafactory 0.5.0
azure-devops 0.22.0

```

**Comment by mingqxu** [comment]
The reason was that the cluster-name already exists.

**Comment by yonzhan** [comment]
route to service team

**Comment by zoharHenMicrosoft** [comment]
https://github.com/Azure/azure-cli-extensions/pull/4360

**Comment by navba-MSFT** [comment]
@mingqxu  Apologies for the late reply. Could you please let us know if you are still facing the issue ? Awaiting your reply.
