### ISSUE TITLE
[Spring-Cloud] Unable to deploy application after upgrading to version 2.12.2

### ISSUE THREAD

**Issue by prabhuofficial** [Azure/azure-cli-extensions#4267]
## Describe the bug

**Command Name**
`az spring-cloud app deploy
Extension Name: spring-cloud. Version: 2.12.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "C:\Users\prabhu.perumal\.azure\cliextensions\spring-cloud\azext_spring_cloud\_utils.py", line 251, in handle_asc_exception
    response_dict = json.loads(ex.response.internal_response.text)
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az spring-cloud app deploy -n {} -s {} -g {} --jar-path {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.25.0 *

Extensions:
spring-cloud 2.12.2

```
## Additional Context
Able to deploy the applications after downgrading version to 2.12.1

**Comment by yonzhan** [comment]
route to service team

**Comment by yuwzho** [comment]
@prabhuofficial Thanks for reporting the issue, we are on the way fixing it. To unblock your usage, you can install the previous version `2.12.1` by running command:

```
az extension remove -n spring-cloud
az extension add -n spring-cloud --version 2.12.1 -y
```

**Comment by LGDoor** [comment]
#4268
