### ISSUE TITLE
az app deploy error on Windows

### ISSUE THREAD

**Issue by Syndrol** [Azure/azure-cli-extensions#4269]
## Describe the bug
I follow the Microsoft learn module; "Deploy Spring microservices to Azure", but I get the following error when I try to deploy either app using azure CLI. My computer doesn't even have a D:-drive, so I don't understand the error.

**Command Name**
`az spring-cloud app deploy
Extension Name: spring-cloud. Version: 2.12.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 713, in _run_job
  File "C:\Users\marjohansen\.azure\cliextensions\spring-cloud\azext_spring_cloud\_utils.py", line 251, in handle_asc_exception
    response_dict = json.loads(ex.response.internal_response.text)
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
- az spring-cloud app deploy --name todo-gateway --service "$SPRING_CLOUD_NAME" --resource-group "$RESOURCE_GROUP_NAME" --jar-path target/demo-0.0.1-SNAPSHOT.jar
- I tried using Git Bash & Windows PowerShell

## Expected Behavior
Application is deployed.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
spring-cloud 2.12.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by yuwzho** [comment]
@Syndrol  Thanks for reporting the issue, we are on the way fixing it. To unblock your usage, you can install the previous version `2.12.1` by running command:

```
az extension remove -n spring-cloud
az extension add -n spring-cloud --version 2.12.1 -y
```

**Comment by LGDoor** [comment]
Fixing in #4268

**Comment by Syndrol** [comment]
Thank you!
