### ISSUE TITLE
JSONDecodeError while deploying app to PRD

### ISSUE THREAD

**Issue by AngeloVK** [Azure/azure-cli-extensions#4270]
## While trying to deploy new spring boot application to azure spring cloud i'm getting JSONDecodeError.

**Command Name**
`az spring-cloud app deploy
Extension Name: spring-cloud. Version: 2.12.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 713, in _run_job
  File "C:\Users\wimst\.azure\cliextensions\spring-cloud\azext_spring_cloud\_utils.py", line 251, in handle_asc_exception
    response_dict = json.loads(ex.response.internal_response.text)
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- build a local spring boot jar with controller restAPI's
- `az spring-cloud app deploy -n {} -s {} -g {} --artifact-path {} --verbose`

## Expected Behavior

Deploying to default deployment of my app so new version can be used.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
spring-cloud 2.12.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by yuwzho** [comment]
@AngeloVK Thanks for reporting the issue, we are on the way fixing it. To unblock your usage, you can install the previous version `2.12.1` by running command:

```
az extension remove -n spring-cloud
az extension add -n spring-cloud --version 2.12.1 -y
```

**Comment by LGDoor** [comment]
Fixing in #4268

**Comment by AngeloVK** [comment]
@yuwzho downgrade fixed issue! Thnx
