### ISSUE TITLE
挑战-将Spring 微服务部署到 Azure-生成 Spring Boot 微服务-部署应用程序报错

### ISSUE THREAD

**Issue by OomoonoO** [Azure/azure-cli-extensions#4271]
## Describe the bug

**Command Name**
`az spring-cloud app deploy
Extension Name: spring-cloud. Version: 2.12.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/jing/.azure/cliextensions/spring-cloud/azext_spring_cloud/_utils.py", line 251, in handle_asc_exception
    response_dict = json.loads(ex.response.internal_response.text)
  File "/opt/az/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az spring-cloud app deploy --name {} --service {} --resource-group {} --jar-path {}`

## Environment Summary
```
Linux-5.4.0-1064-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.31.0

Extensions:
spring-cloud 2.12.2
ai-examples 0.2.5
ssh 1.0.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by yuwzho** [comment]
@OomoonoO Thanks for reporting the issue, we are on the way fixing it. To unblock your usage, you can install the previous version `2.12.1` by running command:

```
az extension remove -n spring-cloud
az extension add -n spring-cloud --version 2.12.1 -y
```

**Comment by LGDoor** [comment]
Fixing in #4268
