### ISSUE TITLE
node upgrade image-only

### ISSUE THREAD

**Issue by rmnunes** [Azure/azure-cli-extensions#4284]
## Describe the bug

**Command Name**
`az aks nodepool upgrade
Extension Name: aks-preview. Version: 0.5.48.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Ran out of input
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\RodrigoNunes\.azure\cliextensions\aks-preview\azext_aks_preview\_client_factory.py", line 38, in cf_agent_pools
    return get_mgmt_service_client(cli_ctx, CUSTOM_MGMT_AKS_PREVIEW).agent_pools
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 70, in get_mgmt_service_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 212, in _get_mgmt_service_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 335, in get_login_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 593, in _create_credential
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 209, in get_user_credential
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 84, in _msal_app_kwargs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 113, in _load_msal_http_cache
EOFError: Ran out of input

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool upgrade --node-image-only -n {} -g {} --cluster-name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
aks-preview 0.5.48
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by rmnunes** [comment]
++ I deleted the .azure folder and it start to work again.

**Comment by navba-MSFT** [comment]
@rmnunes Apologies for the late reply. Thanks for the update. I am glad that the issue is resolved now. Please let us know if you have any questions on this issue before we proceed with the archival of this thread. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rmnunes 
I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by rmnunes** [comment]
> @rmnunes Apologies for the late reply. Thanks for the update. I am glad that the issue is resolved now. Please let us know if you have any questions on this issue before we proceed with the archival of this thread. Awaiting your reply.

no questions. Thanks
