### ISSUE TITLE
AttributeError: 'AssignmentsOperations' object has no attribute 'cli_ctx'

### ISSUE THREAD

**Issue by masonhuemmer** [Azure/azure-cli-extensions#4297]
## Describe the bug

**Command Name**
`az blueprint assignment update
Extension Name: blueprint. Version: 0.3.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'AssignmentsOperations' object has no attribute 'cli_ctx'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/mason/.azure/cliextensions/blueprint/azext_blueprint/custom.py", line 671, in update_blueprint_assignment
    _assign_owner_role_in_target_scope(client, resource_scope, spn)
  File "/home/mason/.azure/cliextensions/blueprint/azext_blueprint/custom.py", line 612, in _assign_owner_role_in_target_scope
    role_assignments = list_role_assignments(cmd, assignee=spn_object_id, role='Owner', scope=role_scope)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 208, in list_role_assignments
    graph_client = _graph_client_factory(cmd.cli_ctx)
AttributeError: 'AssignmentsOperations' object has no attribute 'cli_ctx'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az blueprint assignment update --name {} --location {} --identity-type {} --locks-mode {} --blueprint-version {} --parameters {} --subscription {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.31.0 *

Extensions:
blueprint 0.3.1

```

**Comment by yonzhan** [comment]
blueprint

**Comment by RakeshMohanMSFT** [comment]
We have verified that this is working as expected in the latest version of az cli [2.40.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli). Please upgrade and retry.

![image](https://user-images.githubusercontent.com/49954584/188549872-3380f076-5fc7-43fc-85e3-e9c668b93160.png)
