### ISSUE TITLE
Elastic Cloud creation can't be made

### ISSUE THREAD

**Issue by morland96** [Azure/azure-cli-extensions#4317]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

elastic

### Description of issue (in as much detail as possible)

Cmd failed:
`az elastic monitor create -g *** -n elastic`

Error:
```
(ResourceCreationValidateFailed) The resource validation failed.
Code: ResourceCreationValidateFailed
Message: The resource validation failed.
```

Description:
When creating the new elastic monitor instance, the cli fails ResourceCreationValidateFailed. 

Extra Information:
- The account has the owner permission of the subscription
- Provider with namespace Microsoft.Elastic is Registered
- The region is in the Elastic Cloud supporting list (australiaeast)

Response in the Debug log:
```
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"ResourceCreationValidateFailed","message":"The resource validation failed."}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/../.azure/cliextensions/elastic/azext_elastic/manual/custom.py", line 51, in elastic_monitor_create
    return sdk_no_wait(no_wait,
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 678, in sdk_no_wait
    return func(*args, **kwargs)
  File "/Users/../.azure/cliextensions/elastic/azext_elastic/vendored_sdks/elastic/operations/_monitors_operations.py", line 357, in begin_create
    raw_result = self._create_initial(
  File "/Users/../.azure/cliextensions/elastic/azext_elastic/vendored_sdks/elastic/operations/_monitors_operations.py", line 306, in _create_initial
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (ResourceCreationValidateFailed) The resource validation failed.
Code: ResourceCreationValidateFailed
Message: The resource validation failed.
```

-----

**Comment by yonzhan** [comment]
route to service team

**Comment by mikaelmattsson** [comment]
I get this error too and I have no idea how to debug this because the error doesn't say what is wrong. Just “The resource validation failed.”

**Comment by morland96** [comment]
> I get this error too and I have no idea how to debug this because the error doesn't say what is wrong. Just “The resource validation failed.” Is there a “verbose” setting or something I can use?

It spends me lots of time, and finally I have realised the --user-info is mandatory. They should really improve their documentation.

**Comment by Kosmonafft** [comment]
> > I get this error too and I have no idea how to debug this because the error doesn't say what is wrong. Just “The resource validation failed.” Is there a “verbose” setting or something I can use?
> 
> It spends me lots of time, and finally I have realised the --user-info is mandatory. They should really improve their documentation.

where have you set "--user-info" ?

**Comment by morland96** [comment]
> > > I get this error too and I have no idea how to debug this because the error doesn't say what is wrong. Just “The resource validation failed.” Is there a “verbose” setting or something I can use?
> 
> > 
> 
> > It spends me lots of time, and finally I have realised the --user-info is mandatory. They should really improve their documentation.
> 
> 
> 
> where have you set "--user-info" ?

Just after the cli.
