### ISSUE TITLE
" az network firewall network-rule create" failed with an unexpected error

### ISSUE THREAD

**Issue by myers-dev** [Azure/azure-cli-extensions#4398]
## Describe the bug

**Command Name**
`az network firewall network-rule create
Extension Name: azure-firewall. Version: 0.11.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/andrew/.azure/cliextensions/azure-firewall/azext_firewall/custom.py", line 391, in create_af_network_rule
    item_name, params, collection_params)
  File "/home/andrew/.azure/cliextensions/azure-firewall/azext_firewall/custom.py", line 344, in _upsert_af_rule
    collection_match = next((x for x in collection if x.name.lower() == collection_name.lower()), None)
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network firewall network-rule create --collection-name {} --destination-ports {} --firewall-name {} --name {} --protocols {} --resource-group {} --action {} --dest-addr {} --source-addresses {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.26.1 *

Extensions:
azure-devops 0.20.0
azure-firewall 0.11.0
virtual-wan 0.2.11

```

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi, 
     @myers-dev , this command works well as below, and my CLI version is 2.37.0, maybe you can update to it and try again:
az network firewall network-rule create --collection-name mycoll01 --source-addresses 10.0.0.0 111.1.0.0/24 --protocols UDP TCP ICMP --destination-fqdns www.bing.com --destination-ports 80 --firewall-name myfw --name myrule --protocols Any --resource-group nyy02 --priority 500 --action Allow
![image](https://user-images.githubusercontent.com/95396631/174954458-82a9ed6c-652e-4656-8ab5-5699b2bd85e0.png)

Best wishes.
