### ISSUE TITLE
az monitor scheduled-query update error

### ISSUE THREAD

**Issue by morro-tr** [Azure/azure-cli-extensions#4405]
## Describe the bug

**Command Name**
`az monitor scheduled-query update
Extension Name: scheduled-query. Version: 0.5.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1172, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 447, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 441, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/mor/.azure/cliextensions/scheduled-query/azext_scheduled_query/vendored_sdks/azure_mgmt_scheduled_query/operations/_scheduled_query_rules_operations.py", line 518, in create_or_update
    deserialized = self._deserialize('ScheduledQueryRuleResource', pipeline_response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1368, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1172, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor scheduled-query update --name {} --resource-group {} --window-size {} --auto-mitigate {}`

## Environment Summary
```
Linux-5.4.0-1068-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0 *

Extensions:
application-insights 0.1.14
scheduled-query 0.5.0
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by morro-tr** [comment]
This is the full command that was executed - 
az monitor scheduled-query update --name "prod-ach-ea-insights - Requests failure rate is higher then 20 percent" --resource-group "prod-ach-eu" --window-size "15m" --auto-mitigate $true
It was executed from Azure Cloud Shell running Powershell.

**Comment by yonzhan** [comment]
monitor

**Comment by necusjz** [comment]
> This is the full command that was executed - az monitor scheduled-query update --name "prod-ach-ea-insights - Requests failure rate is higher then 20 percent" --resource-group "prod-ach-eu" --window-size "15m" --auto-mitigate $true It was executed from Azure Cloud Shell running Powershell.

Hi @morro-tr ,

I cannot reproduce this issue. Could you replace `$true` after --auto-mitigate with `True` and re-execute?

**Comment by morro-tr** [comment]
Same issue - 
`PS /home/mor> az monitor scheduled-query update --name "prod-ach-ea-insights - Requests failure rate is higher then 20 percent" --resource-group prod-ach-eu --window-size 15m --auto-mitigate True
The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1172, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 447, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 441, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/mor/.azure/cliextensions/scheduled-query/azext_scheduled_query/vendored_sdks/azure_mgmt_scheduled_query/operations/_scheduled_query_rules_operations.py", line 518, in create_or_update
    deserialized = self._deserialize('ScheduledQueryRuleResource', pipeline_response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1368, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1172, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'`

**Comment by necusjz** [comment]
@morro-tr It seems quotes need to be escaped, i.e.,
```
az monitor scheduled-query update --name \"prod-ach-ea-insights - Requests failure rate is higher then 20 percent\" --resource-group prod-ach-eu --window-size 15m --auto-mitigate True
```

If it doesn't work, could you share the command you created the scheduled-query? Then I can go into details, thanks.

**Comment by morro-tr** [comment]
Same error message - 
`az monitor scheduled-query update --name \"prod-ach-ea-insights - Requests failure rate is higher then 20 percent\" --resource-group prod-ach-eu --window-size 15m --auto-mitigate True
The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1172, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 447, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 441, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/mor/.azure/cliextensions/scheduled-query/azext_scheduled_query/vendored_sdks/azure_mgmt_scheduled_query/operations/_scheduled_query_rules_operations.py", line 518, in create_or_update
    deserialized = self._deserialize('ScheduledQueryRuleResource', pipeline_response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1368, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1172, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'`

**Comment by necusjz** [comment]
@morro-tr It's weird, could you share the commands (or procedures) you created the scheduled-query?

BTW, the complicated string -- "prod-ach-ea-insights - Requests failure rate is higher then 20 percent" is used for `--name` or `--condition`?

**Comment by morro-tr** [comment]
It's used for name.
I'm a little concerned now that maybe the alerts are not working as they
should if they are faulting out like this?

The alerts were created using Azure Powershell

$logMetricTrigger = New-AzScheduledQueryRuleLogMetricTrigger -
ThresholdOperator "GreaterThan" -Threshold 2 -MetricTriggerType
"Consecutive" -MetricColumn "name"
    $logTriggerCondition = New-AzScheduledQueryRuleTriggerCondition -
ThresholdOperator "GreaterThan" -Threshold 20 -
MetricTrigger $logMetricTrigger
    $logAzNsActionGroup = New-AzScheduledQueryRuleAznsActionGroup -
ActionGroup $newActionIdList -EmailSubject
"Request failures 500s more than 20%"
    $logAlertingAction = New-AzScheduledQueryRuleAlertingAction -
AznsAction $logAzNsActionGroup -Severity "2" -Trigger $logTriggerCondition
    $logSchedule = New-AzScheduledQueryRuleSchedule -FrequencyInMinutes 15 -
TimeWindowInMinutes 30
    $query = 'requests
    | extend t = bin(timestamp, 15m)
    | join kind=leftouter (
        dependencies
    ) on operation_Id
    | join kind=leftouter (
        exceptions
    ) on operation_Id
    | join (
        requests
        | summarize totalCount=sum(itemCount) by name, t=bin(timestamp, 15m)
        )
        on name, t
    | join kind=leftouter (
        requests
        | where success == false and toint(resultCode) >= 500
        | summarize failedCount=sum(itemCount) by name, t=bin(timestamp, 15m)
        )
        on name, t
    | where name1 !contains "GET /api/v2/sessions/validate-token"
    | extend AggregatedValue=(toreal(failedCount) / toreal(totalCount)) * 100
    | extend dependency_service = trim_end("\\|.*", target)
    | project bin(timestamp, 15m), name, AggregatedValue, failedCount,
totalCount, dependency_service, dependency_name=name1,
dependency_data=data, exception_type=type, exception_method=method,
exception_outerMessage=outerMessage'
    $source = New-AzScheduledQueryRuleSource -Query $query -
DataSourceId $targetId
    New-AzScheduledQueryRule -Source $source -Schedule $logSchedule -
Action $logAlertingAction -Location $location -Name $alertName -
Enabled $enabled -ResourceGroupName $resourceGroupName

**Comment by necusjz** [comment]
@morro-tr We can use `az monitor scheduled-query show` to check the alerts are working or not:
```
az monitor scheduled-query show --name {} --resource-group {}
```
`az monitor scheduled-query update --name {} --resource-group {} --window-size {} --auto-mitigate {}` should work if the alert exists.

**Comment by morro-tr** [comment]
That returns the alert correctly, but I still cannot update it with az
monitor update.
Any update on what is going on and why it is failing?

**Comment by necusjz** [comment]
@morro-tr , this kind of error is usually a parameter passing error. Let me share my procedures of successfully updating `--window-size` and `--auto-mitigate`, hope it's useful for you:
```
az vm create -n ethan-vm -g ethan-rg --image UbuntuLTS --nsg-rule None --workspace ethan-ws --generate-ssh-keys
az monitor scheduled-query create -g ethan-rg -n ethan-sq --scopes {vm_id_from_last_step} --condition 'count \"placeholder_1\" > 360' --condition-query placeholder_1="union Event, Syslog | where TimeGenerated > ago(1h)" --description "Test rule"
az monitor scheduled-query update -g ethan-rg -n ethan-sq --window-size 15m --auto-mitigate false
```
