### ISSUE TITLE
az aks kollect command failed

### ISSUE THREAD

**Issue by glennr8686** [Azure/azure-cli-extensions#4407]
## Describe the bug

**Command Name**
`az aks kollect
Extension Name: aks-preview. Version: 0.5.51.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: '/home/glenn/.azure/cliextensions/aks-preview/azext_aks_preview/deploymentyaml/aks-periscope.yaml'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/glenn/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1044, in aks_kollect
    deployment_yaml = _read_periscope_yaml()
  File "/home/glenn/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1134, in _read_periscope_yaml
    yaml_file = open(periscope_yaml_file, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/glenn/.azure/cliextensions/aks-preview/azext_aks_preview/deploymentyaml/aks-periscope.yaml'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks kollect -g {} -n {} --storage-account {} --sas-token {}`

## Environment Summary
```
Linux-5.4.0-1068-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0 *

Extensions:
aks-preview 0.5.51
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by Tatsinnit** [comment]
💡just fyi: this should be fixed as part of this pr : https://github.com/Azure/azure-cli-extensions/pull/4382

thanks

**Comment by navba-MSFT** [comment]
@glennr8686 Please upgrade to the most recent `aks-preview` extension and then update your Azure CLI. Please test the above command then. The below action plan should resolve the issue. 

>az extension update -n aks-preview
az upgrade

If that doesn't resolve the issue, please feel free to reopen this github thread. We would be happy to work with you again on this issue.
