### ISSUE TITLE
Cannot List scheduled queries being monitored via az cli

### ISSUE THREAD

**Issue by ahernandez411** [Azure/azure-cli-extensions#4435]
## Describe the bug

**Command Name**
`az monitor scheduled-query list
Extension Name: scheduled-query. Version: 0.5.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (/usr/local/Cellar/azure-cli/2.28.1/libexec/lib/python3.9/site-packages/azure/mgmt/core/policies/__init__.py)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.28.1/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.28.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.28.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.28.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.28.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.28.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/adaher/.azure/cliextensions/scheduled-query/azext_scheduled_query/_client_factory.py", line 9, in cf_scheduled_query
    from .vendored_sdks.azure_mgmt_scheduled_query._monitor_management_client import MonitorManagementClient
  File "/Users/adaher/.azure/cliextensions/scheduled-query/azext_scheduled_query/vendored_sdks/azure_mgmt_scheduled_query/__init__.py", line 9, in <module>
    from ._monitor_management_client import MonitorManagementClient
  File "/Users/adaher/.azure/cliextensions/scheduled-query/azext_scheduled_query/vendored_sdks/azure_mgmt_scheduled_query/_monitor_management_client.py", line 16, in <module>
    from ._configuration import MonitorManagementClientConfiguration
  File "/Users/adaher/.azure/cliextensions/scheduled-query/azext_scheduled_query/vendored_sdks/azure_mgmt_scheduled_query/_configuration.py", line 13, in <module>
    from azure.mgmt.core.policies import ARMChallengeAuthenticationPolicy, ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (/usr/local/Cellar/azure-cli/2.28.1/libexec/lib/python3.9/site-packages/azure/mgmt/core/policies/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- run `az login` to login
- `az monitor scheduled-query list --resource-group {}`

## Expected Behavior
Should give results as explained in [az monitor scheduled-query list](https://docs.microsoft.com/en-us/cli/azure/monitor/scheduled-query?view=azure-cli-latest#az-monitor-scheduled-query-list)

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.28.1 *

Extensions:
storage-preview 0.7.3
scheduled-query 0.5.0

```

**Comment by ahernandez411** [comment]
Upgrading to 2.33.1 fixed it

**Comment by ahernandez411** [comment]
Upgrade fixed it
