### ISSUE TITLE
az blueprint create from JSON parameter

### ISSUE THREAD

**Issue by Gauravkumargupta** [Azure/azure-cli-extensions#4451]
### Description:

I'm trying to create a Azure Blueprint definition via CLI command with help of one of the pre-built sample available at Azure.

### Command Name:

az blueprint create --subscription <subscription-id>--name MyTestBlueprint --description "My First Blueprint" --target-scope subscription --parameters blueprint.json

### Error:

Command group 'blueprint' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1665, in deserialize_dict
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1665, in <dictcomp>
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1631, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/3017971/.azure/cliextensions/blueprint/azext_blueprint/custom.py", line 104, in create_blueprint
    return client.create_or_update(resource_scope=resource_scope,
  File "/Users/3017971/.azure/cliextensions/blueprint/azext_blueprint/vendored_sdks/blueprint/operations/_blueprints_operations.py", line 98, in create_or_update
    body_content = self._serialize.body(blueprint, 'Blueprint')
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 622, in body
    raise_with_traceback(
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1665, in deserialize_dict
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1665, in <dictcomp>
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1631, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

### Environment Summary

mac os Big Sur 11.6.2
azure-cli                         2.33.1

Python                            3.9.10

Extensions:
blueprint                          0.3.1

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

**Comment by yonzhan** [comment]
route to CXP team
