### ISSUE TITLE
Error after uninstalling Anaconda environment

### ISSUE THREAD

**Issue by gilbertsmink** [Azure/azure-cli-extensions#4482]
## Describe the bug
After uninstalling my Anaconda environment the following error started to occur when using azure cli  

**Command Name**
`az ssh config
Extension Name: ssh. Version: 1.0.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Command '['C:\\WINDOWS\\SysNative\\openSSH\\ssh-keygen.exe', '-L', '-f', 'C:\\Users\\NLGISMI/.ssh\\az_ssh_config\\52.158.114.142\\id_rsa.pub-aadcert.pub']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\NLGISMI\.azure\cliextensions\ssh\azext_ssh\custom.py", line 53, in ssh_config
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip, public_key_file, private_key_file, use_private_ip,
  File "C:\Users\NLGISMI\.azure\cliextensions\ssh\azext_ssh\custom.py", line 93, in _do_ssh_op
    cert_file, username = _get_and_write_certificate(cmd, public_key_file, None)
  File "C:\Users\NLGISMI\.azure\cliextensions\ssh\azext_ssh\custom.py", line 129, in _get_and_write_certificate
    username = ssh_utils.get_ssh_cert_principals(cert_file)[0]
  File "C:\Users\NLGISMI\.azure\cliextensions\ssh\azext_ssh\ssh_utils.py", line 79, in get_ssh_cert_principals
    info = get_ssh_cert_info(cert_file)
  File "C:\Users\NLGISMI\.azure\cliextensions\ssh\azext_ssh\ssh_utils.py", line 75, in get_ssh_cert_info
    return subprocess.check_output(command, shell=platform.system() == 'Windows').decode().splitlines()
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command '['C:\\WINDOWS\\SysNative\\openSSH\\ssh-keygen.exe', '-L', '-f', 'C:\\Users\\NLGISMI/.ssh\\az_ssh_config\\52.158.114.142\\id_rsa.pub-aadcert.pub']' returned non-zero exit status 1.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh config --file {} --ip {} --overwrite`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.0

Extensions:
azure-devops 0.18.0
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @gilbertsmink thanks for reaching on this issue!
Could you please run this command on a new machine where we don't have Conda environments? wanted to check with you if this is caused consistently by the Conda environment Addition\Removal?

Also please refer to a similar [issue](https://github.com/Azure/azure-cli-extensions/issues/4181#issuecomment-996823549):

> Thank you for bringing this problem to our attention. We will have if fixed on the next release of the extension. Meanwhile, another possible workaround is to use the --keys-destination-folder parameter to save the generated keys on a different folder. For example:

`az ssh config --ip '*.internal 10.31.*' --file ~/.ssh/azure/config --keys-destination-folder ~/.ssh/azure/mykeys`

**Comment by SatishBoddu-MSFT** [comment]
Hello @gilbertsmink 
Since we didn't receive any response, we will now close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
