### ISSUE TITLE
Error on webapp create

### ISSUE THREAD

**Issue by kandreadou** [Azure/azure-cli-extensions#4490]
## Describe the bug

**Command Name**
`az webapp create
Extension Name: appservice-kube. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got multiple values for argument 'linux'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/katerina/.azure/cliextensions/appservice-kube/azext_appservice_kube/commands.py", line 42, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/katerina/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 505, in create_webapp
    helper = _StackRuntimeHelper(cmd, client, linux=(is_linux or is_kube))
TypeError: __init__() got multiple values for argument 'linux'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --name {} --resource-group {} --plan {} --deployment-container-image-name {}`

## Environment Summary
```
Linux-5.4.0-1070-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.0 *

Extensions:
appservice-kube 0.2.2
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@kandreadou Apologies for the late reply. I believe you are trying to create a webapp on linux worker. I tried to reproduce the same in my machine and it worked fine. Below are the commands that I ran in order:


>az group create -l eastus -n MyRG

>az appservice plan create -g MyRG -n MyPlan --is-linux --number-of-workers 2 --sku S1

>az webapp create --name MyWebaAppName --resource-group MyRG --plan MyPlan --deployment-container-image-name MyImage:Mytag

Could you please install the Microsoft official Azure CLI for the Deb package from [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and then test the command ? Awaiting your reply.

**Comment by panchagnula** [comment]
@StrawnSC you mentioned that the latest SDK update on core broke some commands on kube extensions is this related to the same?

**Comment by StrawnSC** [comment]
Hi @kandreadou -- it looks like you're running an old version of the extension from private preview (since your version number is `0.2.2`). You should uninstall the extension with `az extension remove -n appservice-kube` and install the latest version (public preview) with `az extension add -n appservice-kube`. You may have to upgrade your CLI version as well
