### ISSUE TITLE
az ssh vm failing with error message

### ISSUE THREAD

**Issue by tap1992** [Azure/azure-cli-extensions#4491]
## Describe the bug
Upon running the command we are receiving an error message. 
have also upgraded the AZ CLI to 2.34.1 and same error occurs. 
Seemed to be working ok yesterday till I restarted my laptop and a windows 11 update installed (may be coincidental) 

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.0.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError -2146893813] : ''
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\travis.perkins\.azure\cliextensions\ssh\azext_ssh\custom.py", line 28, in ssh_vm
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip, public_key_file, private_key_file, use_private_ip,
  File "C:\Users\travis.perkins\.azure\cliextensions\ssh\azext_ssh\custom.py", line 93, in _do_ssh_op
    cert_file, username = _get_and_write_certificate(cmd, public_key_file, None)
  File "C:\Users\travis.perkins\.azure\cliextensions\ssh\azext_ssh\custom.py", line 121, in _get_and_write_certificate
    credential, _, _ = profile.get_login_credentials(subscription_id=profile.get_subscription()["id"])
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 335, in get_login_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 593, in _create_credential
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 233, in get_user_credential
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line 44, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 930, in get_accounts
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 968, in _find_msal_accounts
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 80, in find
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 58, in _reload_if_necessary
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/persistence.py", line 180, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/windows.py", line 114, in unprotect
OSError: [WinError -2146893813] : ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --ip {}`

## Expected Behavior
Creates a SSH Connection

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.0 *

Extensions:
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@tap1992 Thanks for reaching out to us. Could you please try running the below commands in order ?

>az account clear
az login

Then you can try to run the [az ssh vm](https://docs.microsoft.com/en-us/cli/azure/ssh?view=azure-cli-latest#az-ssh-vm) command check if that works. 
If the above steps doesn't fix the issue and if you still see the same error, you can try to delete the contents of the folder
 `C:\Users\<user>\.azure` and run the `az login` command and then try running the [az ssh vm](https://docs.microsoft.com/en-us/cli/azure/ssh?view=azure-cli-latest#az-ssh-vm) command again. Hope this helps.

Please let me know if you have any questions on this. Awaiting your reply.

**Comment by tap1992** [comment]
Hi, deleting the C:\Users\<user>\.azure folder resolved this issue, although not sure why it occurred in the first place

**Comment by navba-MSFT** [comment]
@tap1992 Thanks for getting back. I am glad that the issue is now resolved. The probable cause of this issue is explained [here](https://github.com/Azure/azure-cli/issues/20231#issuecomment-964474753) in this thread Azure/azure-cli#20231. 
We will now proceed with closure of this issue. If the issue resurfaces in future, feel free to reopen this github thread. We would be happy to help.
