### ISSUE TITLE
Unexpected 'az kusto cluster create' error: local variable 'deserialized' referenced before assignment

### ISSUE THREAD

**Issue by til10** [Azure/azure-cli-extensions#4508]
## Describe the bug

**Command Name**
`az kusto cluster create
Extension Name: kusto. Version: 0.4.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
local variable 'deserialized' referenced before assignment
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\<username>\.azure\cliextensions\kusto\azext_kusto\generated\custom.py", line 116, in kusto_cluster_create
    return sdk_no_wait(no_wait,
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 678, in sdk_no_wait
  File "C:\Users\<username>\.azure\cliextensions\kusto\azext_kusto\vendored_sdks\kusto\operations\_clusters_operations.py", line 219, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "C:\Users\<username>\.azure\cliextensions\kusto\azext_kusto\vendored_sdks\kusto\operations\_clusters_operations.py", line 171, in _create_or_update_initial
    return cls(pipeline_response, deserialized, {})
UnboundLocalError: local variable 'deserialized' referenced before assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az kusto cluster create --resource-group {} --location {} --name {} --sku {} {} {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.1 *

Extensions:
azure-iot 0.13.0
kusto 0.4.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by navba-MSFT** [comment]
@til10 Thanks for reaching out to us. We are aware of this issue. The Fix for that is planned for release refer PR Azure/azure-cli-extensions#4360. More Info on the similar issue Azure/azure-cli-extensions#4086 and Azure/azure-cli-extensions#4218. 
I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@til10 I am discussing this with the product owners. I will provide an update on this by next week.

**Comment by navba-MSFT** [comment]
@zoharHenMicrosoft Could you please provide an update on the fix once you get a chance ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
Following up with @zoharHenMicrosoft  offline for the update on the fix.

**Comment by navba-MSFT** [comment]
@til10 Apologies for the late reply. The PR Azure/azure-cli-extensions#4625 is still under review phase. We will update this thread once we have done some progress on this. We appreciate your patience on this.

**Comment by navba-MSFT** [comment]
@til10 Apologies for the late reply. We appreciate your patience on this. I see that the above PR has been merged now. Could you please update to the most recent version of the `kusto` CLI extension (0.5.0) and then run the command again. 

>az extension update --name kusto

Please let us know if you still face the same issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@til10 I wanted to do quick follow-up to check if you had a chance to look at my [above](https://github.com/Azure/azure-cli-extensions/issues/4508#issuecomment-1101987512) comment. Please upgrade to the most recent version of the `kusto` extension and let us know if you still see the same issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@til10 We will now proceed with closure of this github issue. If you see the same issue after upgrading your kusto extension,  please feel free to reopen this thread. We would be happy to help.

**Comment by til10** [comment]
I've given the command another try with the latest extension; the bug appears to have been fixed! Thanks all!

**Comment by zoharHenMicrosoft** [comment]
@Naveen ***@***.***> Hi, still blocked, I sent an email about the current blocker to Ethan
