### ISSUE TITLE
Error running the 'az kusto database-principal-assignment create' command: The value for property 'location' in the input object cannot be empty.

### ISSUE THREAD

**Issue by til10** [Azure/azure-cli-extensions#4509]
## Describe the bug

Note that location is not a valid parameter for this command. The extension may need to provide this value.

**Command Name**
`az kusto database-principal-assignment create
Extension Name: kusto. Version: 0.4.0.`

**Errors:**
```
(InvalidPropertyValue) The value for property 'location' in the input object cannot be empty.
Code: InvalidPropertyValue
Message: The value for property 'location' in the input object cannot be empty.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az kusto database-principal-assignment create --debug --cluster-name {} --database-name {} --principal-assignment-name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.1 *

Extensions:
azure-iot 0.13.0
kusto 0.4.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@til10 Thanks for reaching out to us. I was able to run the above command in my box and it worked fine. Could you please use the [most recent version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)of Azure CLI and try to run the command again ? If you face the issue again, Please share the output of the command with --debug parameter. Awaiting your reply.

**Comment by til10** [comment]
@navba-MSFT I've upgraded to the latest version of Azure CLI. The error remains the same with a couple different cluster locations and SKUs. Perhaps it has to do with the extension-swapping workaround related to the [cluster creation issue](https://github.com/Azure/azure-cli-extensions/issues/450), and documented in the PowerShell below.

```
az extension remove -n kusto # previous kusto extension seems to work better for cluster creation

Run "Kusto: create cluster" (
	az kusto cluster create --resource-group $rg `
		--location $adxClusterLocation --name $names.ADX `
		--sku $sku.ADX.SKU --capacity 2
)

az extension add -n kusto --yes # upcoming kusto extension seems to work fine for database creation

Run "Kusto: create database" (
	az kusto database create --cluster-name $names.ADX `
		--resource-group $rg --database-name $names.ADXDB `
		--read-write-database location=$adxClusterLocation
)

Run "Kusto: assign database principal" (
	az kusto database-principal-assignment create --debug --cluster-name $names.ADX `
		--database-name $names.ADXDB `
		--principal-assignment-name $principalName --resource-group $rg
)
```

The last command results in the error.

**Comment by til10** [comment]
Requested trace with --debug flag:

```
az -v
azure-cli                         2.34.1

core                              2.34.1
telemetry                          1.0.6

Extensions:
azure-iot                         0.13.0
kusto                              0.4.0

cli.knack.cli: Command arguments: ['kusto', 'database-principal-assignment', 'create', '--debug', '--cluster-name', '<prefix>adx', '--database-name', '<prefix>adxdb', '--principal-assignment-name', '<principal name>', '--resource-group', '<RG name>']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Init colorama.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x030640B8>, <function OutputProducer.on_global_arguments at 0x030D1F10>, <function CLIQuery.on_global_arguments at 0x031FAAD8>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'kusto': ['azext_kusto']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: kusto                     0.361        15        77  C:\Users\<username>\.azure\cliextensions\kusto
cli.azure.cli.core: Total (1)                 0.361        15        77
cli.azure.cli.core: Loaded 15 groups, 77 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : kusto database-principal-assignment create
cli.azure.cli.core: Command table: kusto database-principal-assignment create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x034C97C0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\<username>\.azure\commands\2022-03-09.10-47-12.kusto_database-principal-assignment_create.9720.log'.
az_command_data_logger: command args: kusto database-principal-assignment create --debug --cluster-name {} --database-name {} --principal-assignment-name {} --resource-group {}
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0351B418>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0351B4F0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x035765C8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x030D1F58>, <function CLIQuery.handle_query_parameter at 0x031FAB20>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03576580>]
az_command_data_logger: extension name: kusto
az_command_data_logger: extension version: 0.4.0
Command group 'kusto' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=KustoManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\<username>\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.identity: _load_msal_http_cache: C:\Users\<username>\.azure\msal_http_cache.bin
cli.azure.cli.core.auth.identity: __load_msal_http_cache: C:\Users\<username>\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
<snip>
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 6d6cf63b-1666-4485-bd0b-b489790398b3
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<subscription>/resourceGroups/<RG>/providers/Microsoft.Kusto/clusters/<prefix>adx/databases/<prefix>adxdb/principalAssignments/<principal>?api-version=2021-08-27'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '2'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'f3534223-9fd0-11ec-a5fe-005056ba91a2'
cli.azure.cli.core.sdk.policies:     'CommandName': 'kusto database-principal-assignment create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug --cluster-name --database-name --principal-assignment-name --resource-group'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.34.1 (MSI) azsdk-python-kustomanagementclient/unknown Python/3.8.9 (Windows-10-10.0.18362-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<subscription>/resourceGroups/<RG>/providers/Microsoft.Kusto/clusters/<prefix>adx/databases/<prefix>adxdb/principalAssignments/<principal>?api-version=2021-08-27 HTTP/1.1" 400 124
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '124'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'e59a9d16-65c1-486f-993a-f0df6f24664e'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests': '199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'cccd02b0-3d71-4aa7-9c2e-b2e64cf358d6'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS2:20220309T174715Z:cccd02b0-3d71-4aa7-9c2e-b2e64cf358d6'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 09 Mar 2022 17:47:14 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InvalidPropertyValue","message":"The value for property 'location' in the input object cannot be empty."}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\<username>\.azure\cliextensions\kusto\azext_kusto\generated\custom.py", line 722, in kusto_database_principal_assignment_create
    return sdk_no_wait(no_wait,
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 678, in sdk_no_wait
  File "C:\Users\<username>\.azure\cliextensions\kusto\azext_kusto\vendored_sdks\kusto\operations\_database_principal_assignments_operations.py", line 290, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "C:\Users\<username>\.azure\cliextensions\kusto\azext_kusto\vendored_sdks\kusto\operations\_database_principal_assignments_operations.py", line 236, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidPropertyValue) The value for property 'location' in the input object cannot be empty.
Code: InvalidPropertyValue
Message: The value for property 'location' in the input object cannot be empty.

cli.azure.cli.core.azclierror: (InvalidPropertyValue) The value for property 'location' in the input object cannot be empty.
Code: InvalidPropertyValue
Message: The value for property 'location' in the input object cannot be empty.
az_command_data_logger: (InvalidPropertyValue) The value for property 'location' in the input object cannot be empty.
Code: InvalidPropertyValue
Message: The value for property 'location' in the input object cannot be empty.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x034C98E0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.099 seconds (init: 0.413, invoke: 2.687)
telemetry.save: Save telemetry record of length 3358 in cache
telemetry.check: Negative: The C:\Users\<username>\.azure\telemetry.txt was modified at 2022-03-09 10:47:02.663864, which in less than 600.000000 s
cli.azure.cli.core.auth.identity: _dump_msal_http_cache: C:\Users\<username>\.azure\msal_http_cache.bin

```

**Comment by navba-MSFT** [comment]
@til10 Thanks for sharing the commands and debug output. I was able to run the same above commands in order and it worked fine for me. I had used `--sku 'Standard_D11_v2' ` and `--location 'eastus'` in my command. Could you please test with the same and let me know if that helps ? Awaiting your reply.

On a side note, I also see that you are removing the kusto extension before creating the cluster. Please be aware that this command is implicitly deprecated because command group 'kusto cluster' is deprecated and will be removed in a future release. Use '"az extension add -n kusto" to install the supported Kusto extension' instead. The same has been documented [here](https://docs.microsoft.com/en-us/cli/azure/kusto/cluster?view=azure-cli-latest). So my recommendation would be to use the kusto extension even during cluster creation.

**Comment by navba-MSFT** [comment]
@til10 This is a quick follow-up to check if you had a chance to look at my above comment and try my suggested action plan? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@til10 Please let me know if you have any update on this issue.

**Comment by til10** [comment]
Thanks for the comments @navba-MSFT. Pretty sure I had attempted a cluster with Standard_D11_v2/D12_v2 and westus2 values. After some trial and error, I found that using the deprecated command for cluster creation was the only viable option for the SKUs I needed, and that's why I've a) resorted to extension swapping in our PowerShell-driven AZ CLI installation script and b) filed the cluster creation issue #4508. Perhaps we can wait on the resolution of #4508, and then test these two issues at the same time to ensure we are on the same page.

**Comment by navba-MSFT** [comment]
@til10 Thanks for getting back. Sure that makes sense. We can wait for the fix to be deployed for the other issue and then test.
I am tagging @zoharHenMicrosoft here for visibility. This thread can be updated once the fix is released. We appreciate your patience on this.

**Comment by navba-MSFT** [comment]
Following up with @zoharHenMicrosoft  offline for the update on the fix.

**Comment by navba-MSFT** [comment]
@til10 Apologies for the late reply. The PR Azure/azure-cli-extensions#4625 is still under review phase. We will update this thread once we have done some progress on this. We appreciate your patience on this.

**Comment by navba-MSFT** [comment]
@til10 Apologies for the late reply. We appreciate your patience on this. I see that the above PR has been merged now. Could you please update to the most recent version of the `kusto` CLI extension (0.5.0) and then run the command again. 

>az extension update --name kusto

Please let us know if you still face the same issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@til10 I wanted to do quick follow-up to check if you had a chance to look at my [above](https://github.com/Azure/azure-cli-extensions/issues/4509#issuecomment-1101987926) comment. Please upgrade to the most recent version of the `kusto` extension and let us know if you still see the same issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@til10 We will now proceed with closure of this github issue. If you see the same issue after upgrading your kusto extension,  please feel free to reopen this thread. We would be happy to help.
