### ISSUE TITLE
Unable to create new aks cluster with --enable-pod-identity

### ISSUE THREAD

**Issue by srozanc-mcs** [Azure/azure-cli-extensions#4510]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.44.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'DecoratorEarlyExitException'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/srozanc/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 969, in aks_create
    from azext_aks_preview.decorator import AKSPreviewModels
  File "/home/srozanc/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 10, in <module>
    from azure.cli.command_modules.acs._consts import (
ImportError: cannot import name 'DecoratorEarlyExitException'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -g {} -n {} --enable-managed-identity --enable-pod-identity --network-plugin {} --node-vm-size {} --node-count {} --generate-ssh-keys`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.29.2 *

Extensions:
aks-preview 0.5.44

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@srozanc-mcs Apologies for the late reply. Thanks for reporting this issue. I see that you are using an older version of _AzCLI_ and _aks-preview_ extension. Please update both _azure-cli_ (via `az upgrade`) and _aks-preview_ (0.5.48, via `az extension update -n aks-preview`) to the latest version. Please let me know if you face any issues after this.

Similar issue Azure/azure-cli-extensions#4116

**Comment by navba-MSFT** [comment]
@srozanc-mcs I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@srozanc-mcs Please let me know if you are still seeing this issue after following the above plan. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@srozanc-mcs We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
