### ISSUE TITLE
az ssh config error

### ISSUE THREAD

**Issue by kitoyomi** [Azure/azure-cli-extensions#4513]
## Describe the bug

**Command Name**
`az ssh config
Extension Name: ssh. Version: 1.0.0.`

**Errors:**
```
 ~ % az ssh config --ip 10.128.8.10 --file ~/.ssh/azconfig
The command failed with an unexpected error. Here is the traceback:
'Profile' object has no attribute 'get_msal_token'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/metroweather_macos3/.azure/cliextensions/ssh/azext_ssh/custom.py", line 28, in ssh_config
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip, public_key_file, private_key_file, use_private_ip, op_call)
  File "/Users/metroweather_macos3/.azure/cliextensions/ssh/azext_ssh/custom.py", line 48, in _do_ssh_op
    cert_file, username = _get_and_write_certificate(cmd, public_key_file, None)
  File "/Users/metroweather_macos3/.azure/cliextensions/ssh/azext_ssh/custom.py", line 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
AttributeError: 'Profile' object has no attribute 'get_msal_token'
To open an issue, please run: 'az feedback'
 ~ %
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh config --ip {} --file {}`

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
ssh 1.0.0
image-copy-extension 0.2.9

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by navba-MSFT** [comment]
@kitoyomi Thanks for reaching out to us. Could you please follow the below action plan in the order and let me know if that works ?

>az ssh config --ip 23.XXX.XX.86 --file ./sshconfig # Add the right public IP address of the VM
ssh -F ./sshconfig 23.XXX.XX.86

If you are trying to run the command with `--ip *`  (asterisk) then it is expected to fail due to a _known_ issue. We will have that fixed on the next version of the extension. For now, you can use the `--keys-destination-folder `parameter to avoid the error when creating config files with * as the IP. The error happens because the extension tries to create a folder for the keys with the provided IP in the name and that is not possible.

>Example:
az ssh config --file ./sshconfig --ip * **--keys-destination-folder** C:\users<username>\my_keys

You might get a warning about the security while running this command. But your config file should be created. Let me know if that solves your problem. Awaiting your reply.

Similar issue Azure/azure-cli-extensions#4483

**Comment by yonzhan** [comment]
route to CXP team

**Comment by kitoyomi** [comment]
Sorry. I forgot to post the error message so I updated it.

I am trying to access the site via VPN, so I am checking to see if the VPN connection is working.

**Comment by jiasli** [comment]
For 

```
  File "/Users/metroweather_macos3/.azure/cliextensions/ssh/azext_ssh/custom.py", line 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
```

`profile.get_msal_token` is guarded:

https://github.com/Azure/azure-cli-extensions/blob/4e4b9c2f225ca4236667d47465b140e40eb202bc/src/ssh/azext_ssh/custom.py#L161-L169

Also, your `/Users/metroweather_macos3/.azure/cliextensions/ssh/azext_ssh/custom.py` doesn't match the content of https://github.com/Azure/azure-cli-extensions/blob/4e4b9c2f225ca4236667d47465b140e40eb202bc/src/ssh/azext_ssh/custom.py

Looks like your file is somehow not updated correctly.

Please delete `/Users/metroweather_macos3/.azure/cliextensions/ssh` and try to install again with 

```
az extension add --name ssh
```

**Comment by kitoyomi** [comment]
Thanks for pointing out the problem areas.

I was able to resolve the issue.
