### ISSUE TITLE
[Error] Unable to list tentant after extension installed

### ISSUE THREAD

**Issue by rafael-souoliveira-ext** [Azure/azure-cli-extensions#4522]
## Describe the bug

**Command Name**
`az account tenant list
Extension Name: account. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.core.rest'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/home/rafael-oliveira/.azure/cliextensions/account/azext_account/manual/_client_factory.py", line 20, in cf_tenants
    return cf_account(cli_ctx).tenants
  File "/home/rafael-oliveira/.azure/cliextensions/account/azext_account/manual/_client_factory.py", line 9, in cf_account
    from ..vendored_sdks.subscription import SubscriptionClient
  File "/home/rafael-oliveira/.azure/cliextensions/account/azext_account/vendored_sdks/subscription/__init__.py", line 9, in <module>
    from ._subscription_client import SubscriptionClient
  File "/home/rafael-oliveira/.azure/cliextensions/account/azext_account/vendored_sdks/subscription/_subscription_client.py", line 12, in <module>
    from azure.core.rest import HttpRequest, HttpResponse
ModuleNotFoundError: No module named 'azure.core.rest'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account tenant list`

## Environment Summary
```
Linux-5.4.0-104-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.27.2 *

Extensions:
account 0.2.2

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by zhoxing-ms** [comment]
This issue is due to PR #4409 bump the new version of  `azure-mgmt-subscription`. Since `azure.core.rest` is introduced by the new Python SDK, it is incompatible with the old version of CLI. 
@rafael-souoliveira-ext Could you please use the command `az upgrade --yes` to upgrade the CLI to the latest version and try again.

**Comment by rafael-souoliveira-ext** [comment]
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.27.2. It will be updated to 2.29.0.
Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:2 http://br.archive.ubuntu.com/ubuntu focal InRelease                                                     
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease                                              
Get:4 http://br.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                  
Hit:5 http://repository.spotify.com stable InRelease                                                  
Get:7 http://br.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]                          
Hit:6 https://hub-dist.unity3d.com/artifactory/hub-debian-prod-local stable InRelease
Fetched 222 kB in 2s (125 kB/s)        
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
azure-cli is already the newest version (2.27.2-1~bionic).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
CLI upgrade failed or aborted.

**Comment by zhoxing-ms** [comment]
> Your current Azure CLI version is 2.27.2. It will be updated to 2.29.0.
   ...
  CLI upgrade failed or aborted.

@jiasli Could you help look at the problems related to `az upgrade`?

@rafael-souoliveira-ext At present, you can refer to the doc [install-azure-cli](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) manually upgrade the latest version (2.34.1) of CLI

**Comment by rafael-souoliveira-ext** [comment]
Worked on 2.34.1. Thanks.

But I was not enable to upgrade by methods on documentation. I did have to uninstall, purge caches at apt and fresh install again.
