### ISSUE TITLE
Container app creation with component not working

### ISSUE THREAD

**Issue by ShafeerAli** [Azure/azure-cli-extensions#4534]
## Content of Component

- name: servicebus-pubsub
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "**********"

## Describe the bug

**Command Name**
`az containerapp create
Extension Name: containerapp. Version: 0.2.4.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
mapping values are not allowed here
  in ".\components.yml", line 2, column 7
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 713, in _run_job
  File "C:\Users\sadiks\.azure\cliextensions\containerapp\azext_workerapp\_client_factory.py", line 38, in _polish_bad_errors
    raise ex
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\sadiks\.azure\cliextensions\containerapp\azext_workerapp\custom.py", line 386, in create_containerapp
    containerapp_dapr_def.components = dapr_components_from_file(cmd, dapr_components)
  File "C:\Users\sadiks\.azure\cliextensions\containerapp\azext_workerapp\_utils.py", line 11, in dapr_components_from_file
    data = yaml.safe_load(stream)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 125, in safe_load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 81, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/constructor.py", line 49, in get_single_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/composer.py", line 36, in get_single_node
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/composer.py", line 55, in compose_document
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/composer.py", line 84, in compose_node
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/composer.py", line 127, in compose_mapping_node
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/parser.py", line 98, in check_event
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/parser.py", line 428, in parse_block_mapping_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/scanner.py", line 116, in check_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/scanner.py", line 223, in fetch_more_tokens
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/scanner.py", line 577, in fetch_value
yaml.scanner.ScannerError: mapping values are not allowed here
  in ".\components.yml", line 2, column 7

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp create --name {} --resource-group {} --environment {} --image {} --enable-dapr --dapr-components {} --dapr-app-id {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
aro 1.0.0
containerapp 0.2.4

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jsntcy** [comment]
@calvinsID, could you please help take a look at this issue?
BTW, where is `ContainApp` in as I didn't find it in https://github.com/Azure/azure-cli-extensions?

**Comment by navba-MSFT** [comment]
@ShafeerAli Apologies for the late reply. I hope you had a chance to look at the above comment. Could you confirm if you are still facing this issue ?

@panchagnula The --source link in your above comment doesn't seem to be correct as it gives blob not found error? Awaiting your reply.

**Comment by anthonychu** [comment]
@ShafeerAli Can you please share the raw contents of your components.yaml file? Looks like there's a formatting problem with the second line. To post the content without formatting, type 3 backticks `` ``` ``, a newline, then paste your YAML content, followed by a newline and 3 backticks `` ``` ``.  See [this doc](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) for more details.

**Comment by ShafeerAli** [comment]
```
- name: servicebus-pubsub
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://pubsub-my-container-apps.servicebus.windows.net/;SharedAccessKeyName=*****"
```

**Comment by ShafeerAli** [comment]
@anthonychu I hope this helps. Please let me know if you need any further details.

**Comment by anthonychu** [comment]
Looks okay to me. Might need @calvinsID and @haroonf to take a look.

**Comment by navba-MSFT** [comment]
@ShafeerAli Thanks for sharing the requested details.

@calvinsID @haroonf Could you please let us know if you had any updates on this ? Awaiting your reply.

**Comment by sisirap** [comment]
> @ShafeerAli Thanks for sharing the requested details.
> 
> @calvinsID @haroonf Could you please let us know if you had any updates on this ? Awaiting your reply.

@calvinsID since this is the old RP support - can you please take a look?

**Comment by panchagnula** [comment]
@ShafeerAli please try our latest CLI extension for Container apps & let us know if this repros. Make sure to delete the existing extension & install the public extension using az extension add -n containerapp. Thanks
