### ISSUE TITLE
`az image copy - The command failed with an unexpected error

### ISSUE THREAD

**Issue by gidipas** [Azure/azure-cli-extensions#4542]
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.9.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/az/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-resource-group {} --source-object-name {} --target-location {} --target-name {} --target-resource-group {} --cleanup`

## Environment Summary
```
Linux-5.4.0-1072-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
image-copy-extension 0.2.9
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
compute

**Comment by zhoxing-ms** [comment]
@gidipas Could you please send me the debug log by email, my email address is Zhou.Xing@microsoft.com, thanks~

**Comment by gidipas** [comment]
@Xing ***@***.***> where do I get that ?

**Comment by gidipas** [comment]
Hi @Giancarlo ***@***.***>,

Please add the “—debug” parameter to the original command and execute it again, and then send the printed information to me

Thanks,
Xing

________________________________
From: Giancarlo DiPasquale ***@***.***>
Sent: Thursday, March 17, 2022 1:53:07 PM
To: Azure/azure-cli-extensions ***@***.***>; Azure/azure-cli-extensions ***@***.***>; Xing Zhou ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-cli-extensions] `az image copy - The command failed with an unexpected error (Issue #4542)


@Xing ***@***.***> where do I get that ?

**Comment by gidipas** [comment]
***@***.***:~$ az image copy --source-resource-group Intel_EDA --source-object-name CC-basegen2v2 --target-location westus3 --target-name CC-basegen2v2-west3 --target-resource-group "Intel_EDA_West3" --cleanup --debug
cli.knack.cli: Command arguments: ['image', 'copy', '--source-resource-group', 'Intel_EDA', '--source-object-name', 'CC-basegen2v2', '--target-location', 'westus3', '--target-name', 'CC-basegen2v2-west3', '--target-resource-group', 'Intel_EDA_West3', '--cleanup', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f89e8adb1f0>, <function OutputProducer.on_global_arguments at 0x7f89e8a130d0>, <function CLIQuery.on_global_arguments at 0x7f89e89a55e0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'image': ['azure.cli.command_modules.vm', 'azext_imagecopy']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.208        54       278
cli.azure.cli.core: Total (1)                 0.208        54       278
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: image-copy-extension      0.052         1         1  /home/giancarlo/.azure/cliextensions/image-copy-extension
cli.azure.cli.core: ai-examples               0.078         1         1  /opt/az/lib/python3.8/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (2)                 0.130         2         2
cli.azure.cli.core: Loaded 55 groups, 280 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : image copy
cli.azure.cli.core: Command table: image copy
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f89e817f550>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/giancarlo/.azure/commands/2022-03-17.06-13-54.image_copy.183.log'.
az_command_data_logger: command args: image copy --source-resource-group {} --source-object-name {} --target-location {} --target-name {} --target-resource-group {} --cleanup --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f89e8104940>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f89e8046ca0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f89e8046dc0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f89e8a13160>, <function CLIQuery.handle_query_parameter at 0x7f89e89a5670>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f89e8046d30>]
az_command_data_logger: extension name: image-copy-extension
az_command_data_logger: extension version: 0.2.9
cli.azext_imagecopy.cli_utils: command: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'group', 'exists', '-n', 'image-copy-rg', '--output', 'tsv'] ended with output: false

cli.azext_imagecopy.custom: Getting OS disk ID of the source VM/image
cli.azext_imagecopy.cli_utils: command: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'image', 'show', '--name', 'CC-basegen2v2', '--resource-group', 'Intel_EDA', '--output', 'json'] ended with output: {
  "extendedLocation": null,
  "hyperVGeneration": "V2",
  "id": "/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/images/CC-basegen2v2",
  "location": "westus2",
  "name": "CC-basegen2v2",
  "provisioningState": "Succeeded",
  "resourceGroup": "Intel_EDA",
  "sourceVirtualMachine": {
    "id": "/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/virtualMachines/azint-baseimggen2v1",
    "resourceGroup": "Intel_EDA"
  },
  "storageProfile": {
    "dataDisks": [],
    "osDisk": {
      "blobUri": null,
      "caching": "ReadWrite",
      "diskEncryptionSet": {
        "id": "/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/INTEL_EDA/providers/Microsoft.Compute/diskEncryptionSets/POCIntelD2E",
        "resourceGroup": "INTEL_EDA"
      },
      "diskSizeGb": 30,
      "managedDisk": {
        "id": "/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d",
        "resourceGroup": "Intel_EDA"
      },
      "osState": "Generalized",
      "osType": "Linux",
      "snapshot": null,
      "storageAccountType": "Premium_LRS"
    },
    "zoneResilient": null
  },
  "tags": {},
  "type": "Microsoft.Compute/images"
}

cli.azext_imagecopy.cli_utils: json output starts at position: 0
cli.azext_imagecopy.custom: found DISK: /subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d
cli.azext_imagecopy.custom: source_os_disk_type: DISK. source_os_disk_id: /subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d. source_os_type: Linux
cli.azext_imagecopy.custom: Creating source snapshot
cli.azext_imagecopy.cli_utils: command failed: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']
cli.azext_imagecopy.cli_utils: output: ERROR: (NotFound) Resource azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d is not found.
Code: NotFound
Message: Resource azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d is not found.

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/az/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/az/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
az_command_data_logger: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/giancarlo/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
 File "/opt/az/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
To open an issue, please run: 'az feedback'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f89e817f790>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 7.014 seconds (init: 0.099, invoke: 6.915)
telemetry.save: Save telemetry record of length 7115 in cache
telemetry.check: Negative: The /home/giancarlo/.azure/telemetry.txt was modified at 2022-03-17 06:11:24.842526, which in less than 600.000000 s
***@***.***:~$

From: Xing Zhou ***@***.***>
Sent: Thursday, March 17, 2022 2:10 AM
To: Giancarlo DiPasquale ***@***.***>; Azure/azure-cli-extensions ***@***.***>; Azure/azure-cli-extensions ***@***.***>
Cc: Mention ***@***.***>; Yong Zhang ***@***.***>
Subject: RE: [Azure/azure-cli-extensions] `az image copy - The command failed with an unexpected error (Issue #4542)

Hi @Giancarlo ***@***.***>,

Please add the "-debug" parameter to the original command and execute it again, and then send the printed information to me

Thanks,
Xing

________________________________
From: Giancarlo DiPasquale ***@***.******@***.***>>
Sent: Thursday, March 17, 2022 1:53:07 PM
To: Azure/azure-cli-extensions ***@***.******@***.***>>; Azure/azure-cli-extensions ***@***.******@***.***>>; Xing Zhou ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [Azure/azure-cli-extensions] `az image copy - The command failed with an unexpected error (Issue #4542)


@Xing ***@***.***> where do I get that ?

**Comment by zhoxing-ms** [comment]
> cli.azext_imagecopy.custom: Creating source snapshot
cli.azext_imagecopy.cli_utils: command failed: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'CC-basegen2v2_os_disk_snapshot', '--location', 'westus2', '--resource-group', 'Intel_EDA', '--source', '/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']
cli.azext_imagecopy.cli_utils: output: ERROR: (NotFound) Resource azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d is not found.
Code: NotFound
Message: Resource azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d is not found.

This problem is caused by the source disk `/subscriptions/1d81cec7-7ded-4731-884e-90c5aa59c622/resourceGroups/Intel_EDA/providers/Microsoft.Compute/disks/azint-baseimggen2v1_OsDisk_1_7756cecd82874923bccb0760f3d0d02d` not being found when creating a source snapshot

**Comment by gidipas** [comment]
The image creation process deletes the vm and os drive. Does this mean we can’t use az image copy to copy an image from one region to another without that os drive?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhoxing-ms** [comment]
> The image creation process deletes the vm and os drive. 

There is no such logic in `az image copy`. May I ask what do you mean by `The image creation process deletes the vm and os drive. `?

**Comment by gidipas** [comment]
Image capture from the portal has an option to delete the VM upon creation.  I believe the customer im working with did that and may not have the OS drive any longer. az image copy will not work if that OS drive no longer exists?

**Comment by ttt-dlloyd** [comment]
This bug was never fixed and it appears that the az image copy command isn't able to function at all - over a year later from these comments. It isn't a feature request; I don't think that can be disputed. It is a feature that exists and has been broken for years now without being fixed.

Correct command as specified by the documentation:
>>               az image copy --source-resource-group CustomImagesRG `
>>               --source-object-name Win10MultiV9.5-20220107 `
>>               --target-resource-group CustomImagesRG `
>>               --target-location eastus `
>>               --target-subscription 12345678-1234-1234-1234-605185bb3005 
>> 

Output: 
>> Getting OS disk ID of the source VM/image
>> Creating source snapshot
>> command failed: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Win10MultiV9.5-20220107_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'CustomImagesRG', '--source', '/subscriptions/12345678-1234-1234-1234-605185bb3005/resourceGroups/AVDImageBuildRG/providers/Microsoft.Compute/disks/AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']
>> output: ERROR: (NotFound) Resource AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88 is not found.
>> Code: NotFound
>> Message: Resource AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88 is not found.
>> 
>> The command failed with an unexpected error. Here is the traceback:
>> Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Win10MultiV9.5-20220107_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'CustomImagesRG', '--source', '/subscriptions/12345678-1234-1234-1234-605185bb3005/resourceGroups/AVDImageBuildRG/providers/Microsoft.Compute/disks/AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned >> non-zero exit status 3.
>> Traceback (most recent call last):
>>   File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
>>     cmd_result = self.invocation.execute(args)
>>   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
>>     raise ex
>>   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
>>     results.append(self._run_job(expanded_arg, cmd_copy))
>>   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
>>     result = cmd_copy(params)
>>   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
>>     return self.handler(*args, **kwargs)
>>   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
>>     return op(**command_args)
>>   File "/home/csp/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
>>     run_cli_command(cli_cmd)
>>   File "/home/csp/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
>>     raise ex
>>  File "/home/csp/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
>>    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
>>   File "/opt/az/lib/python3.10/subprocess.py", line 420, in check_output
>>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>>   File "/opt/az/lib/python3.10/subprocess.py", line 524, in run
>>     raise CalledProcessError(retcode, process.args,
>> subprocess.CalledProcessError: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Win10MultiV9.5-20220107_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'CustomImagesRG', '--source', '/subscriptions/12345678-1234-1234-1234-605185bb3005/resourceGroups/AVDImageBuildRG/providers/Microsoft.Compute/disks/AVDImageBuild_OsDisk_1_4125c892f47a42c09530358ab9632b88', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.

**Comment by DavidDAmato** [comment]
First I got this error: 

`command failed: ['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'image_os_disk_snapshot', '--location', 'westus', '--resource-group', 
'ImageStoreRG', '--source', '/subscriptions/subID/resourceGroups/rg/providers/Microsoft.Compute/disks/VM-IMAGEVM_UNIQUEID', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: (NotFound) Resource M-IMAGEVM_disk1_UNIQUEID is not found.
Code: NotFound
Message: Resource VM-IMAGEVM_disk1_UNIQUEID is not found.`

I had to create a new VM off my current image and take a new image so both the source VM and image existed at the same time. That shouldn't be required but is. Next the --target-location is used to generate a storage account name (3 to 24 chars, no spaces or special characters) and doesn't need to be a valid azure location input like 'West US'. WestUS worked for me.


```Powershell

# Login 
$sourceSubscription = "sourceSubID"
az login
az account set --subscription $sourceSubscription

# Set vars
$sourceResourceGroup = "ImageStoreRG"
$sourceObjectName = "myImageName"
$targetLocation = "WestUS"
$targetResourceGroup = "destinationRG"
$targetSubscriptionId = "targetSubID"
# vmName needs to exist as a vm object. It is the VM that you used to create your sourceObjectName imageID
$vmName = "imageVMobj"

# add extension if you don't have it
az extension add --name image-copy-extension
az image copy --source-resource-group $sourceResourceGroup --source-object-name $sourceObjectName --source-type image --target-location $targetLocation --target-resource-group $targetResourceGroup --target-subscription $targetSubscriptionId
```

I tested this script in PS7 with the latest AZ libraries as of January 2023 and successfully copied from one subscription to another. It shouldn't require both VM image and also the source VM object to take a snapshot of but I have not found a away around that.

**Comment by barakbd** [comment]
I am also getting an error:
```$ az image copy --source-resource-group RESOURCE_GROUP --source-object-name OBJECT1 --target-resource-group RESOURCE_GROUP --target-location WUS2 --target-name OBJECT1

Getting OS disk ID of the source VM/image
The command failed with an unexpected error. Here is the traceback:
'managedDisk'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.56.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.56.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.56.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.56.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.56.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.56.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/b0b0cu5/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 61, in imagecopy
    source_os_disk_id = json_cmd_output['storageProfile']['osDisk']['managedDisk']['id']
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'managedDisk'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```
