### ISSUE TITLE
CSI Secret store add on flag not working

### ISSUE THREAD

**Issue by sebastian2696** [Azure/azure-cli-extensions#4543]
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.28.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\sefouber\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 1871, in aks_update
    azure_keyvault_secrets_provider_addon_profile.config[CONST_SECRET_ROTATION_ENABLED] = "true"
TypeError: 'NoneType' object does not support item assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --enable-secret-rotation`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
aks-preview 0.5.28

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context

The driver is installed, just the add on is not enabled

Following (this guide)[https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#enable-and-disable-autorotation]

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@sebastian2696 I do not see any issues with the cmdlet.  Can you try updating the extension by using `az extension update --name aks-preview`?

**Comment by sebastian2696** [comment]
I tried it after updating and that didn't work either

**Comment by RakeshMohanMSFT** [comment]
@sebastian2696 Apologies for the delay in getting back. Can you please upgrade to the latest cli [2.40.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry? if you still see the issue, do share the debug traces with us after sanitizing sensitive information from them.
