### ISSUE TITLE
"az webapp create" issue after installing latest extension

### ISSUE THREAD

**Issue by GregWrightkjhiuj** [Azure/azure-cli-extensions#4561]
## Describe the bug

**Command Name**
`az webapp create
Extension Name: appservice-kube. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got multiple values for argument 'linux'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/greg/.azure/cliextensions/appservice-kube/azext_appservice_kube/commands.py", line 42, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/greg/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 505, in create_webapp
    helper = _StackRuntimeHelper(cmd, client, linux=(is_linux or is_kube))
TypeError: __init__() got multiple values for argument 'linux'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create -g {} -p {} -n {}`

## Environment Summary
```
Linux-5.4.0-1073-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
customlocation 0.1.3
k8s-extension 1.0.4
appservice-kube 0.2.2
connectedk8s 1.2.7
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@GregWrightkjhiuj It looks like you're running an old version of the extension from private preview (since your version number is 0.2.2). You should uninstall the extension with `az extension remove -n appservice-kube` and install the latest version (public preview) with `az extension add -n appservice-kube`. After this you can test the command again. Awaiting your reply.

Similar issue https://github.com/Azure/azure-cli-extensions/issues/4490

**Comment by navba-MSFT** [comment]
@GregWrightkjhiuj I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@GregWrightkjhiuj We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
