### ISSUE TITLE
az aks get-credentials returns a Pyhton error: KeyError: 'name' 

### ISSUE THREAD

**Issue by gpaulissen** [Azure/azure-cli-extensions#4569]
## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.5.58.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'name'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/gpaulissen/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 937, in aks_get_credentials
    _print_or_merge_credentials(
  File "/Users/gpaulissen/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2316, in _print_or_merge_credentials
    merge_kubernetes_configurations(
  File "/Users/gpaulissen/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2392, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
  File "/Users/gpaulissen/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2335, in _handle_merge
    if i['name'] == j['name']:
KeyError: 'name'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --overwrite-existing`

## Environment Summary
```
macOS-11.6.1-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
aks-preview 0.5.58

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@gpaulissen Apologies for the late reply. Thanks for reaching out us and sharing this feedback. You can check under the user profile for file ~/.kube/config. There are 3 required sections which must be present: clusters, contexts and users. I feel there seems to be an issue to read this config file. You can try to rename or delete the file and run the [az aks get-credentials ](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials)command and check if that works.

Alternatively you can pass the --file or --overwrite-existing parameter and run the command again. More Info here.

Please let us know if you still need any assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@gpaulissen I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@gpaulissen Please let me know if you have update on this. Also please do reach out to me if you have any further questions on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@gpaulissen We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
