### ISSUE TITLE
Cannot deserialize content type out on command az redisenterprise database list-keys

### ISSUE THREAD

**Issue by BobBrackeRD** [Azure/azure-cli-extensions#4575]
## Describe the bug
We use this command in an automated way to get the access key from the enterprise redis cache. However. the command stopped working around 17hours ago. Resulting in the following error mentioned below. Sometime the first run works but after that the command keeps spewing out the error.

**Command Name**
`az redisenterprise database list-keys
Extension Name: redisenterprise. Version: 0.1.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize content-type: text/plain
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Bob_b\.azure\cliextensions\redisenterprise\azext_redisenterprise\generated\custom.py", line 195, in redisenterprise_database_list_keys
    return client.list_keys(resource_group_name=resource_group_name,
  File "C:\Users\Bob_b\.azure\cliextensions\redisenterprise\azext_redisenterprise\vendored_sdks\redisenterprise\operations\_databases_operations.py", line 635, in list_keys
    error = self._deserialize(models.ErrorResponse, response)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1367, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1539, in _unpack_content
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/universal.py", line 203, in deserialize_from_text
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-  az account set -s {subscriptionID}
- `az redisenterprise database list-keys --resource-group {} --cluster-name {}`

## Expected Behavior
The command should return the access keys that are available for the database in the enterprise redis cache

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
account 0.2.2
front-door 1.0.16
redisenterprise 0.1.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by BobBrackeRD** [comment]
Also does not work when calling the REST api: 
`az rest --uri https://management.azure.com/subscriptions/subID/resourceGroups/rgName/providers/Microsoft.Cache/redisEnterprise/redisname/listKeys?api-version=2021-03-01 --method post --headers $header`
The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 538, in shell_safe_json_parse
  File "json\__init__.py", line 370, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 844, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 563, in shell_safe_json_parse
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse JSON: System.Collections.Hashtable
Error detail: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 23, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 847, in send_raw_request
ValueError: not enough values to unpack (expected 2, got 1)
To open an issue, please run: 'az feedback'

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@jsntcy In which region your Redis Cache resource is located ?

**Comment by BobBrackeRD** [comment]
We are using ENTERPRISE redis cache in the West Europe with the SKU: Enterprise_E10

**Comment by SaurabhSharma-MSFT** [comment]
@BobBrackeRD I have checked this with the same configuration but I am not getting any errors.  I could get the results without any issues - 
![image](https://user-images.githubusercontent.com/38112130/162093402-42722bdb-67ae-4be0-8257-dc1f773d809d.png)

**Comment by BobBrackeRD** [comment]
@SaurabhSharma-MSFT I am owner of the resources. It does however work again now. This was not the case when I initially posted this issue. Can be closed now for me, however no explanation to what caused this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@BobBrackeRD sure, thanks for the confirmation.  We will now proceed to close this thread. Please feel free to open a new issue in case you see any other issues. 
Thanks
Saurabh
