### ISSUE TITLE
[db-up] `db-up` fails to install on Python 3.10

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli-extensions#4608]
### Extension name (the extension in question)

`db-up`

### Description of issue (in as much detail as possible)

`db-up` fails to install on Python 3.10. This will become a big problem since MSI's bundled Python has been updated to 3.10 (https://github.com/Azure/azure-cli/pull/21746):

```
> az extension add -n db-up --debug
...
Building wheels for collected packages: pymssql
  Created temporary directory: C:\Users\username\AppData\Local\Temp\pip-wheel-cxx55aw1
  Destination directory: C:\Users\username\AppData\Local\Temp\pip-wheel-cxx55aw1
  Building wheel for pymssql (pyproject.toml): started
  Running command Building wheel for pymssql (pyproject.toml)
  setup.py: platform.system() => Windows
  setup.py: platform.architecture() => ('64bit', 'WindowsPE')
  setup.py: include_dirs => []
  setup.py: library_dirs => []
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\pymssql
  copying src\pymssql\__init__.py -> build\lib.win-amd64-3.10\pymssql
  running build_ext
  cythoning src\pymssql\_mssql.pyx to src\pymssql\_mssql.c
  cythoning src\pymssql\_pymssql.pyx to src\pymssql\_pymssql.c
  building 'pymssql._mssql' extension
  creating build\temp.win-amd64-3.10
  creating build\temp.win-amd64-3.10\Release
  creating build\temp.win-amd64-3.10\Release\src
  creating build\temp.win-amd64-3.10\Release\src\pymssql
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\cli\py310\include -IC:\Users\username\AppData\Local\Programs\Python\Python310\include -IC:\Users\username\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /Tcsrc\pymssql\_mssql.c /Fobuild\temp.win-amd64-3.10\Release\src\pymssql\_mssql.obj -DMSDBLIB
  _mssql.c
  src\pymssql\_mssql.c(688): fatal error C1083: Cannot open include file: 'sqlfront.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  error: subprocess-exited-with-error

  Building wheel for pymssql (pyproject.toml) did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'D:\cli\py310\Scripts\python.exe' 'D:\cli\py310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\username\AppData\Local\Temp\tmpopi20ied'
  cwd: C:\Users\username\AppData\Local\Temp\pip-install-ot5wfu1n\pymssql_0116479ec63146699bcb3b2980383a29
  Building wheel for pymssql (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for pymssql
Failed to build pymssql
ERROR: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "D:\cli\py310\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\cli\py310\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "D:\cli\py310\lib\site-packages\pip\_internal\commands\install.py", line 375, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects
Removed build tracker: 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-req-tracker-l41tejjf'
```

**Comment by yonzhan** [comment]
db-up
