### ISSUE TITLE
Token error when connecting via SSH to Ubuntu VM with Azure AD login

### ISSUE THREAD

**Issue by marineadz** [Azure/azure-cli-extensions#4611]
## Describe the bug

Unable to connect via SSH to an Ubuntu VM using Azure AD login (AADSSHLoginForLinux extension) - token error

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 0.1.6.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity.Â The token was issued on 2021-11-07T15:33:50.2272016Z and was inactive for 90.00:00:00.\r\nTrace ID: c3312c26-f395-4027-8ae0-278146bf2f00\r\nCorrelation ID: a08e5af8-a9b1-43ab-9276-56a04c7f8341\r\nTimestamp: 2022-04-01 10:23:15Z","error_codes":[700082],"timestamp":"2022-04-01 10:23:15Z","trace_id":"c3312c26-f395-4027-8ae0-278146bf2f00","correlation_id":"a08e5af8-a9b1-43ab-9276-56a04c7f8341","error_uri":"https://login.microsoftonline.com/error?code=700082"}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\MyUserName\.azure\cliextensions\ssh\azext_ssh\custom.py", line 22, in ssh_vm
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip,
  File "C:\Users\MyUserName\.azure\cliextensions\ssh\azext_ssh\custom.py", line 49, in _do_ssh_op
    cert_file, username = _get_and_write_certificate(cmd, public_key_file, None)
  File "C:\Users\MyUserName\.azure\cliextensions\ssh\azext_ssh\custom.py", line 74, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 645, in get_msal_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 1115, in retrieve_token_for_user
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/authentication_context.py", line 145, in acquire_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/authentication_context.py", line 128, in _acquire_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/authentication_context.py", line 143, in token_func
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/token_request.py", line 349, in get_token_from_cache_with_refresh
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/token_request.py", line 127, in _find_token_from_cache
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/cache_driver.py", line 198, in find
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/cache_driver.py", line 177, in _refresh_entry_if_necessary
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/cache_driver.py", line 153, in _refresh_expired_entry
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/token_request.py", line 137, in _get_token_with_token_response
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/token_request.py", line 341, in _get_token_with_refresh_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/token_request.py", line 112, in _oauth_get_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/oauth2_client.py", line 289, in get_token
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity.Â The token was issued on 2021-11-07T15:33:50.2272016Z and was inactive for 90.00:00:00.\r\nTrace ID: c3312c26-f395-4027-8ae0-278146bf2f00\r\nCorrelation ID: a08e5af8-a9b1-43ab-9276-56a04c7f8341\r\nTimestamp: 2022-04-01 10:23:15Z","error_codes":[700082],"timestamp":"2022-04-01 10:23:15Z","trace_id":"c3312c26-f395-4027-8ae0-278146bf2f00","correlation_id":"a08e5af8-a9b1-43ab-9276-56a04c7f8341","error_uri":"https://login.microsoftonline.com/error?code=700082"}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --ip {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.0 *

Extensions:
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@marineadz Apologies for the late reply. The error is self explanatory. Due to inactivity the refresh AAD bearer token seems to be expired. Could you please follow the below steps in order ?

>az extension update --name ssh  # update ssh extension since you are using an older one
az login # Login to your Azure account. So that we get a new AAD bearer token

On a side note, you may also have to [update your AzCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) since you are using an older version. Please let me know if you still encounter the same issue after following the above plan. Awaiting your reply.

**Comment by marineadz** [comment]
@navba-MSFT All solved, updating AzCLI did the trick. Thanks for your help.
