### ISSUE TITLE
"UnboundLocalError: local variable 'deserialized'" with azure-cli 2.34.1

### ISSUE THREAD

**Issue by jaburi** [Azure/azure-cli-extensions#4612]
## Describe the bug

**Command Name**
`az kusto cluster create
Extension Name: kusto. Version: 0.4.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
local variable 'deserialized' referenced before assignment
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/aadmin/.azure/cliextensions/kusto/azext_kusto/generated/custom.py", line 116, in kusto_cluster_create
    return sdk_no_wait(no_wait,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/util.py", line 678, in sdk_no_wait
    return func(*args, **kwargs)
  File "/home/aadmin/.azure/cliextensions/kusto/azext_kusto/vendored_sdks/kusto/operations/_clusters_operations.py", line 219, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/home/aadmin/.azure/cliextensions/kusto/azext_kusto/vendored_sdks/kusto/operations/_clusters_operations.py", line 171, in _create_or_update_initial
    return cls(pipeline_response, deserialized, {})
UnboundLocalError: local variable 'deserialized' referenced before assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az kusto cluster create --cluster-name {} --resource-group {} --subscription {} --sku {} {} {} --location {} --type {}`

## Environment Summary
```
Linux-5.4.0-1072-azure-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
kusto 0.4.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by SaurabhSharma-MSFT** [comment]
@jaburi Thanks for your feedback! We will investigate and update as appropriate.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@jaburi I am able to reproduce this issue and checking internally with the products team on the same.  I will get back to you as soon as I have an update -
![image](https://user-images.githubusercontent.com/38112130/163457694-04578e7e-ca5f-4e0a-9814-32fe1a6909e0.png)

**Comment by SaurabhSharma-MSFT** [comment]
@jaburi This has been fixed in the newer version of Az module. Please use Kusto 0.5.0 version and let me know if you have any questions.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@jaburi We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
