### ISSUE TITLE
az quantum job submit --target-id ionq.simulator  : basic experiment fails on CLI

### ISSUE THREAD

**Issue by nittikkin** [Azure/azure-cli-extensions#4620]
## Describe the bug

**Command Name**
`az quantum job submit
Extension Name: quantum. Version: 0.14.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.core.rest'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\NSK031\.azure\cliextensions\quantum\azext_quantum\operations\job.py", line 196, in submit
    return get(cmd, job_id, resource_group_name, workspace_name, location)
  File "C:\Users\NSK031\.azure\cliextensions\quantum\azext_quantum\operations\job.py", line 34, in get
    client = cf_jobs(cmd.cli_ctx, info.subscription, info.resource_group, info.name, info.location)
  File "C:\Users\NSK031\.azure\cliextensions\quantum\azext_quantum\_client_factory.py", line 73, in cf_jobs
    return cf_quantum(cli_ctx, subscription_id, resource_group_name, workspace_name, location).jobs
  File "C:\Users\NSK031\.azure\cliextensions\quantum\azext_quantum\_client_factory.py", line 62, in cf_quantum
    from .vendored_sdks.azure_quantum import QuantumClient
  File "C:\Users\NSK031\.azure\cliextensions\quantum\azext_quantum\vendored_sdks\azure_quantum\__init__.py", line 9, in <module>
    from ._quantum_client import QuantumClient
  File "C:\Users\NSK031\.azure\cliextensions\quantum\azext_quantum\vendored_sdks\azure_quantum\_quantum_client.py", line 17, in <module>
    from .operations import JobsOperations, ProvidersOperations, QuotasOperations, StorageOperations
  File "C:\Users\NSK031\.azure\cliextensions\quantum\azext_quantum\vendored_sdks\azure_quantum\operations\__init__.py", line 9, in <module>
    from ._jobs_operations import JobsOperations
  File "C:\Users\NSK031\.azure\cliextensions\quantum\azext_quantum\vendored_sdks\azure_quantum\operations\_jobs_operations.py", line 16, in <module>
    from azure.core.rest import HttpRequest
ModuleNotFoundError: No module named 'azure.core.rest'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az quantum job submit --target-id {} -o {} -g {} -w {} -l {} --job-name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.1 *

Extensions:
quantum 0.14.0

```

**Comment by yonzhan** [comment]
quantum

**Comment by navba-MSFT** [comment]
@nittikkin Apologies for the late reply. Since you are using an older version of the Azure CLI, Could you please upgrade to the [most recent AzCLI version](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli) using the below command ?

>az upgrade

Please test again after you upgrade and let me know if you face any issues. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@nittikkin I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@nittikkin We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
