### ISSUE TITLE
[INTERACTIVE] Exception when starting interactive mode

### ISSUE THREAD

**Issue by justinwilaby** [Azure/azure-cli-extensions#464]
I am seeing the following exception when using `az interactive`:

>Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/microsoft/.azure/cliextensions/interactive/azext_interactive/azclishell/threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "/Users/microsoft/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 87, in dump_command_table        *
    main_loader.load_arguments(None)-------------------------------------------------------------
  File "/Users/microsoft/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 33, in load_arguments-------------------------------------------------------------
    from azure.cli.core import ArgumentsContextide the application
ImportError: cannot import name 'ArgumentsContext' from 'azure.cli.core' (/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py)

Az Cli was installed on macOs Mojave using HomeBrew.

```sh
azure-cli (2.0.52)

acr (2.1.10)
acs (2.3.12)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.8)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.2)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.9)
core (2.0.52)
cosmosdb (0.2.5)
dla (0.2.3)
dls (0.1.6)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.4)
keyvault (2.2.8)
lab (0.1.4)
maps (0.3.2)
monitor (0.2.7)
network (2.2.10)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.6)
role (2.1.11)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.9)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.6)
vm (2.2.9)

Extensions:
interactive (0.4.1)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/microsoft/.azure/cliextensions'

Python (Darwin) 3.7.2 (default, Dec 27 2018, 07:35:06) 
[Clang 10.0.0 (clang-1000.11.45.5)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by yonzhan** [comment]
add to backlog

**Comment by jiasli** [comment]
This is a very old version of Azure CLI. Please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest to install the latest version and update `interactive` to 0.4.4 with `az extension update -n interactive`.
