### ISSUE TITLE
An error occurred when I run command - az webapp create

### ISSUE THREAD

**Issue by hothotsyu** [Azure/azure-cli-extensions#4650]
## Describe the bug

**Command Name**
`az webapp create
Extension Name: appservice-kube. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got multiple values for argument 'linux'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/hothotsyu/.azure/cliextensions/appservice-kube/azext_appservice_kube/commands.py", line 42, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/hothotsyu/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 505, in create_webapp
    helper = _StackRuntimeHelper(cmd, client, linux=(is_linux or is_kube))
TypeError: __init__() got multiple values for argument 'linux'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create -g {} -p {} -n {}`

## Environment Summary
```
Linux-5.4.0-1074-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
appservice-kube 0.2.2
ai-examples 0.2.5
ssh 1.0.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by panchagnula** [comment]
@hothotsyu i believe you are using an old private extension version here Extensions:
appservice-kube 0.2.2
please remove this version & install the latest using az extension add -n appservice-kube

**Comment by hothotsyu** [comment]
Hello Sisira,
Good day!

Thanks for your kind response!

Best Reagrds,
Peter

________________________________
差出人: Sisira Panchagnula ***@***.***>
送信日時: 2022年4月8日 4:09
宛先: Azure/azure-cli-extensions ***@***.***>
CC: hothotsyu ***@***.***>; Mention ***@***.***>
件名: Re: [Azure/azure-cli-extensions] An error occurred when I run command - az webapp create (Issue #4650)


@hothotsyu<https://github.com/hothotsyu> i believe you are using an old private extension version here Extensions:
appservice-kube 0.2.2
please remove this version & install the latest using az extension add -n appservice-kube

**Comment by hothotsyu** [comment]
Hello Sisira,
Good day!

My adding extension command is [az extension add --yes --source "https://aka.ms/appsvc/appservice_kube-latest-py2.py3-none-any.whl"], Is it wrong?

Best Reagrds,
Peter
________________________________
差出人: Sisira Panchagnula ***@***.***>
送信日時: 2022年4月8日 4:09
宛先: Azure/azure-cli-extensions ***@***.***>
CC: hothotsyu ***@***.***>; Mention ***@***.***>
件名: Re: [Azure/azure-cli-extensions] An error occurred when I run command - az webapp create (Issue #4650)


@hothotsyu<https://github.com/hothotsyu> i believe you are using an old private extension version here Extensions:
appservice-kube 0.2.2
please remove this version & install the latest using az extension add -n appservice-kube
