### ISSUE TITLE
az monitor app-insights web-test list

### ISSUE THREAD

**Issue by pdahlgren** [Azure/azure-cli-extensions#4679]
## Describe the bug

**Command Name**
`az monitor app-insights web-test list
Extension Name: application-insights. Version: 0.1.16.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type, KeyError: 'HeaderField'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in deserialize_iter
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1620, in deserialize_data
KeyError: 'HeaderField'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 705, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 84, in __next__
  File "C:\Users\A004644\.azure\cliextensions\application-insights\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2018_05_01_preview\operations\_web_tests_operations.py", line 96, in extract_data
    deserialized = self._deserialize('WebTestListResult', pipeline_response)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1368, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in deserialize_iter
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in deserialize_iter
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1620, in deserialize_data
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: 'HeaderField'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- There is a manually created standard (preview) test in the resource group
- `az monitor app-insights web-test list --resource-group {} --subscription {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
application-insights 0.1.16

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
monitor

**Comment by YuanyuanNi** [comment]
Hi：
      @pdahlgren 'az monitor app-insights web-test list' works well as below ,maybe you can  update your CLI version and try again, you can also refer below steps:
1.az monitor app-insights component create -a test-app -l westus -g nyy01 --kind web --application-type web
2.az monitor app-insights web-test create -n test-webtest -l westus -g nyy02 --enabled true --frequency 900 --web-test-kind standard --locations Id=us-fl-mia-edge --defined-web-test-name test-webtest --http-verb POST --request-body SGVsbG8gd29ybGQ= --request-url https://www.bing.com/ --retry-enabled true --synthetic-monitor-id test-webtest --timeout 120 --ssl-lifetime-check 100 --ssl-check true --tags /subscriptions/XX/resourceGroups/nyy01/providers/microsoft.insights/components/test-app=Resource
3.az monitor app-insights web-test list -g nyy01
![image](https://user-images.githubusercontent.com/95396631/175485293-243b799a-062c-435b-acf3-3d0f1e97be15.png)


Best wishes.

**Comment by RakeshMohanMSFT** [comment]
@pdahlgren Please reopen this issue if the issue resurfaces.
