### ISSUE TITLE
Installation of ml extension fails on Windows 10

### ISSUE THREAD

**Issue by Roy7017** [Azure/azure-cli-extensions#4682]
- If the issue is to do with Azure CLI 2.0 in particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
The extension in particular is the new azure ml extension (v2 preview).

#### Describe the bug

az extension add -n ml -y fails with error:
```
ERROR: Cannot install ml because these package versions have conflicting dependencies.

The conflict is caused by:
    docker 5.0.3 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.2 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.1 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.0 depends on pywin32==227; sys_platform == "win32"
```

### To reproduce
Windows 10 Home Version 21H2 Build 19044.1586
```
❯ python --version
Python 3.8.5
```
```
❯ pip --version
pip 20.1.1
```
```
❯ az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```
The command was run in PowerShell administrator mode
Running the command `az extension add -n ml -y --debug` in debug gives:
```
...

Collecting applicationinsights<=0.11.10
  Created temporary directory: C:\Users\roybm\AppData\Local\Temp\pip-unpack-kicn9wba
  https://files.pythonhosted.org:443 "GET /packages/a1/53/234c53004f71f0717d8acd37876e0b65c121181167057b9ce1b1795f96a0/applicationinsights-0.11.9-py2.py3-none-any.whl HTTP/1.1" 200 58531
  Downloading applicationinsights-0.11.9-py2.py3-none-any.whl (58 kB)
     ---------------------------------------- 58.5/58.5 KB 1.6 MB/s eta 0:00:00
  Added applicationinsights<=0.11.10 from https://files.pythonhosted.org/packages/a1/53/234c53004f71f0717d8acd37876e0b65c121181167057b9ce1b1795f96a0/applicationinsights-0.11.9-py2.py3-none-any.whl#sha256=b88bc5a41385d8e516489128d5e63f8c52efe597a3579b1718d1ab2f7cf150a2 (from ml==2.2.2) to build tracker 'C:\\Users\\roybm\\AppData\\Local\\Temp\\pip-req-tracker-dk38kj5r'
  Removed applicationinsights<=0.11.10 from https://files.pythonhosted.org/packages/a1/53/234c53004f71f0717d8acd37876e0b65c121181167057b9ce1b1795f96a0/applicationinsights-0.11.9-py2.py3-none-any.whl#sha256=b88bc5a41385d8e516489128d5e63f8c52efe597a3579b1718d1ab2f7cf150a2 (from ml==2.2.2) from build tracker 'C:\\Users\\roybm\\AppData\\Local\\Temp\\pip-req-tracker-dk38kj5r'
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pathspec to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of ml to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install ml because these package versions have conflicting dependencies.

The conflict is caused by:
    docker 5.0.3 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.2 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.1 depends on pywin32==227; sys_platform == "win32"
    docker 5.0.0 depends on pywin32==227; sys_platform == "win32"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Exception information:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 385, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('pywin32==227; sys_platform == "win32"'), parent=LinkCandidate('https://files.pythonhosted.org/packages/54/f3/7af47ead249fbb798d64a0438bad5c26f17ef6ac5cd324d802038eb10d90/docker-5.0.3-py2.py3-none-any.whl#sha256=7a79bb439e3df59d0a72621775d600bc8bc8b422d285824cb37103eab91d1ce0 (from https://pypi.org/simple/docker/) (requires-python:>=3.6)')), RequirementInformation(requirement=SpecifierRequirement('pywin32==227; sys_platform == "win32"'), parent=LinkCandidate('https://files.pythonhosted.org/packages/59/86/b2430d652d082a2132bbd6023b3f298d0582977c27f125c7e3875c65e178/docker-5.0.2-py2.py3-none-any.whl#sha256=9b17f0723d83c1f3418d2aa17bf90b24dbe97deda06208dd4262fa30a6ee87eb (from https://pypi.org/simple/docker/) (requires-python:>=3.6)')), RequirementInformation(requirement=SpecifierRequirement('pywin32==227; sys_platform == "win32"'), parent=LinkCandidate('https://files.pythonhosted.org/packages/0f/f6/7bffaae55542f5317d292f95171a65d535ac26eaf4de65f2c539d680a93d/docker-5.0.1-py2.py3-none-any.whl#sha256=b88eef725b33c0ed59c67506631bbb09b480b7ca5a739bbbb948b446443fe914 (from https://pypi.org/simple/docker/) (requires-python:>=3.6)')), RequirementInformation(requirement=SpecifierRequirement('pywin32==227; sys_platform == "win32"'), parent=LinkCandidate('https://files.pythonhosted.org/packages/b2/5a/f988909dfed18c1ac42ad8d9e611e6c5657e270aa6eb68559985dbb69c13/docker-5.0.0-py2.py3-none-any.whl#sha256=fc961d622160e8021c10d1bcabc388c57d55fb1f917175afbe24af442e6879bd (from https://pypi.org/simple/docker/) (requires-python:>=3.6)'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\commands\install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 103, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Removed build tracker: 'C:\\Users\\roybm\\AppData\\Local\\Temp\\pip-req-tracker-dk38kj5r'

cli.azure.cli.core.extension.operations: Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'pip', 'install', '--target', 'C:\\Users\\roybm\\.azure\\cliextensions\\ml', 'C:\\Users\\roybm\\AppData\\Local\\Temp\\tmp97uuymd0\\ml-2.2.2-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at C:\Users\roybm\.azure\cliextensions\ml
cli.azure.cli.core.util: Failed to delete 'C:\Users\roybm\.azure\cliextensions\ml': [WinError 3] The system cannot find the path specified: 'C:\\Users\\roybm\\.azure\\cliextensions\\ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete 'C:\Users\roybm\.azure\cliextensions\ml': [WinError 3] The system cannot find the path specified: 'C:\\Users\\roybm\\.azure\\cliextensions\\ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete 'C:\Users\roybm\.azure\cliextensions\ml': [WinError 3] The system cannot find the path specified: 'C:\\Users\\roybm\\.azure\\cliextensions\\ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete 'C:\Users\roybm\.azure\cliextensions\ml': [WinError 3] The system cannot find the path specified: 'C:\\Users\\roybm\\.azure\\cliextensions\\ml'. You may try to delete it manually.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 341, in add_extension
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 173, in _add_whl_ext
knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.

cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 1. Use --debug for more information.
az_command_data_logger: An error occurred. Pip failed with status code 1. Use --debug for more information.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0472A100>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 32.666 seconds (init: 0.422, invoke: 32.244)
telemetry.save: Save telemetry record of length 3132 in cache
telemetry.check: Negative: The C:\Users\roybm\.azure\telemetry.txt was modified at 2022-04-14 17:51:15.338597, which in less than 600.000000 s
```
-----

**Comment by SaurabhSharma-MSFT** [comment]
@Roy7017 We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @Roy7017 Thanks for reporting this issue!

Could you please try with Az CLI version 2.34.1 ?

![image](https://user-images.githubusercontent.com/62923178/163504466-e871046a-b222-490c-ab20-f2bab07be31b.png)

**Comment by Roy7017** [comment]
> Hello @Roy7017 Thanks for reporting this issue!
> 
> Could you please try with Az CLI version 2.34.1 ?
> 
> ![image](https://user-images.githubusercontent.com/62923178/163504466-e871046a-b222-490c-ab20-f2bab07be31b.png)
> 
> After I upgrade to the latest Az CLI version, it's failing on my side.
> 
> Routing to the service Teams' attention.
> 
> ![image](https://user-images.githubusercontent.com/62923178/163505503-e8043992-0425-44bf-86cc-a39bea70fb2d.png)

Thank you very much. Downgrading to version azure 2.34.1 fixed the issue for me
