### ISSUE TITLE
Command fail for az monitor

### ISSUE THREAD

**Issue by nitish81** [Azure/azure-cli-extensions#4690]
## Describe the bug

**Command Name**
`az monitor data-collection rule association list
Extension Name: monitor-control-service. Version: 0.2.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 704, in _run_job
    result = list(result)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/Users/quest2021/.azure/cliextensions/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rule_associations_operations.py", line 104, in get_next
    request = prepare_request(next_link)
  File "/Users/quest2021/.azure/cliextensions/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rule_associations_operations.py", line 82, in prepare_request
    'resourceUri': self._serialize.url("resource_uri", resource_uri, 'str', skip_quote=True, min_length=1),
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/msrest/serialization.py", line 650, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor data-collection rule association list`

## Environment Summary
```
macOS-12.3-x86_64-i386-64bit, Darwin 21.4.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.30.0 *

Extensions:
monitor-control-service 0.2.0

```

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
It seems some parameters are missed in your command. Could you follow these [examples](https://docs.microsoft.com/en-us/cli/azure/monitor/data-collection/rule/association?view=azure-cli-latest#az-monitor-data-collection-rule-association-list-examples) in doc and try again. I will close the issue, if you have more problems you can add comments in it and I will reopen it.
