### ISSUE TITLE
[Quantum] "--max-poll-wait-secs" parameter causes "az quantum job wait" command to fail

### ISSUE THREAD

**Issue by warren-jones** [Azure/azure-cli-extensions#4697]
### Extension name

Quantum extension V0.14.0 and earlier

### Description of issue

The az quantum job wait command fails if the --max-poll-wait-secs parameter is used.  The the error message is:
```
The command failed with an unexpected error. Here is the traceback:
'>=' not supported between instances of 'float' and 'str'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\georgenm\.azure\cliextensions\quantum\azext_quantum\operations\job.py", line 296, in wait
    poll_wait = max_poll_wait_secs if poll_wait >= max_poll_wait_secs else poll_wait * 1.5
TypeError: '>=' not supported between instances of 'float' and 'str'
```

**Comment by warren-jones** [comment]
Fixed by [PR 4616](https://github.com/Azure/azure-cli-extensions/pull/4616)
