### ISSUE TITLE
Enable virtual node add-on to existing AKS cluster throws exception

### ISSUE THREAD

**Issue by gandersson** [Azure/azure-cli-extensions#4723]
## Describe the bug
When adding ACI capabilities to an existing cluster, the command fails and thows the AttributeError: 'NoneType' object has no attribute 'rpartition' error below. The virtual-node-aci-linux does get added to the cluster nodes, however.

**Command Name**
`az aks enable-addons 
Extension Name: aks-preview. Version: 0.5.45.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rpartition'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/gandersson/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2466, in aks_enable_addons
    add_virtual_node_role_assignment(
  File "/home/gandersson/.azure/cliextensions/aks-preview/azext_aks_preview/addonconfiguration.py", line 870, in add_virtual_node_role_assignment
    vnet_id = vnet_subnet_id.rpartition('/')[0]
AttributeError: 'NoneType' object has no attribute 'rpartition'

```

## To Reproduce:
Steps to reproduce the behavior. 

1. Create an AKS cluster with default values. Do not enable virtual nodes.
2. Manually add a subnet intended for ACI in the MC* resource group (needed for the command to work). Name the subnet aks-aci-subnet
3. Run the command: az aks enable-addons --resource-group myaksresourcegroup--name myclustername --addons virtual-node  --subnet-name aks-aci-subnet

## Expected Behavior
ACI virtual node to be added to the cluster without throwing exceptions.

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.34, Ubuntu 22.04 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
aks-preview 0.5.45
application-insights 0.1.14

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @gandersson 
We are routing this issue to the service team's attention!

**Comment by navba-MSFT** [comment]
@gandersson Apologies for the late reply. Could you please follow the below action plan ?

1. Update your python libraries
2. Update your Azure CLI and then test the command again.

Once this is done, please test your AKS CLi command again and let me know if you see the same issue. Awaiting your reply.
