### ISSUE TITLE
az aks update --enable-secret-rotation fails with NoneType error

### ISSUE THREAD

**Issue by mohamedsaif** [Azure/azure-cli-extensions#4735]
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.53.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/localadmin/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 856, in aks_update
    mc = aks_update_decorator.update_mc_preview_profile()
  File "/home/localadmin/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 2159, in update_mc_preview_profile
    mc = self.update_default_mc_profile()
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/decorator.py", line 6416, in update_default_mc_profile
    mc = self.update_addon_profiles(mc)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/decorator.py", line 6362, in update_addon_profiles
    self.update_azure_keyvault_secrets_provider_addon_profile(azure_keyvault_secrets_provider_addon_profile)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/decorator.py", line 6296, in update_azure_keyvault_secrets_provider_addon_profile
    azure_keyvault_secrets_provider_addon_profile.config[
TypeError: 'NoneType' object does not support item assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -g {} -n {} --enable-secret-rotation --rotation-poll-interval {}`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.3 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
containerapp 0.2.2
connectedk8s 1.2.1
k8s-extension 1.0.4
aks-preview 0.5.53
appservice-kube 0.1.2
k8s-configuration 1.4.1
customlocation 0.1.3

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@mohamedsaif Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
It seems we save the config for this addon as null. We are investigating why this happening.

As for the workaround, could you please disable the addon first by az aks disable-addons -g {resource_group_name} -n {cluster_name} -a azure-keyvault-secrets-provider and then enable this addon by az aks enable-addons -g {resource_group_name} -n {cluster_name} -a azure-keyvault-secrets-provider --enable-secret-rotation?

**Comment by RakeshMohanMSFT** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/20438
