### ISSUE TITLE
`az account tenant list` fails

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli-extensions#4761]
## Describe the bug

**Command Name**
`az account tenant list
Extension Name: account. Version: 0.2.3.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.core.rest'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\diberry\.azure\cliextensions\account\azext_account\manual\_client_factory.py", line 20, in cf_tenants
    return cf_account(cli_ctx).tenants
  File "C:\Users\diberry\.azure\cliextensions\account\azext_account\manual\_client_factory.py", line 9, in cf_account
    from ..vendored_sdks.subscription import SubscriptionClient
  File "C:\Users\diberry\.azure\cliextensions\account\azext_account\vendored_sdks\subscription\__init__.py", line 9, in <module>
    from ._subscription_client import SubscriptionClient
  File "C:\Users\diberry\.azure\cliextensions\account\azext_account\vendored_sdks\subscription\_subscription_client.py", line 12, in <module>
    from azure.core.rest import HttpRequest, HttpResponse
ModuleNotFoundError: No module named 'azure.core.rest'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account tenant list`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.1 *

Extensions:
account 0.2.3
application-insights 0.1.16

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@diberry Apologies for the delay! can you please upgrade to the latest version of azure cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and see if you are still facing this issue?
