### ISSUE TITLE
TypeError: login() got an unexpected keyword argument 'msi'

### ISSUE THREAD

**Issue by felix-rojas** [Azure/azure-cli-extensions#4789]
## Describe the bug
The command was executed from a bash terminal with kali-linux, a similar error occurs on the powershell and cmd terminal as well. I'm new to bug reporting btw, Sorry for the inconveniences!

**Command Name**
`az login
Extension Name: azure-ml-admin-cli. Version: 0.0.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
login() got an unexpected keyword argument 'msi'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Felix\.azure\cliextensions\azure-ml-admin-cli\azext_admin\custom.py", line 82, in mls_login
    return login(username=username,
TypeError: login() got an unexpected keyword argument 'msi'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Expected Behavior
Interactive login with azure

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.4
Installer: 

azure-cli 2.36.0

Extensions:
azure-ml-admin-cli 0.0.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by felix-rojas** [comment]
Oh just wanted to follow up on this, kali-linux rolling is running this. 
Turns out I already have the azure client terminal installed alongside Windows Terminal. I will try with ubuntu WSL2 now and see if anything changes.

**Comment by paulshealy1** [comment]
@felix-rojas `azure-ml-admin-cli` is for Machine Learning Server. This product is [being retired](https://docs.microsoft.com/en-us/machine-learning-server/what-is-happening-to-machine-learning-server). 

Are you looking for the CLI for Azure Machine Learning? Installation instructions are available [here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli).
