### ISSUE TITLE
Fail to load extension 'alias' and 'arcdata'

### ISSUE THREAD

**Issue by daxianji007** [Azure/azure-cli-extensions#4798]
### Related command
az alias xxx
az arcdata xxx

### Extension name (the extension in question)
'alias' and 'arcdata'

### Description of issue (in as much detail as possible)
The extension can be installed but cannot be loaded. Looks like dependency package version issue. But I cannot workaround it. Check my re-pro steps and my real logs.
```
pip install azure-cli
az extension add -n alias
az alias -h
```
![image](https://user-images.githubusercontent.com/8327019/167766792-7791a7c1-cdf7-4a55-a49e-5c9f860cb1da.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@daxianji007 Thanks for reaching out to us and reporting this issue. I am looking into this issue. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@daxianji007 I am unable to reproduce this issue. Sharing the versions I am using.

C:\>pip list
Package                     Version
pip                              22.0.4
setuptools                  58.1.0


C:\>python --version
Python 3.10.4

C:\windows\system32>az version
{
  **"azure-cli": "2.35.0",**
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    **"alias": "0.5.2",**
    **"arcdata": "1.4.0",**
   }
}

Could you please upgrade your libraries and try to use the same versions and check if that helps ? Awaiting your reply.

**Comment by daxianji007** [comment]
@navba-MSFT I can provide a clean log with versions in my local machine.
![image](https://user-images.githubusercontent.com/8327019/168107338-04e60ec6-40f5-469c-9f99-6e70bd382183.png)

**Comment by navba-MSFT** [comment]
@daxianji007 Could you please share the `--debug `output While you run the command ? I sharing sharing the command here if that helps. Awaiting your reply.

>az alias -h --debug

**Comment by daxianji007** [comment]
@navba-MSFT 
```
PS C:\_works\AzureCLI.vNext> az alias -h --debug
cli.knack.cli: Command arguments: ['alias', '-h', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Init colorama.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x00000207D7F673A0>, <function OutputProducer.on_global_arguments at 0x00000207D8290AF0>, <function CLIQuery.on_global_arguments at 0x00000207D82B70D0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: No module found from index for '['alias', '-h', '--debug']'
cli.azure.cli.core: Loading all modules and extensions
cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'cosmosdb', 'databoxedge', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'identity', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'serviceconnector', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.015        30       126
cli.azure.cli.core: acs                       0.211        10        64
cli.azure.cli.core: advisor                   0.003         3         6
cli.azure.cli.core: ams                       0.007        22       100
cli.azure.cli.core: apim                      0.009        10        56
cli.azure.cli.core: appconfig                 0.004         7        37
cli.azure.cli.core: appservice                0.015        66       240
cli.azure.cli.core: aro                       0.009         1         7
cli.azure.cli.core: backup                    0.005        15        55
cli.azure.cli.core: batch                     0.032        33        96
cli.azure.cli.core: batchai                   0.004        10        30
cli.azure.cli.core: billing                   0.012        19        52
cli.azure.cli.core: botservice                0.004        12        42
cli.azure.cli.core: cdn                       0.007        39       133
cli.azure.cli.core: cloud                     0.003         1         7
cli.azure.cli.core: cognitiveservices         0.003         8        31
cli.azure.cli.core: config                    0.003         2         7
cli.azure.cli.core: configure                 0.003         3         9
cli.azure.cli.core: consumption               0.004         8         9
cli.azure.cli.core: container                 0.003         1        11
cli.azure.cli.core: cosmosdb                  0.012        47       167
cli.azure.cli.core: databoxedge               0.006         5        27
cli.azure.cli.core: deploymentmanager         0.004         7        30
cli.azure.cli.core: dla                       0.005        23        62
cli.azure.cli.core: dls                       0.004         7        41
cli.azure.cli.core: dms                       0.004         3        22
cli.azure.cli.core: eventgrid                 0.004        18        61
cli.azure.cli.core: eventhubs                 0.005        18        61
cli.azure.cli.core: extension                 0.001         1         7
cli.azure.cli.core: feedback                  0.003         1         1
cli.azure.cli.core: find                      0.002         1         1
cli.azure.cli.core: hdinsight                 0.003         8        39
cli.azure.cli.core: identity                  0.003         1         5
cli.azure.cli.core: interactive               0.001         1         1
cli.azure.cli.core: iot                       0.061        17        74
cli.azure.cli.core: keyvault                  0.012        20       122
cli.azure.cli.core: kusto                     0.004         3        14
cli.azure.cli.core: lab                       0.007        11        34
cli.azure.cli.core: managedservices           0.003         3         8
cli.azure.cli.core: maps                      0.003         5        13
cli.azure.cli.core: marketplaceordering       0.006         1         2
cli.azure.cli.core: monitor                   0.009        34       139
cli.azure.cli.core: natgateway                0.003         3         6
cli.azure.cli.core: netappfiles               0.005        16        69
cli.azure.cli.core: network                   0.058       141       653
cli.azure.cli.core: policyinsights            0.004         6        12
cli.azure.cli.core: privatedns                0.006        14        66
cli.azure.cli.core: profile                   0.003         2         9
cli.azure.cli.core: rdbms                     0.175        46       199
cli.azure.cli.core: redis                     0.005         5        27
cli.azure.cli.core: relay                     0.004        10        37
cli.azure.cli.core: reservations              0.003         5        12
cli.azure.cli.core: resource                  0.010        43       197
cli.azure.cli.core: role                      0.003        16        56
cli.azure.cli.core: search                    0.003         7        22
cli.azure.cli.core: security                  0.005        44        94
cli.azure.cli.core: servicebus                0.006        19        68
cli.azure.cli.core: serviceconnector          0.218         4        53
cli.azure.cli.core: servicefabric             0.005        26        75
cli.azure.cli.core: signalr                   0.004         6        20
cli.azure.cli.core: sql                       0.010        45       178
cli.azure.cli.core: sqlvm                     0.004         4        17
cli.azure.cli.core: storage                   0.038        56       260
cli.azure.cli.core: synapse                   0.015        52       231
cli.azure.cli.core: util                      0.002         2         4
cli.azure.cli.core: vm                        0.028        54       279
cli.azure.cli.core: Total (66)                1.132      1161      4693
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: account                   0.007         4        12  C:\Users\shujia\.azure\cliextensions\account
cli.knack.cli: Event: MainLoader.OnFailedExtensionLoad []
cli.azure.cli.core: Unable to load extension 'alias: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\shujia\.azure\cliextensions\alias\markupsafe\__init__.py)'. Use --debug for more information.
cli.azure.cli.core: Traceback (most recent call last):
  File "C:\Users\shujia\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\cli\core\__init__.py", line 359, in _update_command_table_from_extensions
    _load_extension_command_loader(self, args, ext_mod)
  File "C:\Users\shujia\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\cli\core\commands\__init__.py", line 1076, in _load_extension_command_loader
    return _load_command_loader(loader, args, ext, '')
  File "C:\Users\shujia\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\cli\core\commands\__init__.py", line 1047, in _load_command_loader
    module = import_module(prefix + name)
  File "C:\Users\shujia\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\shujia\.azure\cliextensions\alias\azext_alias\__init__.py", line 15, in <module>
    from azext_alias._validators import (
  File "C:\Users\shujia\.azure\cliextensions\alias\azext_alias\_validators.py", line 13, in <module>
    from azext_alias.argument import get_placeholders
  File "C:\Users\shujia\.azure\cliextensions\alias\azext_alias\argument.py", line 13, in <module>
    import jinja2 as jinja
  File "C:\Users\shujia\.azure\cliextensions\alias\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Users\shujia\.azure\cliextensions\alias\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Users\shujia\.azure\cliextensions\alias\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Users\shujia\.azure\cliextensions\alias\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\shujia\.azure\cliextensions\alias\markupsafe\__init__.py)

cli.azure.cli.core: Total (1)                 0.007         4        12
cli.azure.cli.core: Loaded 1153 groups, 4705 commands.
cli.azure.cli.core: Updated command index in 0.004 seconds.
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x00000207DAAD2280>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\shujia\.azure\commands\2022-05-13.12-54-48.unknown_command.4368.log'.
az_command_data_logger: command args: alias -h --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x00000207DAAF13A0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x00000207DAB62CA0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x00000207DAB62DC0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x00000207DC043700>]
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22alias%22%2C+%22parameters%22%3A+%22--help%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.36.0%22%2C+%22errorType%22%3A+%22UnknownSubcommand%22%2C+%22correlationId%22%3A+%221a79757b-aef6-4601-bc18-ef52729eb32d%22%2C+%22subscriptionId%22%3A+%228decc521-bcab-4cef-a8d5-ac8edb60c4b4%22%2C+%22eventId%22%3A+%22307cf39f-549c-4476-8aba-141b8ec18070%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.azclierror: 'alias' is misspelled or not recognized by the system.
az_command_data_logger: 'alias' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x00000207DAAD24C0>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 2.807 seconds (init: 0.488, invoke: 2.319)
telemetry.save: Save telemetry record of length 3073 in cache
telemetry.check: Negative: The C:\Users\shujia\.azure\telemetry.txt was modified at 2022-05-13 12:46:28.663255, which in less than 600.000000 s
PS C:\_works\AzureCLI.vNext>
```

**Comment by navba-MSFT** [comment]
@daxianji007 Could you please run this command and then check if that helps ? Awaiting your reply. 

>pip install MarkupSafe==2.0.1

**Comment by navba-MSFT** [comment]
@daxianji007 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@daxianji007 The action is currently on you to follow the above plan and let us know if that helps. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by daxianji007** [comment]
@navba-MSFT Sorry for late response. This can mitigate the issue.

> @daxianji007 Could you please run this command and then check if that helps ? Awaiting your reply.
> 
> > pip install MarkupSafe==2.0.1

**Comment by zorfling** [comment]
I've just run into the same issue - pinning markupsafe does fix the issue. Can we pin it directly in the alias source so others don't have to do this manually? 

For future Mac/Homebrew users, I needed to activate the az python virtualenv, then pip install MarkupSafe at the safe version.

```sh
$ source /opt/homebrew/opt/az/libexec/bin/activate
$ pip install MarkupSafe==2.0.1
```
