### ISSUE TITLE
Cannot deserialize as [OperationsDefinition] an object of type <class 'dict'>

### ISSUE THREAD

**Issue by yurych** [Azure/azure-cli-extensions#4856]
## Describe the bug

**Command Name**
`az providerhub provider-registration generate-operation
Extension Name: providerhub. Version: 0.2.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize as [OperationsDefinition] an object of type <class 'dict'>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\*****\.azure\cliextensions\providerhub\azext_providerhub\generated\custom.py", line 354, in providerhub_provider_registration_generate_operation
    return client.generate_operations(provider_namespace=provider_namespace)
  File "C:\Users\*****\.azure\cliextensions\providerhub\azext_providerhub\vendored_sdks\providerhub\operations\_provider_registrations_operations.py", line 548, in generate_operations
    deserialized = self._deserialize(
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1368, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1407, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1645, in deserialize_iter
msrest.exceptions.DeserializationError: Cannot deserialize as [OperationsDefinition] an object of type <class 'dict'>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az providerhub provider-registration generate-operation --provider-namespace {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0

Extensions:
providerhub 0.2.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
providerhub

**Comment by navba-MSFT** [comment]
@yurych Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@yurych A quick update on this. I have reached out to the product owners and they are investigating this in the background. I will keep you updated about this.

**Comment by navba-MSFT** [comment]
@yurych As a next action plan, Could you please update the right parameters in the below command and run it ? I was able to run it and get the Operation details:

>az login    # Login to your Azure Account before you run the below command
>
>
>az rest --method POST --uri "https://management.azure.com/subscriptions/XXXXXXXXX/providers/Microsoft.ProviderHub/providerRegistrations/XXXXX/generateOperations?api-version=2020-11-20"

Hope this helps. Awaiting your reply.

**Comment by yurych** [comment]
> @yurych As a next action plan, Could you please update the right parameters in the below command and run it ? I was able to run it and get the Operation details:
> 
> > az login    # Login to your Azure Account before you run the below command
> > az rest --method POST --uri "https://management.azure.com/subscriptions/XXXXXXXXX/providers/Microsoft.ProviderHub/providerRegistrations/XXXXX/generateOperations?api-version=2020-11-20"
> 
> Hope this helps. Awaiting your reply.
> 
> PS Edit: Internal workitem has been created for the fix. No ETA for the fix now. So please follow the above workaround for now.

calling rest method directly works for me, thank you!

**Comment by navba-MSFT** [comment]
@yurych Thanks for getting back. I am glad that the above suggestion works. As mentioned earlier, the workitem has been filed for the actual fix. There is no ETA for the fix now. We will now proceed with closure of this github issue for now. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
