### ISSUE TITLE
AZure AKS Create issue

### ISSUE THREAD

**Issue by visingh-BRONGA** [Azure/azure-cli-extensions#4869]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.51.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
can't set attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/vinod/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 770, in aks_create
    aks_create_decorator = AKSPreviewCreateDecorator(
  File "/home/vinod/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 1541, in __init__
    self.models = AKSPreviewModels(cmd, resource_type)
  File "/home/vinod/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 117, in __init__
    self.init_nat_gateway_models()
  File "/home/vinod/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 145, in init_nat_gateway_models
    self.nat_gateway_models = nat_gateway_models
AttributeError: can't set attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -n {} -g {} --enable-addons {} --enable-managed-identity -l {}`

## Environment Summary
```
Linux-5.4.0-1078-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
aks-preview 0.5.51
ai-examples 0.2.5
ssh 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```
## Additional Context

<!--auto-g

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@visingh-BRONGA Thanks for reaching out to us and sharing this feedback. I see that you are using an older version of the `aks-preview`. Could you please run the below command and update your extension ?

>az extension update --name aks-preview

Hope this helps.

**Comment by navba-MSFT** [comment]
@visingh-BRONGA I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@visingh-BRONGA The action is currently pending on you to update your `aks-preview `extension by running the above command. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
