### ISSUE TITLE
`az aks addon list-available` fails with an exception

### ISSUE THREAD

**Issue by tehret77** [Azure/azure-cli-extensions#4932]
## Describe the bug

**Command Name**
`az aks addon list-available
Extension Name: aks-preview. Version: 0.5.76.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
''
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/d035779/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2029, in aks_addon_list_available
    "description": ADDONS_DESCRIPTIONS[v]
KeyError: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks addon list-available`

## Environment Summary
```
macOS-12.4-x86_64-i386-64bit, Darwin 21.5.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.37.0

Extensions:
aks-preview 0.5.76
logic 0.1.3
azure-devops 0.18.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by navba-MSFT** [comment]
@tehret77 Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. I am able to reproduce this issue. We are looking into this issue. We will provide an update once we have more details on this.

**Comment by navba-MSFT** [comment]
@tehret77 @mmckechney Could you please update your `aks-preview` extension ? This should resolve the issue.

>az extension update -n aks-preview

Please follow this action plan and let me know if you face any issue. Awaiting your reply.

**Comment by mmckechney** [comment]
@navba-MSFT  -- the extension update worked and I can now list the addons! Thanks.

**Comment by navba-MSFT** [comment]
@mmckechney Thanks for getting back. I am glad that the action plan helped you to resolve the issue.

@tehret77 Please follow the [above](https://github.com/Azure/azure-cli-extensions/issues/4932#issuecomment-1148157738) suggested plan to update your `aks-preview` extension. If you still face the same issue, feel free to reopen this thread. We would be happy to help.

**Comment by tehret77** [comment]
@navba-MSFT After the extension update it works for me too. Thanks!
