### ISSUE TITLE
Error running 'az aks addon list-available'

### ISSUE THREAD

**Issue by mmckechney** [Azure/azure-cli-extensions#4936]
## Describe the bug

**Command Name**
`az aks addon list-available
Extension Name: aks-preview. Version: 0.5.77.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
''
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/mmckechney/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2031, in aks_addon_list_available
    "description": ADDONS_DESCRIPTIONS[v]
KeyError: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks addon list-available --debug`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
aks-preview 0.5.77

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by mmckechney** [comment]
Duplicate of [#4932](https://github.com/Azure/azure-cli-extensions/issues/4932)
