### ISSUE TITLE
az webapp create throwing errors after installing appservice-kube

### ISSUE THREAD

**Issue by mfsidanisha1** [Azure/azure-cli-extensions#4957]
## Describe the bug

**Command Name**
`az webapp create
Extension Name: appservice-kube. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
_StackRuntimeHelper.__init__() got multiple values for argument 'linux'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/danish/.azure/cliextensions/appservice-kube/azext_appservice_kube/commands.py", line 42, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/danish/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 505, in create_webapp
    helper = _StackRuntimeHelper(cmd, client, linux=(is_linux or is_kube))
TypeError: _StackRuntimeHelper.__init__() got multiple values for argument 'linux'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --resource-group {} --plan {} --name {}`

## Environment Summary
```
Linux-5.4.0-1080-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
appservice-kube 0.2.2
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by StrawnSC** [comment]
Hi, based on the version number of the appservice-kube extension it looks like you're still using the private extension from before public preview. The current highest release number for the public preview version is `0.1.6`. 

Could you install the public preview appservice-kube extension by running: 
`az extension remove -n appservice-kube` followed by `az extension add -n appservice-kube`

Please reopen the issue if you're still encountering errors after the upgrade
