### ISSUE TITLE
https://docs.microsoft.com/en-us/azure/aks/devops-pipeline?pivots=pipelines-yaml&tryIt=true&source=docs#code-try-1

### ISSUE THREAD

**Issue by rotorr** [Azure/azure-cli-extensions#4965]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.51.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
can't set attribute 'nat_gateway_models'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/rolando/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 770, in aks_create
    aks_create_decorator = AKSPreviewCreateDecorator(
  File "/home/rolando/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 1541, in __init__
    self.models = AKSPreviewModels(cmd, resource_type)
  File "/home/rolando/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 117, in __init__
    self.init_nat_gateway_models()
  File "/home/rolando/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 145, in init_nat_gateway_models
    self.nat_gateway_models = nat_gateway_models
AttributeError: can't set attribute 'nat_gateway_models'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys`

## Environment Summary
```
Linux-5.4.0-1083-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
containerapp 0.3.5
application-insights 0.1.15
aks-preview 0.5.51
azure-firewall 0.13.0
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@rotorr Thanks for reaching out to us and sharing this feedback. We are looking into this. We will provide an update once we have more details.

**Comment by navba-MSFT** [comment]
@rotorr I see that you are using an older version of `aks-preview` . Could you please update it to the most recent version using the below command and then test again ?

>az extension update -n aks-preview

Hope this helps. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rotorr I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  are still facing the issue after following the above plan. Awaiting your reply.
