### ISSUE TITLE
Error when attempting to create an IoT Hub device-id

### ISSUE THREAD

**Issue by eustacea** [Azure/azure-cli-extensions#4975]
## Describe the bug

**Command Name**
`az iot hub device-identity create
Extension Name: azure-cli-iot-ext. Version: 0.8.7.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/eustace/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 87, in iot_device_create
    target = get_iot_hub_connection_string(cmd, hub_name, resource_group_name, login=login)
  File "/home/eustace/.azure/cliextensions/azure-cli-iot-ext/azext_iot/common/_azure.py", line 112, in get_iot_hub_connection_string
    client = iot_hub_service_factory(cmd.cli_ctx)
  File "/home/eustace/.azure/cliextensions/azure-cli-iot-ext/azext_iot/_factory.py", line 28, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- Following this QSG: https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux?view=iotedge-2020-11 
- Running Az CLI from Edge browser.
- Create a resource group in EAST US
- Create an IoT Hub in S1 sku, then attempt command below with a new device device name for the created IoT Hub
- `az iot hub device-identity create --device-id {} --edge-enabled --hub-name {}`

## Expected Behavior
Returns error above.

## Environment Summary
```
Linux-5.4.0-1080-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
azure-cli-iot-ext 0.8.7
azure-iot 0.14.1
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by eustacea** [comment]
Issue resolved.

In addition to the 'azure-iot' Azure CLI extension installed, I also had the older 'azure-cli-iot-ext' still installed.  Removing the older version solved the problem.  

Closing as resolved.
