### ISSUE TITLE
Unable to view details of firewall collection group with weird exception

### ISSUE THREAD

**Issue by nlasok1** [Azure/azure-cli-extensions#4988]
## Describe the bug
The collection group exists. Unable to view it with CLI.
Additionally 'list' returns empty reposnce.

**Command Name**
`az network firewall network-rule collection show
Extension Name: azure-firewall. Version: 0.14.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/home/sokolovskyi/.azure/cliextensions/azure-firewall/azext_firewall/_util.py", line 48, in get_func
    result = next((x for x in items if x.name.lower() == item_name.lower()), None)
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network firewall network-rule collection show --collection-name {} --firewall-name {} --resource-group {}`

## Environment Summary
```
Linux-5.4.0-1083-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
azure-firewall 0.14.1
virtual-wan 0.2.12
containerapp 0.3.5
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi,
     @nlasok1 "az network firewall network-rule collection show" works well as below, the steps I use as below:
1.create network-rule and collection first, notice that collections are created as part of the az network firewall network-rule create command:
 az network firewall network-rule create --collection-name mycoll  --source-addresses 10.0.0.0 111.1.0.0/24 --protocols UDP TCP ICMP --destination-fqdns [www.bing.com](http://www.bing.com/) --destination-ports 80 --firewall-name myfw --name myrule --protocols Any --resource-group nyy02 --priority 300 --action Allow
2.collection show command:
az network firewall network-rule collection show --collection-name mycoll --firewall-name myfw -g nyy02
3.collection list command:
az network firewall network-rule collection list --firewall-name myfw -g nyy02

![image](https://user-images.githubusercontent.com/95396631/174519001-7c69f767-609e-45ae-9052-427e11641d99.png)

Best wishes.
