### ISSUE TITLE
Not able to connect to aks cluster using az ask get-credentials

### ISSUE THREAD

**Issue by sharmakhushboo** [Azure/azure-cli-extensions#4996]
## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.5.19.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'name'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/khushboosharma/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1945, in aks_get_credentials
    _print_or_merge_credentials(
  File "/Users/khushboosharma/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3513, in _print_or_merge_credentials
    merge_kubernetes_configurations(
  File "/Users/khushboosharma/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3589, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
  File "/Users/khushboosharma/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3532, in _handle_merge
    if i['name'] == j['name']:
KeyError: 'name'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
macOS-12.4-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.25.0 *

Extensions:
aks-preview 0.5.19

```

**Comment by sharmakhushboo** [comment]
I had to delete the ~/.kube/config file to fix this issue.
I'm not sure why the config got messed up though.

**Comment by yonzhan** [comment]
route to CXP team
