### ISSUE TITLE
Azure blob storage download to local filesystem failed!!

### ISSUE THREAD

**Issue by adey3** [Azure/azure-cli-extensions#5018]
## Describe the bug

**Command Name**
`az storage azcopy blob download
Extension Name: storage-preview. Version: 0.8.3.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
MSI auth not yet supported.
Traceback (most recent call last):
  File "/home/azureuser/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 81, in blob_client_auth_for_azcopy
    token_info = _unserialize_non_msi_token_payload(token_info)
  File "/home/azureuser/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 104, in _unserialize_non_msi_token_payload
    parsed_authority = urlparse(token_info['_authority'])
KeyError: '_authority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/azureuser/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 252, in new_handler
    handler(ex)
  File "/home/azureuser/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 194, in handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/azureuser/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 24, in storage_blob_download
    azcopy = _azcopy_blob_client(cmd, client)
  File "/home/azureuser/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 65, in _azcopy_blob_client
    return AzCopy(creds=blob_client_auth_for_azcopy(cmd, client))
  File "/home/azureuser/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 83, in blob_client_auth_for_azcopy
    raise Exception('MSI auth not yet supported.')
Exception: MSI auth not yet supported.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage azcopy blob download -c {} --account-name {} --auth-mode {} -s {} -d {}`

## Environment Summary
```
Linux-5.13.0-1031-azure-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
storage-preview 0.8.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Can you use other auth options instead of `--auth-mode login`?
Maybe you could try using `--account-key` or `--sas-token`. 

See how to get account key or sas token in https://github.com/Azure/azure-cli/blob/dev/doc/storage_data_plane_commands_auth.md

**Comment by joshk0** [comment]
I'd like to reopen this - it seems like this command should work with `--auth-mode login`. Is there a reason it's deprecated or would not be supported in a GA version of azcopy?

**Comment by evelyn-ys** [comment]
There's conflicts between azcopy's support for AAD auth with CLI's support for AAD auth. So we can't integrate azcopy's AAD auth in CLI.

If customer has strong dependence on azcopy's AAD auth, they can call `azcopy` directly. CLI has installed `azcopy` already.
