### ISSUE TITLE
[containerapp] Cannot deploy simple Hello World with Container Apps Compose

### ISSUE THREAD

**Issue by agoncal** [Azure/azure-cli-extensions#5051]
## Describe the bug

I have the following Docker Compose file using a simple hello world app from NGinx:

```
version: "3"
services:

  hello-world-one:
    image: nginxdemos/nginx-hello
    container_name: hello-world-one
    ports:
      - "8081:8080"
    restart: on-failure
```

I execute it with the following command and I can access it on http://localhost:8081

```
docker compose -f deploy/docker-compose/test.yml up
```

But when I try to deploy it to Azure Container Apps using Compose, it fails. Here is the command I'm executing:

**Command Name**

```
az containerapp compose create \                                    
  --environment "$CONTAINERAPPS_ENV" \
  --resource-group "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --compose-file-path deploy/docker-compose/test.yml
```

**Errors:**

When I execute the command I have the following error:

```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/Users/agoncal/.azure/cliextensions/containerapp-compose/azext_containerapp_compose/custom.py", line 120, in create_containerapps_from_compose
    managed_environment = show_managed_environment(cmd=cmd,
  File "/Users/agoncal/.azure/cliextensions/containerapp-compose/azext_containerapp_compose/_monkey_patch.py", line 113, in show_managed_environment
    return ManagedEnvironmentClient.show(cmd=cmd,
  File "/Users/agoncal/.azure/cliextensions/containerapp/azext_containerapp/_clients.py", line 542, in show
    r = send_raw_request(cmd.cli_ctx, "GET", request_url)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 982, in send_raw_request
    raise HTTPError(reason, r)
azure.cli.core.azclierror.HTTPError: Bad Request({"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2022-03-01' is invalid. The supported versions are '2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/agoncal/.azure/cliextensions/containerapp-compose/azext_containerapp_compose/custom.py", line 124, in create_containerapps_from_compose
    managed_environment = create_containerapps_compose_environment(cmd,
  File "/Users/agoncal/.azure/cliextensions/containerapp-compose/azext_containerapp_compose/_monkey_patch.py", line 98, in create_containerapps_compose_environment
    return custom.create_managed_environment(cmd,
  File "/Users/agoncal/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 795, in create_managed_environment
    _ensure_location_allowed(cmd, location, CONTAINER_APPS_RP, "managedEnvironments")
  File "/Users/agoncal/.azure/cliextensions/containerapp/azext_containerapp/_utils.py", line 311, in _ensure_location_allowed
    location_formatted = location.lower().replace(" ", "")
AttributeError: 'NoneType' object has no attribute 'lower'

```

## Environment Summary
```
macOS-12.4-arm64-arm-64bit, Darwin 21.5.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.37.0

Extensions:
deploy-to-azure 0.2.0
containerapp-compose 0.1.0
containerapp 0.3.7

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@agoncal Thanks for the feedback! We will investigate and get back to you.

**Comment by RakeshMohanMSFT** [comment]
@agoncal Apologies for the delay, we managed to get it to work without any issue with the latest version of az cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli). Can you try upgrading to see if it working for you? if not please share debug log with us for further troubleshooting.

**Comment by agoncal** [comment]
Yes, it's working. Thanks
