### ISSUE TITLE
Error listing workflows

### ISSUE THREAD

**Issue by mmentella** [Azure/azure-cli-extensions#5063]
## Describe the bug

**Command Name**
`az logic workflow list
Extension Name: logic. Version: 0.1.6.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type, KeyError: 'OpenAuthenticationAccessPolicies'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1620, in deserialize_data
KeyError: 'OpenAuthenticationAccessPolicies'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 710, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 84, in __next__
  File "C:\Users\mtmentella\.azure\cliextensions\logic\azext_logic\vendored_sdks\logic\operations\_workflow_operations.py", line 96, in extract_data
    deserialized = self._deserialize('WorkflowListResult', pipeline_response)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1368, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in deserialize_iter
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1620, in deserialize_data
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: 'OpenAuthenticationAccessPolicies'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az logic workflow list`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
account 0.2.3
logic 0.1.6
resource-graph 2.1.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
logic

**Comment by RakeshMohanMSFT** [comment]
@mmentella We are unable to reproduce this issue with latest version of azure cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli). Can you please upgrade and try again?
