### ISSUE TITLE
az quantum execute ascii error

### ISSUE THREAD

**Issue by nvannier** [Azure/azure-cli-extensions#5071]
## Describe the bug

**Command Name**
`az quantum execute
Extension Name: quantum. Version: 0.16.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ascii' codec can't decode byte 0x82 in position 113: ordinal not in range(128)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Nicolas VANNIER\.azure\cliextensions\quantum\azext_quantum\operations\job.py", line 342, in run
    job = submit(cmd, program_args, resource_group_name, workspace_name, location, target_id,
  File "C:\Users\Nicolas VANNIER\.azure\cliextensions\quantum\azext_quantum\operations\job.py", line 182, in submit
    build(cmd, target_id=target_id, project=project, target_capability=target_capability)
  File "C:\Users\Nicolas VANNIER\.azure\cliextensions\quantum\azext_quantum\operations\job.py", line 90, in build
    print(result.stdout.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 113: ordinal not in range(128)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az quantum execute --target-id {} -o {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
quantum 0.16.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by nvannier** [comment]
thx,

best regards,

Nicolas


Le ven. 1 juil. 2022 à 11:50, Yong Zhang ***@***.***> a
écrit :

**Comment by navba-MSFT** [comment]
@nvannier Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by nvannier** [comment]
Please,  Thank you for your answer.


Best regards,

Nicolas VANNIER


Le mer. 6 juil. 2022 à 08:47, navba-MSFT ***@***.***> a
écrit :

**Comment by navba-MSFT** [comment]
@nvannier Could you please try to update the Windows system language setting by following the below plan ?

Control panel -> Clock and Region -> Region -> Administrative -> Change system locale -> Check Beta: Use Unicode UTF-8 for worldwide language support

![image](https://user-images.githubusercontent.com/57353862/177490588-dee39b1e-d556-442b-a895-9997812a90c4.png)


The change will require reboot. Could you check and let me know if this action plan helps ?

**Comment by navba-MSFT** [comment]
@nvannier I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  are still facing the issue after following the above suggestion. Awaiting your reply.

**Comment by nvannier** [comment]
No, I did not. I test this this morning


Best regards,

Nicolas


Le ven. 8 juil. 2022 à 05:47, navba-MSFT ***@***.***> a
écrit :

**Comment by nvannier** [comment]
I works ! it's fine...

Thx very much...

Best regards,

Nicolas

**Comment by navba-MSFT** [comment]
@nvannier Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by nvannier** [comment]
Thanks a lot.
Best regards,

Nicolas


Le ven. 8 juil. 2022 à 13:18, navba-MSFT ***@***.***> a
écrit :
