### ISSUE TITLE
"account tenant list" fails with: No module named 'azure.core.rest'

### ISSUE THREAD

**Issue by pchevallier** [Azure/azure-cli-extensions#5072]
## Describe the bug

**Command Name**
`az account tenant list
Extension Name: account. Version: 0.2.3.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.core.rest'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/xxxxxx/.azure/cliextensions/account/azext_account/manual/_client_factory.py", line 20, in cf_tenants
    return cf_account(cli_ctx).tenants
  File "/Users/xxxxxx/.azure/cliextensions/account/azext_account/manual/_client_factory.py", line 9, in cf_account
    from ..vendored_sdks.subscription import SubscriptionClient
  File "/Users/xxxxxx/.azure/cliextensions/account/azext_account/vendored_sdks/subscription/__init__.py", line 9, in <module>
    from ._subscription_client import SubscriptionClient
  File "/Users/xxxxxx/.azure/cliextensions/account/azext_account/vendored_sdks/subscription/_subscription_client.py", line 12, in <module>
    from azure.core.rest import HttpRequest, HttpResponse
ModuleNotFoundError: No module named 'azure.core.rest'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account tenant list`

## Expected Behavior
Get the tenants for our account as per 
https://docs.microsoft.com/en-us/cli/azure/account/tenant?view=azure-cli-latest

## Environment Summary
```
macOS-12.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.27.0 *

Extensions:
kusto 0.3.0
azure-iot 0.10.15
azure-devops 0.21.0
account 0.2.3

```

**Comment by yonzhan** [comment]
account

**Comment by obiii** [comment]
Hi, 

We are having similar issues when running an ADF pipeline from azure devops azure cli task:

`$runId=az datafactory pipeline create-run --factory-name test-adf  --name "pl_load_training_data" --resource-group test-rg --query "runId" --output tsv`

results in:
![image](https://user-images.githubusercontent.com/17766651/188667035-459c5c75-81b0-44ba-97d4-d8996295b51a.png)

**Comment by rbkasat** [comment]
same issue for us.

**Comment by zhoxing-ms** [comment]
This is because the official CLI version you are using is too old and incompatible with the new extension. Could you upgrade the official CLI to the latest version ([2.40.0](https://learn.microsoft.com/en-us/cli/azure/what-is-azure-cli)) and try again?

**Comment by obiii** [comment]
Hi, we were able to fix this by installing the cli via python step: (Having these in our requiremtns.txtx)
# azureml
azure-cli-core==2.35.0   
azureml-sdk==1.42.0





> @pchevallier @obiii @rbkasat This is because the official CLI version you are using is too old and incompatible with the new extension. Could you upgrade the official CLI to the latest version ([2.40.0](https://learn.microsoft.com/en-us/cli/azure/what-is-azure-cli)) and try again?

Installing the version 2.40.0 as mentioned by a comment above is not helpful as well.

**Comment by maksteel** [comment]
For me, just upgrading `azure-cli-core==2.35.0` did the trick
