### ISSUE TITLE
`az k8s-extension create` install extension in a namespace

### ISSUE THREAD

**Issue by shubham1172** [Azure/azure-cli-extensions#5073]
### Related command

`az k8s-extension`

### Extension name (the extension in question)
`k8s-extension`

https://github.com/Azure/azure-cli-extensions/tree/main/src/k8s-extension/azext_k8s_extension

### Description of issue (in as much detail as possible)
Create a k8s-extension in a particular release namespace using `az k8-extension create` like the following:

```bash
az k8s-extension create \
--cluster-type managedClusters \
--cluster-name dapr-aks \
--resource-group shubhash-rg \
--name dapr-ext \
--extension-type microsoft.dapr \
--release-namespace dapr-system-ext
```
This throws the following error:
```bash
When --scope is 'namespace', --release-namespace must not be given.
```

What is the default value of scope? I couldn't find it here - https://docs.microsoft.com/en-us/cli/azure/k8s-extension?view=azure-cli-latest#az-k8s-extension-create

Also, on appending the argument `--scope namespace`, it starts throwing the following error:
```bash
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'namespace'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/shubham1172/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 187, in create_k8s_extension
    __validate_scope_after_customization(extension_instance.scope)
  File "/Users/shubham1172/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 406, in __validate_scope_after_customization
    and scope_obj.namespace is not None
AttributeError: 'str' object has no attribute 'namespace'
```
-----

**Comment by shubham1172** [comment]
Never mind, I figured out the problem from the code, our particular extension is not using these namespaces at all. Closing this.
