### ISSUE TITLE
az aks draft setup-gh was NOT executed successfully

### ISSUE THREAD

**Issue by sanjaypatil22** [Azure/azure-cli-extensions#5074]
## Describe the bug

**Command Name**
`az aks draft setup-gh
Extension Name: aks-preview. Version: 0.5.85.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
`az aks draft setup-gh` was NOT executed successfully
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\adminuser\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 2313, in aks_draft_setup_gh
    aks_draft_cmd_setup_gh(app, subscription_id, resource_group, provider, gh_repo, path)
  File "C:\Users\adminuser\.azure\cliextensions\aks-preview\azext_aks_preview\aks_draft\commands.py", line 58, in aks_draft_cmd_setup_gh
    raise ValueError('`az aks draft setup-gh` was NOT executed successfully')
ValueError: `az aks draft setup-gh` was NOT executed successfully

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks draft setup-gh --provider={} --subscription-id={} --resource-group={} --gh-repo {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
aks-preview 0.5.85

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@sanjaypatil22 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@sanjaypatil22 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Could you please provide an update once you test this suggestion? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sanjaypatil22 Please let me know if you have any update on this.

**Comment by sanjaypatil22** [comment]
I was using same app name which was exist. Used new app reg name and it is working fine. Thanks for looking into the issue.

**Comment by sanjaypatil22** [comment]
Thanks issue is closed.
