### ISSUE TITLE
aks create gpu cluster failed

### ISSUE THREAD

**Issue by xwang2713** [Azure/azure-cli-extensions#5077]
## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.5.25.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'users'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/ming/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1973, in aks_get_credentials
    _print_or_merge_credentials(
  File "/home/ming/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3735, in _print_or_merge_credentials
    merge_kubernetes_configurations(
  File "/home/ming/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3812, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'users', replace)
  File "/home/ming/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3748, in _handle_merge
    if existing[key] is None:
KeyError: 'users'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --admin --overwrite-existing`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.35.0 *

Extensions:
aks-preview 0.5.25

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@xwang2713 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@xwang2713 Apologies for the late reply. You can check under the user profile for file ~/.kube/config. There are 3 required sections which must be present: clusters, contexts and users. May be due to an incorrect entry under clusters you might be facing this issue. You can also rename or delete the config file and then [az aks get-credentials](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) should start working again.

Alternatively you can pass the `--file` or` --overwrite-existing` parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).


Awaiting your reply.

**Comment by xwang2713** [comment]
It is due to my ~/.kube/config corrupted. But the error message didn't mention it.   This can be closed
