### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'

### ISSUE THREAD

**Issue by spowser** [Azure/azure-cli-extensions#5094]
Error while trying to enable the OIDC Issuer

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.70.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.command_modules.acs.decorator'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\<user>\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 902, in aks_update
    from azure.cli.command_modules.acs.decorator import AKSParamDict
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -n {} -g {} --enable-oidc-issuer`

## Expected Behavior

Command doesn't throw an error and enables the oidc issuer

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0

Extensions:
aks-preview 0.5.70

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@spowser Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@spowser You seem to be using an older version of the `aks_preview` extension. Could you please run the command to update the extension and then test this again ?

>az extension update -n aks-preview

Awaiting your reply.

**Comment by spowser** [comment]
@navba-MSFT Yup.  That fixed it.  Thanks for the resolution.  As a note, the documentation might need to be updated to reflect that the extension version needs to be higher than it states

https://azure.github.io/azure-workload-identity/docs/installation.html

**Comment by navba-MSFT** [comment]
@spowser I am glad that the issue is resolved. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
