### ISSUE TITLE
pod-identity command did not work

### ISSUE THREAD

**Issue by nishantrajmitra** [Azure/azure-cli-extensions#5103]
## Describe the bug

**Command Name**
`az aks pod-identity delete
Extension Name: aks-preview. Version: 0.5.76.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.command_modules.acs.decorator'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/nishant/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 3023, in aks_pod_identity_delete
    from azext_aks_preview.decorator import AKSPreviewModels
  File "/home/nishant/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 16, in <module>
    from azure.cli.command_modules.acs.decorator import (
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks pod-identity delete --name {} --namespace {} --resource-group {} --cluster-name {}`

## Environment Summary
```
Linux-5.4.0-1085-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
aks-preview 0.5.76
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@nishantrajmitra Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@nishantrajmitra You seem to be using an older version of the `aks_preview` extension. Could you please run the command to update the extension and then test this again ?

>az extension update -n aks-preview

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@nishantrajmitra I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@nishantrajmitra The action is currently pending on you to update the `aks-preview` extension and then test the command again. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
