### ISSUE TITLE
Stream blob null error

### ISSUE THREAD

**Issue by baelter** [Azure/azure-cli-extensions#5108]
### Related command
```
pg_basebackup -D - -X fetch --format tar --gzip --compress=3 | \
  az storage blob upload --data @- -c wal -n $(hostname -s)/base.tar.gz
```

### Extension name (the extension in question)
storage-blob-preview

### Description of issue (in as much detail as possible)
```
ERROR: '>' not supported between instances of 'NoneType' and 'int' 
Traceback (most recent call last): 
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke 
    cmd_result = self.invocation.execute(args) 
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute 
    raise ex 
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially 
    results.append(self._run_job(expanded_arg, cmd_copy)) 
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job 
    return cmd_copy.exception_handler(ex) 
  File "/etc/azure/cliextensions/storage-blob-preview/azext_storage_blob_preview/__init__.py", line 265, in new_handler 
    raise ex 
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job 
    result = cmd_copy(params) 
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__ 
    return self.handler(*args, **kwargs) 
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler 
    return op(**command_args) 
  File "/etc/azure/cliextensions/storage-blob-preview/azext_storage_blob_preview/operations/blob.py", line 675, in upload_blob 
    _adjust_block_blob_size(client, blob_type, length) 
  File "/etc/azure/cliextensions/storage-blob-preview/azext_storage_blob_preview/operations/blob.py", line 622, in _adjust_block_blob_size 
    if length > 50000 * 4 * 1024 * 1024: 
TypeError: '>' not supported between instances of 'NoneType' and 'int' 
```

**Comment by yonzhan** [comment]
storage
