### ISSUE TITLE
Error While Running az aks update with --enable-keda

### ISSUE THREAD

**Issue by itskumart** [Azure/azure-cli-extensions#5138]
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.91.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rpartition'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\NateshDange\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 806, in aks_update
    return aks_update_decorator.update_mc(mc)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 5775, in update_mc
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 5756, in put_mc
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 5718, in postprocessing_after_mc_created
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/addonconfiguration.py", line 797, in add_virtual_node_role_assignment
AttributeError: 'NoneType' object has no attribute 'rpartition'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --subscription {} --enable-keda`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0

Extensions:
aks-preview 0.5.91

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@itskumart Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@itskumart I was able to run the command to enable Keda in my AKS Cluster and that worked just fine.

Could you please confirm if you have Registered the `AKS-KedaPreview` for the namespace and subscription?

>az account set --subscription "XXXXXXX"
>az feature register --name AKS-KedaPreview --namespace Microsoft.ContainerService 

Once the feature 'AKS-KedaPreview' is registered, invoking 'az provider register -n Microsoft.ContainerService' is required to get the change propagated.

Then please run the below command:
>az aks update --resource-group {} --name {} --subscription {} --enable-keda

Hope this helps.

**Comment by navba-MSFT** [comment]
@itskumart I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  have any follow-up questions on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@itskumart The action is currently pending on you to try the above suggestion. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
