### ISSUE TITLE
az monitor app-insights web-test create

### ISSUE THREAD

**Issue by tphilley** [Azure/azure-cli-extensions#5139]
### Related command
az monitor app-insights web-test create

### Extension name (the extension in question)
application-insights

### Description of issue (in as much detail as possible)
Running the 'az monitor app-insights web-test create' command while passing in the --headers argument results in an error. Running the command without the --headers argument works as intended.
Error Message:
```Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1649, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1649, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1620, in deserialize_data
    obj_type = self.dependencies[data_type]
KeyError: 'HeaderField'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1631, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1649, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1649, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1620, in deserialize_data
    obj_type = self.dependencies[data_type]
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: 'HeaderField'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/extensions/application-insights/azext_applicationinsights/custom.py", line 483, in create_web_test
    return client.create_or_update(resource_group_name=resource_group_name,
  File "/opt/az/extensions/application-insights/azext_applicationinsights/vendored_sdks/mgmt_applicationinsights/v2018_05_01_preview/operations/_web_tests_operations.py", line 228, in create_or_update
    body_content = self._serialize.body(web_test_definition, 'WebTest')
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 622, in body
    raise_with_traceback(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1631, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1649, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1649, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrest/serialization.py", line 1620, in deserialize_data
    obj_type = self.dependencies[data_type]
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, KeyError: 'HeaderField', DeserializationError: Unable to deserialize to object: type, KeyError: 'HeaderField'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/__main__.py", line 48, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/__main__.py", line 35, in cli_main
    return cli.invoke(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 243, in invoke
    exit_code = self.exception_handler(ex)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 135, in exception_handler
    return handle_exception(ex)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/util.py", line 64, in handle_exception
    from msal_extensions.persistence import PersistenceError
ImportError: cannot import name 'PersistenceError' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py) 
```
-----
### Environment Summary
Tested with multiple versions of application-insights/CLI with same results
```azure-cli                         2.37.0 *

core                              2.37.0 *
telemetry                          1.0.6

Extensions:
ml                                 2.5.0
application-insights              0.1.16

Dependencies:
msal                              1.17.0
azure-mgmt-resource               21.0.0

Python location '/anaconda/envs/azureml_py38/bin/python'
Extensions directory '/opt/az/extensions'

Python (Linux) 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]```

**Comment by yonzhan** [comment]
monitor

**Comment by RakeshMohanMSFT** [comment]
@tphilley Thank you for reaching out, we are looking into it.

**Comment by SBAESH** [comment]
I'm encountering the same error. Any update yet?

ImportError: cannot import name 'PersistenceError' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py)
