### ISSUE TITLE
Some "az ml" commands are completely broken due to metadata errors

### ISSUE THREAD

**Issue by jberezanski-mdg** [Azure/azure-cli-extensions#514]
### Extension name (the extension in question)
Machine Learning CLI extension version 1.0.10

### Description of issue (in as much detail as possible)

-----

These `az ml` commands fail to run at all, even just to display help text:

```
> az ml service tags remove -h
command authoring error for 'ml service tags remove': 'verbose' conflicting option string: --verbose

> az ml image tags remove -h
command authoring error for 'ml image tags remove': 'verbose' conflicting option string: --verbose

> az ml service properties -h
The operation 'azext_ml.service.service#service_properties_add' is invalid.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\azure-cli-core\azure\cli\core\__init__.py", line 491, in get_op_handler
AttributeError: module 'azext_ml.service.service' has no attribute 'service_properties_add'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\azure-cli-core\azure\cli\core\commands\__init__.py", line 276, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1024, in __call__
    parser.print_help()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\azure-cli-core\azure\cli\core\parser.py", line 154, in format_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\knack\knack\parser.py", line 225, in format_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\knack\knack\help.py", line 664, in show_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\knack\knack\help.py", line 219, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\knack\knack\help.py", line 163, in load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\knack\knack\parser.py", line 216, in __getattribute__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\azure-cli-core\azure\cli\core\__init__.py", line 450, in default_description_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-r8nye8gm\azure-cli-core\azure\cli\core\__init__.py", line 496, in get_op_handler
ValueError: The operation 'azext_ml.service.service#service_properties_add' is invalid.
```

**Comment by yonzhan** [comment]
ml
