### ISSUE TITLE
az aks create failing for  AKS Azure CNI Dynamic allocation of IPs 

### ISSUE THREAD

**Issue by ssbandari1** [Azure/azure-cli-extensions#5161]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.64.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.command_modules.acs.decorator'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/sabanda/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 805, in aks_create
    from azure.cli.command_modules.acs.decorator import AKSParamDict
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --location {} --max-pods {} --node-count {} --network-plugin {} --network-policy {} --vnet-subnet-id {} --pod-subnet-id {} --generate-ssh-keys --debug -y`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
aro 1.0.6
k8s-extension 1.2.4
aks-preview 0.5.64

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ssbandari1 Thank you for reaching out, we are looking into it.

**Comment by FumingZhang** [comment]
Hi @ssbandari1, sorry for the inconvenience, the old version of aks-preview (0.5.64) has some compatibility issues with the latest version of azure-cli (2.38.0). Please update your aks-preview, the latest version is 0.5.92.
`az extension update -n aks-preview`
