### ISSUE TITLE
'NoneType' object has no attribute 'kind'

### ISSUE THREAD

**Issue by DaleyKD** [Azure/azure-cli-extensions#5190]
## Describe the bug

**Command Name**
`az hcs update
Extension Name: hcs. Version: 0.4.9.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/kyle/.azure/cliextensions/hcs/azext_hcs/custom.py", line 383, in update_hcs
    if source_channel_supported(app):
  File "/home/kyle/.azure/cliextensions/hcs/azext_hcs/custom.py", line 768, in source_channel_supported
    if app.kind == 'ServiceCatalog':
AttributeError: 'NoneType' object has no attribute 'kind'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az hcs update -g {} --name {} --consul-version {}`

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0 *

Extensions:
hcs 0.4.9
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by DaleyKD** [comment]
Derp, never mind. Wrong resource name.
