### ISSUE TITLE
AttributeError: 'NetworkManagerCommitsOperations' object has no attribute 'post'

### ISSUE THREAD

**Issue by sjovang** [Azure/azure-cli-extensions#5201]
## Describe the bug

**Command Name**
`az network manager post-commit
Extension Name: virtual-network-manager. Version: 0.5.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NetworkManagerCommitsOperations' object has no attribute 'post'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/tsg/.azure/cliextensions/virtual-network-manager/azext_network_manager/custom.py", line 116, in network_manager_commit_post
    return client.post(resource_group_name=resource_group_name,
AttributeError: 'NetworkManagerCommitsOperations' object has no attribute 'post'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network manager post-commit --commit-type Connectivity -n networkmanager -g NetworkManager --target-locations westeurope --configuration-ids /subscriptions/<redacted>/resourceGroups/NetworkManager/providers/Microsoft.Network/networkManagers/networkmanager/connectivityConfigurations/hub-spoke`

## Environment Summary
```
macOS-12.5-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.39.0

Extensions:
virtual-network-manager 0.5.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
network

**Comment by RakeshMohanMSFT** [comment]
@sjovang Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@sjovang Can you please upgrade your virtual-network-manager extension to 0.5.3 and retry?

**Comment by sjovang** [comment]
I have tested with version 0.5.3 and can confirm that `az network manager post-commit` now works as expected
