### ISSUE TITLE
Having issue running aks get-credentials with aks-preview extensino - case_insensitve_dict error

### ISSUE THREAD

**Issue by udubnate** [Azure/azure-cli-extensions#5215]
## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.5.92.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\utils\__init__.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\nathbr\.azure\cliextensions\aks-preview\azext_aks_preview\_client_factory.py", line 31, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "C:\Users\nathbr\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\_container_service_client.py", line 607, in managed_clusters
    from .v2022_06_02_preview.operations import ManagedClustersOperations as OperationClass
  File "C:\Users\nathbr\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_06_02_preview\__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "C:\Users\nathbr\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_06_02_preview\_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "C:\Users\nathbr\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_06_02_preview\operations\__init__.py", line 9, in <module>
    from ._operations import Operations
  File "C:\Users\nathbr\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_06_02_preview\operations\_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\utils\__init__.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *

Extensions:
aks-preview 0.5.92

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@udubnate Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@udubnate I am unable to replicate this issue using the same version of `aks-preview` extension. The only difference was that I am using most recent version of Azure CLI. 

I could see that you are using an older version of `azure-cli 2.37.0 * `. To isolate this issue, Could you please use the[ most recent version of AzCLI ](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)and test again ?

**Comment by Uditanshu1612** [comment]
Hi,
Is the issue is resolved? I'm also facing the same issue while importing a package.
Currently My azure-core is a version of 1.26.0 so while executing the module using this version of azure-core it throws me an error
![image](https://user-images.githubusercontent.com/115619000/196407530-75a5d4b6-82e2-4d75-9b31-c7dd22a61e15.png)


So here by observing the error I get to know that module requires an azure-core of version <=1.22.1. So if downgrade the version to 1.22.1 or less than that, then I'm facing an error
![image](https://user-images.githubusercontent.com/115619000/196407499-2b14a091-1a71-4f0b-b503-0244608089d2.png)


did anyone have the solution how to resolve the error and successfully import the module?
