### ISSUE TITLE
API version 2022-03-01 does not have operation group 'virtual_machines'

### ISSUE THREAD

**Issue by matiasveritone** [Azure/azure-cli-extensions#5268]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.1.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2022-03-01 does not have operation group 'virtual_machines'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/catman/.azure/cliextensions/ssh/azext_ssh/custom.py", line 64, in ssh_vm
    ssh_session.resource_type = _decide_resource_type(cmd, ssh_session)
  File "/home/catman/.azure/cliextensions/ssh/azext_ssh/custom.py", line 391, in _decide_resource_type
    vm, vm_error, is_azure_vm = _check_if_azure_vm(cmd, op_info.resource_group_name, op_info.vm_name)
  File "/home/catman/.azure/cliextensions/ssh/azext_ssh/custom.py", line 443, in _check_if_azure_vm
    vm = compute_client.virtual_machines.get(resource_group_name, vm_name)
  File "/usr/lib/python3/dist-packages/azure/mgmt/compute/_compute_management_client.py", line 1982, in virtual_machines
    raise ValueError("API version {} does not have operation group 'virtual_machines'".format(api_version))
ValueError: API version 2022-03-01 does not have operation group 'virtual_machines'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --name {} --resource-group {}`

## Environment Summary
```
Linux-5.18.0-kali5-amd64-x86_64-with-glibc2.33, Kali GNU/Linux Rolling
Python 3.10.5
Installer: DEB

azure-cli 2.39.0

Extensions:
ssh 1.1.2
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@matiasveritone Can you please uninstall cli and use pip to install official Azure CLI from PyPI: https://pypi.org/project/azure-cli/ on you Kali linux machine.

**Comment by SaurabhSharma-MSFT** [comment]
@matiasveritone Please let me know if you still having any issues else, we will proceed with the closure of this case.

**Comment by matiasveritone** [comment]
@SaurabhSharma-MSFT sorry for the delay.

Indeed it was solved by running in Python, which isn't ideal, but it did work!

Thx!

**Comment by SaurabhSharma-MSFT** [comment]
@matiasveritone We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
