### ISSUE TITLE
Error when trying to update the max concurrency property on an ADF trigger

### ISSUE THREAD

**Issue by micai** [Azure/azure-cli-extensions#5269]
## Describe the bug

**Command Name**
`az datafactory trigger update
Extension Name: datafactory. Version: 0.5.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 210, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 491, in set_properties
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 708, in _find_property
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 698, in _update_instance
TypeError: argument of type 'NoneType' is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datafactory trigger update --factory-name {} --resource-group {} --name {} --set properties.typeProperties.maxConcurrency=5`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
azure-devops 0.25.0
datafactory 0.5.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@micai You need to use `--set properties.maxConcurrency=30` to update the Max Concurrency property.  See below.
![image](https://user-images.githubusercontent.com/38112130/186786037-fb4dc35d-b2c1-4e39-84ce-ddd4a57f7e25.png)

Thanks
Saurabh
