### ISSUE TITLE
Unable to list the ground stations 

### ISSUE THREAD

**Issue by yebarri** [Azure/azure-cli-extensions#5284]
## Describe the bug

**Command Name**
`az orbital available-ground-station list
Extension Name: orbital. Version: 0.1.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'MSIAuthenticationWrapper' object has no attribute 'get_auxiliary_tokens'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_paging.py", line 49, in __next__
    return next(self._page_iterator)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_paging.py", line 26, in __next__
    self._executor(self._next_link)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 213, in executor_wrapper
    executor()
  File "/home/yerrayya/.azure/cliextensions/orbital/azext_orbital/aaz/latest/orbital/available_ground_station/_list.py", line 56, in _execute_operations
    self.AvailableGroundStationsListByCapability(ctx=self.ctx)()
  File "/home/yerrayya/.azure/cliextensions/orbital/azext_orbital/aaz/latest/orbital/available_ground_station/_list.py", line 68, in __call__
    session = self.client.send_request(request=request, stream=False, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_client.py", line 86, in send_request
    session = self._pipeline.run(request, stream=stream, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_http_policy.py", line 105, in send
    self.on_request(

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
@thisisdevanshu, could you please help look at this issue?

cc// @kairu-ms

**Comment by yebarri** [comment]
Hi, any update on this issue?

**Comment by yebarri** [comment]
Hi,
    I can list the ground stations using the portal CLI, but when I install the Azure CLI on Windows 64.  I'm not seeing any issues, but I'm getting empty outputs.

**C:\Users\yebarri>az orbital contact-profile list
[]**

Thanks, Yerrayya

**Comment by navba-MSFT** [comment]
@yebarri Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please share the `--debug` output while running the concerned AzCLI command ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@yebarri I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@yebarri The action is pending on you to share the `--debug `output. Please feel free to reopen this thread once you are ready to resume troubleshooting on this. We would be happy to help.

**Comment by yebarri** [comment]
The issue was resolved. I'm able to run the commands on my local pc.

> az orbital available-ground-station list
[
  {
    "altitudeMeters": 392.5,
    "city": "Quincy",
    "id": "/subscriptions/xxx/providers/Microsoft.Orbital/availableGroundStations/Microsoft_Quincy",
    "latitudeDegrees": 47.2393,
    "location": "westus2",
    "longitudeDegrees": -119.88515,
    "name": "Microsoft_Quincy",
    "providerName": "Microsoft",
    "releaseMode": "GA",
    "type": "Microsoft.Orbital/availableGroundStations"
  },
  {
    "altitudeMeters": 13.65,
    "city": "Awarua",
    "id": "/subscriptions/xxx/providers/Microsoft.Orbital/availableGroundStations/KSAT_Awarua",
    "latitudeDegrees": -46.52877,

Thanks, Yerrayya
