### ISSUE TITLE
Error attaching ACR to AKS

### ISSUE THREAD

**Issue by elaamrani** [Azure/azure-cli-extensions#5288]
## Describe the bug

**Command Name**
`az aks update -n <k8s-name> -g <resource-group-name> --attach-acr <acr-name>
Extension Name: aks-preview. Version: 0.5.51.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.command_modules.acs.decorator'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/ahmedelaamrani/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 843, in aks_update
    from azure.cli.command_modules.acs.decorator import AKSParamDict
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -n {} -g {} --attach-acr {}`

## Environment Summary
```
macOS-12.2.1-arm64-arm-64bit, Darwin 21.3.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.38.0 *

Extensions:
aks-preview 0.5.51
account 0.2.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by elaamrani** [comment]
Additional content: I previously was able to pull images from my ACR inside AKS. I woke up this morning and it does not work anymore. The connection is refused.
I then tried to reattach ACR to AKS using
`az aks update -n <k8s-name> -g <resource-group-name> --attach-acr <acr-name>`
However, I got the above error. Could you please help?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@elaamrani Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@elaamrani can you go through this and see it helps you? https://github.com/Azure/azure-cli/issues/9598#issuecomment-1064355654
