### ISSUE TITLE
Error when using aks show command on aks-preview

### ISSUE THREAD

**Issue by jpmckearin** [Azure/azure-cli-extensions#5289]
## Describe the bug

**Command Name**
`az aks show
Extension Name: aks-preview. Version: 0.5.94.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/core/utils/__init__.py)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 352, in handler
    client = self.client_factory(self.cli_ctx) if self.client_factory else None
  File "/Users/jmckearin/.azure/cliextensions/aks-preview/azext_aks_preview/_client_factory.py", line 31, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/Users/jmckearin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/_container_service_client.py", line 642, in managed_clusters
    from .v2022_07_02_preview.operations import ManagedClustersOperations as OperationClass
  File "/Users/jmckearin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "/Users/jmckearin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "/Users/jmckearin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/__init__.py", line 9, in <module>
    from ._operations import Operations
  File "/Users/jmckearin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/core/utils/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- `az aks show -g {} -n {} -o table`

## Expected Behavior
Expected to see a table output of the current aks cluster status

## Environment Summary
```
macOS-12.5-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.37.0 *

Extensions:
aks-preview 0.5.94

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
I also ran into the same issue when running `az aks kollect`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@jpmckearin Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@jpmckearin We are unable to reproduce this issue at our end.

![image](https://user-images.githubusercontent.com/49954584/187616040-58815b00-387f-456f-aea9-02a59cf709e0.png)

Can you please try upgrading to the latest version of Az CLI 2.39.0
