### ISSUE TITLE
error when running: az account subscription rename

### ISSUE THREAD

**Issue by ElwinDo** [Azure/azure-cli-extensions#5294]
## Describe the bug

**Command Name**
`az account subscription rename
Extension Name: account. Version: 0.2.3.`

**Errors:**
```
(InvalidResourceType) The resource type 'rename' could not be found in the namespace 'Microsoft.Subscription' for api version '2021-10-01'. The supported api-versions are '2019-03-01-preview,2019-10-01-preview,2020-09-01,2021-01-01-privatepreview'.
Code: InvalidResourceType
Message: The resource type 'rename' could not be found in the namespace 'Microsoft.Subscription' for api version '2021-10-01'. The supported api-versions are '2019-03-01-preview,2019-10-01-preview,2020-09-01,2021-01-01-privatepreview'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account subscription rename --subscription-id {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.1 *

Extensions:
account 0.2.3
init 0.1.0
interactive 0.4.5

```

**Comment by ElwinDo** [comment]
I was trying to rename a subscription, but when I installed the newest az cli and running the command "az account subscription rename", it shows:

Command group 'account subscription' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InvalidResourceType) The resource type 'rename' could not be found in the namespace 'Microsoft.Subscription' for api version '2021-10-01'. The supported api-versions are '2019-03-01-preview,2019-10-01-preview,2020-09-01,2021-01-01-privatepreview'.
Code: InvalidResourceType
Message: The resource type 'rename' could not be found in the namespace 'Microsoft.Subscription' for api version '2021-10-01'. The supported api-versions are '2019-03-01-preview,2019-10-01-preview,2020-09-01,2021-01-01-privatepreview'.

I guess it may remove the function in the new version, so I reinstalled ver 2.22.1, but got another error: 

Command group 'account subscription' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.core.rest'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 798, in default_command_handler
  File "C:\Users\*\.azure\cliextensions\account\azext_account\generated\_client_factory.py", line 16, in cf_subscription
    return cf_account(cli_ctx).subscription
  File "C:\Users\*\.azure\cliextensions\account\azext_account\generated\_client_factory.py", line 9, in cf_account
    from ..vendored_sdks.subscription import SubscriptionClient
  File "C:\Users\*\.azure\cliextensions\account\azext_account\vendored_sdks\subscription\__init__.py", line 9, in <module>
    from ._subscription_client import SubscriptionClient
  File "C:\Users\*\.azure\cliextensions\account\azext_account\vendored_sdks\subscription\_subscription_client.py", line 12, in <module>
    from azure.core.rest import HttpRequest, HttpResponse
ModuleNotFoundError: No module named 'azure.core.rest'


Could you please help give some suggestions? thanks a lot.

**Comment by yonzhan** [comment]
@jiasli for awareness
