### ISSUE TITLE
Error using "az datafactory integration-runtime list" command

### ISSUE THREAD

**Issue by cyrmul** [Azure/azure-cli-extensions#5304]
Hi, 

My Azure DevOps pipeline is failing because of this instruction : az datafactory integration-runtime list --resource-group *** --factory-name ***

It works well yesterday afternoon but not today.

## Describe the bug

**Command Name**
`az datafactory integration-runtime list
Extension Name: datafactory. Version: 0.6.0.`

**Errors:**
I use a self-hosted agent. On my Windows agent, the traceback is:
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.core.rest'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\CMuller\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 24, in cf_integration_runtime
    return cf_datafactory_cl(cli_ctx).integration_runtimes
  File "C:\Users\CMuller\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 14, in cf_datafactory_cl
    from azext_datafactory.vendored_sdks.datafactory import DataFactoryManagementClient
  File "C:\Users\CMuller\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\__init__.py", line 9, in <module>
    from ._data_factory_management_client import DataFactoryManagementClient
  File "C:\Users\CMuller\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\_data_factory_management_client.py", line 14, in <module>
    from azure.core.rest import HttpRequest, HttpResponse
ModuleNotFoundError: No module named 'azure.core.rest'
```

I tried on my personal computer, the traceback is different (but I steel have an error):

```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\utils\__init__.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\cmuller\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 24, in cf_integration_runtime
    return cf_datafactory_cl(cli_ctx).integration_runtimes
  File "C:\Users\cmuller\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 14, in cf_datafactory_cl
    from azext_datafactory.vendored_sdks.datafactory import DataFactoryManagementClient
  File "C:\Users\cmuller\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\__init__.py", line 9, in <module>
    from ._data_factory_management_client import DataFactoryManagementClient
  File "C:\Users\cmuller\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\_data_factory_management_client.py", line 19, in <module>
    from .operations import ActivityRunsOperations, DataFlowDebugSessionOperations, DataFlowsOperations, DatasetsOperations, ExposureControlOperations, FactoriesOperations, GlobalParametersOperations, IntegrationRuntimeNodesOperations, IntegrationRuntimeObjectMetadataOperations, IntegrationRuntimesOperations, LinkedServicesOperations, ManagedPrivateEndpointsOperations, ManagedVirtualNetworksOperations, Operations, PipelineRunsOperations, PipelinesOperations, PrivateEndPointConnectionsOperations, PrivateEndpointConnectionOperations, PrivateLinkResourcesOperations, TriggerRunsOperations, TriggersOperations
  File "C:\Users\cmuller\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\operations\__init__.py", line 9, in <module>
    from ._operations import Operations
  File "C:\Users\cmuller\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\operations\_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\utils\__init__.pyc)

```

## Environment Summary (personal computer)
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0 *

Extensions:
datafactory 0.6.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by mohadelrezk** [comment]
We confirm seeing the same on both (Jenkins agent and local machines)

**Comment by navba-MSFT** [comment]
@cyrmul Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@cyrmul I am unable to reproduce this issue at my end using the higher version of AzCLI. So could you please update your Azure CLI version to the [most recent version](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli) and then run the same command again ? Awaiting your reply.

**Comment by achrefbcl** [comment]
Hello , 
I had the same issue this morning with listing integration runtimes for ADF .
 I had to upgrade azure CLI  to the latest version with the command  "az upgrade" and now it's working

**Comment by navba-MSFT** [comment]
@cyrmul I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by cyrmul** [comment]
Hi, 

Yes the problem is solved!
I just execute the command `az upgrade` on all my servers (thanks @achrefbcl ) and now it works just fine. :)

Thanks folks for your help!
