### ISSUE TITLE
Draft setup-gh not working

### ISSUE THREAD

**Issue by skazure** [Azure/azure-cli-extensions#5310]
## Encountered below error while setting up Draft with VS Code DevX etension

**Command Name**
`az aks draft setup-gh
Extension Name: aks-preview. Version: 0.5.97.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Binary check was NOT executed successfully
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\DTSANDKUMA\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 1884, in aks_draft_setup_gh
    aks_draft_cmd_setup_gh(app, subscription_id, resource_group, provider, gh_repo, path)
  File "C:\Users\DTSANDKUMA\.azure\cliextensions\aks-preview\azext_aks_preview\aks_draft\commands.py", line 48, in aks_draft_cmd_setup_gh
    file_path, arguments = _pre_run(download_path,
  File "C:\Users\DTSANDKUMA\.azure\cliextensions\aks-preview\azext_aks_preview\aks_draft\commands.py", line 136, in _pre_run
    raise ValueError('Binary check was NOT executed successfully')
ValueError: Binary check was NOT executed successfully

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks draft setup-gh`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
aks-preview 0.5.97
ssh 1.0.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by skazure** [comment]
Same error for az aks draft create as well. see below reported issue.
https://github.com/Azure/azure-cli-extensions/issues/5336

**Comment by FumingZhang** [comment]
Should be a bug of aks-preview on windows, can be reproduced with older versions. The following screenshot is captured with an extra `--debug` option to the command.

The binary check tried to download the binary of aks-draft from `https://github.com/Azure/draft/releases/download/v0.0.22/draft-windows-amd64` and met 404. The correct url should be `https://github.com/Azure/draft/releases/download/v0.0.22/draft-windows-amd64.exe`.

![image](https://user-images.githubusercontent.com/81607949/189872257-41732423-118e-44cd-96c2-a9ed7ae5078e.png)

A workaround is to download the binary (for aks-preview >= 0.5.99, please choose [v0.0.22](https://github.com/Azure/draft/releases/download/v0.0.22/draft-windows-amd64.exe), for aks-preview <= 0.5.97, please choose [v0.0.23](https://github.com/Azure/draft/releases/download/v0.0.23/draft-windows-amd64.exe), aks-preview 0.5.98 won't work) in advance, **rename** it to remove the `.exe` suffix and move it to the directory where this command is used.

**Comment by FumingZhang** [comment]
[Fix](https://github.com/Azure/azure-cli-extensions/pull/5345) is on the way, will release a new version of aks-preview to fix it.

**Comment by SaurabhSharma-MSFT** [comment]
@skazure Did you check with the new version if this has been fixed.

**Comment by SaurabhSharma-MSFT** [comment]
@skazure We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
