### ISSUE TITLE
Azure CLI core's new release is causing failures in fleet commands

### ISSUE THREAD

**Issue by shashankbarsin** [Azure/azure-cli-extensions#5315]
### Related command

**az fleet create**

### Description of issue (in as much detail as possible)

When we try to create fleet resource using the following command, we are always getting "cannot import name 'case_insensitive_dict'" error.

az fleet create -n name -g group
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/opt/az/lib/python3.10/site-packages/azure/core/utils/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/home/shasb/.azure/cliextensions/fleet/azext_fleet/_client_factory.py", line 21, in cf_fleets
    return get_container_service_client(cli_ctx).fleets
  File "/home/shasb/.azure/cliextensions/fleet/azext_fleet/vendored_sdks/_container_service_client.py", line 400, in fleets
    from .v2022_06_02_preview.operations import FleetsOperations as OperationClass
  File "/home/shasb/.azure/cliextensions/fleet/azext_fleet/vendored_sdks/v2022_06_02_preview/__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "/home/shasb/.azure/cliextensions/fleet/azext_fleet/vendored_sdks/v2022_06_02_preview/_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "/home/shasb/.azure/cliextensions/fleet/azext_fleet/vendored_sdks/v2022_06_02_preview/operations/__init__.py", line 9, in <module>
    from ._operations import Operations
  File "/home/shasb/.azure/cliextensions/fleet/azext_fleet/vendored_sdks/v2022_06_02_preview/operations/_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/opt/az/lib/python3.10/site-packages/azure/core/utils/__init__.py)
```

```
az -v
azure-cli                         2.37.0 *

core                              2.37.0 *
telemetry                          1.0.6 *

Extensions:
fleet                              0.1.0
connectedk8s                       1.2.9
k8s-extension                      1.2.3
maintenance                        1.3.0
aks-preview                       0.5.81
providerhub                        0.2.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/shasb/.azure/cliextensions'

Python (Linux) 3.10.4 (main, May 23 2022, 14:03:08) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by shashankbarsin** [comment]
Seems to be related to #5304. Multiple command modules were probably impacted by this issue

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jsntcy** [comment]
@shashankbarsin, please upgrade to [most recent Azure CLI version](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli) to see if the issue still exists.

**Comment by pdaru** [comment]
I failed to repro the error using az cli v2.39.0 & v.2.40. Could you try upgrading the version? @shashankbarsin

**Comment by navba-MSFT** [comment]
@shashankbarsin Please update the AzCLI version and let us know if you see the same issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@shashankbarsin Please let us know if you had any update on this.

**Comment by navba-MSFT** [comment]
@shashankbarsin The action is currently pending on you to upgrade your AzCLI version and test. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
