### ISSUE TITLE
The behavior of this command has been altered by the following extension: aks-preview

### ISSUE THREAD

**Issue by dejimarquis** [Azure/azure-cli-extensions#5329]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.51.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.command_modules.acs.decorator'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\aymarqui\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 766, in aks_create
    from azure.cli.command_modules.acs.decorator import AKSParamDict
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'

```
## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
aks-preview 0.5.51
azure-iot 0.14.1
blockchain 0.1.1
kusto 0.5.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@dejimarquis Thanks for reaching out to us and reporting this issue. I see that you are using an older version of `aks-preview` extension. Could you please update it using the below command and then run your AzCLI command again ?

>az extension update -n aks-preview

Awaiting your reply.

**Comment by dejimarquis** [comment]
> @dejimarquis Thanks for reaching out to us and reporting this issue. I see that you are using an older version of `aks-preview` extension. Could you please update it using the below command and then run your AzCLI command again ?
> 
> > az extension update -n aks-preview
> 
> Awaiting your reply.

That resolved the issue. Thanks!

**Comment by navba-MSFT** [comment]
@dejimarquis Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
