### ISSUE TITLE
not able to run az aks draft create on windows

### ISSUE THREAD

**Issue by skazure** [Azure/azure-cli-extensions#5336]
## Describe the bug

**Command Name**
`az aks draft create
Extension Name: aks-preview. Version: 0.5.100.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Binary check was NOT executed successfully
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\skuma\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 1875, in aks_draft_create
    aks_draft_cmd_create(destination, app, language, create_config, dockerfile_only, deployment_only, path)
  File "C:\Users\skuma\.azure\cliextensions\aks-preview\azext_aks_preview\aks_draft\commands.py", line 30, in aks_draft_cmd_create
    file_path, arguments = _pre_run(download_path,
  File "C:\Users\skuma\.azure\cliextensions\aks-preview\azext_aks_preview\aks_draft\commands.py", line 139, in _pre_run
    raise ValueError('Binary check was NOT executed successfully')
ValueError: Binary check was NOT executed successfully

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks draft create`

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
aks-preview 0.5.100

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@skazure Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@skazure Looking at the source code [here](https://github.com/Azure/azure-cli-extensions/blob/c15670efcb175ef1daffe93a5b86616af4dda197/src/aks-preview/azext_aks_preview/aks_draft/commands.py#L136), the exception seem to have occurred while checking the download path. Could you please confirm the `--destination` path you had entered in your command ?

`--destination`: Specify the path to the project directory. The Default value is **.**. Here ' . ' means the current directory.

If you don't specify the `--destination `parameter it will generate the files in the **Current** directory. 

Could you please navigate to the concerned directory and then run the same command **without** specifying the `--destination `parameter and check if that works ?

More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks/draft?view=azure-cli-latest#az-aks-draft-create-examples).

**Comment by skazure** [comment]
Hi @navba-MSFT , 
I tried all possible combinations and nothing works. All the commands results to similar error

az aks draft create --language=java --app=beapp4  
The required binary was not found. Would you like us to download the required binary for you? (y/N): y
The command failed with an unexpected error. Here is the traceback:
Binary check was NOT executed successfully
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler  
  File "C:\Users\skuma\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 1875, in aks_draft_create
    aks_draft_cmd_create(destination, app, language, create_config, dockerfile_only, deployment_only, path)
  File "C:\Users\skuma\.azure\cliextensions\aks-preview\azext_aks_preview\aks_draft\commands.py", line 30, in aks_draft_cmd_create
    file_path, arguments = _pre_run(download_path,
  File "C:\Users\skuma\.azure\cliextensions\aks-preview\azext_aks_preview\aks_draft\commands.py", line 139, in _pre_run
    raise ValueError('Binary check was NOT executed successfully')
ValueError: Binary check was NOT executed successfully
To open an issue, please run: 'az feedback'

I tried other commands such as "az aks draft generate-workflow" as  well and have same error

**Comment by FumingZhang** [comment]
Should be a bug of aks-preview on windows, can be reproduced with older versions. The following screenshot is captured with an extra `--debug` option to the command.

The binary check tried to download the binary of aks-draft from `https://github.com/Azure/draft/releases/download/v0.0.22/draft-windows-amd64` and met 404. The correct url should be `https://github.com/Azure/draft/releases/download/v0.0.22/draft-windows-amd64.exe`.

![image](https://user-images.githubusercontent.com/81607949/189872257-41732423-118e-44cd-96c2-a9ed7ae5078e.png)

A workaround is to download the binary (for aks-preview >= 0.5.99, please choose [v0.0.22](https://github.com/Azure/draft/releases/download/v0.0.22/draft-windows-amd64.exe), for aks-preview <= 0.5.97, please choose [v0.0.23](https://github.com/Azure/draft/releases/download/v0.0.23/draft-windows-amd64.exe), aks-preview 0.5.98 won't work) in advance, **rename** it to remove the `.exe` suffix and move it to the directory where this command is used.

**Comment by navba-MSFT** [comment]
Thanks @FumingZhang 

@skazure Could you please try the above workaround for now and let us know if that helps.

**Comment by FumingZhang** [comment]
[Fix](https://github.com/Azure/azure-cli-extensions/pull/5345) is on the way, will release a new version of aks-preview to fix it.

**Comment by skazure** [comment]
Workaround works fine.

**Comment by navba-MSFT** [comment]
@skazure The above PR has been merged. Refer this milestone for more details about the fix: https://github.com/Azure/azure-cli-extensions/milestone/71
We will now proceed with the archival of this issue, Please feel free to reopen this thread if you have any follow-up questions on this. We would be happy to help.
