### ISSUE TITLE
az k8s-extension extension-types list failed

### ISSUE THREAD

**Issue by t0rben** [Azure/azure-cli-extensions#5356]
## Describe the bug

**Command Name**
`az k8s-extension extension-types list
Extension Name: k8s-extension. Version: 1.3.3.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cf_k8s_extension() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/tbock/.azure/cliextensions/k8s-extension/azext_k8s_extension/_client_factory.py", line 21, in cf_k8s_cluster_extension_types_operation
    return cf_k8s_extension(cli_ctx, consts.EXTENSION_TYPE_API_VERSION).cluster_extension_types
TypeError: cf_k8s_extension() takes 1 positional argument but 2 were given

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az k8s-extension extension-types list -g {} --cluster-name {} --cluster-type {}`

## Environment Summary
```
macOS-12.6-arm64-arm-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.40.0

Extensions:
connectedk8s 1.3.3
k8s-extension 1.3.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by t0rben** [comment]
I've tried it additionally using windows and latest versions of the azure-cli as well as both extensions and got the same behaviour.

**Comment by navba-MSFT** [comment]
@t0rben Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@t0rben The above PR has been filed to address this. It is currently under review. Please let me know if you have any questions in the meantime.
