### ISSUE TITLE
Error during copy azure image

### ISSUE THREAD

**Issue by yaronkaikov** [Azure/azure-cli-extensions#5362]
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.9.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-object-name {} --source-resource-group {} --target-resource-group {} --target-name {} --source-type {} --target-location {}`

## Environment Summary
```
Linux-5.19.8-200.fc36.x86_64-x86_64-with-glibc2.35, Fedora Linux 36 (Workstation Edition)
Python 3.10.6
Installer: PIP

azure-cli 2.39.0 *

Extensions:
image-copy-extension 0.2.9

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by yanzhudd** [comment]
Hello @yaronkaikov, could you please provide the debug information? The debug information could be obtained by add `--debug` parameter to your executed command.

**Comment by yaronkaikov** [comment]
attached 
```
[yaronkaikov@london]~$ az image copy --source-object-name ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28 --source-resource-group scylla-images --target-resource-group scylla-images --target-name ScyllaDB-5-0-2 --source-type image --target-location eastus --debug
cli.knack.cli: Command arguments: ['image', 'copy', '--source-object-name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28', '--source-resource-group', 'scylla-images', '--target-resource-group', 'scylla-images', '--target-name', 'ScyllaDB-5-0-2', '--source-type', 'image', '--target-location', 'eastus', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f4cd6d21a20>, <function OutputProducer.on_global_arguments at 0x7f4cd6c28670>, <function CLIQuery.on_global_arguments at 0x7f4cd6a5d870>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'image': ['azure.cli.command_modules.vm', 'azext_imagecopy']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.131        56       292
cli.azure.cli.core: Total (1)                 0.131        56       292
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: image-copy-extension      0.001         1         1  /home/yaronkaikov/.azure/cliextensions/image-copy-extension
cli.azure.cli.core: Total (1)                 0.001         1         1  
cli.azure.cli.core: Loaded 56 groups, 293 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : image copy
cli.azure.cli.core: Command table: image copy
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f4cd5fad6c0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/yaronkaikov/.azure/commands/2022-09-21.10-43-25.image_copy.16801.log'.
az_command_data_logger: command args: image copy --source-object-name {} --source-resource-group {} --target-resource-group {} --target-name {} --source-type {} --target-location {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f4cd5fc70a0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f4cd608f760>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f4cd608f880>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f4cd6c28700>, <function CLIQuery.handle_query_parameter at 0x7f4cd6a5d900>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f4cd608f7f0>]
az_command_data_logger: extension name: image-copy-extension
az_command_data_logger: extension version: 0.2.9
cli.azext_imagecopy.custom: Getting OS disk ID of the source VM/image
cli.azext_imagecopy.cli_utils: command: ['/usr/bin/python3', '-m', 'azure.cli', 'image', 'show', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28', '--resource-group', 'scylla-images', '--output', 'json'] ended with output: {
  "extendedLocation": null,
  "hyperVGeneration": "V2",
  "id": "/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28",
  "location": "eastus",
  "name": "ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28",
  "provisioningState": "Succeeded",
  "resourceGroup": "scylla-images",
  "sourceVirtualMachine": {
    "id": "/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/virtualMachines/pkrvm1m3oli2ddw",
    "resourceGroup": "pkr-Resource-Group-1m3oli2ddw"
  },
  "storageProfile": {
    "dataDisks": [],
    "osDisk": {
      "blobUri": null,
      "caching": "ReadWrite",
      "diskEncryptionSet": null,
      "diskSizeGb": 30,
      "managedDisk": {
        "id": "/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw",
        "resourceGroup": "pkr-Resource-Group-1m3oli2ddw"
      },
      "osState": "Generalized",
      "osType": "Linux",
      "snapshot": null,
      "storageAccountType": "Standard_LRS"
    },
    "zoneResilient": false
  },
  "tags": {
    "ScyllaJMXVersion": "5.0.2-0.20220807.299122e78-1",
    "ScyllaMachineImageVersion": "5.0.2-20220807.1b1f0b86367-1",
    "ScyllaPython3Version": "5.0.2-0.20220807.299122e78-1",
    "ScyllaToolsVersion": "5.0.2-0.20220807.299122e78-1",
    "ScyllaVersion": "5.0.2-0.20220807.299122e78-1",
    "arch": "x86_64",
    "branch": "master",
    "build_id": "28",
    "build_tag": "",
    "operating_system": "ubuntu20.04",
    "scylla_build_sha_id": "",
    "user_data_format_version": "2"
  },
  "type": "Microsoft.Compute/images"
}

cli.azext_imagecopy.cli_utils: json output starts at position: 0 
cli.azext_imagecopy.custom: found DISK: /subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw
cli.azext_imagecopy.custom: source_os_disk_type: DISK. source_os_disk_id: /subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw. source_os_type: Linux
cli.azext_imagecopy.custom: Creating source snapshot
cli.azext_imagecopy.cli_utils: command failed: ['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']
cli.azext_imagecopy.cli_utils: output: ERROR: (NotFound) Resource pkros1m3oli2ddw is not found.
Code: NotFound
Message: Resource pkros1m3oli2ddw is not found.

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
az_command_data_logger: Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/yaronkaikov/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/yaronkaikov/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ScyllaDB-5.0.2-0.20220807.299122e78-1-build-28_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-1m3oli2ddw/providers/Microsoft.Compute/disks/pkros1m3oli2ddw', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
To open an issue, please run: 'az feedback'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f4cd5fad900>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 9.542 seconds (init: 0.076, invoke: 9.465)
telemetry.save: Save telemetry record of length 7206 in cache
telemetry.check: Negative: The /home/yaronkaikov/.azure/telemetry.txt was modified at 2022-09-21 10:42:40.695379, which in less than 600.000000 s
```

**Comment by yanzhudd** [comment]
Hello @yaronkaikov It seems that the disk named 'pkros1m3oli2ddw' is not found. Could you please check if it exists?

**Comment by yaronkaikov** [comment]
Thanks I will check
