### ISSUE TITLE
Unable to create WASM/WASI node pool using az aks nodepool add

### ISSUE THREAD

**Issue by raorugan** [Azure/azure-cli-extensions#5370]
## Describe the bug

**Command Name**
`az aks nodepool add
Extension Name: aks-preview. Version: 0.5.94.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\utils\__init__.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\raorugan\.azure\cliextensions\aks-preview\azext_aks_preview\_client_factory.py", line 35, in cf_agent_pools
    return get_container_service_client(cli_ctx).agent_pools
  File "C:\Users\raorugan\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\_container_service_client.py", line 375, in agent_pools
    from .v2022_07_02_preview.operations import AgentPoolsOperations as OperationClass
  File "C:\Users\raorugan\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_07_02_preview\__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "C:\Users\raorugan\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_07_02_preview\_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "C:\Users\raorugan\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_07_02_preview\operations\__init__.py", line 9, in <module>
    from ._operations import Operations
  File "C:\Users\raorugan\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_07_02_preview\operations\_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\utils\__init__.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool add --resource-group {} --cluster-name {} --name {} --node-count {} --workload-runtime {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *

Extensions:
aks-preview 0.5.94
containerapp 0.3.8

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@raorugan Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@raorugan I am unable to reproduce this issue at my end. I could see that you are using an older version of azure-cli 2.37.0 * . Could you please use the[ most recent version of AzCLI ](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)and test again ?

Also I would recommend you to use the most recent version of `aks-preview` extension.

>az extension update -n aks-preview

**Comment by raorugan** [comment]
this was helpful! we can close the issue

**Comment by navba-MSFT** [comment]
@raorugan Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
