### ISSUE TITLE
Az webapp create show error.

### ISSUE THREAD

**Issue by MarsWangyang** [Azure/azure-cli-extensions#5382]
## Describe the bug

**Command Name**
`az webapp create
Extension Name: appservice-kube. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
_StackRuntimeHelper.__init__() got multiple values for argument 'linux'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/Users/mars/.azure/cliextensions/appservice-kube/azext_appservice_kube/commands.py", line 42, in _polish_bad_errors
    raise ex
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/mars/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 505, in create_webapp
    helper = _StackRuntimeHelper(cmd, client, linux=(is_linux or is_kube))
TypeError: _StackRuntimeHelper.__init__() got multiple values for argument 'linux'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --name {} --plan {} --resource-group {}`

## Environment Summary
```
macOS-12.6-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.39.0 *

Extensions:
connectedk8s 1.2.11
azure-firewall 0.14.3
k8s-extension 1.2.6
aks-preview 0.5.102
azure-devops 0.25.0
appservice-kube 0.2.2
customlocation 0.1.3
interactive 0.4.5
log-analytics 0.2.2
containerapp 0.3.8
spring-cloud 3.1.5
spring 1.1.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@MarsWangyang Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@MarsWangyang Could you please update your extension by running the below command and check if that helps ?

>az extension update -n appservice-kube

Awaiting your reply.

**Comment by MarsWangyang** [comment]
Run it, and it's good. Thanks.
