### ISSUE TITLE
Recent az-cli issues coming up in azuredevops

### ISSUE THREAD

**Issue by sauravrout** [Azure/azure-cli-extensions#5396]
## Describe the bug

**Command Name**
`az datafactory trigger list
Extension Name: datafactory. Version: 0.6.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/home/srout104/.azure/cliextensions/datafactory/azext_datafactory/generated/_client_factory.py", line 52, in cf_trigger
    return cf_datafactory_cl(cli_ctx).triggers
  File "/home/srout104/.azure/cliextensions/datafactory/azext_datafactory/generated/_client_factory.py", line 14, in cf_datafactory_cl
    from azext_datafactory.vendored_sdks.datafactory import DataFactoryManagementClient
  File "/home/srout104/.azure/cliextensions/datafactory/azext_datafactory/vendored_sdks/datafactory/__init__.py", line 9, in <module>
    from ._data_factory_management_client import DataFactoryManagementClient
  File "/home/srout104/.azure/cliextensions/datafactory/azext_datafactory/vendored_sdks/datafactory/_data_factory_management_client.py", line 19, in <module>
    from .operations import ActivityRunsOperations, DataFlowDebugSessionOperations, DataFlowsOperations, DatasetsOperations, ExposureControlOperations, FactoriesOperations, GlobalParametersOperations, IntegrationRuntimeNodesOperations, IntegrationRuntimeObjectMetadataOperations, IntegrationRuntimesOperations, LinkedServicesOperations, ManagedPrivateEndpointsOperations, ManagedVirtualNetworksOperations, Operations, PipelineRunsOperations, PipelinesOperations, PrivateEndPointConnectionsOperations, PrivateEndpointConnectionOperations, PrivateLinkResourcesOperations, TriggerRunsOperations, TriggersOperations
  File "/home/srout104/.azure/cliextensions/datafactory/azext_datafactory/vendored_sdks/datafactory/operations/__init__.py", line 9, in <module>
    from ._operations import Operations
  File "/home/srout104/.azure/cliextensions/datafactory/azext_datafactory/vendored_sdks/datafactory/operations/_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datafactory trigger list --factory-name {} --resource-group {} --query {} -o {} --only-show-errors`

## Environment Summary
```
Linux-4.18.0-372.16.1.el8_6.x86_64-x86_64-with-redhat-8.6-Ootpa, Red Hat Enterprise Linux 8.6 (Ootpa)
Python 3.6.8
Installer: RPM

azure-cli 2.37.0 *

Extensions:
datafactory 0.6.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by SaurabhSharma-MSFT** [comment]
@sauravrout I am not able to reproduce this.  Can you please try upgrading your [Azure CLI version]( https://learn.microsoft.com/en-us/cli/azure/update-azure-cli).

**Comment by sauravrout** [comment]
> @sauravrout I am not able to reproduce this. Can you please try upgrading your [Azure CLI version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli).

Yes, upgrading the az cli fixed the issue.
