### ISSUE TITLE
containerapp revision copy fails when --from-revision is used

### ISSUE THREAD

**Issue by yasseryehya** [Azure/azure-cli-extensions#5435]
## Description

**Command Name**
`az containerapp revision copy
Extension Name: containerapp. Version: 0.3.11.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/yasser/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/yasser/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 1515, in copy_revision
    return update_containerapp_logic(cmd=cmd,
  File "/home/yasser/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 782, in update_containerapp_logic
    new_containerapp["properties"]["template"]["scale"].pop(["rules"])
TypeError: unhashable type: 'list'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp revision copy --name {} --resource-group {} --revision-suffix {} --scale-rule-name {} --scale-rule-type {} --scale-rule-auth {} --scale-rule-metadata {} {} --set-env-vars {} --from-revision {}`

## Environment Summary
```
Linux-5.18.18-200.fc36.x86_64-x86_64-with-glibc2.35, Fedora Linux 36 (Workstation Edition)
Python 3.9.14
Installer: RPM

azure-cli 2.40.0

Extensions:
containerapp 0.3.11

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team
