### ISSUE TITLE
Mycli error when attempting "az mysql flexible-server connect --interactive"

### ISSUE THREAD

**Issue by juranosaurustechs** [Azure/azure-cli-extensions#5475]
## Describe the bug

**Command Name**
`az mysql flexible-server connect --interactive
Extension Name: rdbms-connect. Version: 1.0.3.`

**Errors:**
```
mysql 8.0.15
mycli 1.22.2
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net/
Thanks to the contributor - Matheus Rosa
Traceback (most recent call last):
  File "/home/adam/.azure/cliextensions/rdbms-connect/bin/mycli", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib64/az/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/az/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/az/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/mycli/main.py", line 1209, in cli
    mycli.run_cli()
  File "/usr/lib64/az/lib/python3.9/site-packages/mycli/main.py", line 732, in run_cli
    reserve_space_for_menu=self.get_reserved_space(),
  File "/usr/lib64/az/lib/python3.9/site-packages/mycli/main.py", line 980, in get_reserved_space
    _, height = click.get_terminal_size()
AttributeError: module 'click' has no attribute 'get_terminal_size'```

## To Reproduce:
- _Put any pre-requisite steps here..._
- `az mysql flexible-server connect -n {} -u {} -p {} -d {} --interactive`

## Expected Behavior
That I'd be logged into mysql via mycli. Note that mycli is still on version 1.22.2 and it seems [bug](https://github.com/dbcli/mycli/pull/1042) was fixed on March 30, 2022 and [tag 1.24.4](https://github.com/dbcli/mycli/tree/v1.24.4) was made the same day. I would expect that upgrading mycli to a tag more recent than 1.24.4 would resolve this.

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.41.0

Extensions:
rdbms-connect 1.0.3
ai-examples 0.2.5
ml 2.10.0
ssh 1.1.2

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by yonzhan** [comment]
route to CXP team

**Comment by alanenriqueo** [comment]
Hi @juranosaurustechs, can we try upgrading to rdbms-connect 1.0.4 please?

**Comment by juranosaurustechs** [comment]
@alanenriqueo thank you! That did the trick!!

To save the next person the trouble of looking up the command, it's:
`az extension update -n rdbms-connect`

If no one objects, I'll close the issue.
