### ISSUE TITLE
'Memory Error' When trying to Query Log Analytics Space Using az monitor log-analytics query

### ISSUE THREAD

**Issue by victorebhojie** [Azure/azure-cli-extensions#5479]
## Describe the bug

**Command Name**
`az monitor log-analytics query
Extension Name: log-analytics. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 239, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 146, in out
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 37, in format_json
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 201, in encode
MemoryError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Having a Log analytics Resource with data
- `az monitor log-analytics query --workspace {} --analytics-query {}`

## Expected Behavior
Return the result of the embedded Kusto Query
## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
log-analytics 0.2.2
log-analytics-solution 0.1.1

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by AllyW** [comment]
Hi, @victorebhojie, the `MemoryError` raised from "json\encoder.py" seems to be related to the scale of the large data you pulled from azure service. A more reasonable logs being checked with parameters, like shorten the timespan queried, would avoid this issue, I assume.
