### ISSUE TITLE
Unable to establish SSH Tunnel using WebApp extension for an ASE (App Service Environment)

### ISSUE THREAD

**Issue by Welasco** [Azure/azure-cli-extensions#550]
### Extension name WebApp

Command used to install:
```bash
$ az extension add -n webapp
```

### Description of issue (in as much detail as possible)

-----

Unable to establish a SSH tunnel remote session against to a ASE (App Service Environment)

Error Message:
```
C:\>az webapp remote-connection create --resource-group RG-Name -n webappname -p 2222
Port 2222 is open
HTTPSConnectionPool(host='webappname.scm.cssilbasev2.com', port=443): Max retries exceeded with url: /api/settings (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\contrib\pyopenssl.py", line 453, in wrap_socket
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\pyOpenSSL\OpenSSL\SSL.py", line 1915, in do_handshake
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\pyOpenSSL\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\pyOpenSSL\OpenSSL\_util.py", line 54, in exception_from_error_queue
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connection.py", line 344, in connect
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\contrib\pyopenssl.py", line 459, in wrap_socket
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\util\retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webappname.scm.cssilbasev2.com', port=443): Max retries exceeded with url: /api/settings (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 386, in _run_jobs_serially
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\six\six.py", line 693, in reraise
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 356, in _run_job
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\azure-cli-core\azure\cli\core\__init__.py", line 452, in default_command_handler
  File "C:\Users\user\.azure\cliextensions\webapp\azext_webapp\custom.py", line 264, in create_tunnel
    _ping_scm_site(cmd, resource_group_name, name)
  File "C:\Users\user\.azure\cliextensions\webapp\azext_webapp\custom.py", line 228, in _ping_scm_site
    requests.get(scm_url + '/api/settings', headers=authorization)
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\api.py", line 75, in get
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\api.py", line 60, in request
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\requests\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='webappname.scm.cssilbasev2.com', port=443): Max retries exceeded with url: /api/settings (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

In order to workaround the first problem I changed this peace of code at custom.py from WebApp extension as follow:

## master/src/webapp/azext_webapp/custom.py

Original Code starting at line 220:
```python
def _ping_scm_site(cmd, resource_group, name):
    #  wakeup kudu, by making an SCM call
    import requests
    #  work around until the timeout limits issue for linux is investigated & fixed
    user_name, password = _get_site_credential(cmd.cli_ctx, resource_group, name)
    scm_url = _get_scm_url(cmd, resource_group, name)
    import urllib3
    authorization = urllib3.util.make_headers(basic_auth='{}:{}'.format(user_name, password))
    requests.get(scm_url + '/api/settings', headers=authorization)
```

Proposed change:
```python
def _ping_scm_site(cmd, resource_group, name):
    #  wakeup kudu, by making an SCM call
    import requests
    #  work around until the timeout limits issue for linux is investigated & fixed
    user_name, password = _get_site_credential(cmd.cli_ctx, resource_group, name)
    scm_url = _get_scm_url(cmd, resource_group, name)
    import urllib3
    authorization = urllib3.util.make_headers(basic_auth='{}:{}'.format(user_name, password))
    # Avoiding SSL Check for ASE environment (Self Signed Certificate) 
    if ".scm.azurewebsites.net" not in scm_url:
        requests.get(scm_url + '/api/settings', headers=authorization, verify=False)
    else:
        requests.get(scm_url + '/api/settings', headers=authorization)
```

After this change I start receiving the following error:

```bash
C:\Users\user>az webapp remote-connection create --subscription  --resource-group RG-Name -n webappname -p 2222
Port 2222 is open
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\util\connection.py", line 57, in create_connection
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connection.py", line 301, in connect
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x061EEF30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\victor\.azure\cliextensions\webapp\azext_webapp\custom.py", line 277, in _start_tunnel
    if not _check_for_ready_tunnel(remote_debugging_enabled, tunnel_server):
  File "C:\Users\victor\.azure\cliextensions\webapp\azext_webapp\custom.py", line 237, in _check_for_ready_tunnel
    default_port = tunnel_server.is_port_set_to_default()
  File "C:\Users\victor\.azure\cliextensions\webapp\azext_webapp\tunnel.py", line 92, in is_port_set_to_default
    preload_content=False
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\request.py", line 68, in request
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\request.py", line 89, in request_encode_url
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\poolmanager.py", line 323, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 667, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 667, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 667, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\util\retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webappname.scm.azurewebsites.net', port=443): Max retries exceeded with url: /AppServiceTunnel/Tunnel.ashx?GetStatus (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x061EEF30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

From the log above I found it was going to a public (multi tenant) Azure WebApp **.scm.azurewebsite.net** instead of a ASE URL:

```log
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\urllib3\urllib3\util\retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webappname.scm.azurewebsites.net', port=443): Max retries exceeded with url: /AppServiceTunnel/Tunnel.ashx?GetStatus (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x061EEF30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

Reviewing the code at master/src/webapp/azext_webapp/tunnel.py I found it was hardcoded at line 87 and 112:

Original Code starting at line 76:

```python
    def is_port_set_to_default(self):
        import certifi
        import urllib3
        try:
            import urllib3.contrib.pyopenssl
            urllib3.contrib.pyopenssl.inject_into_urllib3()
        except ImportError:
            pass

        http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
        headers = urllib3.util.make_headers(basic_auth='{0}:{1}'.format(self.remote_user_name, self.remote_password))
        url = 'https://{}{}'.format(self.remote_addr, '.scm.azurewebsites.net/AppServiceTunnel/Tunnel.ashx?GetStatus')
        r = http.request(
            'GET',
            url,
            headers=headers,
            preload_content=False
        )
        if r.status != 200:
            raise CLIError("Failed to connect to '{}' with status code '{}' and reason '{}'".format(
                url, r.status, r.reason))
        msg = r.read().decode('utf-8')
        logger.info('Status response message: %s', msg)
        if 'FAIL' in msg.upper():
            logger.warning('WARNING - Remote debugging may not be setup properly. Reponse content: %s', msg)
        if '2222' in msg:
            return True
        return False
```

Original Code starting at line 105:
```python
    def _listen(self):
        self.sock.listen(100)
        index = 0
        basic_auth_string = self.create_basic_auth()
        while True:
            self.client, _address = self.sock.accept()
            self.client.settimeout(1800)
            host = 'wss://{}{}'.format(self.remote_addr, '.scm.azurewebsites.net/AppServiceTunnel/Tunnel.ashx')
            basic_auth_header = 'Authorization: Basic {}'.format(basic_auth_string)
            cli_logger = get_logger()  # get CLI logger which has the level set through command lines
            is_verbose = any(handler.level <= logs.INFO for handler in cli_logger.handlers)
            if is_verbose:
                logger.info('Websocket tracing enabled')
                websocket.enableTrace(True)
            else:
                logger.warning('Websocket tracing disabled, use --verbose flag to enable')
                websocket.enableTrace(False)
            self.ws = create_connection(host,
                                        sockopt=((socket.IPPROTO_TCP, socket.TCP_NODELAY, 1),),
                                        class_=TunnelWebSocket,
                                        header=[basic_auth_header],
                                        sslopt={'cert_reqs': ssl.CERT_NONE},
                                        enable_multithread=True)
            logger.info('Websocket, connected status: %s', self.ws.connected)
            index = index + 1
            logger.info('Got debugger connection... index: %s', index)
            debugger_thread = Thread(target=self._listen_to_client, args=(self.client, self.ws, index))
            web_socket_thread = Thread(target=self._listen_to_web_socket, args=(self.client, self.ws, index))
            debugger_thread.start()
            web_socket_thread.start()
            logger.info('Both debugger and websocket threads started...')
            logger.warning('Successfully connected to local server..')
            debugger_thread.join()
            web_socket_thread.join()
            logger.info('Both debugger and websocket threads stopped...')
            logger.warning('Stopped local server..')
```

In order to workaround the problem I changed both methods above and the constructor of the class to use the ASE WebApp SCM URL and avoid SSL check for ASE since it uses SelfSigned certificate.
I also changed the **master/src/webapp/azext_webapp/custom.py** where it was invoking **TunnelServer**

Method **create_tunnel** at **master/src/webapp/azext_webapp/custom.py**:
```python
def create_tunnel(cmd, resource_group_name, name, port=None, slot=None):
    webapp = show_webapp(cmd, resource_group_name, name, slot)
    is_linux = webapp.reserved
    if not is_linux:
        logger.error("Only Linux App Service Plans supported, Found a Windows App Service Plan")
        return
    import time
    profiles = list_publish_profiles(cmd, resource_group_name, name, slot)
    user_name = next(p['userName'] for p in profiles)
    user_password = next(p['userPWD'] for p in profiles)
    import threading
    from .tunnel import TunnelServer

    if port is None:
        port = 0  # Will auto-select a free port from 1024-65535
        logger.info('No port defined, creating on random free port')
    host_name = name
    if slot is not None:
        host_name += "-" + slot
    scm_url = _get_scm_url(cmd, resource_group_name, name)
    tunnel_server = TunnelServer('', port, host_name, user_name, user_password, scm_url)
    config = get_site_configs(cmd, resource_group_name, name, slot)
    _ping_scm_site(cmd, resource_group_name, name)

    t = threading.Thread(target=_start_tunnel, args=(tunnel_server, config.remote_debugging_enabled))
    t.daemon = True
    t.start()

    # Wait indefinitely for CTRL-C
    while True:
        time.sleep(5)
```

Constructor at **master/src/webapp/azext_webapp/tunnel.py**:
```python
    def __init__(self, local_addr, local_port, remote_addr, remote_user_name, remote_password, remote_scm_url):
        self.local_addr = local_addr
        self.local_port = local_port
        if self.local_port != 0 and not self.is_port_open():
            raise CLIError('Defined port is currently unavailable')
        self.remote_addr = remote_addr
        self.remote_user_name = remote_user_name
        self.remote_password = remote_password
        self.client = None
        self.ws = None
        self.remote_scm_url = remote_scm_url
        logger.info('Creating a socket on port: %s', self.local_port)
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        logger.info('Setting socket options')
        self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        logger.info('Binding to socket on local address and port')
        self.sock.bind((self.local_addr, self.local_port))
        if self.local_port == 0:
            self.local_port = self.sock.getsockname()[1]
            logger.warning('Auto-selecting port: %s', self.local_port)
        logger.info('Finished initialization')
```

Method **is_port_set_to_default** at **master/src/webapp/azext_webapp/tunnel.py**:
```python
    def is_port_set_to_default(self):
        import certifi
        import urllib3
        try:
            import urllib3.contrib.pyopenssl
            urllib3.contrib.pyopenssl.inject_into_urllib3()
        except ImportError:
            pass

        # Avoiding SSL Check for ASE environment (Self Signed Certificate) 
        if ".scm.azurewebsites.net" not in self.remote_scm_url:
            http = urllib3.PoolManager(cert_reqs='CERT_NONE', assert_hostname=False)
        else:
            http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())

        headers = urllib3.util.make_headers(basic_auth='{0}:{1}'.format(self.remote_user_name, self.remote_password))
        url = '{}{}'.format(self.remote_scm_url, '/AppServiceTunnel/Tunnel.ashx?GetStatus')
        r = http.request(
            'GET',
            url,
            headers=headers,
            preload_content=False
        )
        if r.status != 200:
            raise CLIError("Failed to connect to '{}' with status code '{}' and reason '{}'".format(
                url, r.status, r.reason))
        msg = r.read().decode('utf-8')
        logger.info('Status response message: %s', msg)
        if 'FAIL' in msg.upper():
            logger.warning('WARNING - Remote debugging may not be setup properly. Reponse content: %s', msg)
        if '2222' in msg:
            return True
        return False
```

Method **_listen** at **master/src/webapp/azext_webapp/tunnel.py**:
```python
    def _listen(self):
        self.sock.listen(100)
        index = 0
        basic_auth_string = self.create_basic_auth()
        while True:
            self.client, _address = self.sock.accept()
            self.client.settimeout(1800)
            host = '{}{}'.format(self.remote_scm_url.replace("https://","wss://"), '/AppServiceTunnel/Tunnel.ashx')
            basic_auth_header = 'Authorization: Basic {}'.format(basic_auth_string)
            cli_logger = get_logger()  # get CLI logger which has the level set through command lines
            is_verbose = any(handler.level <= logs.INFO for handler in cli_logger.handlers)
            if is_verbose:
                logger.info('Websocket tracing enabled')
                websocket.enableTrace(True)
            else:
                logger.warning('Websocket tracing disabled, use --verbose flag to enable')
                websocket.enableTrace(False)
            self.ws = create_connection(host,
                                        sockopt=((socket.IPPROTO_TCP, socket.TCP_NODELAY, 1),),
                                        class_=TunnelWebSocket,
                                        header=[basic_auth_header],
                                        sslopt={'cert_reqs': ssl.CERT_NONE},
                                        enable_multithread=True)
            logger.info('Websocket, connected status: %s', self.ws.connected)
            index = index + 1
            logger.info('Got debugger connection... index: %s', index)
            debugger_thread = Thread(target=self._listen_to_client, args=(self.client, self.ws, index))
            web_socket_thread = Thread(target=self._listen_to_web_socket, args=(self.client, self.ws, index))
            debugger_thread.start()
            web_socket_thread.start()
            logger.info('Both debugger and websocket threads started...')
            logger.warning('Successfully connected to local server..')
            debugger_thread.join()
            web_socket_thread.join()
            logger.info('Both debugger and websocket threads stopped...')
            logger.warning('Stopped local server..')
```

After those changes worked fine.

In order to test just replace both attached files under your extension installation folder like:

Windows:

    C:\Users\user\.azure\cliextensions\webapp\azext_webapp

Mac:

    '/Users/user/.azure/cliextensions/webapp/azext_webapp/

[webapp-extension.zip](https://github.com/Azure/azure-cli-extensions/files/2921466/webapp-extension.zip)

**Comment by mehmetkut** [comment]
Hello, 

Thanks @williexu for your great patch.

I really don't understand how Microsoft ignore ASE for such a cruical work.

I also patched the code for working properly with slots.

You can download patched zip file.

[azext_webapp_ase_with_slots.zip](https://github.com/Azure/azure-cli-extensions/files/2978614/azext_webapp_ase_with_slots.zip)

**Comment by panchagnula** [comment]
this issue should now be fixed & is also moved to core as preview please use that https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-ssh

**Comment by PrakashLakhara** [comment]
Hi, 
I have a different error. I can't connect to webapp ssh via azure cli.
Error is: **Verifying if the app is running....
App is running. Trying to establish tunnel connection...**

It does not connect after that. 
Website is running fine and webapp ssh was working. But when I installed new ubuntu 20 LTS II am facing this problem.
**Operating system details:**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
