### ISSUE TITLE
commands erroring out

### ISSUE THREAD

**Issue by ewagner14-cscc** [Azure/azure-cli-extensions#5508]
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.94.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/opt/az/lib/python3.10/site-packages/azure/core/utils/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/home/comrit-vm-admin/.azure/cliextensions/aks-preview/azext_aks_preview/_client_factory.py", line 31, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/home/comrit-vm-admin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/_container_service_client.py", line 642, in managed_clusters
    from .v2022_07_02_preview.operations import ManagedClustersOperations as OperationClass
  File "/home/comrit-vm-admin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "/home/comrit-vm-admin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "/home/comrit-vm-admin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/__init__.py", line 9, in <module>
    from ._operations import Operations
  File "/home/comrit-vm-admin/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/opt/az/lib/python3.10/site-packages/azure/core/utils/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -g {} -n {} --enable-azure-rbac`

## Environment Summary
```
Linux-5.13.0-1028-azure-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0 *

Extensions:
aks-preview 0.5.94

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ewagner14-cscc Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ewagner14-cscc I see that you are using an older version of `aks-preview `extension. Could you please update it to the most recent version and test the command again ?

> az extension update -n aks-preview

On a side note, also update your Azure CLI to the [most recent version.](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) Hope this helps.

**Comment by navba-MSFT** [comment]
@ewagner14-cscc I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ewagner14-cscc The action is currently pending on you to update your` aks-preview` extension and run the AzCLI command again.  If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
