### ISSUE TITLE
Cannot show logs of container apps from Azure CLI

### ISSUE THREAD

**Issue by beohoang98** [Azure/azure-cli-extensions#5518]
## Describe the bug

**Command Name**
`az containerapp logs show
Extension Name: containerapp. Version: 0.3.13.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'logStreamEndpoint'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/home/beohoang98/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2478, in stream_containerapp_logs
    logstream_endpoint = token_response["properties"]["logStreamEndpoint"]
KeyError: 'logStreamEndpoint'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp logs show -n {}`

## Environment Summary
```
Linux-5.15.0-52-generic-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0 *

Extensions:
deploy-to-azure 0.2.0
containerapp 0.3.13

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@beohoang98  Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@samavos @beohoang98 I am able to reproduce this issue at my end. We are looking into this further. We will get back to you once we have more details.

**Comment by StrawnSC** [comment]
I have a PR in review to fix this: https://github.com/Azure/azure-cli-extensions/pull/5527

**Comment by navba-MSFT** [comment]
@beohoang98 The above PR ( https://github.com/Azure/azure-cli-extensions/pull/5527 )  has been merged now. The fix will be released as part of this milestone https://github.com/Azure/azure-cli-extensions/milestone/73
