### ISSUE TITLE
Preview Feature | Update SSH key on an existing AKS cluster (preview) | Not working

### ISSUE THREAD

**Issue by NitroAMD** [Azure/azure-cli-extensions#5559]
## Describe the bug
Following the steps outlined in the Microsoft Learning Docs for updating the SSH keys on VMSS (AKS) is erroring out (see below):
https://learn.microsoft.com/en-us/azure/aks/node-access#update-ssh-key-on-an-existing-aks-cluster-preview

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.115.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'ssh'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/namepii/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 832, in aks_update
    mc = aks_update_decorator.update_mc_profile_preview()
  File "/home/namepii/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3227, in update_mc_profile_preview
    mc = self.update_linux_profile(mc)
  File "/home/namepii/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3179, in update_linux_profile
    mc.linux_profile.ssh = self.models.ContainerServiceSshConfiguration(
AttributeError: 'NoneType' object has no attribute 'ssh'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -g {} -n {} --ssh-key-value {}`

## Expected Behavior
https://learn.microsoft.com/en-us/azure/aks/node-access#update-ssh-key-on-an-existing-aks-cluster-preview

## Environment Summary
```
Linux-5.15.74.2-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.42.0

Extensions:
aks-preview 0.5.115

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@NitroAMD Apologies for the late reply. Thanks for reaching out to us and reporting this issue. https://github.com/Azure/azure-cli-extensions/pull/5562 PR was filed to fix this issue. This PR is now merged. Fix will be released as a part of this milestone https://github.com/Azure/azure-cli-extensions/milestone/73
