### ISSUE TITLE
No module named 'azure.communication'

### ISSUE THREAD

**Issue by vipinsainiJT** [Azure/azure-cli-extensions#5570]
## Describe the bug

**Command Name**
`az communication identity user create
Extension Name: communication. Version: 1.3.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.communication'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/officespace/.azure/cliextensions/communication/azext_communication/manual/_client_factory.py", line 13, in cf_communication_identity
    from azure.communication.identity import CommunicationIdentityClient
ModuleNotFoundError: No module named 'azure.communication'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az communication identity user create --connection-string {}`

## Environment Summary
```
macOS-13.0.1-arm64-arm-64bit, Darwin 22.1.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.42.0

Extensions:
communication 1.3.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@vipinsainiJT I believe this is likely caused by an installation issue. Could you try the steps mentioned here in the [official docs](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos#unable-to-find-python-or-installed-packages) and/or try reinstalling Azure CLI?

Here are the same for reference

```sh
brew update && brew install python@3.10 && brew upgrade python@3.10
brew link --overwrite python@3.10
```
