### ISSUE TITLE
container app log stream broken

### ISSUE THREAD

**Issue by charlesavos** [Azure/azure-cli-extensions#5574]
## Describe the bug

**Command Name**
`az containerapp logs show
Extension Name: containerapp. Version: 0.3.13.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'logStreamEndpoint'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/home/charlie/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2478, in stream_containerapp_logs
    logstream_endpoint = token_response["properties"]["logStreamEndpoint"]
KeyError: 'logStreamEndpoint'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp logs show -g {} -n {}`

## Environment Summary
```
Linux-5.15.0-52-generic-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.42.0

Extensions:
containerapp 0.3.13
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@charlesavos Thank you for reaching out to us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@charlesavos Can you please upgrade to the latest version of containerapp 0.3.16 and retry? it works

![image](https://user-images.githubusercontent.com/49954584/204242858-f33bfbc9-a65c-4771-8959-4cd6b1ba8cc1.png)
