### ISSUE TITLE
az k8s-extension create not working for --cluster-type managedClusters

### ISSUE THREAD

**Issue by MichalKosowski** [Azure/azure-cli-extensions#5581]
### Related command
az k8s-extension create --cluster-type managedClusters --cluster-name clusterName --resource-group resourceGroupName --name dapr --extension-type Microsoft.Dapr

### Extension name (the extension in question)
k8s-extension

### Description of issue (in as much detail as possible)
I am following guidelines [here (MS Docs)](https://learn.microsoft.com/en-us/azure/aks/dapr) and [here (Dapr docs)](https://docs.dapr.io/developing-applications/integrations/azure/azure-kubernetes-service-extension/). I have the latest version of extension installed (as of 27.11.2022

When I try to run above command to instal Dapr extension to my AKS cluster, I am getting below error:

```
Command group 'k8s-extension' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
InvalidArgumentValueError: Error! Cluster type 'managedClusters' is not supported
```

I can't progress further with that. The `--debug` output is:

```cli.knack.cli: Command arguments: ['k8s-extension', 'create', '--cluster-type', 'managedClusters', '--cluster-name', 'clusterName', '--resource-group', 'rgName', '--name', 'dapr', '--extension-type', 'Microsoft.Dapr', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0323BAE0>, <function OutputProducer.on_global_arguments at 0x0338FF60>, <function CLIQuery.on_global_arguments at 0x033F0ED0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'k8s-extension': ['azext_k8s_extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: k8s-extension             0.005         1         4  C:\Users\micha\.azure\cliextensions\k8s-extension
cli.azure.cli.core: Total (1)                 0.005         1         4
cli.azure.cli.core: Loaded 1 groups, 4 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : k8s-extension create
cli.azure.cli.core: Command table: k8s-extension create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0361B0C0>]
az_command_data_logger: command args: k8s-extension create --cluster-type {} --cluster-name {} --resource-group {} --name {} --extension-type {} --debug
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\micha\.azure\commands'.
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03672A08>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x03686198>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x036861E0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03686270>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0338FFA8>, <function CLIQuery.handle_query_parameter at 0x033F0F18>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x03686150>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03686228>]
az_command_data_logger: extension name: k8s-extension
az_command_data_logger: extension version: 0.4.1
Command group 'k8s-extension' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SourceControlConfigurationClient
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': '3d1ae4d2-6e8e-11ed-9121-34cff605595a'
cli.azure.cli.core.commands.client_factory:     'CommandName': 'k8s-extension create'
cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '--cluster-type --cluster-name --resource-group --name --extension-type --debug'
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 659, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 722, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 715, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-s5x_2dzp\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 693, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 330, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\__init__.py", line 786, in default_command_handler
  File "C:\Users\micha\.azure\cliextensions\k8s-extension\azext_k8s_extension\custom.py", line 86, in create_k8s_extension
    cluster_rp = __get_cluster_rp(cluster_type)
  File "C:\Users\micha\.azure\cliextensions\k8s-extension\azext_k8s_extension\custom.py", line 246, in __get_cluster_rp
    raise InvalidArgumentValueError("Error! Cluster type '{}' is not supported".format(cluster_type))
azure.cli.core.azclierror.InvalidArgumentValueError: Error! Cluster type 'managedClusters' is not supported

cli.azure.cli.core.azclierror: InvalidArgumentValueError: Error! Cluster type 'managedClusters' is not supported
cli.azure.cli.core.azclierror: InvalidArgumentValueError: Error! Cluster type 'managedClusters' is not supported
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0361B1E0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.695 seconds (init: 0.120, invoke: 0.575)
telemetry.save: Save telemetry record of length 3182 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\micha\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by MichalKosowski** [comment]
ok, I tested it again on a different machine (I am using laptop and PC) and on PC I am still heaving the first bug (originally reported) while on laptop it is working fine but then failing on finding a feasible region. I will appreciate any assistance.... :(

**Comment by RakeshMohanMSFT** [comment]
@MichalKosowski Can you please run az version in both the machines (laptop and PC) and see if there is any difference in the Az CLI Version and k8s-extension extension?

**Comment by MichalKosowski** [comment]
hi, yes, there was a difference in the version. I update everything, AZ CLI and k8s extension to the newest version and now everything is working. No issues with the region or cluster-type errors.
