### ISSUE TITLE
az monitor data-collection rule association list: FAILURE.

### ISSUE THREAD

**Issue by pejuborg** [Azure/azure-cli-extensions#5621]
## Describe the bug

**Command Name**
`az monitor data-collection rule association list
Extension Name: monitor-control-service. Version: 0.3.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/pejub/.azure/cliextensions/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rule_associations_operations.py", line 104, in get_next
    request = prepare_request(next_link)
  File "/home/pejub/.azure/cliextensions/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rule_associations_operations.py", line 82, in prepare_request
    'resourceUri': self._serialize.url("resource_uri", resource_uri, 'str', skip_quote=True, min_length=1),
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 652, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 760, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor data-collection rule association list`

## Expected Behavior
Get a list of data collection rule associations

## Environment Summary
```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.43.0

Extensions:
monitor-control-service 0.3.0
connectedmachine 0.5.1
resource-graph 2.1.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by AllyW** [comment]
@pejuborg please refer to https://github.com/Azure/azure-cli-extensions/issues/6431.
