### ISSUE TITLE
Builds failing for PRs

### ISSUE THREAD

**Issue by kevinhillinger** [Azure/azure-cli-extensions#5623]
PR's are failing their builds including the one I submitted #5611 with an error in the build check:

```bash
======================================================================
ERROR: test_ref_doc_vmware (__main__.IndexRefDocs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/vss/_work/1/s/./scripts/ci/index_ref_doc.py", line 65, in test
    raise e
  File "/mnt/vss/_work/1/s/./scripts/ci/index_ref_doc.py", line 62, in test
    check_call(script_args)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.10.8/x64/bin/python', '/mnt/vss/_work/1/s/scripts/refdoc/generate.py', '--extension-file', '/tmp/tmp8g__583j/vmware-5.0.0-py2.py3-none-any.whl', '--output-dir', '/tmp/tmp2rbu5pnn/vmware']' returned non-zero exit status 1.
```

**Comment by wangzelin007** [comment]
resloved.
