### ISSUE TITLE
Azure CLI Break to update AKS State.

### ISSUE THREAD

**Issue by sreedharbukya** [Azure/azure-cli-extensions#5659]
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.55.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.command_modules.acs.decorator'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/sreedhar/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 845, in aks_update
    from azure.cli.command_modules.acs.decorator import AKSParamDict
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {}`

## Environment Summary
```
macOS-13.1-arm64-arm-64bit, Darwin 22.2.0
Python 3.10.9
Installer: HOMEBREW

azure-cli 2.43.0

Extensions:
aks-preview 0.5.55
account 0.2.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@sreedharbukya Please let us know if you are still having issues.

**Comment by SaurabhSharma-MSFT** [comment]
@sreedharbukya We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
