### ISSUE TITLE
Getting error when updating auto secret rotation after creation of AKS cluster

### ISSUE THREAD

**Issue by kshitijcode** [Azure/azure-cli-extensions#5661]
## Describe the bug

Getting error when updating auto secret rotation after the creation of AKS cluster through az cli. It however works if we do it through terraform. 

**Command Name**
`az aks addon update
Extension Name: aks-preview. Version: 0.5.94.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/core/utils/__init__.py)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/_client_factory.py", line 31, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/_container_service_client.py", line 642, in managed_clusters
    from .v2022_07_02_preview.operations import ManagedClustersOperations as OperationClass
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/__init__.py", line 9, in <module>
    from ._operations import Operations
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/core/utils/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks addon update -g {} -n {} -a {} --enable-secret-rotation`

## Environment Summary
```
macOS-13.1-x86_64-i386-64bit, Darwin 22.2.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.37.0

Extensions:
connectedk8s 1.2.7
k8s-extension 1.0.4
aks-preview 0.5.94
ml 2.0.1a4

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@kshitijcode Thanks for reaching out to us and reporting this issue. I see that you are using an older version of` aks-preview` extension. Could you please update your extension by running the below command and test again ?

> **az extension update -n aks-preview**

Hope this helps.

**Comment by kshitijcode** [comment]
When I run the command I get 
`❯ az extension update -n aks-preview
No updates available for 'aks-preview'. Use --debug for more information`

**Comment by navba-MSFT** [comment]
@kshitijcode Thanks for getting back. Could you please remove `aks-preview` extension and install it again ? Below are the commands that you can run:

> **az extension remove -n aks-preview**

> **az extension add -n aks-preview**

**Comment by kshitijcode** [comment]
I get the same error @navba-MSFT 

`❯ az aks enable-addons --addons azure-keyvault-secrets-provider --name  aks-cluster-enabled --resource-group aks-playground
The behavior of this command has been altered by the following extension: aks-preview
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/core/utils/__init__.py)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/_client_factory.py", line 31, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/_container_service_client.py", line 642, in managed_clusters
    from .v2022_07_02_preview.operations import ManagedClustersOperations as OperationClass
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/__init__.py", line 9, in <module>
    from ._operations import Operations
  File "/Users/sharmaks/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/usr/local/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/core/utils/__init__.py)
To open an issue, please run: 'az feedback'`

**Comment by navba-MSFT** [comment]
@kshitijcode Thanks for getting back with the details. I see that you are using an older version of the Azure CLI. Please upgrade to the [most recent version of Azure CLI ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)and that should help.

**Comment by kshitijcode** [comment]
Updating aks-preview extension resolved the issue.
