### ISSUE TITLE
az containerapp hostname bind stopped working at 2022-12-15

### ISSUE THREAD

**Issue by stefanj78** [Azure/azure-cli-extensions#5673]
## Describe the bug

**Command Name**
`az containerapp hostname bind
Extension Name: containerapp. Version: 0.3.18.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\stefanj\.azure\cliextensions\containerapp\azext_containerapp\_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\stefanj\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 2884, in bind_hostname
    new_custom_domains = list(filter(lambda c: c["name"] != hostname, custom_domains))
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:

az containerapp hostname bind \
          --name berikarwebapp \
          --resource-group rg-berikar-test \
          --environment env-berikar-test \
          --hostname test.berikar.se \
          --certificate cert-test.berikar.se

## Expected Behavior

It should work to bind to the host name which worked before 2022-12-15.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0 *

Extensions:
containerapp 0.3.18

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by navba-MSFT** [comment]
@stefanj78 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by stefanj78** [comment]
Same error when running locally on Windows as from a unix azure pipeline (Image: ubuntu-22.04, Version: 20221212.1).

**Comment by navba-MSFT** [comment]
@stefanj78 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by stefanj78** [comment]
Verified that it works using this version now:

az extension add -n containerapp --version 0.3.20

The 0.3.19 version did not work though.
