### ISSUE TITLE
not able to do az login

### ISSUE THREAD

**Issue by tharun-work** [Azure/azure-cli-extensions#5737]
## Describe the bug

**Command Name**
`az login
Extension Name: azure-ml-admin-cli. Version: 0.0.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
login() got an unexpected keyword argument 'msi'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\saidu\.azure\cliextensions\azure-ml-admin-cli\azext_admin\custom.py", line 82, in mls_login
    return login(username=username,
TypeError: login() got an unexpected keyword argument 'msi'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0

Extensions:
azure-ml-admin-cli 0.0.1

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Looks like the new extension `azure-ml-admin-cli` 0.0.1 doesn't call `login` correctly. Involving service team to check.

**Comment by paulshealy1** [comment]
`azure-ml-admin-cli` is part of Machine Learning Server, and support ended on July 1st, 2022:

https://learn.microsoft.com/en-us/machine-learning-server/what-is-happening-to-machine-learning-server
