### ISSUE TITLE
az containerapp create

### ISSUE THREAD

**Issue by ArcherHuang** [Azure/azure-cli-extensions#5738]
## Describe the bug

**Command Name**
`az containerapp create
Extension Name: containerapp. Version: 0.3.14.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/Users/archer/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/archer/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 572, in create_containerapp
    handle_raw_exception(e)
  File "/Users/archer/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "/Users/archer/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 562, in create_containerapp
    if "configuration" in r["properties"] and "ingress" in r["properties"]["configuration"] and "fqdn" in r["properties"]["configuration"]["ingress"]:
TypeError: argument of type 'NoneType' is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp create --name {} --resource-group {} --environment {} --registry-server {} --image {} --min-replicas {} --max-replicas {}`

## Environment Summary
```
macOS-13.0.1-arm64-arm-64bit, Darwin 22.1.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.41.0 *

Extensions:
azure-iot 0.18.3
containerapp 0.3.14
account 0.2.5

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by RakeshMohanMSFT** [comment]
@ArcherHuang We are unable to reproduce this issue at our end. Can you please upgrade your AZ CLI version to 2.43.0 and containerapp extension version to 0.3.20
![image](https://user-images.githubusercontent.com/49954584/211229653-3d36ee40-cbe0-4972-8d35-38506faa8207.png)
![image](https://user-images.githubusercontent.com/49954584/211229692-fa3f79d9-c206-45dd-a669-7ff68e69e647.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by ArcherHuang** [comment]
@RakeshMohanMSFT 
Successful execution after upgrade AZ CLI version to 2.43.0 and containerapp extension version to 0.3.20. 
Thanks
