### ISSUE TITLE
`PermissionError` occurs at the creating ACR task step when executing `az containerapp up` on Windows

### ISSUE THREAD

**Issue by horihiro** [Azure/azure-cli-extensions#5743]
## Describe the bug
When executing `az containerapp up` without Dockerfile on Windows OS, `PermissionError` occurs at the ACR task creation step.
It seems that temporary files cannot be accessed.
This issue can be reproduced on Windows Sandbox also.
 
**Command Name**
`az containerapp up
Extension Name: containerapp. Version: 0.3.20.`

**Errors:**
The following traceback was generated on Windows Sandbox.
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: 'C:\\Users\\WDAGUT~1\\AppData\\Local\\Temp\\tmpaa2d2k9z'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\containerapp\azext_containerapp\_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 2712, in containerapp_up
    app.run_acr_build(dockerfile, source, quiet=False, build_from_source=not _has_dockerfile(source, dockerfile))
  File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\containerapp\azext_containerapp\_up_utils.py", line 407, in run_acr_build
    self.build_container_from_source(image_name, source)
  File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\containerapp\azext_containerapp\_up_utils.py", line 375, in build_container_from_source
    acr_task_create(self.cmd, task_client, task_name, registry_name, context_path="/dev/null", file=task_file.name)
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/task.py", line 137, in acr_task_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/task.py", line 292, in create_task_step
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_utils.py", line 266, in get_yaml_template
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\WDAGUT~1\\AppData\\Local\\Temp\\tmpaa2d2k9z'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp up --name {} --source {} --ingress {}`

## Expected Behavior
The ACR task can be added.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.44.0

Extensions:
containerapp 0.3.20

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by horihiro** [comment]
In case of WSL, the same command is succeeded.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@horihiro Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@horihiro Could you please let me know if the issue occurs if you run the AzCLI from `cmd `prompt using admin mode ?

As per [this ](https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-up-examples)documentation for `--source` parameter:

> **Preview: If no Dockerfile is present, a container image is generated using Oryx. See the supported Oryx runtimes here: https://github.com/microsoft/Oryx/blob/main/doc/supportedRuntimeVersions.md.**

Please check if you are on the right supported platform and runtime versions:

> **The full list of supported platform versions for Oryx can be found [here](https://github.com/microsoft/Oryx/blob/main/doc/supportedPlatformVersions.md).**

**Comment by horihiro** [comment]
Even using admin mode for `cmd`, this issue still occurs, and updating Azure CLI to 2.44.1 cannot resolve this.

My app I tried to deploy is very simple PHP app. There is just one file `index.php`. 
![image](https://user-images.githubusercontent.com/4566555/211741468-fa2b4f24-515b-4d66-97dd-89b5a59d0f83.png)
And it was succeeded to deploy this app from WSL(Ubuntu 22.04) by executing the same command, as [I mentioned above](https://github.com/Azure/azure-cli-extensions/issues/5743#issuecomment-1378028241).

Can't you reproduce this issue by your Windows with AzureCLI@2.44.x and containerapp extension@0.3.20?

**Comment by horihiro** [comment]
Adding `delete=False` option to `NamedTemporaryFile` at [this line](https://github.com/Azure/azure-cli-extensions/blob/18d195af0446cb31fe2094db50a5e41fd5f8eb56/src/containerapp/azext_containerapp/_up_utils.py#L371) and manual tmp file deletion have possibility to resolve this issue like [this](https://github.com/bravoserver/bravo/issues/111).
