### ISSUE TITLE
Error executing az aks snapshot list or show

### ISSUE THREAD

**Issue by rohernan** [Azure/azure-cli-extensions#5787]
## Describe the bug

**Command Name**
`az aks snapshot list
Extension Name: aks-preview. Version: 0.5.94.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\utils\__init__.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\clar\.azure\cliextensions\aks-preview\azext_aks_preview\_client_factory.py", line 51, in cf_mc_snapshots
    return get_container_service_client(cli_ctx).managed_cluster_snapshots
  File "C:\Users\clar\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\_container_service_client.py", line 521, in managed_cluster_snapshots
    from .v2022_07_02_preview.operations import ManagedClusterSnapshotsOperations as OperationClass
  File "C:\Users\clar\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_07_02_preview\__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "C:\Users\clar\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_07_02_preview\_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "C:\Users\clar\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_07_02_preview\operations\__init__.py", line 9, in <module>
    from ._operations import Operations
  File "C:\Users\clar\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_07_02_preview\operations\_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\utils\__init__.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks snapshot list --resource-group {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *

Extensions:
account 0.2.1
aks-preview 0.5.94
storage-preview 0.8.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by PramodValavala-MSFT** [comment]
@rohernan Looks like you are using an outdated version of Azure CLI. Could you try upgrading to the latest by running `az upgrade` and try again?

**Comment by rohernan** [comment]
It was throwing the aks-preview as being the cause but the upgrade sorted it.

Thank you!

**Comment by PramodValavala-MSFT** [comment]
@rohernan Glad we could help! Closing.
