### ISSUE TITLE
extension anf-preview, 502 error creating an ANF account

### ISSUE THREAD

**Issue by garvct** [Azure/azure-cli-extensions#579]
### 502 Error creating an ANF account

When I run this script (to create an ANF account), I get a 502 error?
(Executed on ubuntu 16.04.2 LTS (Windows 10 Linux subsystem))

#!/bin/bash
#
#add ANF az cli extension
az extension add --name anf-preview

#Create ANF account
RG="cgnetapps2"
ANFACCNAME="cgnetappsacc"
LOCATION="eastus"
az anf account create --resource-group ${RG} -n ${ANFACCNAME} --location ${LOCATION}

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/f5a67d06-2d09-4090-91cc-e3298907a021/resourceGroups/cgnetapps2/providers/Microsoft.NetApp/netAppAccounts/cgnetappsacc?api-version=2017-08-15 (Caused by ResponseError('too many 502 error responses',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/f5a67d06-2d09-4090-91cc-e3298907a021/resourceGroups/cgnetapps2/providers/Microsoft.NetApp/netAppAccounts/cgnetappsacc?api-version=2017-08-15 (Caused by ResponseError('too many 502 error responses',))

Any ideas how to resolve this error?

Thanks.
-----

**Comment by garvct** [comment]
Seems to work now. Probably a temporary Azure portal issue and not related to a bug in the anf-preview extension. Will see if this error occurs on a regular basis, for now closing this issue.
