### ISSUE TITLE
--cluster-autoscaler-profile scale-down-unneeded-time COMMAND failed

### ISSUE THREAD

**Issue by Jacky-harmonicinc** [Azure/azure-cli-extensions#5790]
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.65.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.command_modules.acs.decorator'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/happybabyyj/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 889, in aks_update
    from azure.cli.command_modules.acs.decorator import AKSParamDict
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --subscription {} --cluster-autoscaler-profile {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.42.0 *

Extensions:
aks-preview 0.5.65

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@Jacky-harmonicinc Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@Jacky-harmonicinc We are unable to reproduce it with the latest version of az cli. Can you please upgrade to latest version and retry?
![image](https://user-images.githubusercontent.com/49954584/213403647-a2fa5e3b-1c8f-443b-9d6a-c65fc53ad42d.png)
