### ISSUE TITLE
storage blob upload failed in cli interactive mode

### ISSUE THREAD

**Issue by softveda** [Azure/azure-cli-extensions#580]
I was following the tutorial at https://docs.microsoft.com/en-us/azure/functions/tutorial-static-website-serverless-api-with-database?tutorial-step=2

I am using az cli interactive mode within windows subsystem for Linux. 
The following command failed
`storage blob upload -c \$web --account-name <storage account name> -f settings.js -n settings.js`

The error message was
`
progress_patch() got an unexpected keyword argument 'det'
Traceback (most recent call last):
  File "/home/pratik/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 659, in cli_execute
    result = invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 237, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 180, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 448, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 325, in upload_blob
    return type_func[blob_type]()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 318, in upload_block_blob
    return client.create_blob_from_path(**create_blob_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/blockblobservice.py", line 463, in create_blob_from_path
    timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/blockblobservice.py", line 567, in create_blob_from_stream
    progress_callback(0, count)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 702, in _update_progress
    hook = cmd.cli_ctx.get_progress_controller(det=True)
TypeError: progress_patch() got an unexpected keyword argument 'det'
`

It worked when I used the command from outside interactive mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c4e415-fc8d-26d5-3213-da937fd6932c
* Version Independent ID: dcb2f2d6-fd80-495d-8582-8be859d68792
* Content: [az storage](https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by josiah14** [comment]
This also happens for the `storage file upload` command within interactive mode (but not from outside of interactive).

```bash
myname@mypc ~/my/working/directory
> $ az interactive
az>> storage file upload --account-name <omitted> --share-name <omitted> --source "<omitted>" --path "<omitted>"
progress_patch() got an unexpected keyword argument 'det'
Traceback (most recent call last):
  File "/Users/jberkebile/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 659, in cli_execute
    result = invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 448, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/multiapi/storage/v2018_03_28/file/fileservice.py", line 1647, in create_file_from_path
    max_connections, timeout)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/multiapi/storage/v2018_03_28/file/fileservice.py", line 1835, in create_file_from_stream
    timeout
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/multiapi/storage/v2018_03_28/file/_upload_chunking.py", line 27, in _upload_file_chunks
    progress_callback(0, file_size)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/command_modules/storage/_validators.py", line 702, in _update_progress
    hook = cmd.cli_ctx.get_progress_controller(det=True)
TypeError: progress_patch() got an unexpected keyword argument 'det'
az>> exit

myname@mypc ~/my/working/directory
> $ az storage file upload --account-name <omitted> --share-name <omitted> --source "<omitted>" --path "<omitted>"
Finished[#############################################################]  100.0000%

```

**Comment by alssau** [comment]
Folks,

Same here. While using az interactive and trying to upload a file to a blob container using the command below
`az storage blob upload -f "/Users/Alonso_Seravalli/Documents/Files/MCK/Training/Azure/azure_upload.txt" -c m
`
I get the error:
`usage: az storage blob upload [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,yamlc,none}] [--query JMESPATH]
                              [--account-name ACCOUNT_NAME] [--account-key ACCOUNT_KEY]
                              [--connection-string CONNECTION_STRING] [--sas-token SAS_TOKEN]
                              [--subscription _SUBSCRIPTION] --container-name CONTAINER_NAME --name
                              BLOB_NAME --file FILE_PATH [--type {block,page,append}]
                              [--metadata METADATA [METADATA ...]] [--validate-content]
                              [--maxsize-condition MAXSIZE_CONDITION]
                              [--max-connections MAX_CONNECTIONS] [--lease-id LEASE_ID]
                              [--tier {P10,P20,P30,P4,P40,P50,P6,P60}]
                              [--if-modified-since IF_MODIFIED_SINCE]
                              [--if-unmodified-since IF_UNMODIFIED_SINCE] [--if-match IF_MATCH]
                              [--if-none-match IF_NONE_MATCH] [--timeout TIMEOUT]
                              [--auth-mode {login,key}] [--content-type CONTENT_TYPE]
                              [--content-encoding CONTENT_ENCODING]
                              [--content-language CONTENT_LANGUAGE]
                              [--content-disposition CONTENT_DISPOSITION]
                              [--content-cache-control CONTENT_CACHE_CONTROL]
                              [--content-md5 CONTENT_MD5] [--no-progress]
                              [--socket-timeout SOCKET_TIMEOUT]
az storage blob upload: error: progress_patch() got an unexpected keyword argument 'det'`

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
`az interactive` is not under active development. Please just use the normal command instead.

**Comment by matt1405** [comment]
I've had this with a simple .txt file
 "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "interactive": "0.4.4"

Again worked fine without interactive
