### ISSUE TITLE
"az providerhub resource-type-registration list..." fails with AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by papadeltasierra** [Azure/azure-cli-extensions#5816]
## Describe the bug

**Command Name**
`az providerhub resource-type-registration list
Extension Name: providerhub. Version: 0.2.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1436, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1180, in rest_key_extractor
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 710, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "C:\Users\pauldsmith\.azure\cliextensions\providerhub\azext_providerhub\vendored_sdks\providerhub\operations\_resource_type_registrations_operations.py", line 514, in get_next
    error = self._deserialize(models.ErrorResponse, response)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1376, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1454, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1436, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1180, in rest_key_extractor
azure.core.exceptions.DeserializationError: ("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az providerhub resource-type-registration list --provider-namespace {} --verbose`

## Expected Behavior
A list of the registrations or at least some sensible error if I don't have permissions to view this information.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0 *

Extensions:
account 0.2.5
azure-devops 0.25.0
connectedk8s 1.3.4
customlocation 0.1.3
k8s-extension 1.3.5
providerhub 0.2.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
`az cli` did suggest upgrading which I did but this did not help.  Same error whether running this on Linux (WSL2) or Powershell.

**Comment by papadeltasierra** [comment]
I tried the example "Microsoft.Contoso" namespace and enabled debug using `--debug` and it looks like this is the cause...
```
li.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '07695af5-5e34-4b31-93c5-e71b98067be7'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '07695af5-5e34-4b31-93c5-e71b98067be7'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'UKSOUTH:20230130T151228Z:07695af5-5e34-4b31-93c5-e71b98067be7'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 30 Jan 2023 15:12:28 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '216'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: "{\"error\":{\"code\":\"InvalidSubscriptionIdForProviderNamespace\",\"message\":\"The subscription 'f2785600-a884-4c0c-984a-46f27b5a4eee' is not a part of allowed subscriptions for namespace 'Microsoft.Contoso'.\"}}"
```
Not good that I get an exception instead of this error though.

**Comment by papadeltasierra** [comment]
Umm, adding `--subscription {}` sometimes results in a sensible error output but sometimes I get the exception.  It depends on what subscription I provide, despite the 400 response looking very similar to me.

**Comment by papadeltasierra** [comment]
Response which seems to be parsed and results in sensible error output...
```
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '210'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '286ad958-d776-44cf-8c6d-870bf6ec3d9c'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '87b50da5-51c0-418b-a4dc-b2d3c92c0c24'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'UKSOUTH:20230130T151630Z:87b50da5-51c0-418b-a4dc-b2d3c92c0c24'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 30 Jan 2023 15:16:29 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InvalidSubscriptionIdForProviderNamespace","message":"The subscription '{redacted-subscription}' is not a part of allowed subscriptions for namespace '{redacted-namespace}'."}}
```

**Comment by papadeltasierra** [comment]
Response which causes the exception.
```
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '0ec424a3-de4f-409e-9b90-036a741f215f'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '0ec424a3-de4f-409e-9b90-036a741f215f'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'UKSOUTH:20230130T152101Z:0ec424a3-de4f-409e-9b90-036a741f215f'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 30 Jan 2023 15:21:01 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '222'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: "{\"error\":{\"code\":\"InvalidSubscriptionIdForProviderNamespace\",\"message\":\"The subscription '{redacted-subscription}' is not a part of allowed subscriptions for namespace '{redacted-namespace}'.\"}}"
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@papadeltasierra Thanks for reaching out to us and reporting this issue. `Microsoft.Contoso` is the namespace provider used in our docs.  May I know the namespace provider you are concerned about ? Also ensure that namespace provider is registered in your subscription as shown below :

Go to **Azure Portal** ---> Select your **Subscription** ---> Click on the  **Resource Providers** --->

![image](https://user-images.githubusercontent.com/57353862/215701618-4bdf25f2-d733-45d3-b500-de2312c13332.png)

Could you please run the below command and check if that helps ?

> **az rest --method get --url https ://management.azure.com/subscriptions/XXXXXXXXXX/providers/Microsoft.ProviderHub/providerRegistrations/Microsoft.MyNamespace/resourcetypeRegistrations?api-version=2020-11-20**

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@papadeltasierra I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@papadeltasierra The action is currently pending on you to try the above suggestion. Please feel free to reopen this thread, if you need any further assistance. We would be happy to help.
