### ISSUE TITLE
az containerapp exception during images registry set

### ISSUE THREAD

**Issue by antoniosalomone** [Azure/azure-cli-extensions#5853]
## Describe the bug

**Command Name**
`az containerapp registry set
Extension Name: containerapp. Version: 0.3.13.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\Administrator\.azure\cliextensions\containerapp\azext_containerapp\_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Administrator\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 2036, in set_registry
    for r in registries_def:
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp registry set -n {} -g {} --server {} --username {} --password {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0 *

Extensions:
containerapp 0.3.13
ssh 1.1.3

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@antoniosalomone  Thanks for reaching out to us and reporting this issue. Could you update your `containerapp` extension by running the below command and then run your CLI command again ? Awaiting your reply.

> az extension update -n containerapp

**Comment by navba-MSFT** [comment]
@antoniosalomone I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by antoniosalomone** [comment]
Hi,

   It is working with the new az cli extension version.

   Thanks,
   Da "navba-MSFT" ***@***.***
   A "Azure/azure-cli-extensions" ***@***.***
   Cc "Antonio Salomone" ***@***.***,"Mention" ***@***.***
   Data Thu, 09 Feb 2023 20:44:58 -0800
   Oggetto Re: [Azure/azure-cli-extensions] az containerapp exception during images registry set (Issue #5853)

   @antoniosalomone I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@antoniosalomone Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
