### ISSUE TITLE
az copy image failed

### ISSUE THREAD

**Issue by yaronkaikov** [Azure/azure-cli-extensions#5869]
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.12.`

**Errors:**
```
command failed: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'scylla-5.3.0-dev-x86_64-2023-02-06T09-46-13_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-lyvn55qkj5/providers/Microsoft.Compute/disks/pkroslyvn55qkj5', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: (NotFound) Resource pkroslyvn55qkj5 is not found.
Code: NotFound
Message: Resource pkroslyvn55qkj5 is not found.

The command failed with an unexpected error. Here is the traceback:
Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'scylla-5.3.0-dev-x86_64-2023-02-06T09-46-13_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-lyvn55qkj5/providers/Microsoft.Compute/disks/pkroslyvn55qkj5', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 116, in imagecopy
    run_cli_command(cli_cmd)
  File "/root/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/root/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/az/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'scylla-5.3.0-dev-x86_64-2023-02-06T09-46-13_os_disk_snapshot', '--location', 'eastus', '--resource-group', 'scylla-images', '--source', '/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/pkr-Resource-Group-lyvn55qkj5/providers/Microsoft.Compute/disks/pkroslyvn55qkj5', '--hyper-v-generation', 'V2', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {}`

## Environment Summary
```
Linux-6.1.9-200.fc37.x86_64-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.45.0

Extensions:
image-copy-extension 0.2.12

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by yaronkaikov** [comment]
Found the problem. I need to keep the disk from the original image build. after doing it, this command is working
