### ISSUE TITLE
Help documentation returns error for "min_profile" and "max_profile"

### ISSUE THREAD

**Issue by garethjensen** [Azure/azure-cli-extensions#588]
### Extension name (the extension in question)
storage-preview

### Description of issue (in as much detail as possible)
Returns the following error when prompting for help via `az storage account -h`

```
Help entry fields 'min_profile' and 'max_profile' are no longer supported. Please use 'supported-profiles' or 'unsupported-profiles'.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 276, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1024, in __call__
    parser.print_help()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\parser.py", line 154, in format_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\parser.py", line 225, in format_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\_help.py", line 146, in show_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\help.py", line 664, in show_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\help.py", line 219, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\_help.py", line 240, in load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\_help_loaders.py", line 152, in versioned_load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\help.py", line 178, in load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\help.py", line 183, in _load_from_file
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\_help.py", line 234, in _load_from_data
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\_help.py", line 201, in _should_include_example
knack.help.HelpAuthoringException: Help entry fields 'min_profile' and 'max_profile' are no longer supported. Please use 'supported-profiles' or 'unsupported-profiles'.
```
-----

**Comment by tjprescott** [comment]
cc @adewaleo

**Comment by adewaleo** [comment]
(cli-venv) [03:55 PM] Work-Mac:azure-cli tosin$ az self-test
This command has been deprecated and will be removed in a future release.
Running CLI self-test.

Loading all commands and arguments...
Commands loaded OK.

Retrieving all help...
Skipped 'storage account create' due to 'Help entry fields 'min_profile' and 'max_profile' are no longer supported. Please use 'supported-profiles' or 'unsupported-profiles'.'
Help loaded OK.

CLI self-test completed: OK
(cli-venv) [03:55 PM] Work-Mac:azure-cli tosin$ 

cc: @tjprescott

**Comment by adewaleo** [comment]
@limingu we will need to fix this bug by updating the storage-preview extension.
