### ISSUE TITLE
Cannot exec into containerapp - 401 Unauthorized

### ISSUE THREAD

**Issue by nattyg93** [Azure/azure-cli-extensions#5888]
## Describe the bug

**Command Name**
`az containerapp exec
Extension Name: containerapp. Version: 0.3.22.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Handshake status 401 Unauthorized
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/nat/.local/share/azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2524, in containerapp_ssh
    conn = WebSocketConnection(cmd=cmd, resource_group_name=resource_group_name, name=name, revision=revision,
  File "/Users/nat/.local/share/azure/cliextensions/containerapp/azext_containerapp/_ssh_utils.py", line 62, in __init__
    self._socket.connect(self._url, header=[f"Authorization: Bearer {self._token}"])
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/websocket/_handshake.py", line 148, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 401 Unauthorized
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a container app
- Try to exec into the app `az containerapp exec --name {} --resource-group {}`

## Expected Behavior

Should be able to exec into the containerapp

## Environment Summary
```
macOS-13.1-arm64-arm-64bit, Darwin 22.2.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.45.0

Extensions:
containerapp 0.3.22
rdbms-connect 1.0.4

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@nattyg93 Sorry, but I am not able to reproduce this issue.  I have checked both `0.3.21` and `0.3.22' versions and it worked fine in both -
![image](https://user-images.githubusercontent.com/38112130/221071708-a71713fd-a9d8-4e0c-ba8d-0418b4dddfa7.png)

**Comment by nattyg93** [comment]
@SaurabhSharma-MSFT Seems to likely be related to this https://github.com/microsoft/azure-container-apps/issues/634.

It magically started working again for me yesterday - seems like something dodgy is going on in ACA.

I'll close for now.
