### ISSUE TITLE
az aks nodepool list fails on specific cluster

### ISSUE THREAD

**Issue by krenaut62** [Azure/azure-cli-extensions#5902]
## Describe the bug
list node pools does not work on one specific cluster 

**Command Name**
`az aks nodepool list
Extension Name: aks-preview. Version: 0.5.104.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerServiceClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/e0146385/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_08_02_preview/operations/_agent_pools_operations.py", line 530, in get_next
    request = prepare_request(next_link)
  File "/home/e0146385/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_08_02_preview/operations/_agent_pools_operations.py", line 515, in prepare_request
    _next_request_params["api-version"] = self._config.api_version
AttributeError: 'ContainerServiceClientConfiguration' object has no attribute 'api_version'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
CLUSTER_NAME="aks03-dev-eus"
CLUSTER_SUB="Microservices"
nodepools=$(az aks nodepool list --cluster-name ${CLUSTER_NAME} \
        --resource-group rg-${CLUSTER_NAME} \
        --subscription "${CLUSTER_SUB}" | jq -r '.[].name')

## Expected Behavior
command should list node pools

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.42.0 *

Extensions:
aks-preview 0.5.104

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by SaurabhSharma-MSFT** [comment]
@krenaut62 We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@krenaut62 I am unable to reproduce this issue.  Can you please upgrade your az version using `az upgrade` and try again. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@krenaut62 Please let us know if you need any help on this issue. Thanks.

**Comment by krenaut62** [comment]
After upgrading az cli, I am no longer able to reproduce the issue.

**Comment by SaurabhSharma-MSFT** [comment]
@krenaut62 Thanks for the confirmation. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
