### ISSUE TITLE
SSH-login via resource group and virtual machine name lookup fails, manually getting vm's ip works 

### ISSUE THREAD

**Issue by johannes-bauma-mayer** [Azure/azure-cli-extensions#6006]
## Describe the bug
ssh-login to virtual machine fails getting ip dynamically via resource group and virtual machine name.
"Direct" ssh-login to manually look up the vm's ip address works.  

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.1.4.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\ugmf100335\.azure\cliextensions\ssh\azext_ssh\custom.py", line 66, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "C:\Users\ugmf100335\.azure\cliextensions\ssh\azext_ssh\custom.py", line 159, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
  File "C:\Users\ugmf100335\.azure\cliextensions\ssh\azext_ssh\ip_utils.py", line 36, in get_ssh_ip
    if public_ip_ref and public_ip_ref.get("id", None):
AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Make sure az ssh is properly authenticated, can access the ressource group and find the vm.

- `az ssh vm -n vm_valid -g RG_NOT_VALID`
(ResourceGroupNotFound) Resource group 'RG_NOT_VALID' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'RG_NOT_VALID' could not be found.

- `az ssh vm -n VM_NOT_VALID -g rg-valid`
A valid resource VM_NOT_VALID in the resource group rg-valid was not found.
Please ensure the active subscription is set properly and resource exists.

Next step should work, but gives error - compare error message above.
- `az ssh vm -n VM_VALID -g RG_VALID`

Alternative login via IP works.
- `az ssh vm --ip VM_IP`

## Expected Behavior
Gather IP information dynamically via resource group and virtual machine name and then login with ssh.

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0

Extensions:
ssh 1.1.4

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by vthiebaut10** [comment]
@johannes-bauma-mayer Try updating to version 1.1.5 using "az extension update -n ssh"

**Comment by navba-MSFT** [comment]
@johannes-bauma-mayer Apologies for the late reply. Thanks for reaching out to us and reporting this issue. This issue is fixed as a part of this PR https://github.com/Azure/azure-cli-extensions/pull/6004. Updating the `ssh` extension by running the below command should fix it.

> **az extension update -n ssh**

Hope this helps.

**Comment by johannes-bauma-mayer** [comment]
@vthiebaut10 and @navba-MSFT I updated as advised and can confirm this issue is fixed.
