### ISSUE TITLE
Error: Az stream-analytics output test 

### ISSUE THREAD

**Issue by SNAKE169** [Azure/azure-cli-extensions#6029]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Az stream-analytics

### Description of issue (in as much detail as possible)
When I run  'az stream-analytics output test --job-name "myjob" --name "Output" --resource-group "myrg" ' command.
The following error is output. 

(BadRequest) The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.
Code: BadRequest
Message: The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.

I tried to rerun it multiple times, and they all output the same.
-----

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
@SNAKE169,
- Could you please add `--debug` to your command to help collect debug log for us to troubleshoot?
- Could you please provide the json as well for troubleshooting?

**Comment by SNAKE169** [comment]
@jsntcy this is the output after I added --debug
cli.knack.cli: Command arguments: ['stream-analytics', 'output', 'test', '--job-name', 'anhbd3asa', '--output-name', 'Output', '--resource-group', 'rsg-anhbd3', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0347E580>, <function OutputProducer.on_global_arguments at 0x03650580>, <function CLIQuery.on_global_arguments at 0x036691D8>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'stream-analytics': ['azext_stream_analytics']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: stream-analytics          0.008         9        47  C:\Users\Onsiter\.azure\cliextensions\stream-analytics
cli.azure.cli.core: Total (1)                 0.008         9        47
cli.azure.cli.core: Loaded 9 groups, 47 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : stream-analytics output test
cli.azure.cli.core: Command table: stream-analytics output test
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04315CD0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\Onsiter\.azure\commands\2023-03-20.12-52-59.stream-analytics_output_test.12424.log'.
az_command_data_logger: command args: stream-analytics output test --job-name {} --output-name {} --resource-group {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0433CDA8>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0433CE38>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0434E340>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x036505C8>, <function CLIQuery.handle_query_parameter at 0x03669220>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0434E2F8>]
az_command_data_logger: extension name: stream-analytics
az_command_data_logger: extension version: 0.1.2
Command group 'stream-analytics' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=StreamAnalyticsManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\Onsiter\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\Onsiter\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/2b7bdc6e-b900-4c29-9677-4c7fb5ab8b40/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/2b7bdc6e-b900-4c29-9677-4c7fb5ab8b40/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/2b7bdc6e-b900-4c29-9677-4c7fb5ab8b40/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/2b7bdc6e-b900-4c29-9677-4c7fb5ab8b40/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/2b7bdc6e-b900-4c29-9677-4c7fb5ab8b40/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/2b7bdc6e-b900-4c29-9677-4c7fb5ab8b40/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/2b7bdc6e-b900-4c29-9677-4c7fb5ab8b40/kerberos', 'tenant_region_scope': 'AS', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: d6735797-0a65-4efc-930f-6d3b8b115028
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/b62479b9-4770-4b52-976b-d327da7d6337/resourcegroups/rsg-anhbd3/providers/Microsoft.StreamAnalytics/streamingjobs/anhbd3asa/outputs/Output/test?api-version=2020-03-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '2'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'b4cd8224-c6d2-11ed-b61f-00d49eb24d09'
cli.azure.cli.core.sdk.policies:     'CommandName': 'stream-analytics output test'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--job-name --output-name --resource-group --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.42.0 azsdk-python-mgmt-streamanalytics/1.0.0b1 Python/3.10.8 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/b62479b9-4770-4b52-976b-d327da7d6337/resourcegroups/rsg-anhbd3/providers/Microsoft.StreamAnalytics/streamingjobs/anhbd3asa/outputs/Output/test?api-version=2020-03-01 HTTP/1.1" 400 483
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-store, no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '483'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'b4cd8224-c6d2-11ed-b61f-00d49eb24d09'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '282ef050-5579-4dd3-bbbf-81f47f7b0b35'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JAPANEAST:20230320T035255Z:282ef050-5579-4dd3-bbbf-81f47f7b0b35'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 20 Mar 2023 03:52:55 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "code": "BadRequest",
  "message": "The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.",
  "details": {
    "code": "400",
    "message": "The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.",
    "correlationId": "282ef050-5579-4dd3-bbbf-81f47f7b0b35",
    "requestId": "b4cd8224-c6d2-11ed-b61f-00d49eb24d09"
  }
}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Onsiter\.azure\cliextensions\stream-analytics\azext_stream_analytics\generated\custom.py", line 417, in stream_analytics_output_test
    return sdk_no_wait(no_wait,
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 722, in sdk_no_wait
  File "C:\Users\Onsiter\.azure\cliextensions\stream-analytics\azext_stream_analytics\vendored_sdks\streamanalytics\operations\_outputs_operations.py", line 543, in begin_test
    raw_result = self._test_initial(
  File "C:\Users\Onsiter\.azure\cliextensions\stream-analytics\azext_stream_analytics\vendored_sdks\streamanalytics\operations\_outputs_operations.py", line 489, in _test_initial
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (BadRequest) The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.
Code: BadRequest
Message: The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.

cli.azure.cli.core.azclierror: (BadRequest) The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.
Code: BadRequest
Message: The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.
az_command_data_logger: (BadRequest) The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.
Code: BadRequest
Message: The JSON provided in the request body is invalid. Required property 'properties' not found in JSON. Path '', line 1, position 2.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04315DF0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.073 seconds (init: 0.451, invoke: 0.622)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3626 in cache
telemetry.check: Negative: The C:\Users\Onsiter\.azure\telemetry.txt was modified at 2023-03-20 12:51:43.971254, which in less than 600.000000 s

**Comment by jsntcy** [comment]
![image](https://user-images.githubusercontent.com/16348853/227827092-e78f9215-446e-4fef-8ca6-2aacb14516f5.png)

Is it possible to share the json in the request body for troubleshooting?

**Comment by SNAKE169** [comment]
@jsntcy I don't add json in the request.

**Comment by ZengTaoxu** [comment]
Hello SNAKE169, please try adding --datasource and --serialization parameters and then try it again.
