### ISSUE TITLE
failure during az containerapp exec

### ISSUE THREAD

**Issue by jsc-di** [Azure/azure-cli-extensions#6158]
## Describe the bug

**Command Name**
`az containerapp exec
Extension Name: containerapp. Version: 0.3.10.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'logStreamEndpoint'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/jonas/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2242, in containerapp_ssh
    conn = WebSocketConnection(cmd=cmd, resource_group_name=resource_group_name, name=name, revision=revision,
  File "/home/jonas/.azure/cliextensions/containerapp/azext_containerapp/_ssh_utils.py", line 56, in __init__
    self._logstream_endpoint = token_response["properties"]["logStreamEndpoint"]
KeyError: 'logStreamEndpoint'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp exec --subscription {} --resource-group {} --name {} --replica {}`

## Environment Summary
```
Linux-5.19.0-38-generic-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.46.0

Extensions:
timeseriesinsights 0.2.1
containerapp 0.3.10
kusto 0.5.0
log-analytics 0.2.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@jsc-di Thanks for reaching out to us and reporting this issue. I see that you are using an older version of `containerapp` extension. Could you please update the extension by running the below command and check if that helps ?

> **az extension update -n containerapp**

Awaiting your reply.

**Comment by jsc-di** [comment]
@navba-MSFT that did it. Thx!
I thought that there are some warning message if I use an older version, though..
