### ISSUE TITLE
az ssh gives error NoneType object has no attribute __name__ 

### ISSUE THREAD

**Issue by sudeeprp** [Azure/azure-cli-extensions#6167]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.1.3.`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --port {} -n {} -g {} {}`

## Environment Summary
```
Linux-5.4.0-137-generic-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.47.0

Extensions:
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@sudeeprp Thanks for reaching out to us and reporting this issue. Could you please run the same command with` --debug `parameter and share the complete error output ? Awaiting your reply.

**Comment by odedonato** [comment]
Same error on MacOS 13.3 with version 2.47.0 installed with brew

`CMD-LOG-LINE-BEGIN 23149 | 2023-04-05 09:20:21,907 | INFO | az_command_data_logger | command args: ssh vm --resource-group {} --vm-name {} --debug
CMD-LOG-LINE-BEGIN 23149 | 2023-04-05 09:20:21,988 | INFO | az_command_data_logger | extension name: ssh
CMD-LOG-LINE-BEGIN 23149 | 2023-04-05 09:20:21,988 | INFO | az_command_data_logger | extension version: 1.1.2
CMD-LOG-LINE-BEGIN 23149 | 2023-04-05 09:20:22,573 | ERROR | az_command_data_logger | The command failed with an unexpected error. Here is the traceback:
CMD-LOG-LINE-BEGIN 23149 | 2023-04-05 09:20:22,579 | ERROR | az_command_data_logger | 'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/omar/.azure/cliextensions/ssh/azext_ssh/custom.py", line 65, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "/Users/omar/.azure/cliextensions/ssh/azext_ssh/custom.py", line 154, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
  File "/Users/omar/.azure/cliextensions/ssh/azext_ssh/ip_utils.py", line 17, in get_ssh_ip
    network_client = client_factory.get_mgmt_service_client(cmd.cli_ctx, profiles.ResourceType.MGMT_NETWORK)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 83, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 220, in _get_mgmt_service_client
    logger.debug('Getting management service client client_type=%s', client_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
CMD-LOG-LINE-BEGIN 23149 | 2023-04-05 09:20:22,579 | INFO | az_command_data_logger | exit code: 1`

**Comment by navba-MSFT** [comment]
@sudeeprp I see that you are using an older version of the `ssh `extension. Could you please update to the most recent version  (1.1.5) by running the below command and check again ? 

> **az extension update -n ssh**

**Comment by odedonato** [comment]
> @sudeeprp I see that you are using an older version of the `ssh `extension. Could you please update to the most recent version (1.1.5) by running the below command and check again ?
> 
> > **az extension update -n ssh**

that solved my problem
