### ISSUE TITLE
Running into issue with Az Costmanagment Export Command

### ISSUE THREAD

**Issue by ChildeOfShade** [Azure/azure-cli-extensions#6172]
## I am getting a bug where I am running two az costmanagment commands to export a csv to a Azure Storage Account. I execute the command and for the first command executes with no issues. The second command produces a error that breaks the Azure CLI API apparently and I'm not sure what is causing it. I checked my scope variable and it didn't seem wrong, so I am not sure what is causing the issue. 

**Command Name**
`az costmanagement export create
Extension Name: costmanagement. Version: 0.2.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize content-type: text/html
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\******\.azure\cliextensions\costmanagement\azext_costmanagement\manual\custom.py", line 44, in costmanagement_export_create
    return client.create_or_update(scope=scope,
  File "C:\Users\*****\.azure\cliextensions\costmanagement\azext_costmanagement\vendored_sdks\costmanagement\operations\_exports_operations.py", line 276, in create_or_update
    error = self._deserialize(_models.ErrorResponse, response)
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1375, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1547, in _unpack_content
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/universal.py", line 203, in deserialize_from_text
azure.core.exceptions.DeserializationError: Cannot deserialize content-type: text/html
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az costmanagement export create --name {} --scope {} --storage-account-id {} --storage-container {} --timeframe {} --type {} --storage-directory {} --schedule-status {} --recurrence {} --recurrence-period {} {}`

## Expected Behavior

Send a command to my Microsoft Azure Subscriptions to create a Reoccurring Export CSV for a Azure Storage Account. It works with one tenant but doesn't work with another. 

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0 *

Extensions:
account 0.2.5
azure-devops 0.26.0
bastion 0.2.3
costmanagement 0.2.1

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ChildeOfShade** [comment]
I found the problem. One of my variables had a "*" in it which was causing the API to perform an action that wasn't allow in the string. Removing it fixed the issue and my code was able to compile with no issues.
