### ISSUE TITLE
DeserializationError on querying data factory

### ISSUE THREAD

**Issue by istinetz** [Azure/azure-cli-extensions#6186]
## Describe the bug

**Command Name**
`az datafactory pipeline list
Extension Name: datafactory. Version: 0.7.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'DeserializationError' from 'azure.core.exceptions' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\exceptions.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\a816412\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 44, in cf_pipeline
    return cf_datafactory_cl(cli_ctx).pipelines
  File "C:\Users\a816412\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 14, in cf_datafactory_cl
    from azext_datafactory.vendored_sdks.datafactory import DataFactoryManagementClient
  File "C:\Users\a816412\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\__init__.py", line 9, in <module>
    from ._data_factory_management_client import DataFactoryManagementClient
  File "C:\Users\a816412\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\_data_factory_management_client.py", line 15, in <module>
    from . import models
  File "C:\Users\a816412\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\models\__init__.py", line 9, in <module>
    from ._models_py3 import AccessPolicyResponse
  File "C:\Users\a816412\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\models\_models_py3.py", line 14, in <module>
    from .. import _serialization
  File "C:\Users\a816412\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\_serialization.py", line 51, in <module>
    from azure.core.exceptions import DeserializationError, SerializationError, raise_with_traceback
ImportError: cannot import name 'DeserializationError' from 'azure.core.exceptions' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\exceptions.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datafactory pipeline list --resource-group {} --factory-name {} --output {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1 *

Extensions:
datafactory 0.7.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@istinetz Is it possible for you to share pipeline's json to understand where the problem is?

**Comment by saewsw** [comment]
I followed the link 'https://learn.microsoft.com/ko-kr/azure/data-factory/quickstart-create-data-factory-azure-cli' but I keep getting the same error.

It occurs while creating a data factory.
Error 'Unable to get name 'DeserializationError' from 'azure.core.exceptions' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\exceptions.pyc)', can you help me what to do next? 
I need your help. Please
