### ISSUE TITLE
AZ ssh vm command crashes

### ISSUE THREAD

**Issue by HontoNoRoger** [Azure/azure-cli-extensions#6193]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.1.3.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/companyname/username/.azure/cliextensions/ssh/azext_ssh/custom.py", line 66, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "/home/companyname/username/.azure/cliextensions/ssh/azext_ssh/custom.py", line 159, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
  File "/home/companyname/username/.azure/cliextensions/ssh/azext_ssh/ip_utils.py", line 17, in get_ssh_ip
    network_client = client_factory.get_mgmt_service_client(cmd.cli_ctx, profiles.ResourceType.MGMT_NETWORK)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 83, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 220, in _get_mgmt_service_client
    logger.debug('Getting management service client client_type=%s', client_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az ssh vm --resource-group {} --vm-name {}`

## Expected Behavior

Login to the VM.

## Environment Summary
```
Linux-5.15.0-67-generic-x86_64-with-glibc2.31, Ubuntu 20.04.6 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.47.0

Extensions:
aks-preview 0.5.76
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```
## Additional Context

When running `--help` with `--debug` or `--verbose`, it tells me that the two parameters are not known.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vthiebaut10** [comment]
@HontoNoRoger - could you try updating the ssh az cli extension to 1.1.5? Just run "az extension update --name ssh".

**Comment by HontoNoRoger** [comment]
> @HontoNoRoger - could you try updating the ssh az cli extension to 1.1.5? Just run "az extension update --name ssh".

That did the trick, thank you! :pray: 

Curious to know: should we auto-update all of the used extensions on a regular bases, as things just crashing like that may break automated pipelines from time to time.

**Comment by PramodValavala-MSFT** [comment]
@HontoNoRoger Glad to hear that your issue was resolved here!

In general, it is always best to check with the latest version to ensure any fixes made solve potential issues that one might run into.
