### ISSUE TITLE
az ssh vm -n -g "The command failed with an unexpected error. . ."

### ISSUE THREAD

**Issue by kyddinit** [Azure/azure-cli-extensions#6195]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.1.5.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'publicIPAddress'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ssh/azext_ssh/custom.py", line 66, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ssh/azext_ssh/custom.py", line 159, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ssh/azext_ssh/ip_utils.py", line 35, in get_ssh_ip
    public_ip_ref = ip_config["publicIPAddress"]
KeyError: 'publicIPAddress'
```

## To Reproduce:
[Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
](https://learn.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-linux#enable-azure-ad-login-for-a-linux-vm-in-azure) followed instructions however vNet is not default.
- _Put any pre-requisite steps here..._see above.
- `az ssh vm -n {} -g {}`

## Environment Summary
```
Linux-5.4.0-1105-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.47.0

Extensions:
ai-examples 0.2.5
ml 2.15.0
ssh 1.1.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vthiebaut10** [comment]
It seems that this PR (https://github.com/Azure/azure-cli-extensions/pull/6126) fixes this issue.

**Comment by kyddinit** [comment]
Hi Azure/azure-cli-extensions,

I'd like to add that this is on microsoft tenant not public.

Regards,

**Comment by navba-MSFT** [comment]
@kyddinit Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by kyddinit** [comment]
@vthiebaut10 The ubuntu linux vm does have a public ip I'm following this article https://learn.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-linux#enable-azure-ad-login-for-a-linux-vm-in-azure my understanding of the article is AAD authentication to an azure linux vm should work seamlessly.

**Comment by vthiebaut10** [comment]
It is still possible to hit that error, even if your VM has a public IP. Optionally, you can confirm if that is the problem by running this temporary build of the extension with the fix. You can install it by unzipping the file and running "az extension add --source <path to .whl file>.
[ssh-1.1.5-py3-none-any.zip](https://github.com/Azure/azure-cli-extensions/files/11214218/ssh-1.1.5-py3-none-any.zip)

**Comment by kyddinit** [comment]
@vthiebaut10 Thank you for your time today to resolve this issue.
