### ISSUE TITLE
Failed to add policy signer certificate

### ISSUE THREAD

**Issue by jiazhang0** [Azure/azure-cli-extensions#6210]
### Related command

```shell
az attestation signer add  \
  --name $AZURE_MAA_CUSTOM_RESOURCE_NAME \
  --resource-group $AZURE_RESOURCE_GROUP \
  --signer-file my_policy_signing_cert.pem.jws
```

Note: the file `my_policy_signing_cert.pem.jws` is generated by the scripts available in https://github.com/jiazhang0/azure-attestation-scripts

### Extension name (the extension in question)

attestation

### Description of issue (in as much detail as possible)

```
Command group 'attestation signer' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
Invalid header padding
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/jwt/api_jws.py", line 226, in _load
    header_data = base64url_decode(header_segment)
  File "/opt/az/lib/python3.10/site-packages/jwt/utils.py", line 34, in base64url_decode
    return base64.urlsafe_b64decode(input)
  File "/opt/az/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/opt/az/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (181) cannot be 1 more than a multiple of 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.azure/cliextensions/attestation/azext_attestation/manual/custom.py", line 127, in add_signer
    header = jwt.get_unverified_header(token)
  File "/opt/az/lib/python3.10/site-packages/jwt/api_jws.py", line 207, in get_unverified_header
    headers = self._load(jwt)[2]
  File "/opt/az/lib/python3.10/site-packages/jwt/api_jws.py", line 228, in _load
    raise DecodeError("Invalid header padding") from err
jwt.exceptions.DecodeError: Invalid header padding
```

### Fix

```
--- attestation/azext_attestation/manual/custom.py	2023-04-17 19:04:20.714795846 +0800
+++ attestation/azext_attestation/manual/custom.py.new	2023-04-17 19:04:16.164762483 +0800
@@ -121,6 +121,7 @@
     provider_client = cf_attestation_provider(cmd.cli_ctx)
     provider = provider_client.get(resource_group_name=resource_group_name, provider_name=provider_name)
     token = client.add(tenant_base_url=provider.attest_uri, policy_certificate_to_add=signer)
+    token = json.loads(token.replace('\'', '"')).get('token')
     result = {'Jwt': token}
 
     if token:
```

The expected result with the fix is:
```json
{
  "Algorithm": "RS256",
  "CertificateCount": 0,
  "Certificates": [],
  "JKU": "https://xxx.yyyyyy.attest.azure.net/certs",
  "Jwt": "eyJhbGciOi..."
}
```

-----

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiazhang0** [comment]
I will upload the script used to generate policy_signing_cert.jwt if necessary.

**Comment by jiazhang0** [comment]
@jsntcy @SaurabhSharma-MSFT @yonzhan @alloy The scripts used to access and test Azure Attestation are available in https://github.com/jiazhang0/azure-attestation-scripts

**Comment by SaurabhSharma-MSFT** [comment]
@jiazhang0 Can you please verify if the certificate token is generated contains a claim "maa-policyCertificate".  Can you please refer to [MAA Service Attestation Sample](https://github.com/Azure-Samples/microsoft-azure-attestation) if this helps. Thanks

**Comment by jiazhang0** [comment]
> @jiazhang0 Can you please verify if the certificate token is generated contains a claim "maa-policyCertificate". Can you please refer to [MAA Service Attestation Sample](https://github.com/Azure-Samples/microsoft-azure-attestation) if this helps. Thanks

The successful certificate token should contain the claim "policyCertificate" rather than "maa-policyCertificate". If the claim "maa-policyCertificate" is used, the following error is received from MAA:
```json
{
  "error": {
    "code": "InvalidOperation",
    "message": "Attestation Enclave operation failed with 104: Exception(0) 83FF0068 Bad message    Msg:[Could not find \"policyCertificate\" claim in policy token] \n\r\nUnhandled Enclave Exception: \"Bad message\"\r\n",
    "innererror": {
      "code": "InvalidOperation",
      "message": "Attestation Enclave operation failed with 104: Exception(0) 83FF0068 Bad message    Msg:[Could not find \"policyCertificate\" claim in policy token] \n\r\nUnhandled Enclave Exception: \"Bad message\"\r\n"
    }
  }
}
```

As you see, MAA is trying to seek the claim "policyCertificate" rather than "maa-policyCertificate". By the way, I assume the api-version is `2022-08-01` as mentioned by https://learn.microsoft.com/en-us/rest/api/attestation/policy-certificates/add.

I cannot run MAA Service Attestation Sample. I just run azure cli and access to REST APIs directly with curl.

By the way, I see the sample request from [aas-policyCertificate](https://learn.microsoft.com/en-us/rest/api/attestation/policy-certificates/add?tabs=HTTP#add-policycertificate) is using the claim "aas-policyCertificate" in the request. However, it also fails with the same error message as using "maa-policyCertificate" in request. So I guess there is something gap in the claim naming.

**Comment by jiazhang0** [comment]
@SaurabhSharma-MSFT @yonzhan Is there any update?
