### ISSUE TITLE
AZ image copy between different EA subscription ( same location/Different location) not working.

### ISSUE THREAD

**Issue by jayaakshayan** [Azure/azure-cli-extensions#622]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az image copy

### Description of issue (in as much detail as possible)

Throws error while copying the image from one EA subscription to another subscription. Tried with same location also different location.
-----
command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'group', 'create', '--name', 'image-copy-rg', '--location', 'southindia', '--output', 'json', '--subscription', '*************', '--tags', 'created_by=image-copy-extension']
output: ERROR: Operation failed with status: 'Forbidden'. Details: 403 Client Error: Forbidden for url: https://management.azure.com/subscriptions/*********/resourcegroups/image-copy-rg?api-version=2018-05-01

The command failed with an unexpected error. Here is the traceback:

Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'group', 'create', '--name', 'image-copy-rg', '--location', 'southindia', '--output', 'json', '--subscription', '**************', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 402, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/home/jaya/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 104, in imagecopy
    target_subscription)
  File "/home/jaya/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 193, in create_resource_group
    run_cli_command(cli_cmd)
  File "/home/jaya/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 35, in run_cli_command
    raise ex
  File "/home/jaya/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/az/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'group', 'create', '--name', 'image-copy-rg', '--location', 'southindia', '--output', 'json', '--subscription', '************', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.

**Comment by tamirkamara** [comment]
@jayaakshayan the command failed because the temporary resource group creation failed - see the first few lines of your message.
Is the user running the image copy command has permissions to create new resource groups?
If not, a quick workaround is to pre-create the group manually just like this command tries to do:
_command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'group', 'create', '--name', 'image-copy-rg', '--location', 'southindia', '--output', 'json', '--subscription', '*************', '--tags', 'created_by=image-copy-extension']_

**Comment by jayaakshayan** [comment]
Thanks Tamir, it was policy level restriction not to create resource group with out tag, I have removed the policy for the specific resource group which sorted out the issue.
