### ISSUE TITLE
[storage-blob-preview] "az storage blob upload-batch" error when the extension is added

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-cli-extensions#6233]
### Related command
az storage blob upload-batch --account-name yangshendls006 -d container1 -s 'c:\powerShell' --pattern '*.ps1' --destination-path 'path1/v1' --account-key "XXXX" --overwrite true --only-show-errors -o table 

### Extension name (the extension in question)

az cli version: 2.47.0
storage-blob-preview 0.7.1

### Description of issue (in as much detail as possible)
When running the command
az storage blob upload-batch --account-name yangshendls006 -d container1 -s 'c:\powerShell' --pattern '*.ps1' --destination-path 'path1/v1' --account-key "XXXX" --overwrite true --only-show-errors -o table 

there will be error
<img width="489" alt="image" src="https://user-images.githubusercontent.com/71274085/233909175-c56fd911-c4a3-4fe9-ba6b-df4add6020d6.png">

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: add_upload_progress_callback.<locals>._update_progress() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure-cli-extensions/storage-blob-preview/azext_storage_blob_preview/__init__.py", line 273, in new_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure-cli-extensions/storage-blob-preview/azext_storage_blob_preview/operations/blob.py", line 294, in storage_blob_upload_batch
    include, result = _upload_blob(cmd, blob_client, file_path=src,
  File "/opt/az/lib/python3.10/site-packages/azure-cli-extensions/storage-blob-preview/azext_storage_blob_preview/util.py", line 226, in wrapper
    return True, func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure-cli-extensions/storage-blob-preview/azext_storage_blob_preview/operations/blob.py", line 277, in _upload_blob
    return upload_blob(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure-cli-extensions/storage-blob-preview/azext_storage_blob_preview/operations/blob.py", line 725, in upload_blob
    response = client.upload_blob(data=stream, length=length, metadata=metadata,
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure-cli-extensions/storage-blob-preview/azext_storage_blob_preview/vendored_sdks/azure_storage_blob/v2021_12_02/_blob_client.py", line 746, in upload_blob
    return upload_block_blob(**options)
  File "/opt/az/lib/python3.10/site-packages/azure-cli-extensions/storage-blob-preview/azext_storage_blob_preview/vendored_sdks/azure_storage_blob/v2021_12_02/_upload_helpers.py", line 123, in upload_block_blob
    progress_hook(adjusted_count, adjusted_count)
TypeError: add_upload_progress_callback.<locals>._update_progress() takes 1 positional argument but 2 were given

Both Windows and Linux az cli have the same issue.
The command works good when the extension is removed.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
will be resolved after https://github.com/Azure/azure-cli-extensions/pull/6161 gets released

**Comment by yangchengs** [comment]
@evelyn-ys  what is the next version of storage-blob-preview?

**Comment by evelyn-ys** [comment]
@yangchengs Sorry for the late response, we just released the new version

**Comment by yangchengs** [comment]
verified in 0.7.2 storage-blob-preview
