### ISSUE TITLE
az datafactory integration-runtime list error  I don't have a D Drive

### ISSUE THREAD

**Issue by reinerra** [Azure/azure-cli-extensions#6273]
## Describe the bug

**Command Name**
`az datafactory integration-runtime list
Extension Name: datafactory. Version: 0.7.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'DeserializationError' from 'azure.core.exceptions' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\exceptions.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\User\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 24, in cf_integration_runtime
    return cf_datafactory_cl(cli_ctx).integration_runtimes
  File "C:\Users\User\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 14, in cf_datafactory_cl
    from azext_datafactory.vendored_sdks.datafactory import DataFactoryManagementClient
  File "C:\Users\User\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\__init__.py", line 9, in <module>
    from ._data_factory_management_client import DataFactoryManagementClient
  File "C:\Users\User\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\_data_factory_management_client.py", line 15, in <module>
    from . import models
  File "C:\Users\User\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\models\__init__.py", line 9, in <module>
    from ._models_py3 import AccessPolicyResponse
  File "C:\Users\User\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\models\_models_py3.py", line 14, in <module>
    from .. import _serialization
  File "C:\Users\User\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\_serialization.py", line 51, in <module>
    from azure.core.exceptions import DeserializationError, SerializationError, raise_with_traceback
ImportError: cannot import name 'DeserializationError' from 'azure.core.exceptions' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\exceptions.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datafactory integration-runtime list --factory-name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0 *

Extensions:
datafactory 0.7.0

```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@reinerra I am not able to reproduce this issue. 
![image](https://github.com/Azure/azure-cli-extensions/assets/38112130/229c2e64-e07e-4a56-ae90-795bdb4db4fc)

Can you try upgrading your Azure CLI version

**Comment by SaurabhSharma-MSFT** [comment]
@reinerra Please let us know if you are still having issues.

**Comment by SaurabhSharma-MSFT** [comment]
@reinerra We will now proceed to close this thread as we haven't heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
