### ISSUE TITLE
az datafactory pipeline create-run failed with an unexpected error

### ISSUE THREAD

**Issue by mike-f50** [Azure/azure-cli-extensions#6275]
## Describe the bug

**Command Name**
`az datafactory pipeline create-run
Extension Name: datafactory. Version: 0.7.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'DeserializationError' from 'azure.core.exceptions' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\exceptions.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\xxxx\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 44, in cf_pipeline
    return cf_datafactory_cl(cli_ctx).pipelines
  File "C:\Users\xxxx\.azure\cliextensions\datafactory\azext_datafactory\generated\_client_factory.py", line 14, in cf_datafactory_cl
    from azext_datafactory.vendored_sdks.datafactory import DataFactoryManagementClient
  File "C:\Users\xxxx\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\__init__.py", line 9, in <module>
    from ._data_factory_management_client import DataFactoryManagementClient
  File "C:\Users\xxxx\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\_data_factory_management_client.py", line 15, in <module>
    from . import models
  File "C:\Users\xxxx\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\models\__init__.py", line 9, in <module>
    from ._models_py3 import AccessPolicyResponse
  File "C:\Users\xxxx\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\models\_models_py3.py", line 14, in <module>
    from .. import _serialization
  File "C:\Users\xxxx\.azure\cliextensions\datafactory\azext_datafactory\vendored_sdks\datafactory\_serialization.py", line 51, in <module>
    from azure.core.exceptions import DeserializationError, SerializationError, raise_with_traceback
ImportError: cannot import name 'DeserializationError' from 'azure.core.exceptions' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\core\exceptions.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datafactory pipeline create-run --factory-name {} --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *

Extensions:
authV2 0.1.2
datafactory 0.7.0
storage-preview 0.8.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mike-f50 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mike-f50 Could you please [update your Azure CLI version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) to the most recent version and check if that helps ?

**Comment by navba-MSFT** [comment]
@mike-f50 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mike-f50 The action is pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
