### ISSUE TITLE
az logic workflow show fails when AAD Authorization Policies are used

### ISSUE THREAD

**Issue by MikeKemmerer** [Azure/azure-cli-extensions#6304]
## Describe the bug

**Command Name**
`az logic workflow show
Extension Name: logic. Version: 0.1.6.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
("Unable to deserialize to object: type, KeyError: 'OpenAuthenticationAccessPolicies'", KeyError('OpenAuthenticationAccessPolicies'))
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1628, in deserialize_data
    obj_type = self.dependencies[data_type]
KeyError: 'OpenAuthenticationAccessPolicies'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/home/michael/.azure/cliextensions/logic/azext_logic/generated/custom.py", line 26, in logic_workflow_show
    return client.get(resource_group_name=resource_group_name,
  File "/home/michael/.azure/cliextensions/logic/azext_logic/vendored_sdks/logic/operations/_workflow_operations.py", line 248, in get
    deserialized = self._deserialize('Workflow', pipeline_response)
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1376, in __call__
    return self._deserialize(target_obj, data)
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1639, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1639, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1454, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/lib64/az/lib/python3.9/site-packages/msrest/serialization.py", line 1628, in deserialize_data
    obj_type = self.dependencies[data_type]
azure.core.exceptions.DeserializationError: ("Unable to deserialize to object: type, KeyError: 'OpenAuthenticationAccessPolicies'", KeyError('OpenAuthenticationAccessPolicies'))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az logic workflow show -n {} -g {}`

## Environment Summary
```
Linux-5.4.0-1107-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.48.1

Extensions:
ai-examples 0.2.5
logic 0.1.6
ml 2.15.1
ssh 1.1.6

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
The root cause is that there is an issue in SDK and we'll have a fix soon.
We need a similar fix (import `OpenAuthenticationAccessPolicies`) with https://github.com/Azure/azure-cli-extensions/pull/4347.
