### ISSUE TITLE
Unable to create appservice plan

### ISSUE THREAD

**Issue by shiva-appani-gep** [Azure/azure-cli-extensions#6316]
## Describe the bug

**Command Name**
`az appservice plan create
Extension Name: appservice-kube. Version: 0.1.7.`

**Errors:**
```
The behavior of this command has been altered by the following extension: appservice-kube
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.web.v2021_01_01'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\Shiva.Appani\.azure\cliextensions\appservice-kube\azext_appservice_kube\commands.py", line 41, in _polish_bad_errors
    raise ex
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Shiva.Appani\.azure\cliextensions\appservice-kube\azext_appservice_kube\custom.py", line 446, in create_app_service_plan
    return create_app_service_plan_inner(cmd, resource_group_name, name, is_linux, hyper_v, per_site_scaling,
  File "C:\Users\Shiva.Appani\.azure\cliextensions\appservice-kube\azext_appservice_kube\custom.py", line 558, in create_app_service_plan_inner
    kube_environment = _get_kube_env_from_custom_location(cmd, custom_location, resource_group_name)
  File "C:\Users\Shiva.Appani\.azure\cliextensions\appservice-kube\azext_appservice_kube\custom.py", line 468, in _get_kube_env_from_custom_location
    client = _get_kube_client(cmd)
  File "C:\Users\Shiva.Appani\.azure\cliextensions\appservice-kube\azext_appservice_kube\custom.py", line 301, in _get_kube_client
    return client.kube_environments
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/_web_site_management_client.py", line 627, in kube_environments
ModuleNotFoundError: No module named 'azure.mgmt.web.v2021_01_01'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Run below command:
- `az appservice plan create --resource-group {} --name {} -c {} --sku {} --per-site-scaling --is-linux`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.48.1 *

Extensions:
appservice-kube 0.1.7
connectedk8s 1.3.16
customlocation 0.1.3
front-door 1.0.17
k8s-extension 1.4.0
logicapp 0.1.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by SaurabhSharma-MSFT** [comment]
@shiva-appani-gep Can you please upgrade your 'appservice-kube' extension to latest version `0.1.8` as this issue seems fixed in the latest build. 
![image](https://github.com/Azure/azure-cli-extensions/assets/38112130/25a79c6a-ccb5-48fa-92f6-673b00e91a1f)
Thanks
