### ISSUE TITLE
az aks create linux fails after enabled vmss (worked on Mac Book)

### ISSUE THREAD

**Issue by david618** [Azure/azure-cli-extensions#635]
### Background 
Followed steps in "Preview ‐ Create and manage multiple node pools for a cluster in Azure Kubernetes Service ﴾AKS﴿" 

### Updated az Version 

```
az --version
azure-cli                         2.0.61

acr                                2.2.3
acs                               2.3.20
advisor                            2.0.0
ams                                0.4.3
appservice                        0.2.16
backup                             1.2.2
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                         0.1.9
cdn                                0.2.1
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.61
cosmosdb                           0.2.9
dla                                0.2.5
dls                                0.1.8
dms                                0.1.3
eventgrid                          0.2.2
eventhubs                          0.3.4
extension                          0.2.4
feedback                           2.1.4
find                               0.3.1
hdinsight                          0.3.2
interactive                        0.4.2
iot                                0.3.7
iotcentral                         0.1.6
keyvault                          2.2.13
kusto                              0.2.1
lab                                0.1.6
maps                               0.3.4
monitor                           0.2.11
network                            2.3.5
nspkg                              3.0.3
policyinsights                     0.1.2
profile                            2.1.4
rdbms                              0.3.9
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.12
role                               2.4.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.15
signalr                            1.0.0
sql                                2.2.0
sqlvm                              0.1.1
storage                            2.3.2
telemetry                          1.0.2
vm                                2.2.17

Extensions:
aks-preview                        0.3.0

Python location '/usr/lib64/az/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 2.7.5 (default, Oct 30 2018, 23:45:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

### Create Resource Group

```
az group create --name dj0409mp --location westus2
{
  "id": "/subscriptions/42e12bff-9125-4a9a-987d-685e9c480b0a/resourceGroups/dj0409mp",
  "location": "westus2",
  "managedBy": null,
  "name": "dj0409mp",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": null
}
```

### Tried to Create AKS

```
az aks create \
>     --resource-group dj0409mp \
>     --name dj0409mp-cluster \
>     --enable-vmss \
>     --node-count 3 \
>     --node-vm-size Standard_D8s_v3 \
>     --enable-addons monitoring \
>     --admin-username azureuser \
>     --ssh-key-value az.pub \
>     --node-osdisk-size 100 \
>     --kubernetes-version 1.12.7
The command failed with an unexpected error. Here is the traceback:

super() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 274, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 266, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py", line 35, in load_arguments
    super().load_arguments(command)
TypeError: super() takes at least 1 argument (0 given)

To open an issue, please visit: https://aka.ms/azcli/issues
```

### Create AKS from Mac Desktop

Reran the exact same az aks create command on Mac and it worked.

```
az aks create \
>     --resource-group dj0409mp \
>     --name dj0409mp-cluster \
>     --enable-vmss \
>     --node-count 3 \
>     --node-vm-size Standard_D8s_v3 \
>     --enable-addons monitoring \
>     --admin-username azureuser \
>     --ssh-key-value az.pub \
>     --node-osdisk-size 100 \
>     --kubernetes-version 1.12.7
The behavior of this command has been altered by the following extension: aks-preview
 - Running .. 
```

Command completed and AKS was created after running command on MAC.

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
@david618 could you validate this is still reproducing for you on the latest CLI preview extension (0.4.50) and a supported k8s version today? Apologies for the delay in response.

**Comment by navba-MSFT** [comment]
@david618 Apologies for the late reply. Could you please upgrade to the [most recent CLI version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and let us know if you are still facing this issue ? This github thread is open for quite sometime, please let us know if you still need assistance on this. Awaiting your reply.
