### ISSUE TITLE
az ssh arc issue

### ISSUE THREAD

**Issue by mSalehsta** [Azure/azure-cli-extensions#6655]
### Describe the bug

The command failed with an unexpected error. Here is the traceback:
cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.azure/cliextensions/ssh/azext_ssh/custom.py", line 151, in ssh_arc
    ssh_vm(cmd, resource_group_name, vm_name, None, public_key_file, private_key_file,
  File "/root/.azure/cliextensions/ssh/azext_ssh/custom.py", line 64, in ssh_vm
    target_os_utils.handle_target_os_type(cmd, ssh_session)
  File "/root/.azure/cliextensions/ssh/azext_ssh/target_os_utils.py", line 24, in handle_target_os_type
    os_type, agent_version = _get_arc_server_os(cmd, op_info.resource_group_name, op_info.vm_name)
TypeError: cannot unpack non-iterable NoneType object

### Related command

az ssh arc --subscription ########### --resource-group ########### --name ########### --local-user ########### --private-key-file /root/.ssh/id_rsa  -- -o StrictHostKeyChecking=no 'MY-COMMAND'

### Errors

The command failed with an unexpected error. Here is the traceback:
cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.azure/cliextensions/ssh/azext_ssh/custom.py", line 151, in ssh_arc
    ssh_vm(cmd, resource_group_name, vm_name, None, public_key_file, private_key_file,
  File "/root/.azure/cliextensions/ssh/azext_ssh/custom.py", line 64, in ssh_vm
    target_os_utils.handle_target_os_type(cmd, ssh_session)
  File "/root/.azure/cliextensions/ssh/azext_ssh/target_os_utils.py", line 24, in handle_target_os_type
    os_type, agent_version = _get_arc_server_os(cmd, op_info.resource_group_name, op_info.vm_name)
TypeError: cannot unpack non-iterable NoneType object

### Issue script & Debug output

The command failed with an unexpected error. Here is the traceback:
cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.azure/cliextensions/ssh/azext_ssh/custom.py", line 151, in ssh_arc
    ssh_vm(cmd, resource_group_name, vm_name, None, public_key_file, private_key_file,
  File "/root/.azure/cliextensions/ssh/azext_ssh/custom.py", line 64, in ssh_vm
    target_os_utils.handle_target_os_type(cmd, ssh_session)
  File "/root/.azure/cliextensions/ssh/azext_ssh/target_os_utils.py", line 24, in handle_target_os_type
    os_type, agent_version = _get_arc_server_os(cmd, op_info.resource_group_name, op_info.vm_name)
TypeError: cannot unpack non-iterable NoneType object

### Expected behavior

Complete the commands successfully

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
ssh                                2.0.1

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@vthiebaut10, could you please take a look?

**Comment by vthiebaut10** [comment]
@mSalehsta Thank you for reporting this bug. I opened a PR to fix this bug.
