### ISSUE TITLE
one body argment for Workloads extension is erroring out

### ISSUE THREAD

**Issue by sagarkeswani** [Azure/azure-cli-extensions#6912]
### Describe the bug

One of the body arguments for the az workloads sap-virtual-instance stop is being errored out as not recognized in Cloud shell. 
![image](https://github.com/Azure/azure-cli-extensions/assets/97089870/59314e40-4ca3-4e68-b1e0-1faaf5bbc067)

For same command, it is failing in Command prompt
![Bug1](https://github.com/Azure/azure-cli-extensions/assets/97089870/b225e09f-8d0d-467c-b443-b876e8046089)

### Related command

az workloads sap-central-instance stop -n cs0 --vis-name CS5 -g Contoso-10  --soft-stop-timeout-seconds 10

### Errors

(SoftStopUnsupported)
                        The operation type SAP soft stop is currently unsupported.
                        Possible Causes: The operation type is not supported
                        Recommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.

Code: SoftStopUnsupported
Message:
                        The operation type SAP soft stop is currently unsupported.
                        Possible Causes: The operation type is not supported
                        Recommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.

### Issue script & Debug output

PS C:\Windows\System32> az workloads sap-central-instance stop -n cs0 --vis-name CS5 -g Contoso-10  --soft-stop-timeout-seconds 10 --debug
cli.knack.cli: Command arguments: ['workloads', 'sap-central-instance', 'stop', '-n', 'cs0', '--vis-name', 'CS5', '-g', 'Contoso-10', '--soft-stop-timeout-seconds', '10', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0251A538>, <function OutputProducer.on_global_arguments at 0x0271B778>, <function CLIQuery.on_global_arguments at 0x027383D0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'workloads': ['azext_workloads']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: workloads                 0.277         6        13  C:\Users\sagarkeswani\.azure\cliextensions\workloads
cli.azure.cli.core: Total (1)                 0.277         6        13
cli.azure.cli.core: Loaded 6 groups, 13 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : workloads sap-central-instance stop
cli.azure.cli.core: Command table: workloads sap-central-instance stop
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x048DB610>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\sagarkeswani\.azure\commands\2023-10-26.21-59-58.workloads_sap-central-instance_stop.34352.log'.
az_command_data_logger: command args: workloads sap-central-instance stop -n {} --vis-name {} -g {} --soft-stop-timeout-seconds {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04902B20>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0492DA90>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0492DC88>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0271B7C0>, <function CLIQuery.handle_query_parameter at 0x02738418>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0492DC40>]
az_command_data_logger: extension name: workloads
az_command_data_logger: extension version: 0.1.0a1
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\sagarkeswani\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\sagarkeswani\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: f163c229-9894-458e-802a-2eefa9a11cc5
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/resourceGroups/Contoso-10/providers/Microsoft.Workloads/sapVirtualInstances/CS5/centralInstances/cs0/stop?api-version=2023-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '30'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e76c3f95-741c-11ee-8f4f-845cf389d2de'
cli.azure.cli.core.sdk.policies:     'CommandName': 'workloads sap-central-instance stop'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n --vis-name -g --soft-stop-timeout-seconds --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"softStopTimeoutSeconds": 10}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/resourceGroups/Contoso-10/providers/Microsoft.Workloads/sapVirtualInstances/CS5/centralInstances/cs0/stop?api-version=2023-04-01 HTTP/1.1" 500 312
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '312'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-providerhub-traffic': 'True'
cli.azure.cli.core.sdk.policies:     'mise-correlation-id': '650d6f5b-594b-47e9-909d-fdcf0f192a49'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/providers/Microsoft.Workloads/locations/EASTUS/operationStatuses/68b895c3-c99c-4a4f-ab21-c93c522acbc4*44D50B877882310C64358B1F69D8FADEE52ED342CDDA6B2575BCE75239290E27?api-version=2023-04-01'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2021-12-01-preview, 2022-10-15-preview, 2022-11-01-preview, 2023-04-01, 2023-10-01-preview'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '68b895c3-c99c-4a4f-ab21-c93c522acbc4'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '545d4fa0-48aa-4724-9eb5-21e7bc888239'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHINDIA:20231026T163001Z:545d4fa0-48aa-4724-9eb5-21e7bc888239'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 26 Oct 2023 16:30:01 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"SoftStopUnsupported","message":"\n\t\t\tThe operation type SAP soft stop is currently unsupported.\n\t\t\tPossible Causes: The operation type is not supported\n\t\t\tRecommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.\n\t\t"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/resourceGroups/Contoso-10/providers/Microsoft.Workloads/sapVirtualInstances/CS5/centralInstances/cs0/stop?api-version=2023-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '30'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e76c3f95-741c-11ee-8f4f-845cf389d2de'
cli.azure.cli.core.sdk.policies:     'CommandName': 'workloads sap-central-instance stop'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n --vis-name -g --soft-stop-timeout-seconds --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"softStopTimeoutSeconds": 10}
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/resourceGroups/Contoso-10/providers/Microsoft.Workloads/sapVirtualInstances/CS5/centralInstances/cs0/stop?api-version=2023-04-01 HTTP/1.1" 500 312
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '312'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-providerhub-traffic': 'True'
cli.azure.cli.core.sdk.policies:     'mise-correlation-id': '6b210bab-816f-4bd6-acad-3ac1a9f8a4dd'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/providers/Microsoft.Workloads/locations/EASTUS/operationStatuses/b5fdb542-8e1e-40cf-91f5-1151c6d9e985*44D50B877882310C64358B1F69D8FADEE52ED342CDDA6B2575BCE75239290E27?api-version=2023-04-01'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2021-12-01-preview, 2022-10-15-preview, 2022-11-01-preview, 2023-04-01, 2023-10-01-preview'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'b5fdb542-8e1e-40cf-91f5-1151c6d9e985'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'fb949821-fd57-4c59-86fd-e90c2b65f71e'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHINDIA:20231026T163002Z:fb949821-fd57-4c59-86fd-e90c2b65f71e'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 26 Oct 2023 16:30:02 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"SoftStopUnsupported","message":"\n\t\t\tThe operation type SAP soft stop is currently unsupported.\n\t\t\tPossible Causes: The operation type is not supported\n\t\t\tRecommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.\n\t\t"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/resourceGroups/Contoso-10/providers/Microsoft.Workloads/sapVirtualInstances/CS5/centralInstances/cs0/stop?api-version=2023-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '30'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e76c3f95-741c-11ee-8f4f-845cf389d2de'
cli.azure.cli.core.sdk.policies:     'CommandName': 'workloads sap-central-instance stop'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n --vis-name -g --soft-stop-timeout-seconds --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"softStopTimeoutSeconds": 10}
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/resourceGroups/Contoso-10/providers/Microsoft.Workloads/sapVirtualInstances/CS5/centralInstances/cs0/stop?api-version=2023-04-01 HTTP/1.1" 500 312
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '312'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-providerhub-traffic': 'True'
cli.azure.cli.core.sdk.policies:     'mise-correlation-id': 'd4e67de0-a352-4932-8598-4ef2db3e3564'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/providers/Microsoft.Workloads/locations/EASTUS/operationStatuses/ffca1d75-41f3-4f3b-b0b1-7922c3341056*44D50B877882310C64358B1F69D8FADEE52ED342CDDA6B2575BCE75239290E27?api-version=2023-04-01'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2021-12-01-preview, 2022-10-15-preview, 2022-11-01-preview, 2023-04-01, 2023-10-01-preview'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ffca1d75-41f3-4f3b-b0b1-7922c3341056'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '8822f216-2398-49b8-ab4b-ca6a4f63c0ed'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHINDIA:20231026T163007Z:8822f216-2398-49b8-ab4b-ca6a4f63c0ed'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 26 Oct 2023 16:30:06 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"SoftStopUnsupported","message":"\n\t\t\tThe operation type SAP soft stop is currently unsupported.\n\t\t\tPossible Causes: The operation type is not supported\n\t\t\tRecommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.\n\t\t"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/resourceGroups/Contoso-10/providers/Microsoft.Workloads/sapVirtualInstances/CS5/centralInstances/cs0/stop?api-version=2023-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '30'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e76c3f95-741c-11ee-8f4f-845cf389d2de'
cli.azure.cli.core.sdk.policies:     'CommandName': 'workloads sap-central-instance stop'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n --vis-name -g --soft-stop-timeout-seconds --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"softStopTimeoutSeconds": 10}
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/resourceGroups/Contoso-10/providers/Microsoft.Workloads/sapVirtualInstances/CS5/centralInstances/cs0/stop?api-version=2023-04-01 HTTP/1.1" 500 312
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '312'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-providerhub-traffic': 'True'
cli.azure.cli.core.sdk.policies:     'mise-correlation-id': 'dcc5663e-be98-447a-ba64-7d0cca17125a'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'subscriptions/2b331373-3d36-4585-bdb9-d3364786e775/providers/Microsoft.Workloads/locations/EASTUS/operationStatuses/9a858473-e5b9-4485-8753-a682312dead1*44D50B877882310C64358B1F69D8FADEE52ED342CDDA6B2575BCE75239290E27?api-version=2023-04-01'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2021-12-01-preview, 2022-10-15-preview, 2022-11-01-preview, 2023-04-01, 2023-10-01-preview'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '9a858473-e5b9-4485-8753-a682312dead1'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'bfe47753-0f83-4ae5-9617-c62103238fbe'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHINDIA:20231026T163012Z:bfe47753-0f83-4ae5-9617-c62103238fbe'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 26 Oct 2023 16:30:11 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"SoftStopUnsupported","message":"\n\t\t\tThe operation type SAP soft stop is currently unsupported.\n\t\t\tPossible Causes: The operation type is not supported\n\t\t\tRecommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.\n\t\t"}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1013, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 83, in _start
  File "C:\Users\sagarkeswani\.azure\cliextensions\workloads\azext_workloads\aaz\latest\workloads\sap_central_instance\_stop.py", line 81, in _execute_operations
    yield self.SAPCentralInstancesStopInstance(ctx=self.ctx)()
  File "C:\Users\sagarkeswani\.azure\cliextensions\workloads\azext_workloads\aaz\latest\workloads\sap_central_instance\_stop.py", line 121, in __call__
    return self.on_error(session.http_response)
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 332, in on_error
azure.core.exceptions.HttpResponseError: (SoftStopUnsupported)
                        The operation type SAP soft stop is currently unsupported.
                        Possible Causes: The operation type is not supported
                        Recommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.

Code: SoftStopUnsupported
Message:
                        The operation type SAP soft stop is currently unsupported.
                        Possible Causes: The operation type is not supported
                        Recommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.

cli.azure.cli.core.azclierror: (SoftStopUnsupported)
                        The operation type SAP soft stop is currently unsupported.
                        Possible Causes: The operation type is not supported
                        Recommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.

Code: SoftStopUnsupported
Message:
                        The operation type SAP soft stop is currently unsupported.
                        Possible Causes: The operation type is not supported
                        Recommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.

az_command_data_logger: (SoftStopUnsupported)
                        The operation type SAP soft stop is currently unsupported.
                        Possible Causes: The operation type is not supported
                        Recommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.

Code: SoftStopUnsupported
Message:
                        The operation type SAP soft stop is currently unsupported.
                        Possible Causes: The operation type is not supported
                        Recommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.

cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x048DB730>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 14.910 seconds (init: 0.686, invoke: 14.224)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4132 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\sagarkeswani\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Successful soft shut down operation. See the same API in Powershell working fine in image below

![image](https://github.com/Azure/azure-cli-extensions/assets/97089870/0c034cd8-2c0b-47e9-963e-68e02be00725)

### Environment Summary

azure-cli                         2.53.0 *

core                              2.53.0 *
telemetry                          1.1.0

Extensions:
workloads                        0.1.0a1

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\sagarkeswani\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kalyaninamuduri** [comment]
@yonzhan do you have an update on this please?

**Comment by jsntcy** [comment]
@Jing-song, please help take a look.

**Comment by Jing-song** [comment]
> az workloads sap-central-instance stop -n cs0 --vis-name CS5 -g Contoso-10 --soft-stop-timeout-seconds 10

> Request body:
 {"softStopTimeoutSeconds": 10}

> Response content:
{"error":{"code":"SoftStopUnsupported","message":"\n\t\t\tThe operation type SAP soft stop is currently unsupported.\n\t\t\tPossible Causes: The operation type is not supported\n\t\t\tRecommended Action: Currently you can use hard stop of SAP system from the Virtual Instance for SAP solutions resource.\n\t\t"}}

hi @mohit1706, Is this request as expected? Is it failing because we are missing parameters?

**Comment by kalyaninamuduri** [comment]
@Jing-song thanks for your update. The message is expected. I installed CLI locally on my computer and everything works as expected. 

However when I use the "Try it" option on Azure CLI doc, I get weird responses like the below on cloud shell. Any idea why this happens?

https://user-images.githubusercontent.com/97089870/278410686-59314e40-4ca3-4e68-b1e0-1faaf5bbc067.png

**Comment by Jing-song** [comment]
@kalyaninamuduri 

> The message is expected. I installed CLI locally on my computer and everything works as expected.

So do we have a way to help this user solve the problem that this version does not support hardstop?

> However when I use the "Try it" option on Azure CLI doc, I get weird responses like the below on cloud shell. Any idea why this happens?

I'm not sure where the problem is. You can use `az workloads sap-central-instance stop -h` to check if this parameter exists first, and rerun with `--debug` to find the problem.
![image](https://github.com/Azure/azure-cli-extensions/assets/37168047/645f2fab-33b7-4724-abe4-20fd4d7afbc6)

**Comment by kalyaninamuduri** [comment]
So do we have a way to solve the problem that this version does not support hardstop?

The message being displayed is incorrect. I have created a bug for our dev team to fix the message. For SAP central instance, although soft stop timeout param exists, it is not a valid operation on this resource type. So we will message it accordingly. Typically don't expect SAP experts to use this soft stop operation on Central instance
