### ISSUE TITLE
az browse failure

### ISSUE THREAD

**Issue by derekkerr1** [Azure/azure-cli-extensions#692]
## Describe the bug

**Command Name**
`az browse
Extension Name: noelbundick. Version: 0.0.14.`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\dekerr\.azure\cliextensions\noelbundick\azext_noelbundick\browse.py", line 46, in launch_azbrowse
    latest_azbrowse = get_latest_azbrowse()
  File "C:\Users\dekerr\.azure\cliextensions\noelbundick\azext_noelbundick\browse.py", line 37, in get_latest_azbrowse
    download = next(x for x in latest if platform in x)
StopIteration
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az browse`

## Environment Summary
```
Windows-10-10.0.18895-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli                         2.0.62 *

Extensions:
aks-preview                        0.4.0
noelbundick                       0.0.14

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dekerr\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

```
## Additional Context

The issue has been copied to your clipboard. Paste it here!
To print out the issue body locally, run `az feedback --verbose`

**Comment by tjprescott** [comment]
You would need to reach out to (presumably) @noelbundick regarding this. This is not an official CLI extension.
