### ISSUE TITLE
'az devops team list' and 'az devops project list' throwing error

### ISSUE THREAD

**Issue by stlbucket** [Azure/azure-cli-extensions#702]
## ps-demo is a project that i have deleted.  in fact, i've deleted and recreated it several times and have been messing with service principals/organizations/etc while learning how to automate my azure environment via the CLI.

**Command Name**
`az devops team list
Extension Name: azure-devops. Version: 0.8.0.`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

TF200016: The following project does not exist: ps-demo. Verify that the name of the project is correct and that the project exists on the specified Azure DevOps Server.  Operation returned an invalid status code of 404.Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 375, in _run_job
    cmd_copy.exception_handler(ex)
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/dev/team/team.py", line 63, in get_teams
    project=project)
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 320, in resolve_instance_and_project
    detect=detect, organization=organization, project=project, project_required=project_required)
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 301, in resolve_instance_project_and_repo
    git_info = get_vsts_info_from_current_remote_url()
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 352, in get_vsts_info_from_current_remote_url
    info = VstsGitUrlInfo(get_remote_url(VstsGitUrlInfo.is_vsts_url_candidate))
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/dev/common/vsts_git_url_info.py", line 42, in __init__
    vsts_info = self.get_vsts_info(remote_url)
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/dev/common/vsts_git_url_info.py", line 94, in get_vsts_info
    return GitClient.get_vsts_info_by_remote_url(uri, credentials=credentials)
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/v5_0/git/git_client.py", line 33, in get_vsts_info_by_remote_url
    response = git_client._send_request(request, headers)
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 51, in _send_request
    self._handle_error(request, response)
  File "/Users/buckfactor/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 253, in _handle_error
    status_code=response.status_code))
azext_devops.devops_sdk.exceptions.AzureDevOpsClientRequestError: TF200016: The following project does not exist: ps-demo. Verify that the name of the project is correct and that the project exists on the specified Azure DevOps Server.  Operation returned an invalid status code of 404.
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- az devops team list
or
- az devops project list

## Expected Behavior

a list of teams/projects.

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli                         2.0.62 *

Extensions:
azure-devops                       0.8.0

Python location '/usr/local/Cellar/azure-cli/2.0.62/libexec/bin/python'
Extensions directory '/Users/buckfactor/.azure/cliextensions'

Python (Darwin) 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]

```
## Additional Context
i have been creating and deleting projects fairly often the last few days.  i imagine this is cached somewhere along the way where it shouldn't be?

**Comment by gauravsaralMs** [comment]
@stlbucket : can you please run your command with --debug option and share the logs?
I suspect that you are running your commands from a git repo which is hosted in Azure DevOps and --detect option is sending the response to an incorrect organization.. 
--debug logs will contain the urls.

cc: @snankani

**Comment by atbagga** [comment]
@stlbucket If you are still facing this issue, please help us with the debug logs so we can debug the issue. 
Lets us know if what Gaurav suggested above was really the issue in your case (unexpected detect project and organization from git repository).

**Comment by atbagga** [comment]
I am closing the issue as a case of mis-configuration. 
If you feel the need of changing something to help improve the experience please share with us by filing a new issue. 
Preferably in  our [extension repo](https://github.com/Azure/azure-devops-cli-extension)
