### ISSUE TITLE
az connectedk8s proxy fails with bad CPU on Mac M3

### ISSUE THREAD

**Issue by DeyvsonL** [Azure/azure-cli-extensions#7861]
### Describe the bug

Az connectedk8s proxy fails with wrong CPU type error.
az connectedk8s proxy --name HCI-SRE-K8S --resource-group mts-azshci-rg -f .\aks-arc-kube-config

<img width="929" alt="image" src="https://github.com/user-attachments/assets/b7351a33-87bf-4376-8c61-69ddee58bf53">

### Related command

az connectedk8s proxy

### Errors

az connectedk8s proxy --name HCI-SRE-K8S --resource-group mts-azshci-rg -f .\aks-arc-kube-config
Failed to start proxy process.[Errno 86] Bad CPU type in executable: '/Users/deyvson.silva/.clientproxy/arcProxyDarwin1.3.022011'

### Issue script & Debug output

az connectedk8s proxy --name HCI-SRE-K8S --resource-group mts-azshci-rg -f .\aks-arc-kube-config --debug
cli.knack.cli: Command arguments: ['connectedk8s', 'proxy', '--name', 'HCI-SRE-K8S', '--resource-group', 'mts-azshci-rg', '-f', '.aks-arc-kube-config', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x103023a60>, <function OutputProducer.on_global_arguments at 0x10337cf40>, <function CLIQuery.on_global_arguments at 0x1033aaa20>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'connectedk8s': ['azext_connectedk8s']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: connectedk8s              0.098         1        10  /Users/deyvson.silva/.azure/cliextensions/connectedk8s
cli.azure.cli.core: Total (1)                 0.098         1        10  
cli.azure.cli.core: Loaded 1 groups, 10 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : connectedk8s proxy
cli.azure.cli.core: Command table: connectedk8s proxy
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x104864b80>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/deyvson.silva/.azure/commands/2024-08-06.14-23-02.connectedk8s_proxy.33007.log'.
az_command_data_logger: command args: connectedk8s proxy --name {} --resource-group {} -f {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1048aa5c0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1048bd940>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1048bda80>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10337cfe0>, <function CLIQuery.handle_query_parameter at 0x1033aaac0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1048bd9e0>]
az_command_data_logger: extension name: connectedk8s
az_command_data_logger: extension version: 1.9.0
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ConnectedKubernetesClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/deyvson.silva/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /Users/deyvson.silva/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b
msal.authority: openid_config("https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/8ce3ccc6-8fa2-409b-be83-3d11ab838c1b/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.knack.cli: Command arguments: ['version', '--output', 'json']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x103023a60>, <function OutputProducer.on_global_arguments at 0x10337cf40>, <function CLIQuery.on_global_arguments at 0x1033aaa20>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'version': ['azure.cli.command_modules.util']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: util                      0.001         3         7
cli.azure.cli.core: Total (1)                 0.001         3         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0  
cli.azure.cli.core: Loaded 3 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : version
cli.azure.cli.core: Command table: version
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x104864b80>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/deyvson.silva/.azure/commands/2024-08-06.14-23-02.version.33007.log'.
az_command_data_logger: command args: version --output {}
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x106d0f6a0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x106d0f740>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x106d0f880>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10337cfe0>, <function CLIQuery.handle_query_parameter at 0x1033aaac0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x106d0f7e0>]
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x1048aa980>, <function _x509_from_base64_to_hex_transform at 0x1048aaa20>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x104864e00>]
az_command_data_logger: exit code: 0
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: ff5407e5-d508-471f-8838-102d78dceabd
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/1504e92a-77c6-4336-aa4b-2c8d5a21f2e7/resourcegroups/mts-azshci-rg/providers/Microsoft.Kubernetes/connectedClusters/HCI-SRE-K8S/listClusterUserCredential?api-version=2021-10-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '52'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '88fbc242-5418-11ef-9f82-26409674d276'
cli.azure.cli.core.sdk.policies:     'CommandName': 'connectedk8s proxy'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group -f --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.62.0 (HOMEBREW) azsdk-python-core/1.28.0 Python/3.11.9 (macOS-14.5-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"authenticationMethod": "AAD", "clientProxy": true}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/1504e92a-77c6-4336-aa4b-2c8d5a21f2e7/resourcegroups/mts-azshci-rg/providers/Microsoft.Kubernetes/connectedClusters/HCI-SRE-K8S/listClusterUserCredential?api-version=2021-10-01 HTTP/1.1" 200 4090
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '4090'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '199'
cli.azure.cli.core.sdk.policies:     'x-ms-providerhub-traffic': 'True'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'mise-correlation-id': 'fe55bf16-bbb3-46f5-830c-622f98bc3ba3'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '5f0a9dd2-035c-4336-8d23-134f7a97c53f'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'b268c86d-7a58-43d6-8f9c-be61d26101a1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '2999'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'BRAZILSOUTH:20240806T172304Z:b268c86d-7a58-43d6-8f9c-be61d26101a1'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: EA9E86CFBFF048278C94FBDEADDCA514 Ref B: RIO201060613051 Ref C: 2024-08-06T17:23:03Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 06 Aug 2024 17:23:03 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"hybridConnectionConfig":{"expirationTime":1722975784,"hybridConnectionName":"microsoft.kubernetes/connectedclusters/753451dad1697bce19d7e292a768a19dd4cfcbc0cee4ac2b498f317d12ac6865/1722964984168982016","relay":"azgnrelay-eastus-l1","token":"SharedAccessSignature sr=http%3A%2F%2Fazgnrelay-eastus-l1.servicebus.windows.net%2Fmicrosoft.kubernetes%2Fconnectedclusters%2F753451dad1697bce19d7e292a768a19dd4cfcbc0cee4ac2b498f317d12ac6865%2F1722964984168982016%2F&sig=lJJn3sQ3e%2FyOdSCWezaot4cfHN83%2BnovktZdZsCWcao%3D&se=1722976384&skn=sender20240806"},"kubeconfigs":[{"name":"KubeConfig","value":"YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6CiAgLSBjbHVzdGVyOgogICAgICBjZXJ0aWZpY2F0ZS1hdXRob3JpdHktZGF0YTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUnFha05EUVc1aFowRjNTVUpCWjBsUlFYcHllRFZ4WTFKeFlVTTNTMGRUZUVoUmJqWTFWRUZPUW1kcmNXaHJhVWM1ZHpCQ1FWRnpSa0ZFUW1oTlVYTjNRMUZaUkZaUlVVZEZkMHBXVlhwRlZrMUNUVWRCTVZWRlEyaE5UVkpIYkc1aFZVNXNZMjVSWjFOWE5XcE5VbXQzUm5kWlJGWlJVVXhGZUVJelpETmpkVnBIYkc1aFYwNXNZMjVSZFZreU9YUk5VMEYzU0dkWlJGWlJVVVJGZUdSRllWZGtjRkV5Vm5sa1EwSklZa2M1YVZsWGQyZFZiVGwyWkVOQ1NFMXFRV1ZHZHpCNFRYcEJORTFFUlhoTmFrRjNUVVJDWVVaM01IcFBSRUY0VFZSVmVFMXFRWGROUkVKaFRVZEZlRU42UVVwQ1owNVdRa0ZaVkVGc1ZsUk5VbFYzUlhkWlJGWlJVVXRGZDNoRllWZGtjRkV5Vm5sa1EwSktZbTFOZUVkVVFWaENaMDVXUWtGelZFVklaRE5rZVRWcllWZGtjRmt5Vm5sa1F6VnFZakl3ZUVsRVFXVkNaMDVXUWtGTlZFWXdVbkJhTW14RVdsaEtNRWxGWkhOaU1rcG9Za05DVTJJeU9UQkpSV041VFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUYxZW1aT1RrNTROMkU0YlhsaFNrTjBVMjVZTDFKeWIyaERaMmxPT1ZKc1ZYbG1kVWt5TDA5MU9HcHhTbXRVZURZMWNYTkhSMjEyVUhKRE0yOVlaMnRyVWt4d2FXMXVOMWR2Tm1nck5FWlNNVWxCVjNOVlRHVmpXWGh3YzAxT2VtRkllRzE0TVhnM1pTOWtabWQ1TlZORVRqWTNjMGd3VGs4eldITnpNSEl3ZFhCVEwydHhZbWwwVDNSVFduQk1XV3cyV25SeVFVZERVMWxRT1ZCSlZXdFpPVEpsVVhFeVJVZHVTUzk1ZFhWdE1EWmFTWGxoTjFoNlZpdG9aRWM0TWsxSVlYVldRa3BXU2poNlZYUnNkVTVLWW1ReE16UXZkRXBUTjFOelZsRmxjR28xVjNwMFEwODNWRWN4UmpoUVlYQnpjRlYzZEZBeFRWWlpkMjVUYkdOVlprbExaSHBZVDFNd2VGcExRbWQ1VFZWT1IxQklaMjByUmpaSWJVbGpjamxuSzFWUmRrbFBiRU56VW01TFVGcDZSa0pST1ZKdVlrUm9lRk5LU1ZSU1RuSjNPVVpFUzFwS2IySnhOMjVOVjNoTk5FMXdhRkZKUkVGUlFVSnZNRWwzVVVSQlVFSm5UbFpJVWsxQ1FXWTRSVUpVUVVSQlVVZ3ZUVUUwUjBFeFZXUkVkMFZDTDNkUlJVRjNTVUpvYWtGa1FtZE9Wa2hSTkVWR1oxRlZWR2xLVlVsQ2FWWTFkVTUxTldjdk5pdHlhMU0zVVZsWWFucHJkMFJSV1VwTGIxcEphSFpqVGtGUlJVeENVVUZFWjJkRlFrRkhRbTVMU2xKMlJHdG9halo2U0dRMmJXTlpNVmxzT1ZCTlYweFRiaTl3ZG5SemNrWTVLM2RZTTA0elMycEpWRTlaUm01UmIxRnFPR3RXYms1bGVVbDJMMmxRYzBkRlRVNUxVM1ZKUlhsRmVIUjJORTVsUmpJeVpDdHRVWEoyU0ZKQmFVZG1lbG93U2taeVlXSkJNRlZYVkZjNU9HdHVaSFJvTDBwemR6RklTMm95V2t3M2RHTjFOMWhWU1U5SFdsZ3hUa2RHWkhSdmJTOUVlazFPVlN0TlpVdE9hRW8zYW1sMGNtRnNhalF4UlRaV1pqaFFiSGRWU0VKSVVWSkdXRWRWTjBGcU5qUkhlRXBWVkVaNU9HSktXamt4T0hKSFQyMWhSblpGTjBaQ1kyWTJTVXR6YUZCRlEwSldNUzlOVlZKbFdHZFNVRlJ4YURWVmVXdDNOeXRWTUdJMlRFb3pMMmw1U3pWVE9XdEtVbUZVWlhCTWFXRlhUakJpWmxaTFptcHNiRVJwU1VkcmJtbGlWbUkyTTJSRVkxa3pabVV3Ukd0b2RteGtNVGt5TjJwNVRuaEdNVmRYTmt4YVdtMDJlazVVWm14TmNsazlDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMwdExTMD0KICAgICAgc2VydmVyOiBodHRwczovL2NhMTkwNDRhNmUxYzQ0ZTQ5ZTMyMjAwNmE1MDhmMDhmLmU5NmIxNDA2ZWFiYjRmYjg5ZGZkYWM2ODBiZWExMDZhLmludC5ldXMuY2MuYXJjLmF6dXJlLm5ldAogICAgbmFtZTogSENJLVNSRS1LOFMKY29udGV4dHM6CiAgLSBjb250ZXh0OgogICAgICBjbHVzdGVyOiBIQ0ktU1JFLUs4UwogICAgICB1c2VyOiBjbHVzdGVyVXNlcl9tdHMtYXpzaGNpLXJnX0hDSS1TUkUtSzhTCiAgICBuYW1lOiBIQ0ktU1JFLUs4UwpjdXJyZW50LWNvbnRleHQ6IEhDSS1TUkUtSzhTCmtpbmQ6IENvbmZpZwpwcmVmZXJlbmNlczogbnVsbAp1c2VyczoKICAtIG5hbWU6IGNsdXN0ZXJVc2VyX210cy1henNoY2ktcmdfSENJLVNSRS1LOFMKICAgIHVzZXI6CiAgICAgIGV4ZWM6CiAgICAgICAgYXBpVmVyc2lvbjogY2xpZW50LmF1dGhlbnRpY2F0aW9uLms4cy5pby92MWJldGExCiAgICAgICAgY29tbWFuZDoga3ViZWxvZ2luCiAgICAgICAgcHJvdmlkZUNsdXN0ZXJJbmZvOiB0cnVlCiAgICAgICAgYXJnczoKICAgICAgICAgIC0gZ2V0LXRva2VuCiAgICAgICAgICAtIC0tZW52aXJvbm1lbnQKICAgICAgICAgIC0gQXp1cmVQdWJsaWNDbG91ZAogICAgICAgICAgLSAtLXNlcnZlci1pZAogICAgICAgICAgLSA2MjU2Yzg1Zi0wYWFkLTRkNTAtYjk2MC1lNmU5YjIxZWZlMzUKICAgICAgICAgIC0gLS1jbGllbnQtaWQKICAgICAgICAgIC0gM2Y0NDM5ZmYtZTY5OC00ZDZkLTg0ZmUtMDljOWQ1NzRmMDZiCiAgICAgICAgICAtIC0tdGVuYW50LWlkCiAgICAgICAgICAtIDhjZTNjY2M2LThmYTItNDA5Yi1iZTgzLTNkMTFhYjgzOGMxYgogICAgICAgICAgLSAtLXdpdGgtcG9wCg=="}]}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/Users/deyvson.silva/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 2593, in client_side_proxy
    clientproxy_process = Popen(args)
                          ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/Users/deyvson.silva/.clientproxy/arcProxyDarwin1.3.022011'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/deyvson.silva/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 2489, in client_side_proxy_wrapper
    client_side_proxy_main(cmd, tenant_id, client, resource_group_name, cluster_name, 0, args, client_proxy_port,
  File "/Users/deyvson.silva/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 2527, in client_side_proxy_main
    expiry, clientproxy_process = client_side_proxy(cmd, tenant_id, client, resource_group_name, cluster_name, 0, args,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deyvson.silva/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 2601, in client_side_proxy
    raise CLIInternalError("Failed to start proxy process." + str(e))
azure.cli.core.azclierror.CLIInternalError: Failed to start proxy process.[Errno 86] Bad CPU type in executable: '/Users/deyvson.silva/.clientproxy/arcProxyDarwin1.3.022011'

cli.azure.cli.core.azclierror: Failed to start proxy process.[Errno 86] Bad CPU type in executable: '/Users/deyvson.silva/.clientproxy/arcProxyDarwin1.3.022011'
az_command_data_logger: Failed to start proxy process.[Errno 86] Bad CPU type in executable: '/Users/deyvson.silva/.clientproxy/arcProxyDarwin1.3.022011'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x104864e00>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.713 seconds (init: 0.135, invoke: 1.578)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 20557 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/bin/python /opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /Users/deyvson.silva/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Command should work and output the kubeconfig file to specified path.

### Environment Summary

azure-cli                         2.62.0 *

core                              2.62.0 *
telemetry                          1.1.0

Extensions:
acrquery                           1.0.1
aksarc                            1.2.23
connectedk8s                       1.9.0

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/bin/python'
Extensions directory '/Users/deyvson.silva/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by DeyvsonL** [comment]
Update: It works after installing rosetta 2.
softwareupdate --install-rosetta
