### ISSUE TITLE
[Artifacts] Az artifacts universal publish failed - 'module' object has no attribute 'uuid4'

### ISSUE THREAD

**Issue by smaley07** [Azure/azure-cli-extensions#810]
## Describe the bug

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'module' object has no attribute 'uuid4'
Traceback (most recent call last):
  File "/Users/gvd/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/gvd/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 566, in execute
    raise ex
AttributeError: 'module' object has no attribute 'uuid4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal publish --organization {} --feed {} --name {} --version {} --description {} --path {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 2.7.16
Shell: bash

azure-cli 2.0.67

Extensions:
azure-devops 0.11.0

```

**Comment by smaley07** [comment]
Duplicate of : https://github.com/Azure/azure-cli-extensions/issues/772
