### ISSUE TITLE
Can't use az image copy

### ISSUE THREAD

**Issue by Wolf7horne** [Azure/azure-cli-extensions#84]
### 'NoneType' object is not subscriptable

Getting os disk id of the source vm/image
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 342, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 315, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 175, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 349, in default_command_handler
    result = op(**command_args)
  File "/home/Wolfthorne/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 27, in imagecopy
    source_os_disk_id = json_cmd_output['storageProfile']['osDisk']['managedDisk']['id']
TypeError: 'NoneType' object is not subscriptable

**Comment by derekbekoe** [comment]
@Wolf7horne Are you attempting to use this against Public Azure?

**Comment by Wolf7horne** [comment]
@derekbekoe Yes I am.

**Comment by tamirkamara** [comment]
@Wolf7horne:
1. Can you share your full command?
2. Is it a managed image (an image created from a managed vm/disk)?
3. Does the source disk still exists in your subscription?

**Comment by Wolf7horne** [comment]
@tamirkamara 
1. az image copy --source-resource-group WestUS --source-object-name Goldv9Image --target-resource-group EastUS --targe-location eastus2 --cleanup
2. osDisk and dataDisk both have managedDisk = null, another thing to note is that it is already generalized as well.
3. Yes it does

**Comment by tamirkamara** [comment]
@Wolf7horne 
I think this means that the vm isn't based on managed disks. Can you rerun the command with _--debug_ and send the full output?

**Comment by PoisonousJohn** [comment]
@tamirkamara the same issue, full output attached.

[log.txt](https://github.com/Azure/azure-cli-extensions/files/1868265/log.txt)

**Comment by tamirkamara** [comment]
@PoisonousJohn 
This extension is using the **managed** disk of the source vm from which the image was created.
In the output it looks like the disk source is in a blob. What was the process to create your image? Was the vm managed-disk based?

Tamir

**Comment by PoisonousJohn** [comment]
@tamirkamara as it was mentioned by @Wolf7horne, the case related to blob-based image (non-managed disk).

I understand that for now this extension assumes you're using image disk. Do you have plan on supporting blob images?
