### ISSUE TITLE
az aks browse does not work for me today (was working before)

### ISSUE THREAD

**Issue by crgarcia12** [Azure/azure-cli-extensions#908]
## Describe the bug

**Command Name**
`az aks browse
Extension Name: aks-preview. Version: 0.4.5.`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0525D1F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
pip-install-izsysaz4\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {} --listen-port {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.65 *

Extensions:
aks-preview 0.4.5
aks-virtual-node 0.2.0

```
## Additional Context

I am doing from PowerShell:
`az aks browse --resource-group $resourceGroup --name $clusterName`

and I get
```
The command failed with an unexpected error. Here is the traceback:

HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x050FA930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\util\connection.py", line 80, in create_connection
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\util\connection.py", line 70, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\connectionpool.py", line 354, in _make_request
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\connection.py", line 181, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x050FA930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-izsysaz4\urllib3\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x050FA930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 560, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 618, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 611, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 588, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 297, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\__init__.py", line 461, in default_command_handler
  File "C:\Users\<USER>\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 469, in aks_browse
    requests.post('http://localhost:8888/closeport/8001')
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\requests\requests\api.py", line 116, in post
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\requests\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\requests\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x050FA930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

```

**Comment by jluk** [comment]
@crgarcia12 I'm confused by your version of aks-preview given our latest is 0.4.24. https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/HISTORY.md

Are you using a local client or cloud shell?

Could you try updating your core cli version while we're here to 2.0.77?
